In [ ]:
!python --version

Python 3.12.12

In [ ]:
#@title colors
color_codes = {
    'red': '\033[91m',
    'green': '\033[92m',
    'yellow': '\033[93m',
    'blue': '\033[94m',
    'purple': '\033[95m',
    'cyan': '\033[96m',
    'white': '\033[97m',
    'reset': '\033[0m' # Resets the color
    }

def print_colored(text, color='reset'):
    """Prints text in the specified color. Defaults to resetting color."""
    code = color_codes.get(color.lower(), color_codes['reset'])
    print(f"{code}{text}{color_codes['reset']}")

In [ ]:
# @title Restaurant project
#
#run code first then look at the code if you wish
name = input("Greetings, what is your name? ").lower() #.lower converts the string into lowercase .title() caps first letter of each word
funny_name_responses = { "cristopher": "Welcome Nerd!",
"cristian": "welcome to my python restaurant have fun get creative and relearn coding cus its fun and then you can start getting into fun projects like me haha!!",
"gabriel": "Good day Gabriel how are your social skills coming along? Have fun with my python project!",
"preston": "Greetings Preston Wei hows school welcome to my python project just mess around with the responses Have fun!!",
"cheick": "welcome mega nerd!! planning to take over the world today? ",
"marina": "welcome friend",
"catherine": "welcome to my project hope it isn't too buggy" }

Bday_suprises = { "preston" : (3,[1,2,3,4]), "catherine" : (9,[17,18,19,20,]), "stephenie" : (6,[23,24,25,26]), "marina" : (8,[26,27,28,29]),"gabriel": (10,{24,25,26,27}), "cristian": (1,[27,28,29,30]), "siddartha": (10,[6,7,8,9]), "sidd" :(10,[6,7,8,9]), "cheick" : (3,[10,11,12,13]), "jason" : (8,[2,3,4,5]), "eliceo": (3,[7,8,9,10]),}
import time
from datetime import datetime
from IPython.display import Audio
from IPython.display import Image
now = datetime.now()
today = (now.month, now.day)
def debug(turtle_input):
    while True:
        try:
            return float(input(turtle_input))
        except ValueError:
            print("Please enter a valid number.")
def bday_surprise():
   #print("Did you really think I gave up on this project\nyou're wrong this was only the beginning\njust you wait....\nSURPRISE_Loading...")
   #time.sleep(15)
   print(f"SUPRISE!!! \nHappy B day {name.upper()}!! (hope it isn't too late or early)")
   #display(Audio(filename="party.mp3", autoplay=True))
   #time.sleep(10)
   #display(Audio(filename="fireworks.mp3", autoplay=True))
   #Assuming the image path is correct, otherwise update with the correct path
   #idea: snake sticking out tongue with party blower sound effect. animation.
   #display(Image("birthday.jpg"))
   #display(Audio(filename="", autoplay=True))
   #display(Audio(filename="", autoplay=True))
   input("(⁠　⁠･⁠ω⁠･⁠)⁠☞")
bd = {"dev":bday_surprise}
#/content/MOVIE[1].mp4
#this is a list a dictionary {} int() converer string > integer float() str() etc (type) defines data type
if name in funny_name_responses: #conditionals
  print(funny_name_responses[name])
if name == "cat":
   rp = input("Are you mean? Yes? No? Maybe? ").lower()
   goods = debug("How many evil deeds have you compensated")
   if (rp.lower() == "yes" or rp.lower() == "maybe") and goods <= 7 :
      print("Get out!")
      exit() # exit() stops the code from going further
   if rp  == "no":
    print("Welcome")
    print("wonderfull name " + name)
elif name == "skip":
  print("Skippin all the questions fine by me GB. ")
  exit()
else:
    print("Welcome, wonderfull name " + name)

Seat_answers = {
    "yes" : "right this way have a seat." ,
    "maybe" : "i insist right this way have a seat." ,
    "no" : "NO NO I insist, can't have you standing right this way."
 }

seats = input("Would you like to have a seat? Yes? No? Maybe? ").lower()
if seats in Seat_answers:
  print(Seat_answers[seats])
else:
  print("You will have a seat whether you like it or not.")
import re

# Step 1: Create a menu with item names and prices
menu = {
    "water": 0,
    "bread": 3,
    "coffee": 9,
    "tea": 6,
    "bagels": 4
    }
   # ", ".join(menu.keys())
print(menu)
items = input(f"{name} here is our menu What would you like? ").lower()

# Calculate the price based on the selected items
price = 0
ordered_items = re.findall(r"[a-z]+", items)
for item in ordered_items:
    if item in menu:
        price += menu[item]
    else:
        print(f"Sorry, we don't have {item}.")
        price = 0 # Reset price if an invalid item is ordered
        break # Exit the loop if an invalid item is found

        #print(f"{citem} costs {Prices[citem]}")

quantity = debug("Excellent choice " + name + " How many? ")

# Calculate the total price before considering discounts
total = price * quantity

Payment_types = " Cash" + " Credit_card" + " debit_card" + " and Google Pay"
Payment_used = input("The payment types we accept are" + Payment_types + " which method will you use to buy our five star food? ")

discount_response = input("Do you have a coupon? (yes/no) ").lower()

# Apply discount if applicable
if discount_response == "yes":
  # Assuming a 10% discount. Update total with the discounted price.
  total = total * 0.90
  print("A 10% discount has been applied!")

# The 'else' block is not needed as total already holds the pre-discount value

# Print the final total, formatted as a string with two decimal places for currency
print("Your total will be: $" + str(round(total, 2))) # Using round for better currency display

print(f" Sounds good  {name} your {quantity} {items}(s) will be ready soon." )
#Date = input("What is todays date? (ex 1/1) ").strip() # manual date alternative
#if name in Bdates and Date == Bdates[name] :
#if Date in Bdates and name in funny_name_responses:
 #print(f"Happy birthday {name.upper()}!!!")
#else:
 #print("thanks")
tip_response = input("here is your receipt, Will you give me a tip? ").lower()
if tip_response == "yes":
  print("Thank you")
  tip = debug("how much? ")
  if tip >= 20 :
   print("How generous!!")
  if tip <= 5:
   input("How selfish of you, you know I deserve better!! Don't you?")
elif tip_response == "maybe":
    print("I would really appreciate it. ")
else:
  print("Thanks anyways")
response = input(name + " would you like a snack in addtion to your " + items + " while you wait ")
print(response +"?" " very well then. ")
print("\n\nhere is your order, " + name + " bon apetite!!")

star = debug("what star rating would you give this restaurant? " + "(numbers only.)" )
#star = star.strip()
if star >= 4:
  print("Thank you for your feedback!")
  print("thanks for coming please come again!!")

if star <= 2.9:
  input("How ungrateful, whatever, fill out this survey to help us improve our services. Ok? ")
  input("Question 1 What did you like about our services?")
  input("Question 2 What can we improve? What did you not like? ")
  print("Thank you for your feedback!")
  print("thanks for coming please come again!!")
#
#def write_bytes_to_file(byte_data, filename):
#    with open(filename, "wb") as f:
#        f.write(byte_data)
#write_bytes_to_file(Partyhorn_68443,"party.mp3")
#write_bytes_to_file(lots_fireworks,"fireworks.mp3")
#write_bytes_to_file(IMG2023_1_1jpg,"birthday.jpg")
#write_bytes_to_file(aaaahhh,"eaahh.mp3")
#write_bytes_to_file(eah_1_1_1,"echo_scream.mp3")
# Write the embedded files to real files
#/content/party-horn-68443mp3.py  /content/AS_fireworks1[1]mp3.py   /content/IMG_2023_(1) (1)~2jpg.py
#yyy
#/content/MOVIE[1].mp4
if name in Bday_suprises:
  month, days = Bday_suprises[name]
  if today[0] in month and today [1] in days:
     bday_surprise()
  else:
     print(f"Not today {name.title()}")
else:
    input("This conludes my python project GG! ")

In [ ]:
# @title Experimental price list calculator
import re
Prices = {
    "water": 0,
    "bread": 3,
    "bagel": 4,
    "tea": 6,
    "coffee": 9
}
citem = input("would you like me list the prices of any items come on tell me tell me (spaces between items only) ").lower()

Price_list = re.findall(r"[a-z]+", citem) # Corrected the regex pattern again
Total_price = 0 # Initialize Total_price before the loop
#manual alternative code
#Price_list = re.split(r"\d+|, | | and | \s+", citem) # Corrected the regex pattern again
#Total_price = 0 # Initialize Total_price before the loop
for citem in Price_list:
    citem = citem.strip()  # remove spaces around item
    if citem in Prices:
        print(f"{citem} costs {Prices[citem]}$")
        Total_price += Prices[citem] # Add the price to the total
    else:
        print(f"We don't have {citem}.")

num = input("how many would you want (numbers only)")
totaled_num = (Total_price * float(num))
print(f"the total price is {totaled_num}")
#Food_list = ["bagels", "tea", "water", "bread"]
#print(Food_list) #[2] to use a listed item in list starting at zero positive for left 10 right negative nums for oppisite

**Press play on both cells to hear my frustration. first the top one wait till it runs then the second one
* the byte cell below is safe to open minimal lag**

In [ ]:
#code cell to run this has been removed the byte cells take up too much storage

In [ ]:
# @title Frustration
import time
from IPython.display import Audio
from IPython.display import Image
play_frustration = Button(description="play",button_style='danger' ,layout=Layout(width='95px',border='0.9px solid #00FF00'))
out = Output()
def play_audio(f):
    with out:
         out.clear_output()
         try:
          display(Audio(filename="eaah.mp3", autoplay=True))
          time.sleep(4.9)
          display(Audio(filename="echo_aaaahhh.mp3", autoplay=True))
         except FileNotFoundError:
            print(f"Error: The file was not found.")
         except Exception as e:
            print(f"An error occurred: {e}")
         display(Video("party_snakeMOVIE.mp4", embed=True))
         return
play_frustration.on_click(play_audio)

display(play_frustration,out)

In [ ]:
# @title video player (snake surprise)
from ipywidgets import Button,Output
from IPython.display import Video
from IPython.display import display
out = Output()
play_vid = Button(description="play",button_style='danger' ,layout=Layout(width='95px',border='0.9px solid #00FF00'))
def play_video(f):
    with out:
         out.clear_output()
         try:
          vid = Video("party_snakeMOVIE.mp4", embed=True)
         except FileNotFoundError:
            print(f"Error: The file was not found.")
         except Exception as e:
            print(f"An error occurred: {e}")
         display(Video("party_snakeMOVIE.mp4", embed=True))
         return
play_vid.on_click(play_video)

display(play_vid,out)

In [ ]:
# @title Early draft of my accounting project (don't run this just there for reference)

#my version
#accounting project
#Assets=Liabilities+Owner’s Equity done section
#Net Income=Revenue−Expenses
#Working Capital = Current Assets - Current Liabilities
#"Gross Profit=Revenue−Cost of Goods Sold (COGS)
#Ending Retained Earnings=Beginning Retained Earnings+Net Income−Dividends
#COGS=Beginning Inventory+Purchases−Ending Inventory"
#Supplies Used (Expense)=Beginning Balance+Purchases−Ending Balance
#ROI (%)=(Net Profit/Investment​)×100
#Current Ratio= Current Assets/ Current Liabilities
#Debt-to-Equity=Total Liabilities/​Shareholder’s Equity
#Revenue=Price per unit×Number of units sold
#Break-Even Units= Fixed Costs/​Price per Unit−Variable Cost per Unit
#-
#not done section Formula   Purpose
#Operating Income = Gross Profit − Operating Expenses   :Step before Net Income
#EBITDA = Net Income + Interest + Taxes + Depreciation + Amortization   :Earnings before ITDA
#Net Profit Margin = (Net Income / Revenue) × 100   :Profitability ratio
#Gross Margin = (Gross Profit / Revenue) × 100  :Efficiency of core business
#Operating Margin = (Operating Income / Revenue) × 100  :Operating efficiency
#Free Cash Flow = Operating Cash Flow − Capital Expenditures    :Cash left over
#Cash Flow from Operations = Net Income + Non-cash Expenses − Change in Working Capital :More advanced
#Inventory Turnover = COGS / Average Inventory  Efficiency in inventory use
#average Inventory = (Beginning + Ending Inventory) / 2 Used in turnover calc
#Receivables Turnover = Net Credit Sales / Avg. Accounts Receivable Collection speed
#Days Sales Outstanding (DSO) = 365 / Receivables Turnover  Days to collect payment
#Payables Turnover = Purchases / Avg. Accounts Payable  How fast you're paying suppliers
#Earnings Per Share (EPS) = Net Income / Average Outstanding Shares :Common stock value
#Book Value per Share = (Equity − Preferred Equity) / Outstanding Shares    Shareholder equity value
#Quick Ratio = (Current Assets − Inventory) / Current Liabilities   Stricter liquidity test
#Return on Equity (ROE) = Net Income / Shareholder’s Equity Profitability on equity
#Return on Assets  (ROA) = Net Income / Total Assets Efficiency of asset use
!pip install simpleeval
Equations = ["assets", "liabilities", "equity", "net income","Revenue", "gross profit", "working capital","ending retained earnings","cost of goods sold (cogs)", "break even units", "ROI",
"suplies used","current ratio", "debt to equity","Operating Income","EBITDA","Net Profit Margin","Gross Margin","Operating Margin","Free Cash Flow",
"Cash Flow from Operations","Inventory Turnover",
"average Inventory","Receivables Turnover","Days Sales Outstanding","Payables Turnover","Earnings Per Share (EPS)","Book Value per Share","Quick Ratio","Return on Equity (ROE)","Return on Assets  (ROA)",]
def debug(turtle_input):
    while True:
        try:
            return float(input(turtle_input))
        except ValueError:
            print("Please enter a valid number.")
def calculate_equity():
    print("equity = assets-liabilities")
    assets = debug("Assets: ")
    liabilities = debug("Liabilities: ")
    equity = assets - liabilities
    print(f"Your equity is: ${equity:,.2f}")
    return equity  # Also return for reuse
Expected = ["Assets=liabilities+owner’s equity","liabilities = Assets - equity","equity = assets - liabilities", "Net Income=Revenue−Expenses", "Working Capital = Current Assets - Current Liabilities","Gross Profit=Revenue−Cost of Goods Sold (COGS)", "Ending Retained Earnings=Beginning Retained Earnings+Net Income−Dividends","COGS=Beginning Inventory+Purchases−Ending Inventory"]
while True:
  print("Greetings! My name is Profitsa Soaring, your accounting assistant.\nOnly numbers and decimals are acceptable inputs.\nalso some equations involve the same math so to keep the code compact\njust enter the input relating to the equation you're solving for.")
  EQUATION = input(f"here is my menu of equations {Equations}\nWhat are you calculating?\n(type x to exit or p to see menu) ").strip().lower()
  if EQUATION.lower() == "x":
    print("goodbye")
    exit()
    break
  if EQUATION in { "net income" , "gross profit"}:
    print("Equity = assets-liabilities,\nNet Income=Revenue−Expenses,\nGross Profit=Revenue−Cost of Goods Sold (COGS)")
    Assets = debug("revenue (numbers only) ")
    liabilities = debug("expenses OR Cost Of Goods Sold (COGS)\n(numbers only) ")
    equity = (Assets-liabilities) # does the same thing as net income = revenue-expenses no worries
    print(f"${equity:,.2f}")
  elif EQUATION == "equity":
    calculate_equity()
  elif EQUATION in ["working capital","free cash flow"]:
    print("Working Capital = Current Assets - Current Liabilities\nFree Cash Flow = Operating Cash Flow − Capital Expenditures ")
    current_assets = debug("current assets OR Operating Cash Flow(numbers only)")
    current_liabilities = debug("current liabilities OR Capital Expenditures\n(numbers only)")
    Working_capital = (current_assets-current_liabilities)
    print(f"Working Capital: ${Working_capital:,.2f}")
  elif EQUATION in ["liabilities", "operating income",]:
    print("liabilities=assets-equity\nOperating Income = Gross Profit − Operating Expense\n")
    Assets = debug("assets OR Gross Profit (numbers only) ")
    equity = debug("equity OR Operating Expenses (numbers only) ")
    Liabilities = (Assets-equity)
    print(f"${Liabilities:,.2f}")
  elif EQUATION in ["assets",]:
    print("Assets = liabilities + equity")
    liabilities = debug("liabitlities(numbers only) ")
    equity = debug("equity(numbers only) ")
    Assets = (liabilities + equity)
    print(f"${Assets:,.2f}")
  elif EQUATION in ["ending retained earnings","cost of goods sold","cogs","supplies used", "cash flow from operations"]:
    print("Ending_retained_earnings = (Begining_retained_earnings + net_income - dividends\nCOGS=Beginning Inventory+Purchases−Ending Inventory\nSupplies Used (Expense)=Beginning Balance+Purchases−Ending Balance\nCash Flow from Operations = Net Income + Non-cash Expenses − Change in Working Capital")
    Begining_retained_earnings = debug("Beginning Retained Earnings OR Beginning balance OR Inventory")
    net_income = debug("Net Income OR Purchases")
    dividends = debug("Dividends OR Ending balance OR Inventory (numbers only)")
    Ending_retained_earnings = (Begining_retained_earnings+net_income-dividends)
    print(f"${Ending_retained_earnings:,.2f}")
  elif EQUATION in ["current ratio","debt-to-equity","return on equity", "earnings per share"]:
    print("Current Ratio= Current Assets/ Current Liabilities\nDebt-to-Equity=Total Liabilities/Shareholder’s Equity\nInventory Turnover = COGS / Average Inventory  Efficiency in inventory use\nReturn on Equity (ROE) = Net Income / Shareholder’s Equity\nEarnings Per Share (EPS) = Net Income / Average Outstanding Shares")
    current_assets = debug("Current Assets OR Total Liabilities (numbers only) ")
    current_liabilities = debug("Current Liabilities OR ​Shareholder’s Equity (numbers only) ")
    Current_ratio = (current_assets)/current_liabilities
    print(f"${Current_ratio:,.2f}")
  elif EQUATION in ["roi","gross margin","operating margin","net profit margin"]:
    print("ROI (%)=(Net Profit/Investment)×100\nGross Margin = (Gross Profit / Revenue) × 100\nOperating Margin = (Operating Income / Revenue) × 100\nNet Profit Margin = (Net Income / Revenue) × 100")
    Net_profit = debug("net profit")
    investment = debug("investment")
    ROI = (Net_profit)/(investment)*100
    print(f"${ROI:,.2f}")
  elif EQUATION in ["revenue",]:
    print("Revenue = price per unit*number of units sold")
    price_per_unit = debug("price per unit")
    number_of_units_sold = debug("number of units sold")
    Revenue = (price_per_unit*number_of_units_sold)
    print(f"${Revenue:,.2f}")
  elif EQUATION in ["break even units",]:
    print("Break_even_units = fixed_costs/price_per_unit-variable_cost_per_unit")
    fixed_costs = debug("fixed costs")
    price_per_unit = debug("price per unit")
    variable_cost_per_unit = debug("variable cost per unit")
    Break_even_units = (fixed_costs)/price_per_unit-variable_cost_per_unit
    print(f"${Break_even_units:,.2f}")
  elif EQUATION in ["ebitda",]:
    print("EBITDA = Net_Income+Interest+Taxes+Depreciation+Amortization")
    Net_Income = debug("Net income (numbers only)")
    Interest = debug("interest (numbers only)")
    Taxes = debug("Taxes (numbers only)")
    Depreciation = debug("Depreciation (numbers only)")
    Amortization = debug("Amortization (numbers only)")
    EBITDA = (Net_Income+Interest+Taxes+Depreciation+Amortization)
    print(f"${EBITDA:,.2f}")
  elif EQUATION in ["inventory turnover","payables turnover"]:
    print("Inventory_Turnover = COGS/Average Inventory")
    COGS = debug("COGS")
    Average_Inventory = debug("Average_Inventory")
    Inventory_Turnover = (COGS)/Average_Inventory
    print(f"${Inventory_Turnover:,.2f}")
  elif EQUATION in ["quick ratio",]:
    print("Quick_Ratio = Current_Assets-Inventory/Current_Liabilities")
    Current_Assets =debug("Current Assets")
    Inventory = debug("COGS")
    Current_Liabilities = debug("Current Liabilities")
    Quick_Ratio = (Current_Assets-Inventory)/Current_Liabilities
    print(f"${Quick_Ratio:,.2f}")
  elif EQUATION in ["average inventory",]:
    print("Average_inventory = (Beginning_inventory + Ending_Inventory)/2")
    Beginning_inventory = debug("Beginning_inventory")
    Ending_Inventory = debug("Ending_Inventory")
    Average_inventory = (Beginning_inventory+Ending_Inventory)/2
    print(f"${Average_inventory:,.2f}")
  elif EQUATION in ["receivables turnover",]:
    print("Receivables Turnover = Net Credit Sales / Avg. Accounts Receivable ")
    Net_Credit_Sales  = debug("Net Credit Sales")
    Average_Accounts_Receivable = debug("Average_Accounts_Receivable")
    Receivables_Turnover = Net_Credit_Sales/(Average_Accounts_Receivable)
    print(f"${Receivables_Turnover:,.2f}")
  elif EQUATION in ["days sales outstanding",]:
    print("DSO = 365/Receivables_Turnover")
    Receivables_Turnover = debug("Beginning_inventory")
    DSO = 365/(Receivables_Turnover)
    print(f"${DSO:,.2f}")
  elif EQUATION in ["book value per share"]:
    print("Book_Value_per_Share = Equity - Preferred_Equity/ Outstanding Shares")
    Equity = debug("Equity")
    Preferred_Equity = debug("Preferred_Equity")
    Outstanding_Shares = debug("Outstanding_Shares")
    Book_Value_per_Share = (Equity-Preferred_Equity)/Outstanding_Shares
    print(f"${Book_Value_per_Share:,.2f}")
  elif EQUATION in ["p",]:
    print(f"{Equations}\n{Expected}")
  else:
    print("sorry I don't understand")

In [ ]:
# @title A quiz project might get added to the accounting project to add study features idea in the making CLI draft
#study guide
score = 0
def x():
  print("gg")
  return score
def quiz_1():
  global score
  print("quiz 1. answer to the best of your abilities if you get any question wrong no worries just try again\n")
  print("x to exit, s to skip a question")
  while True:
    ans1 = input("1. what are the 4 accounting principles (G.A.A.P)\nA)revenue recognition,expense,full disclosure,cost\nB)honesty,integrity,honor,efficiency\nC)fraud,theft,dishonesty,secrecy \n").lower().strip()
    if ans1 == "a":
      print("correct\n")
      score += 1
      break
    if ans1 == "s":
      print("skip")
      break
    if ans1 == "x":
      x()
    else:
      print("incorrect\n")
  while True:
    ans2 = input("2. what does D.E.A.R.L.O stand for?\nA)deadly,exteme,awesome,lethal,operational\nB)dividend,expense,allocation,revenue,liabilities,operationional equity\nC)Dividend,Expense,Asset,Revenue,Liabilities,Owner's equity \n").lower().strip()
    if ans2 == "c":
      print("correct\n")
      score += 1
      break
    if ans2 == "x":
      x()
    if ans2 == "s":
      print("skip")
      break
    else:
      print("incorrect\n")
  while True:
    ans3 = input("3. what are the six account types\nA)debt,expense,asset revenue,liability,operations\nB)dividend,expense,asset,revenue,liability,Owner's equity\nC)dividend,exports,assets,unearned revenue,liability,owners equity\n").lower().strip()
    if ans3 == "x":
      x()
    if ans3 == "s":
      print("skip")
      break
    if ans3 == "b":
      print("correct\n")
      score += 1
      break
    else:
      print("incorrect (hint dearlo)\n")
  while True:
    ans4 = input("4) true (t) or false (f) the 4 financial statements are income,balance,cash flow, and equity \n").lower().strip()
    if ans4 == "x":
      x()
    if ans4 == "s":
      print("skip")
      break
    if ans4 == "t":
      print("correct\n")
      score += 1
      break
    else:
      print("incorrect\n")
  while True:
    ans5 = input("5. What are the three transaction types?\n" "A) Buying, Selling, Saving\n" "B) Operating, Investing, Financing\n" "C) Borrowing, Lending, Donating \n ").lower().strip()
    if ans5 == "x":
      x()
    if ans5 == "s":
      print("skip")
      break
    if ans5 == "b":
      print("Correct!\n")
      score += 1
      break
    else:
      print("incorrect\n")
  while True:
    ans6 = input("what three values are debit types\nA)dividend\nB)expense\nC)asset\nD)all the above \n ").lower().strip()
    if ans6 == "x":
      x()
    if ans6 == "s":
      print("skip")
      break
    if ans6 == "d":
      print("correct\n")
      score += 1
      break
    else:
      print("incorrect\n")
  while True:
    ans7 = input("(t/f) D.E.A.D stands for Dividend,Expense,Asset,Debit \n").lower().strip()
    if ans7 == "x":
      x()
    if ans7 == "s":
      print("skip")
      percentage = (score/7) * 100
      print(f"Your score is {score} out of 7 that's {percentage:,.2f}%\nthis concludes the quiz\nNo matter the outcome keep trying you'll get there")
      break
    if ans7 == "t":
      print("correct\n")
      score += 1
      break
    else:
      print("incorrect\n")
  percentage = (score/7) * 100
  print(f"Your score is {score} out of 7 that's {percentage:,.2f}%\nthis concludes the quiz\nNo matter the outcome keep trying you'll get there")
  return score
def quiz_2():
  print("quiz")
quizzes = {"q1": {"topic":"accounting principles", "quiz":quiz_1, }}
for key, value in quizzes.items():
    print(f"{key}: {value['topic']}")
q = input(f"select your quiz or x to exit ")
if q.lower() == "x":
        x()
elif q in quizzes:
        # Call the corresponding function #f6
        print(f"You selected: {quizzes[q]['topic']}")
        result = quizzes[q]['quiz']()
        print(f"\nResult for {q}: {result}\n")

else: #hmm
    print("Invalid selection")

In [ ]:
# @title text_input acts like CLI equivalent of input
from IPython.display import display,clear_output
from ipywidgets import (Style,Layout,Combobox,
    Button, Checkbox, Dropdown, FloatSlider, IntSlider,
    RadioButtons, Text, Textarea, ToggleButton, VBox, HBox, Label,interact,Output,IntText, FloatText)
out = Output()
# Text Input
text_input = Text(value='hey', placeholder='Type something', description='Text:')
def handle_enter(change): #
    with out:
        clear_output()
        print(f"You entered: {change.value}")

text_input.on_submit(handle_enter)
display(text_input, out)

In [ ]:
#@title YT link
from IPython.display import display, Markdown

VIDEO_ID = 'gsNaR6FRuO0'
VIDEO_URL = f"https://www.youtube.com/watch?v={VIDEO_ID}"

# Using Markdown(for custom text) to create a clickable link
print_colored("VIDEO PLAYER IS CURRENTLY UNAVAILABLE DUE TO ERROR 153.", "red")
display(Markdown(f"**Click here to watch the video directly on [YouTube]({VIDEO_URL})**"))

VIDEO PLAYER IS CURRENTLY UNAVAILABLE DUE TO ERROR 153.

**Click here to watch the video directly on [YouTube](https://www.youtube.com/watch?v=gsNaR6FRuO0)**

In [ ]:
# @title HTML code


from IPython.display import  Audio,display, clear_output,YouTubeVideo,HTML,Image,Video
from ipywidgets import Layout,Combobox,Output, FloatText, Button, VBox, Label,FloatProgress,Tab,Text,HBox,HTML
# <p> paragraph
#<span> for customizing text including color
#<br> similar to \n for new lines
# end the HTML code with </> matching the opening
out = Output()
colored_text=HTML("""<p><span style='color: #00FF00; font-size: 20px; font-weight: bold;''
    >green</span></p>""")
btn = Button(description='Click me')
labs = HTML("""<p><span style'color: #00FF00;'>HTML styled text</span></p>""")
box = HBox([btn,labs])
combo_x = Combobox(description="text",)
tabs = Tab(children=[btn,combo_x,box],layout=Layout(width='800px', height='auto', border='8.5px solid #00FF00'))
tabs.set_title(0, 'Base')
# Display the widgethtml_widget
display(HTML("""<style>.widget-button {color: #00FF00 !important; /* Forces green text on ALL buttons */}</style>"""))
display(HTML("""<style>label.widget-label{color: #00FF00 !important}</style>"""))# forces green on description in widgets
display(HTML("""
<style>
label.widget-label {color: #00FF00 !important}
/* Forces green text on ALL buttons */
.widget-button {color: #00FF00 !important;}
/*for colorng input*/
widget.value{color: #00FF00 !important}
/* Active Tab Background */
.lm-TabBar-tab.lm-mod-current {
    background-color: #00FF00; !important;}
/* Target the active tab header */
.lm-TabBar-tab.lm-mod-current {
/* Remove the default bottom border to avoid double lines */
border-bottom: none !important;
/* Set the border color, thickness, and style for the TOP edge */
border-top: 7px solid #00FF00 !important;}
/* Inactive Tabs Background */
.lm-TabBar-tab {
    background-color: #00FF00; !important;}
/* Tab Header Text Color (optional) */
.lm-TabBar-tab.lm-mod-current .lm-TabBar-tabLabel {
    color: #00FF00 !important;} /* White text for the blue active tab */
.Textarea.widget-value {color: #00FF00 !important;}
</style>
"""))
display(colored_text,tabs,labs,)

HTML(value='<style>.widget-button {color: #00FF00 !important; /* Forces green text on ALL buttons */}</style>'…

HTML(value='<style>label.widget-label{color: #00FF00 !important}</style>')

HTML(value='\n<style>\nlabel.widget-label {color: #00FF00 !important}\n/* Forces green text on ALL buttons */\…

HTML(value="<p><span style='color: #00FF00; font-size: 20px; font-weight: bold;''\n    >green</span></p>")

Tab(children=(Button(description='Click me', style=ButtonStyle()), Combobox(value='', description='text'), HBo…

HTML(value="<p><span style'color: #00FF00;'>HTML styled text</span></p>")

Below are some optional sound effects the code will run either way,it will play after booting the functions and after a timed break.

In [3]:
# @title 🟢Dial Up ▶️🎵 (sound effects)
old_dialing = b'\xff\xfb\xd0d\x00\x00\x07\x07{9\x1db`\x02m\xcff\xc0\xa0\x8c\x00b\x9dq#\x99\xee\x80\x01\xcc\xba\x9fW\x060\x00\x00\x02\x08\x10\x0c\x86\x1aci\xce \xe9\x8e\x08\xe1c\xb2\x95\x84\xd1\x03\x93\x00Lc\x81p\x9bjy\xd9\xccd\x80\x03\xef@\xeeP\xc5\xc0h\x80\x1c\x18\x02\x88\x18\xd0\xb40\xc4\xe2t \x85\xd1\x97\x16X\xe3>`\\7Q09\x83\x98A\t\xc5\x97\xc70\x82\x13\x86\x88fd\xd8\xe6\x13\x88\x93c\x9e9\xe4\x1c\xdc\x98\x1c\xf1\xcf\'\xdd\x02\xe1q\x05\x97\r&e\xf2\xfat\x0b\xe5\xf3t\xd4`\\4Yp\xb8\\4B\xba\x8b\xe5\xf2\xf9\xbajA\n\x08 \x82\x08V\x99p\xb8\\4A\x96\x9ah!\xa6\x9ai\xa6\x82\x082e\xf2\xf9\xba\x89\xb2|\xben\x9e\x82\t\xa6\x9b\xf4\x107N\x82\x08 \xcb"\x84P\xd1\xbd4\x0b\x85\xc2\xe1q\x06Y|\x8a\x17\r\x1b\xefA\x06Zi\xa94\x90A\n\xd3\x7fM4\xddE\xf2\xfai\xa7\xd0M7\xfa\x05\xf3t\xf0\x00\x11\x8cn@\xf8\x00\x040\x01\x05]\xdf\x8e\xe7\xa2\x17Q\x10\xab\xbb\xc007\xe2!h\x88\x85\xff\xd7s\x88\x9a"!~\xe8\x9b\xbb\xbe\x8e\xfa"y\xa2\x17]\xcd\x00\xc0\xdfDB\xa8\x89\xff\xfb\xbb\xf1\n\xa2!\x7f\xff\xbb\xbb\xf1\xdfD/\xff\xeb\xbe\x80b\xdfDBp\x00\x04\xdd\xcf\xeb\xbb\xf1\n\x84\x10\x85\xbb\xbe\xee\xef\xfe\x8eq\x10\xbf\xfa\xef\xfa;\xf1\x11\t\xc0\x00\n8x\x00\x00\x00\x00H\x00\x03\tC\x00\x00`,\n\xe6\x0e 4`\xb4\x1ff)B\xd0`v\x08C@\xdaa8\x0b\xc6%A\x9ci\x12\x92f7\x82\xfe`\x0b6&w\xe0\xc6:\x1a\xe6!!\nb\xc6\xb3f\x90b\xc4bDYg\x8c\x83hi\x99\x0ea\xe0\xa8t\xcd\xe4g\x126b\xdb\xe6d\x102`\xc0zb\x10\x08`\xd8Zl\xa3\x14e\xf1\x8aax<$\r\x03\x80\xa5nW\xe0`-\x91&\xa1\x80\x01B\xe40t\x1c0\x10\x13\x00\x00t\xa3\x00\x8dd\xc0\x84f\xf2;kl8\x01uB\xc0*\x14\x15@:\xb9c\xd8\xbb\x8fA9(\x9c\x0e\x00\x90L\xdb4V\x1c\xb0;\xc7\xf7\xffOE\x1b\x9fw\xe6\xa2\x89\x88\x98\xb1\x06\xb5\x1cSe\x93\x96\xbb\xaf\xff\x96^\xce\xf5=\xb9~\xb0\xbe\xe4\xce80#\x8c\xedE\xa2?\xff\xff\xff\xff\x87;\xcc\xfb\x9e\xb0\xc3\xe9\xa6i%:\xb5\xaai\x9c\xe9\x7f\xff\xff\xff\xff\xff\xff?\xcf\\\xc3\xfb\xfd\xfe\xebUp\xb5[\xb8\xfdZ\x80\xb0\x19\xff\xc0\x1fO\xf0T`,\x0f\x12\r\x03@Q\x19"c\x0c#\x1al\xeei$\'c5"ay\xb2T\xbe\xc4\x8a\xd8\x97}5\x8cD\xf5\xd2\xb7r\xe5\x04\xbf\xc3\xd4V^\xf7\xa8r\xea\xfa,\xbb\xf3\x90\xcaAkQ\x0b:\xd4\xe1\x1f\xfeE\x94|\xb2\xa6\xdf-$\xa18\x96\x9d\xf2\xe3\xc4+#\t\x13\x9d\x97\x0b\xa4\x0eV\xae\xea\xa6\xa6\xdbi?\xf3\xb3c\x9c\xa8SC\xb5?\xff\xff\xf1n\xf0\xb13\xa2D\x84?\x05\xc4\xa7\xd0cJ\x0e\xcc\x04\xd0\x02\x8c\x03P\n\x0c\x05\xf0NL\x02\xf0\x13\x02\xc0\n\x18\x1d\x80i\x980\xc1\x1c\x98TA\x10\x98\x16\x84\xd7\x9b\xba`@\x98\x80!A\x18\x16\xe09\x98\t\x008\x98\x0e\xa1\x14\x18B\xa2?\x1a[*\x8b\x99\xe3\xc3\x96\x98\x80\xc1\xcc\xff\xfb\xd2D$\x0c\xc5\xf8(C\x8f\x7f\xa0\x00\xc1%\xe8\x82\xef\xf4\x00\x17H\xc7\x12n\x7f\x86\xc2\xd7\x99c\r\xcfd\xe0\x9c\xab\x10\x1d\x0f\'\x19^\xdf\x18\xb2\x0f\x18b\x02\x02\x813\x08\x00A\xe0\x00\xb9\xc6\x1c\x02\t\xf6\xd3\xde\x87A\x89\x08\x06A\xe1\x89\xaf3K.\xdbw0\x10fLe\x06\x94\xd3\xbbb\x80\n\x0b<\xd5\xb9\xcdr\xcc\xae_\xc9\xbb_\x9fs\xed\x9c\xfb\xce\xfe{\xcf;t\xf9\xfd8D\xd0ae\xc2*\x18\x08\x06B\xc9\'X0.\x176\xaeCZ\x1b\xa0e\xbc\xc5\xefv\xef\xef\xb5\xa9t[\xb7\xff\x14\x00%\xb3\x00\xfc\x00\xa3\x00\x9c\x02#\x01<\x11\x13\x00\xec\x01@p\x06f\x05\xd0\x15f\x0b\xb0=&\x10\xe0>&\x0b\x10\xf7\xe6\xd782&\x1d\xa8H\x06\x04\x18\x0b\xe6\x02@\tf\x04\x98.\x86\x138eF\x8aJkfd\xf0\xcd\xe6\x1e\x10]\xe7\x11\xc0\x06\xed\xc9\x86I\xadF\x1a\x89\x86\t\x82E\xad\n\x81\xa8\xce\x0e\x04\x8c"\x02\x1c(b1.`\xc3\x02q0\xbe\xcc\x9bG\x8d\x9d\xb70\x00\xa4\xa0\xcb\x8aG3\x14A\n+F\xabg\xca~\xd7\xcb\nK\xd6\xed\xd4\xe6\xf3\xe7\x7f?\xff\xfc0\xcf?\xfds\x97m\xf3\xf5\xcd\xf7\xfe\xeea\xe3\xf0\x04r\xe5\xfc\xe6\xfc\x95\x16\xea\x17\xe17\xa4\xf5\xba\x94M\xabE\xa1\xb4\x9d8D\xe1\x86\x0c\xb7\xff\xf4\x00$d\x12\x0c\x0b\x00\x02\xe6(\x8b\x18(\x0ec#\x91\x88\xc9\xa0`\xe9\x98l&\x17\x00\xa3F\xbb8(\x86\x07H\x08\x86\x01\xd0\rF\x02x\r&\x02\xe0$\xc6\rxW\xa6Rr\xcd&A\x98mf\x0fP)\x06\xb8s\x1c%\xeek5I\x95\t\x08\x82`\x81\x82o\x98<\x16\x01\x01\x0c\x86U\xb5\x95)\xfcl\x12\x15\x07\x87T\xcd!\xc3\x86"f\x1b\x1f\xcbY54\x15\x16_$\xc0\n\x98g\xbf\xa7\xaa\xef)\xd4\x81\xb2#\xfa\xc2\xbb\x0c\x11\xa68P\xbaJ*\x99\xc5\xa9\x1d\xdaW\xf6AM\x04\xccCO\x1d\r\x89\x8bV9w\x0b\x1a\xafKo\xb2\xed\xd1\xe2v\xc7\xaf\x04\x94e\xde\x91\xe8\xff\x0eh\xff\x8b\xa3\xa8\x9b=`)\xeb)\x88\x81\x04\x803\x10*\x84\x86\xa6"\x16\x18\xc4\xc6g\x02\xb1\xae\xeaf<\t\xf0~n.\xc6\x07\xe0\x86`\x88\x05\xc6\x08`f`\xc4\x12\xc6\x19$2m\xa1\xed\xe6\x9f\xe3\xdeb$\r\xc6\x18\xc1$`\xc2 \xe6\x08\xe1N`\x1c\x02\xc6q\xa6\xb0\xa0#\x88\x89\x8e\x85KT\x10K\xbb\xcd\x16(\x16\xa9\xf1\x91\xcb\xf9Nc\xba\xbdi\xe1\xda\\\xd8\xc8\xb1\x92\n{\x19^\xddw\xfa#\x18\x86 \x98\xdb\xcf7\x1c\x97OI\xdd\tlm\xdd\x83[\x83\xfc\xfd.\x96\x04\xce\x9e6\\\xcf\xed\xe5\x8flg(\xa9\x8d=\xfc0\xab7K-\xcf\x1bEf\xc1\x11R\x04A!\x9d\xdd\x9e\x8e\xdd\xbf\xb7\x9e$\xed\xfaj\x00H\xc8$(\n\x18&\x03\x99n\xff\x98\x16\x1a\x98\xb8J\x18z?\x99\xcc\x91\x1b39\x98\x91\r\xb1\x1a+d\xc4\x18#\xc0\xdd\x98\t`\x0c\x18\n =\x18\x16\xc0\xad\x98<b\x9b\x1a\x15\x13\xa9\x19\xa8\xe1\xf3\x18$@\x86\x98(-\x1aq\x06\x9ap\xa8\x99~3 LhSVq \\`\x070l$/{\xc4\xfe\xbcw\t\n\x02!\x8a\x12\xfe>P4\x9c\xc6 \xc1g>\xae\xbcbD\xad\xff\xfb\xd2d;\x8c\xc698\xc3\x9b\xbf\xe9\xb0\x95\x86(\x93o\xdb6\x1a\x88\xe5\x06/\xf0\xd1Bq\x94!\x89\xbfl\xd8\x82A\x8c\xa3.\\\xb3V\xb2\xc9p\xd8\x8b\xb8\xd5\xd9\x83\xfb\x1ct\xe3O\xa4F[g\x95\xf1\x9d\xa5\xbb\x0f\xbe\xd5]8b[,\xbds\x1c\xb0\xeeV\xea\xcc\xd8\xa9j\xa5J\xd9\xff,\xf3\xf5\xfd\xc3\xf5\xfb\xb2\x8c[{2vn\xbb\xa2yK\xeb\xab\xb3\xa6\xca9\xaau\x00kD\x01\x12dD"\x06\x08je\x00&\xc4la#\xa7>\xf2`\xa8\x0c\xa6\xdad\xeaa\xa6\x08\xa0\xe0y\x16\x01\xf3\x000<0w\x0cs!w\xdd1\x7f\x053\x0f\xe0\x893\xd6c3\x812u\x02S\xc0p\x11X\x98\x08\x80\x94\r+\x8b\xfbV\x82-\x7f\xa5P\x07\xd6!*\x88Ar4@\x9b\x83\xe0\xf9l\x07\x0c\xf6W\xcd\xff)\xe7\x1e\xe6}6\xf3\xcc\xbd3\x94\x13\x90}\x03\xf1\xb9\xcb9\xf3*[\xba\xb9\xf1Y\x8c-\\\xddmw-\xfe}\xbf\x96{\xb9\xe2\xeb\\;*`x\x03\xecP\xc0\x06\x00\xf4B\x00\xb1\x84\x08\x17\xc2\xa60\x11\xc0I0:@\xd2\x06\x01|`\t\x83\xaea\x19\xe4Ts4\x1c\x08b\xdf\x06\x0ea!\x81\xe4a\x06\x00\xfcaB\x83\xb6b\xa7\x11\x1cq}\xea\x88nM\x10xb\xc7\x866aG\x85\xd2aq\t\xf8`\xd6\x05\x90`g\x81vg\x04\x80a\xa8!8,&18P2rY\xd7]\x8e;1\xa1I\x80Ay\x94\xc3\x94i\x9e\xaa\x86\xc3\x1a\x04\x0fY\xbb3t]\xb1\x90\xf0\x84\x13,\xabMI#\x95\xdc\x86\xe0\xc7\xe9\xde~h\xe0\x0cg\xb0ti\x99\x89\x13 \x01\x92@\x12* Q\xea\x99x\xf9\x8c\xcd\x9c\xb8\xef\x9f\xf6\xf9\xbe\xe3/\xc2E\x05\x12]\xe7\x16\x82.@g\xcd\x8a\xb5\xa1\xc4g\x1d1\x9cr\x07\x9f\xd5if\x0b\xe6o\xb1}\xa9r\xc8GW\xda\x05\xa0\x0eIzAJ\xa6dv\x02D\x0c\x873\xa3\xb3\x8f\xe92Pc\xa3\xab\xb3\x001\x05\x00S\x07`\x0509\x00s\x06\xa0;0\xe7\x0fcy\x86~5\x89\x01  ^\x1b;\xa1\xbb\xdf\x98\xb6\x08\xeb\xc1\x8e\x87\x0b\x11\x96Q\x9c\xb4\x85\x1c\x1d\x00l\xfa\x8b\xf9\x00\x92\x99S\xbbo#\x91\x0f\xa1\x1b\xdf~\xa4.\x9ae\xe5\xed\xedwvp\xdd\xd8\xdc\xbd\xae\xc9\xb0\x92\xd7\xbb-\x9d\xb3\xdf\xa5\xb1M?\x1a\xb5\x8c\t~l\xe9\xa3`H\x90\xd1\x904$\xf5\xe8\x90E\xdeE\x9f\xa5\x8c\xae\xad;\xfb\xbd\xd5\xdf\xd9\xf73\xfe\x9a\xea\x03\x00\xbc\x05\x00\xd0\xc2G\n\xe4\xc0\x1a\x00\xf0\xc0\x87\x02d\xc0\xb2\x01\xe0\xc0\x9d\x03T\xc2v\x068\xc7\x1b\x82\x08\xfb\x06\x1f\xf0\xc5"\nd\xc25\x06\xa8\xc1R\x06\xc4\xc1\x87\n\xa0\xc2\x90\x1e\xdc\xd5\xc7\xdf\xdc\xd36\x1a\x84\xc2W\x02\xd0\xc5b\xcc\xdb\xdc(\xddw\xb8\xd1\xc2\xbc\xc5\xf0\x18\xc1\x80\xcc\xc0\xb0\xa9\xe6k\x06B\x84\xe3@2\xe8a\xd2\x97\xd8Q6/\xe3r\x8d9+\x0c\x90\xe6L\x12\xe2A\\U\xa12\xd9)}\x83\x86x\xd5/2\x91\xd2e\x16\xb1A\x00\xceIwO\x9dYu\xd4\xe9\xe2L\x1ah()\xa0xk\xd4r\'9\xca\xb3!%\xc8\xac\xa4~\xad.e\xebs\xe2\xaf34\xcf<\xcf>\xd2N\xb7\xe5\x1e\x9b\xe6s\xeeY\xcc\xbf\xbes#>\x13v\xf3\xff\xfb\xd2Dd\x8c\xc6\xddiA\x03\xfd\x1b\xe0\xb6$\xe8Rs\xfd6\x1b`\xef\x14O\xe91\x03\xa2\x9d\xe2\t\xcf\xec\xe0\xb9\x17\x1e\xb5\x04\x84\xa9KIR9\x83\xc1{\x12\xd5L\x8ep\x1c\x00\x18L\x1a\x0e\x00\x9c\xb7\x12a\xa1!\x87Mf\x1cC\x19e\x92w\x8d!\x8b~h\xb1\xd3\xb4\x17\xa1\x87\xb4\x0b\xb9\x82\x8a\x08q\x81\x84\ni\x81\xba\x11\xc1\x82\xdc5\x99\x94\xbf\x94\xc9\x93\xe4/i\x81^\x10\x01\xa2\xc1\xc1\xc3\xacQ\xb5&\xb0\x93\x9a,+\x18$\x10\x80@\xe4<\x15\x05\xcc;\x05\xd7\x9cb\x82fh\x94\x98\x1e\x03\xb7\n\x93=\xcc<\xc4a\x85q\xc1\xf4\xb1I\x03\xb44%\xcfr\xff-\xf7q)\x0cF\x17\x14vg\xa9\xa5S\x91+|\xbb\xbd]\xb1v\xa5j{\xc3EE\x1a\xeb\xa9\x00\x0e\x02\xd1}g\xba\xeeGe+&\xe7^\xac\xcd\xfd\x08\x96~\xf6\xe2\xf4\xdc!\xeb\xf9\xba\xbb\x18\xf6 \x15\xb5KJ`\x03\x80 `l\x01d`\x12\x80\x06`\r\x00D\x04\x01L\xc0o\x00\xd0\xc1(\x02\xe0\xc3\x8d\t\xec\xd5\xc0\t\x04\xc1\xde\x02\xb0\xc0\xbd\x02l\x10\x04Q\x818\x00\xd9\x83b\x0c\xf9\x94(q9\x91\x9a\ry\x83\xe8\x08\xb1\x82\x8c\x08\xc1\x82\x06\x0e\x99\x80\xaa\x02\x98\xb0\x1f\'\xd4\xd9\xc0\x84\x05\xa2f\xd9\x03\xca\x1d\xa7\xc6\x85\xd8\xcaC \x0cYy\x8c\x0c\x15\x8c\x14\x0cP0\x14@\xb9\xe9\xcc\xbf\x0c\x9b\xa5H\xf8\xcb\xa4\x0f\xa2\x8e\x91\x12r\x1e\xb7\xfa\x04\x7f\xe8\'\x89\x0b\x9c\x14\x8f\x85\x06M\x89\xc4\x02\x93\xe4\x84e\x90\x9bF\x93(\xd4\x8b\xd4\x89\x86\xc8\x13h\xc1\x19g\x12#I\x96\xd0\\\x9c\xa2\xaf@u\x13\x91\xc1\xec.\xa4_\x05ZmB`\x99\x03d\x07EV*\x81c\x01d\x9cC\r+\xca\x0b\xbf\x10\xd9\xfe\xfd\x0c\xff\xa8\x00`\x01\x80\x93\x00\x86\r\xb8\xf61\xf8t\xc1D\xa3\x0c\x15\xcd\x1a2=ep\xc4\xa3*4\xd8\xd0\x13D\xc2\x04\x04\xa0\xc0\xcb\x03\xfc\xc0/\x03\xb0\xc1\x1e\x03\x0c\xc2\xb7\x04\xa4\xd0\xa0.L\xcea\x06,\xc2\xc4\x05\x00\xc1\x8e\x06p\xc1;\x0b\xc4\xc0=\x03\xd4 \x11\x03\x8fC5GC\x03s3\x14\xa0\x16\xa1\xb9+\x19\xea\x98\xa9\xa1\x8e\x07\x89%\x98\xc0\x80\x14\xe8* V b\x80@\x10\xb42T\x06\x1e\x94\x8a\x8f\\\x9d\xf8v\x10,hI\xc8\x82\xdf\xe8C\xffAGI+\xa0\x8c\xcb\xe5\x1428~!)\xa3\x8cJ\xe6\xa5\xb3\xf2\xb9\x8ci\xeacn\xa66)\xe5\x17mX\x95\xcdN\xcb)\xeeY\xb7syX\xa4\xdd\xfaJ\xf9^\xafs.gS\x1bu.\xda\xb7P6\t\x90\x03\x90\x0b5fEM\x05\x81\x05%h\x08\xa0[\xb0\xd5\xea\x1bJ\nu\xfdlq\x0fw\xa7K=5\x00\x00<\x89\xb6\xad\x03\x00`[0#\x06\xe3\x01pm0Z\x03c\x08\xd0\x060\xac\ts\x08Q\x1e0S\x19\x13&A\xc70\x90\x0b\xd3\x18\xe1)\n\x06\x11\x85\xd8 \x18I\t\xb9\x86\x80\xfb\x1a`\xb2q\xae\x19\x84\x18k\x10Y\xa3b\xa7Z\x19\x9b\xa5\x1cjf\xd9\x89zG\x1d\x93\x83\xe3\x87eq\x1bBNb\x88\x99\xaf\x91F\xeb\r\x1b\x01"b\x92\xc1\x81G\xa6&\x10\x19\x0c\x0cbA\x08\x00:[\x01\xa5\x17u\xc5g.+vr\xc1b8tE\x00\x15\xc3Zo`Z \x81\x0bL\xff\xfb\xd2dI\x80\xd9;P\xc8\xd3\xdc\xc3\xb0\x97e\x18A{cz\x17\x98\xbb\x0c\xd5\xdc\x80\x034\x19\xe1\n\xbd\xc0\x00\x14\xa3\x14\xc2\xc2"p\x00(xL#\x00\xc5XZ\x81\xad\x1b\x0e\r\x805#X\x01x\x00\xb1\xc3#\x80q\x8b\xaa\xa2\x8b\x8d"V\xd3\x07O\x94\x12\xa6\xe2}\x97\xe4\xba\xc9J\x9d\t\x9c\x8a\xab\x02\xc4\x16r\xedl\x8f;\x11fN\xdb\xcc\xce[\xb3\xb6\xe6\xb1&\xe2\xfa<\xee3\xa3\x10\x83\xdf\xd8\xf4\xbe\x1d\x86\xa3\x929l\xaanr])\xa0\xb1j\x96\xe5\xfb5\xb3\xbdKr\xdc\xed4\xcd\x8b\xf4\xb5p\xbf\x8e\xb3\xc7-\xf7\x1a\xdb\xe5\xaa\xba\x07\x82@Pl\x04\xc0\x13@\xac{\x1dQ!\xec\x1b\xf1\xe1\x02\xddG\xc00k\x05\xc0(\xb4\xe5\xee0\'\x03\xd3\n\x00\x1a1\xe9d\xe3\xff\xe1\x861z\x07S\x05PZ\x0b\x83\t\x82\xb0i\x18l\x8e\xe9\xb2\'\xd6\x9b\r\x92\x19\x88\xa0a\x1at1\xd3\xfe\x9b]\x99\x99\x07\x17\xbc\x14\x12\x1c*\xd0\x1dR\x10x\xeb\xdb-\xc3\x02S\xa2\xb2\x8bp\xfb\xd1=N`\x822\xba)\xdc\xf7*O<\xff\x7f\xff\x9f\x10\x89H\xd7\x9b\xdaV\xb7\xde\x87\x06\xea\x0e\xadI;\x99v\x94"\xf5D\x99\xff{\xfb\x10\x15\xd4\x964\x98\xbe\xbb$\xd6\xbcq\xa5\xfc\x1e\xb5\xe0n\xde\xb6\xed\x98\xa5\x00\x03\xf2\xa9\x91\xa0!\x83\xa0\xf9\x8f\x80\t\x00ta\xd0\xa4d\x00h`8Za\xc0\x92h\xb9\xd4\x7f\x94\xfae\xb8Vb \xf88\x17\x98\x0e\x16\x8e\x0fF\xe2\x16\x06\x1e\x0b\xe6U\x91\xa7v\xe4Q\x0e\xc0p\x18@\x89\x91A\x90y\xb78A\xe7u\x87\x13\xc6`\x82\xa5\xaa1\x00I\x80T\x15S\x16\xbd\xcfZ\x08\xa8c\x1e\xca\xe0\xf8~\xdd\xc7\xf5q\xc0\xee\x9c)\xe9~\xa5\x91f\xb9\x07OaK\x03\xc9&\x9c\xb6v\xba\xeeT\xa7\xb1\xc8bU\x8fi)3\xa9\x9e\xfb\x9eU\xedc\xadr\x9f+\x05\x88\x03\x02\x807\x82\xe2\xe49\x96\x08\x19\xb8\\\x0e\x9b\xf6\xb6\xf0;\xc5\x94\xac\x92\xda\xc70\xcb\xb1\xcbc\x96\xf5\xebM\x9d\xf5\xf4Y\xde\x90Y\xf1\x11\x80Q\x82\xc0\x1a\x98\x03\x00\xa1\x80@\n\x12\x81\t\x08#\x98\x1c\x86\x19\x8fyl\x9e\x06+y\x88\xc8n\x18j\x02\xf1\x83\xa0\x83\x18\x9a\x06Q\x87A;\x1a\xe8s\x81\xbc\xc8\x85\x18\\\x03\xb9\xbb"\x86t\xa2\x89D\x0c\xc6\x890\xe8\xac9~f  \x18\x0edR\xa9\x81\x82\xa1\x02v\x96\\\xb0H\x14\x04\x1f\x1c\x1d\x18\xa8\x16\x93Q\xa6\x96\xa5\xef\xb8\x04 \xc0\x16#\xda\xff6v\xb2\x8f\xccB\x86\x1f\x94A,\x9e\'*\x7f#\x13\x9d\xce\xbc\xd4\xa2rbX\xfe77\xee\x1f\xa3\x86\x1f\xcb\x12\xfd\xcb\xf2\xaf\xac\xb0\xaf\x9d\xbc.^\xee\xf9\x9exac\x99w\xf9t,\x18>*\xf7$\x91\xe8\x8c\x0fg4/\xed\xdf]Z\xf2\x89\xadX\r\xe1g\xd9K\xa8U;\xe6\x15<\xd4\x96\xdc\xb5L\x00\x00\x04\x04\x03\x83`\xdb%\x80\x00\x00\x03\x06@\x80 \xc4`\xa8\\`\xc0\x1e`\xe0Le\x91P\x0c4Ma\x13H\x83\x13A\xc6\xe3\x12\x04\x93\x87\x07C\x02\x86\x83\x1e\x80C\x03\x80s_\xc03W\xe0sWI\xc01x\xfc\x0c\x12?\x03\x1b\x83\x808\xdc\x07y\xc7\x81\xddD b\xd1\xa8\x18\x00F\x06\x07\x01\x05\x88\x17\x89 8\xf3`\x16W\x81\x93\xff\xfb\xd2d5\x00\x07AO\xc8nv\xa0\x00\xda\xc7\x88\x99\xcfp\x00"Y\x13)Y\xef\x00\x02\x01\x8f#\xcb;\xa0\x00\x89@b@0c`j\x02)\x86\'\x07\x04\x800\x02M\x01\x8e\x00\x80\x14\x0c\x17a\xbf\x87x\\\x84X_\x90\xf0\xb2\xe0\xb8\x14C4G\x81\x82@ai\xe4X@2`\xc0\xa8u\t]\x12vb\x9b\x9a\x00P@5\x10\xe5\xc5\x06D\x9e\xf5f)\xaa\xf5\x8e\x02,\x1f\x00\xd0\x10\x00}\x8e6\xb7\xff\xf2.n\x81\xf3\x06\'\x0c\xcd\xff\xff\xffM\xd0H\xc1\x8d\x16\x99\xbb\xff\xffq\xc0\x88\x1d\x04\x10\xdf\xff\xff\xff\x0b\x00\x13\xc6\xa2\x00\x00\x01W\xe0\x00\x00\x00\x18\t\x03a\x80(\x11\x18\x08\x80\x81T\x12D \x8e`L\x04F\x1aeZi\xb4\'&!gFL\xce\xa6\x03\x88\xaad\xa4\x0e&\x04\xc6\xf8mJzf\x19d\xaes\x96x\x86\x04\'\x86j4\x0c\x86\x95\x8e\x19\x95\x9cg[\xe1\xb7\x94\xc7*f\x82\xb4\x86+\x17\x18p\x92c\xe1\xb1`.db\xf8\x90d\xce\xe3\x83\x07\x08\x90d\xc3\xe4S\x12\x02\x10e2\x80\xc1C\x0c\x03\xd72\x8e\x02\x8c\xa0\xe0\xdb\xb8\xc8\x13-\x12\x19R\xb1\xf0\x94\x0c\x08\n6\xef\xbc\x02J\x00J\xd7\xb2G\x0e\xc9\xa5\x9b\x87ms\xe5\x16a\xfa\xdb\x88|\xaa\xe68\xda\xab\xdb\xbf\xaf\xbf\xf5\xf3\xe79\xcd\xcd\xe3\xacww\r\xff\xf7\xff\x7f\xaa\x98\xeb\xff\xba\xd5\x9e\xa5H{\x8a]\xf1\xe0M\xccGn\xdfG\xfam\xeb\xb3\xff\xa7\xfe\x8f\xd3H\x00\x00\x07v\xfa\xedB\x00@\x00\x18:\x86Q\x81\x18y\x82Ax\xc0t1L\x16\x01\x0c\xc0D\x04\x8c\x19\x07\xec\xd8p\x95L\x04P\x9c\xdddTL~\x89(\xce\xa9\x1a\x8c8\xc3(\x10(\xc6\x1d\xe0\xc0\x05\x06\xd3\t \x870\xa1\x08\xc3\n\xc5\x0f5Q\x1d\x83\x12\xe4\x075\xee*\xe3\x0c\xe1\xbe8\xbc\x13\xb3\x03aS0e\t\x03\x03\x10\x110\x8e\x04\x18fh\xc3X\x14\x1fJ\xc6\x0f\xc0\xce`\x04\x03&\x00\xc02`\x16\x07P\xfc\x1cJ\x0331\x17|\xa8\x04b\xc0\x0e\x1c\x01\xa6\x05 |`\x02\x01\x06\x05\xa00\x01\x008U1\x80\x08\x05\x0b\x014\xea\xce_&\x01\xe0\xe6`0\x00\xcd\xa8`\x10\x98\x05\x00I\x80\xa0\x01\x8c\x80b\xc5\x04\x80\x17\xbev?^\xfb,Y\xfan\xe2!\x00\x10(\x03(9vUU5PE\xbd\xef]\xff\xff\xff\xff\xf8\xaa\xb78\xec:\x1bq[\x8bMn\xdf\xff\xff\xff\xff\xff\xff\xff\xff\xf8\xd3W\x95gf\xad\x9a\xdc\xa6\xff\xe0\xf1 \xd1\xe0\xa8T\x02\xef\xff\xcb\x08\x9a\x12\t\x01\x90H\xf0 \x81\x17\xdf\xaf\x92\x00\xb5\xa4\x01A\x92\xa8\x10\x14\x01\x8c\ni\xc2\x06#\x05\x14S%D\x90\xa0Bd\x10\xbc\x1cV\x1c\xfcr\x83\x10\xe3\'\xc9\x10H\xdce\x88\xb4s\x94\x9b\x12B(\x01\x15\x8c;\xc0P\x13(,\xc7\tT#F@\xc3\xd6\xfag\x80\x91\xa2\x8a\xbb\x98\xa3\x9fm\x9f\xbcqP\xd9e\'\xc9kU\xc7\xean\xdd\x8f\x95T\xa6\xbf\xb5\x07\x0f=\x0f\x1c,hf\x84l\xd5\xd5\xf4QS\xab^\xaeOG\xd5\xc9^\xbf\x8f\x00\xa4S\x028\x03\xb3\x03\x94\x16\xc3\x01\xa0\x03S\x01X\x05S\x01\x94\nC\x02\xdc\x17\xa3\x0b\x8c3\xa3\x06\xccO\xe3\x05\xbcq3\r)\x02#\xb48>\xd3"\xf0XS\t\xff\xfb\xd2d\x1a\x04G\xe6:C\x17\x7f\xe0\x00\x88\xc6)\x1a\xeel\x00Xl\xdb\x1dN{\'B&\x9ad)\x9e0\xf8\xf8\x0f\xb3\x06\xd0\x0b\x91\xa0X\x8c\x18 \xd3\xcc;\xb0P\x0c\x03`(L\x01\xe0%\x8c2Qo\x0ci\xf1\xf5\x8e{\xd5\xbdM\x04\xe2\xa8LG\xe0{\xcc\x17 \x1b\xcc\t\xb0*\x0c\n\xf0$\x8c\x02\x80&Q\x11\x92\x0b\x01\xae\x8d\xc1`\n\x0b\xf04\x00BW\x00\x80\x06_\x8d\x98\xbb!@\x00\xcc\x06@\x0c\x8c\x03\xb0\x03\x18\xb5\xe8ip\xbd1\xc7\xaa\x85h\x98\x00\x80\x0c\x98\n\xc0\x17>J\x96[\x9e\xeaR\xf7P\x00\xa0\x01\xce\xf5H\xbc\x86\x0e\xa4\x9c\xc2%\x9dh\xed\xf8\xf6\xbe\x9e_\xffW\xb7\xe5w\xb2\xbd1\x87;\x8eV+\xf6\xafm\xe5S\x1e\xe7\x9e\xb1\xcf.]\x1c\xe3g\x18A\t\x03\x05\x0e-Z\x176\x1f\x141\x10\x97\x8b\x8f\xa1m\x7f\xee\xb4N\x8d\x88\xd0CG\xa40\x00\x00\x0b\xfe\x00?\x16^\xc6@\x80\x83\x0b\x83\x87CdA\x83 \x15\xccq\x017\xaaD\xc1\x02\xe1\xa2\x88\xa0\x00\xa8;\x03/\x8dL\r\x00\x84\xccHP\xc6N\xcc\xfct\xf6\xb4\r\x10\xe0\xcdF\xc1Ff\x08\x1c\x82t^t\xd4\xa1\x14\x18\xe4n\xd4\xe5Z\xd3\x9f\xbc\xf5rv\x9eww,\xd7\xb7\x9d\x9b}\xc6\xfe\xb3\xfa\xf5\xfe\xee]\xec\xabo\xe4\xe4\x1fC#\x8c^\xc2\x18\xb1w\n\xf1\xa8\xdd\xe9\xd9d\xa6E\xbb\x9b\xbd~\xc5=5\x8e\xacg_\x9e\xfd\x92\xc0!_\xa3\x90X\x0ed\xe4H\xa9\x08\xc3\xe0\xf2A\xb1\x89@\x86\x18#\x19^\xa4b\xce\x1df \xd38~\xf0#&\x12\xc0p`\xca\x01\xa6\x02\xc0\x02!\x043\x03\x80\xd2\x08\x1es\x00\xe0\x0e\x0e\t3\x06\xc0<1;\r\xd3\xd0)\xc3\x0188\x08pL\x0e\xc0D0!L\x04\xc6\x13"!\x0f\xdb\xaahQ\xb3fu\x00Fy\xcb\xb3@\x9b\x15\x05\xbb1X\xdb\xfd$\xed$\xa4`C\xa89\x12q\\\x7f\xfa\xef@\x0f\xf4\xdb:\x06\x9cP$6\xc4!\xb7\x96\xe5\x03\x8d&\xd3\x95\x1a\x8dS?K\x9a\x96\xe4NS;M\x94B\xbe3\xf3\xb67\xaak\xb9j\xd7;\xdf\xe7\xd7\xacDX\x15\x10\x83Jsid+\xef\x16S\x9e\x9e\xa4nO\xfd\x16\x8d\xdc\x1a\x00)\xf5\x80G\x9d\xe6\xe6\x99\',GUg\x13dt\x08\x87F3\x84\x99\xec\xbc\xe1\x0c\x03\x0b\xae$\x122\xf1\xe4\x98\x1e\x1c1\x1e\x00\x04\x0b\x8c\x90\x177\xbc`\xe0B@\xb8h\xc3\xe1\xc3\n\x82\xd4\x8a1\xa1\xba\xf5I\x86\xf9O\xc9c3\xb2%\x95\x96\n\xeeQ\x92\xfc\x94\x8d\xd45f\xc9\x9e\xb5\x9c\xf6\x97\xa4C{1Qd0\x06\xc0\xd8\xc5\tY\xe5O`+\xbbzt+"|\xf25\xaf\xc3w\'\xa0{\xa7kx>\xc4\x13\x14T\xc9e8\xcd\xfe\xa5\x01\xd0E~d:\x84\x06\n\x0c\x02\x07L,\x0e\x0cW&LB\x1b\rK\xcc\x0cR\x90J\xcc\x10\'\x0b\x8d\xc6\x00@L\x0e\x80\x1a\x8c\x07\xb0\x03\xcc\x05\x80\x04L\x06\xf05\x0c\n`\xce\x80@\xc2\x98\x0b\xa0\x04\x18\x05 \x02\x18\t\xe0@\x98\x1a\x02\n\x19\xcf0F\x18\x8bA,\x18\x19`f\x98\x00\xc0\xa4\x18\x01`D\x9c\x01\xb1\x8d\x1f\x00\x01\xc4A\xc6h\x0e\x00\x12T\xe0\x90\x91\x10+\xdf\x16\x95\xc3\xac\xb9-L\x95\xd48U\xb7g\xff\xfb\xd2D@\x8cF\xb13C\x13\xbf\xd9\xd0\xac\xe5\x98\xfdo\xdc8\x19p\xc5\nN\xffGB\xf6\x98b\x1d\xbf\xe4\xe8\x8e\xac?V2\xd8\xaa\xde\x19\x0c40\xfbqjK\x96h)nW\x90\x85\xc2P\xb6]\x1d\x8b\xc6\xa4r\xcaY\\.\x96]\xdb\xf1\xebV\xf5\x85o\xadc\xf0\xb1\xdcp\xca\xae_\xbea|\xf8\x86\x99\x86 \x8e\xca{L\xb7\xcb5\x0fPI\xcd\x97u\xb6=\xf4Q\xaf\xfe\xa5\xffg\xf4\x88\x80\x00\x00\x02w\xda\xe4\xb4c)\x86&\x10\x99\xa6($\x18\xac`DFCHcz\x12f\x0b\xf2\x14p\xd0$&\x0b\x804`\x1a\x00\x06\x01\x80\x08U\x02C\x02P7\x19\x01C\x01\x90\x110\x05\x02\x83\x00\xd0-0\x8a\x16\xc3\\]\x12=\x02\x10\xc8d\xf3\x08\x08\x0c\x1e\x1f\x1d\x01"\xac\xa9\xedo[Xa\xa9\xdf\x96v\x92\xad\xf8d\xc1b\xd2\xfc\xcb\xab<T\xd8\xc9(&\xe9V\x08\x14k\x81^\xeaZiN1\xac&a\xd1P\n\xac\xb1\x19\x8dC\x13\xb8\xdb\x85\xefs\xd7e\xb6\xe9\xedrw]\xc3U\x8e9\xe2\xaa\x10\x1f8\x00(\xf3\t\x11\x04\xff\xd5\xfb\xbf\xfb\xff\xf7j\x00\x90\x000\x10c\xd2\xc2`\xf8\x14`\xe88$\x0e\xb23\x1c\x87\x03Q\xe8\x03\x1bL\x11\x93\tBR\xe3a P1\xc0L\x0c\x08\xf0\n\xcc\x05P\x0c\x0c\x00\xa0,L\x0b\xf0\x06\xc0\xc0\xaa\x81@<04\x80\xd50\t\x00\xf40\x10\xc4c1\xc9j\xeb0\x8e\x8310\x0e\xc1h0\x1a\x00\xa30\t\x00P4\xca\xcdB\x11p\xa6HQ\x9c\x0cX\x00Y\xb7q\xa1\xbc\xca\xac\xe9@\xd0s\x178\xcfB+\xae\x08\x8c\x035N\xfd\xba\xb3-`BT\xe9\x9ad\x8f&\xecK\xb5^\x82\xfc\xa4\x90\x9bojS=\xaa\xf2\xdc\xafZ\xd7gj\xdc\x97\xe3\xf5y\xf6\xbf<\xb7_/\xff\xbf\x90\x99\x8c*\xa4.\xf5\xb7f\xf4X?\xa8\xadlW\xdft\xf5+\xe3\x12u5\xf8\xa6\xca{;\xfe\xb4\x00\x062Re\x86\xb5\xe2a\x05aqT\x06\x82JL\x99(\xf1p\x8cPp\x16L$\x96\xc9\x0c\xc0\xa0\xb8\xcc\x00`3\x8c\x01\xa0\x1a\xc0\xa0.\r\x01,`\x02\x80\xc4`\x88\x80\xc8`\x1a\x00\x16`(\x01\x0e`*\x81\xec`\x1e\x88\x12cL\xc7\xee`^\x05\xca0\x05\xd1\x80*\x03\xeai\x01q\x03\x0c\xbc0\x0c\xa1\xffMb\x81\x9f\xd6M\x1b~mN8g7"\xcf\xce\xc9h\xa6\xae\xea\x9a\xbcxt\xd3m\'Q\xcc\xdf\xf3Uh*\xd5 ._\x8453,\xa7\xed\x99\x8eMY\x98\xad\xf9n\x96\x93\\\xbdg\x98\xf7,\xb0\xca\xe5\xa1d\xdca/\xfe\xab\xde\x05\xafje\xd8\xd5H\x10[PM}\xf0\xf1\x87\xdd\x7f"\x93\xff\xf5\xaa\x02\x90\x01#\x89\xac\xfa\xc0\xc01\x86\xc0&\x10\x0f\x98\x1cZi\x001\xe8P\xa6Q\xd8\x19\x06\x1a\xde\x9f\xc6$\x90\xce\xa6\x01p2\x06\x01h\x0b&\x00\xe8\nF\x00\xa0(\xa1p4\x0c\x0f@\x19L\tp\x12\x0c\np8\x0c\x17@pL%\xf1_\x0e.\xacB\x8c\x9bq\x10\x8c \xe0ML\x0b\x10-\x0c\x08\xe0\x11H\x8c\x8cL\x10\x1c\x9ca\x04\x02H\xach\xb2*\xe1\xc9ue8C\xcf\t` \xc1;\x81 \x10\xfcO9\x15I\xaa{r\xe0\xa0\xa9\xc7\x070d\x91w\xac\xdc\xab^\x1b\x88t\xff\xfb\xd2dJ\x0cFj+B\x93\x9f\xd9\xd0\x96e\x18v{\x88\x88)\xade\x14n\x7fG\x89\xf3\x10b\x89\xbf58\x0c"V;!\xa6\xa6\xa6\xd4\xaa\xb4;\xac\xb3\xb1\xac>\xaf\xdd\x98\xea\xc3\xa3e\x80j\x8b\x06\x90\x85\xb1K\x1a<v)\xa6\xfayOEK\xa4S\x94\xbd\x18\xd3\xc4\xa8\xabl\x83\xba\x12\x8fzH\x01\x0c\x80\xbb\xe0\xe0E/Pp\n\x04\x01\x90\x80\x00\x84\x00>`\x94$\x86\x0fA\x1aa\x04W\xa6\xf8\xc1\x94`<\x05\xe6\x01 N<\x01\xa6\x06\xa0<`\xa4\x13\xe6\r@\xdc\xee\x18\x15\x03\t\x82\xe8@\x18:\n\xd9\xb9\x8c \x9f\xd9\xd6 \x07\x98 \x02\x15\x16\xa8B44\x95\x8c\x15\x05\xb6\x8e\xcb\x93N\xdbH\x1d\x19\x05J\xe8\xe5\x07j\xd4\xccj\xdd%\x8e^fbA.\x0e\x974\xb5\x96 \x06Y\xa3\xc9gQ\x88\xd5u(I\xe5\x02\x87g\x80\xd5\xd2\x97\xd1W\x7f\xfa\x19\xfe\x8fw\xddrE\xf10\x00\xcb\x19\x06\xc4g\x1c0\x1al\x85\xc1\xb3\x99\xc6\xbcJ\x1a1(ae\xd9\xc6Y\xe6(h\x17\xe6\x05{J\x06z\xa9\x1ff0\xe8y&\x17\xf8^&\x16HGf\x11\x085\xe6\x10\x988&\t8*f\t\xd8\x1a&\x04\x00\x00&\t\xb8>f\r\x18E\xa6\xb2(<\xe6\\ \xb9F\x18\xf0MF\x13\xa0>\x06\n\xd0 \x86\x08\x10\x19\x06\x04\x18\x07\xe6\x018\x00\xa6\x01P\n\x86\x01\xd0\x07G\x021\xc6po\x16\x1a"\x00\xa2\rI*\x0bH\x8a\x0e)\xad\nL\xe0\xb8e\x931\x01\x0c\x10 \x10\x04Pu#\xec=-\x8cQ\xf00\x04\x1c]\x13\xaf\xbb;k\xee\xfd\xa8m#\x81A\xcb\x96d\xc8\x98\xd0\xe0\xa0i\xd7Ya\xcb\xc6\x80t\x8bi\xf3K\x91!\x11@\xbel\x1e\x08/ \x00\x01\x82\x0ca\x83\x18`\x80\xa0\x85\xf3m\xe6\x19B\xeck\x92h\x9b\x96\xb1\x15"\xa4b\x0f\xc5\xd7mw\xacu\x04X\x8dr\x1c\xbd7\r\xcb\xf3\x9bv\xdd\xb6\xb6\xce\xdc\xb7~_n\xbcm\xff\x7f\xe3v\xfbR\x92_O\xda\x90\xc40\xe49\x0e\xe4\xbe\xde\x7f\x86\x18~xRRRa\xcd\xe7\x9d%%%\x8c?y\xe7\xff\x9ey\xdb\xcc=\xd1\xcb\xfe\xc3\xfe\x00\x00x\xff\xa3\xe0\x00\x001\xe0\x00\x1f\xaf\xfc\xc3\xc0\x04\x7f\xff\x87\x87\x8f\x00\xfa\xe8\x89\x89\x88q\xf7I\x14\xda\x14\x080zC\x13%8@\xd3_\x00)0"\x02\x00\x10\x05#\x89\x80(\x12\x98$\x010@\x0e\xda\x0c\x02a`=0I\x03\xd3g`\x911\xa9\x00A`%ji`\x96\xe9\xca\xff\xbbj\xdc\xeb\xccEe\x94\xf5p\xe6\xae\xb7]\xd6\xbeb\xa5V\x8cX\x80\xf0\xe6\xb6m\x96\xa1\xf9\xc3\x80\xad\x1e\xa3cXQ\x92\x03EC\t\x9e\xffOv\x05\xff\x92Z\xd2\xb0\xd5\xbf\xef\xeaW\xae\x00\x16C\npn0\x17\x03#\x04\x10D0c\n\x83\x0c\xb0\xd00\xfd\x15\xa3\x14\xf0\xdc0\xe9\x18\xc3Es\xee1\xfb\x85\xe3\xd8\xb5D3\x97\x11c\x03\xe0\x910v\x0f\xf3\x16A\xb91\xc2\x1d\xb3!\x02\x112T+S!R\x8c2\xe1:\xc3:Qd4&n\x13b$%1b\x01c\x02P\n0\x8f\x0e#\xc7\xb27\xca\x93\x98}6\xe6SX?3\xa2s\x12\x05W\x85\xba0\x10\x04\x00\xb2W\x88\xbd\xc0\xe0$9\xb0"\xd9"\x94\n\xdd\x91\xff\xfb\xd2dC\x0e\xc8yQE\x13\xdbd\xb0\xa0%\xe8b{\xab\x88\x1c\xe0\xdb\x06\x15\xfe\x80\n\xcb\x16"\x0e\xbb\xe0\x00\xe8\xbb\xc5\xb6/\x12\x9b%\xf0\x08\t\xa0\x92\x89BQ\x95\xc9"\x08"\r\x80\x90\x8d\x19\xc8\x82\x04@\x88\x11\x06\xc4\xe7\xb5\x96k\x8d\x12A\xa85\x03\xa2)\x8b\xb8tbbbz\xeeYr\xee\xb1\xd1(J\x12\x84\xa2q\x93\xb3e\xcb\xad\xf5er\xe5\xd6\xa9\xc9\x88\x92$\x99\x19.\xb4\xd6\xb35Zrrb\xb6\xb3j\xadZ\xb6\xbd9i\x9cir\xe5\xcb\x97\x06\x8b\x03R\xc0\xd1\xe2\xa0\xa84\rr\xa0\xa8*b%\t\xf8\x18\x1a\x05A^X(\r\x05)\xbf\xc9\x00\x90\x8c\xe9\x81@\x17\x96\xa9\x92\xa0\x14\xc0D\x00K\xec`j\x1c\xc6\x0f \xba`\x0cT\xc7-\x00\xe2<!&\x04\x80N`>\x04$\x00@\x17\x02\x100t\x18\x11\x81\x08\x08\x14L\x18\xc3$\x08\x17\x076w\xb0uA\xecb\xe8\x18b\xd0@`8*\x89%\xc1\x0e\x02\xd7J\xb0@\x94K\t\x16\x8f\xd9\xb3c\xb4\n\xa9\x0fn7R1\xcc\xa9\xea]f\x00`f\xd8\xef\xb5\xdc\xd3\xdb\xe9\xc1\xc4!\x9cW_\xff\xdb\xee\xed\xb0\xaa\xae\xd1\xb41\xe9\xf7\x12\xc5\xf6\xd2j\x03\xd6\xd1O\xf7\xa3\x99E\x1b\x98\xda\x90\xeb\x19\xfd\xb6\xf7\xae\x95\xedB\x81\xc0\xdb\x98\t\xe0\x11\x18\x04\x80(\x18\x04\x00\x1b\x98\x02\xa0\'\x98\x1a\xa0C\x98\x1b`\x8e\x98\x03am\x98M\xa0\xbe\x98\xe1\x86^\x1b=\xe0g\x98>`\xfc\x98B\xa0\x14\x18\x08\xe0U\x81\x00\xba0\x00\xc0~0I\x01F08\x80#2\xd4\r1,\xed3=\x02?\x1fS=\xde\x978,\xbd2\xb4.\x08\x12\x0c\x90\x15\x8c\x03!\x8cP\x08\xc1\xc18\x04\rK\x83\x02\x81D\xb7\x00\x80\xab]d\xb8\x8a\xd8\xc6p,\x02\tGu\xf9\x87\x1b\xf8\xc4AvC\xd3N\x9a\xc7\x962K\x96\xbb\xc9eo\x8f\xf1\xac\xda\xb7Rs\x93?c\x97mas\x1c\xefT\xafO\xdb\xb5\xf2\xdd_\xcb\x0ea\xaf\xe7\xea\xe6\xb9r\xa6xX!\x19\xda\x0e\xb7\xe3M\xa1\xe3\xc6\x1a\x9cM\xe4\xc7\xdc\xf5\x98\xf6k\x97\xe4\xee\xdd5\xeff\xad\xdf\xbf;\xfb\xfe\xadw\xeb:\xe87/\x7f\xfbG^\xd7\xef\xff\x01N \t}\x8c\r\x04\x81\xa0X8\x12\x12\n\x0c\x10\x11\x0c\x10\x08\x8c\x8b\t\r\x0b\x03\r\x9a\xe9\x0f\xec\xbdL\x14B\x0c\xca\x18\xc2\xa1\x99\x96\xa0y\x95\x03\x19\x8e\xc1\x89\x89\x00\xd1\x80\x08z\x983\x0b\x11\x89`\x9e\x99FX\xe9\x86\x80n\x98\x9f\x85\xe9\x86X;\xa8y\x80\x88\x1c\x01\x80\\\x1a\x00\xa6\x04\xe0Z\x10\x00\xc6\x00@\x05\x16\xaa\xb5\x1b\xcc\xa5\xdd\xa9H\x96\xec\xdd\x86\xc2\xda|\xa5\xdfu*\xb5\xf8}6\x88\x80}\xbc\x9fy\xf9\x95JY\xe8\xa4-\xa3\xba\x92\xc8z\x85\xf9e\xf1G\xd2#\x1c\xb1z\xddJ[\xd9Y\xb3\x9e8]\x04\x01P\x11CS(^\x9f\xbb\xff\xf5\xc9_w\xf4{?\xff\xef1\x00\x00\x00\x02\x00\x81\x06S\xf5KD\x80\x90\x00\x00\xc0p\r\x85@\xfc\xc28\'\x8c)\x83x\xc0\x9c\x00\x8c\x07\xc1\x08\xc1\xd8-Lq\xc4\x88\xc2\xe0J\x0cd\x01\x04\xc8\xe4)\x8c\x1d\xe0\xf4h\x16\xc0\xc0\x18a\xca\x1c"\xc1\xb4bf"\xa6U\xc1\xfe`^(f\x1aa\x94c\xfa8\xe6\x1b\x80^g>\xd6F\xff\xfb\xd2d.\x80\tBGJ~{\xc0\x00\x8e\xa4\xc8\xe9\xce\xf4\x00\x9fx\xbb\x08=\xff\x80\x11\xec\x15$+\xb9\xc0\x01\x04\x81\x10`\xf2&&\x05\xc0\x80\x02\x00\xa3\x07\xf0m0\xc6\x07\x83\x04\xc0 0\xbb\t&\xf4\xc0\x0c\x03"\x0f,f\x050@\x00C\x03p507\x03s\x02\xb0\x110\x1f\x02`\xb0\x05\x98\r\x01\x88X\x07\xea2\x97\xd5\x88\xca\xc0\x00\x0e`2\x02!\x00\x1e`$\x01\x86\x01\x00\x14_`0\x0f=\x12\x96\xd3+\xf50\xe7@\xc00`*\x00m\xbc\xe3\xa6\xa0i|\x9a&\x00@\x06`\x04\x00\xaaT\x8a\xdf\xff\xff\xfe\xd3\xcb\xc0\x91\r1\x83\xbf\xf2\xf5\x02\xb3\x12v\xa0\x16r\xb0\xbf\xff\xff\xff\xff\xba{r\xcaK\x12\xfc\xfe\xb557\xeb*\xb4\xb4\xbf\xff\xff\xff\xff\xff\xf9\xf6\x92\xc0&\x1f\x01\x83G\xa2P\x91\xef\xe0@@\x1fD@\x03\x07\xb0TD\x15\xff\xff\x02w\x82\x05\xff\xc1\xa2\xa7P\x00\x00(\xc3\x04@\x00\x00\x1dS\x05\x04\x82\x00\x18\xc0pu\x04c\x01a\x92h\x19\xb5\xa5\xf9\x12\x88hJ0b\xbadx04bH\x86$q\x91\x03&?\x0f\xa6\x10\x00\xe6\x19\t\xa6\x11\xae\xa7\x81\xb0\x068<&\xf5\r\xc6\x17\x17\xe0\xf0\x10\xe1R\x0c\xc0\xc0\xa8\x00\x02\x19,\r\x18\x8e!\xe20\x10%\x93]\x08\x05\x9eD\xfc04\x03\x91r\xe4^A\x9c\x11\x92\xce\x03\x02\x04\xa0\x83u\x7f\xad^\x95[\xf9nR\xbc>\xa7e73\xde\xee~\xff\xf3\xce\xb6yL\xcb\xbe*\x10\x18\x1a\xe0G\x18\x0b\xe0\n\x98\x12!Y\x98\x03\x809\x98\x1c@m\x986A\x04\x98FA\xba\x98\xa6\x01\x9e\x98\x93\x81\x95\x98\x86\x03\xa9\x98!q\xcb\x9e\xf2e\xd8\x19\xb3\xe4(\x18\x8c\xe0\xf3\x18X \xeb\x18 \xe0\\\x18\xc6b&\x98\xb0b\x0c\x18\x88\xa6\xfa\x1d\x02U6\x98\xab\xc2\x19\x98s\x81\xc7\x98F\xc0\xe7\x98\x04@c\x98\x16\xa0\xb5\x18\x10\xa0-\x0f\x01\x90L\x00\xc1\x80,\x019\x80\x10\x00\x9a;\x8b\x00|\x15\x00\xc0F\x00\xe9qU]\xf4Y\x0e\xbaG\x85\x80\x050\x11\x80\xce0\x02@\x14\x07\x00\r\x0c\xbf\x12\x05\x01-(\x8c\x08\xd1\xe0\x17]\xb8\x15\xa8\xc4\xa0\x88\t#\x8c\x01\xb0\x02c6)\xa7\xa3Q\xeb\x12\x98&T\xfeC\xd7.W\xaf_;\xf8\xea!\x86?\x9fp\xc7\xec\xe1z\xc4p\x00\xb9\xd5\x10>a\x08. \x1aY\xe8CR\x97\x1aV{kL\xd5\xbe\x86)\x86\x17\xd8e-\x02^\x82\x03\x10{\xd3<\xabR\xccZv|\xd0@\x00\x00\'\xea\x00R\xbf\xcda\x95\xa9\x808\x14\x17\x07\x18 8\r!\x99N\xb0c\x83\x98\x00Ra \xd1\x87\x00\x86\x04\x10\x18\x1c`\x00\x0b\x98\xa4FadA\xa9\x11FbA\x9c\xb4"a\x01i\x8e\x85(n\x02\x07\'\x12\x91NjiL\x99\xec\xa9/\xb7\xf7\xf2\xed\xc9\x8ci\xef\xca\xedJ\xa5\x98c\xbb\xbc\xb3\xaeo\xf7\x9fy\xdf\xd64\x14\x14\x9419^\xecNn\x9e\x9e\xb5\xee\xd7\xd8+X\x9d\xaa\'\xdd\x00M\x1a\x8c*\x00\x05\x02#\x1f\x88\x03\x0e\xc0 \xa0@!\r\xcc\\)N\x02\x0c\x80\xa0q\x85`\xe1\x85b{\xd9\x9a\x86\x1aQ\x82F\x06\x89\x80\x82\x03\x01\x80:\x00\xa0\xc8\tf\x0b\x90Q\xc6\x04\x90\x04\xe6\x01\x08.f\xa8\xb9bF\x12h\'\xe6\n`$gT\xff\xfb\xd2d\'\x84\x05\xf95F\x1b\xbf\xd20y%\xf9\'sI\x84T4\xc7!\xae{(\xc1\xe1\x98di\xae\xb1(@Y\x00p\xd5(\x12\x98\x08B"\x1c\x96I\xdd B@\xd3y\x04o9k\xef,\x80\xcc\xaa\x98\x17\xb4W\xec\xc6(FV\xba\xbc\xe5>\x0f\xbc0\xb2\xccX\x89\xb7\xda\x18\xc5\xd0\x9fwc\x0f#\xb1K*\xb4\xeeJ\xe3\xcf\x0b\xc5_6\xcc\xba\xeb\xda\xa7\xad\x87\xfd\xdc\xf3\xfb\x7f\x95\xdde_\x1bz\xef+bp\xcc\x044\x00\xd1\xe9y\\\x87\xa5f#\xd1\xdfun\xc8`\x05\x18\x04\x04\xfa\x80 6\xc8\xd7\x18\xd3\xc0\x8f\x0b$\x14\x040\x18p\xc3I#JGL^\x8a\x04\x87\xc1A`\xe290\x00\xc0!\xe3\x11\x04\x0cvX;\x9e\xb4\xcadcF\x07\xcd\xbc\xa0\x10\xf5\x04/\xe3\xb0\xe48\xcd=N\x14\xda\x1d\x93\xc9\xe1\xc9\x88}\x80]\x98\xa9\xbe\x9c\xa6z\xafHf\xf5\xe4\xbe:lL>m\x180\x93$\xcfaU\x05i\xea\xbd_\xa9)\x06!\x0e\xf9\x06\x99R\xd6\xeb\xc6?\xa8H\x80\x06\x84\xfe\xbb^\xf4T1\xb9\x88\x04\x1c\x10\x8c\x9f\xa0P\x94\xe7@s\x17\x89@\xa3\x03\x07\x9a\x9f2\xb1\x18\xc3\x0707"\x04s\x00\xb030\x08\x03#\x03\x91\x9b0\x12\x01\xd3\n\x00 >\n"\x13\x0c\xc0F0\x8f\x13\x81E\x03\x1d&u\x94\xc7SR\xac[O\xe8\xc0\xa0\xeb\x9dh\xa5K\xfa\xabx\xe6R\x06\xc2\x9b\xf2\xe6%\x83[\xff\xdfr\xad\x94\xc9\x13\x94\x97\xeej\xadk\xd7\xe3|\xa6\xb9b+\xcc\xb2\xa6\xb9\x85\xda\xb8cK\x95\xaao\x88K\xb3\x97[\xb1A\xad\xd5\xae\xc0n\xa2(\x00\xc0\xfb\xff\xfe\xe7z}\xf8\xafw\xa1\xfa\x94\x15\x08\x00\x0e\x7f@\x132\x16\x1c\xe4/\xd0\xb0\x00P\xa1g\xa6,\x00\x12\xd1\x99\xc2\x89\xa4\x01AT\x1f^\xa4\xc1\x19\x80ax\xb1b`\xc0\nb(.`d\x94\x08\x04L\xf5\x18\x82\x03\x80Pr\xd7\x15\xcaL\xb1\xc6\x15-qW\x11\xfe7!\xaf\xfbEH\xa9\xebL0\xc8G\r\xad\x15\xbbi\xedf.{\xb7\xde?,\xf1\xc4\xd95\x965u\xd7\x8e\xc8}x\xd8\xaeSg\x9c\xbf2\x94\xa6\x85\x96C\x95\x02\xd0\x00p `\x00\x86c\xbc\x86bP\xb2a((b\xe8\x8c`\\\x01Lb}\x01\xde`?\x81\x02`\xaa\x82x`\xa2I\xceh5\x0cX`w\x02\xb6`+\x82$`\x12\x800`F\x02RaG\x8c `\x86\x83``\xda\x83\\x\xeb\xa1Jb\xf9\x80\x14`\xc2\x07Nl\x82\x86\xe8\x1a%\x0e\x02e2!\x11\x10P\\\xc9\x0e\xa4\xc0C\x81!BS(\x04~\xe3m5\xf5\x8a<O\xe0\xd8:0\xc2\x9fW\x9f\x97\xf3 o\x12\x8f\x9c\xab\x07X\x96\xc3\xa5\x80\x03\x01\x15\x95e]\xde\x9a\xbe\xefa\x1e\xa6\x96\xce\xc6!\x1d\x96\xc9c7\xeaO^\xb3\xda\xd9a\xac\xf0\xc7=c\xaa\xb6"\x86\x9b\x9c\xe5t8S\xee]\x7f\xdd\xdf\xd9\xff\xfeO!O\xa1\x0f\xd6\x1c\x00\x00\x01y\x00\x12ha[-7\xa3 Y\x80\x81\xe2\x12\x84\x008\x88\x860\xc8C8H.\x19\x05D\x819\xc1\x00\nc\xf8\x1aa\x18L`H\x96m7\na\x98\x98b\x81:v\x0b\x08\xcb\x91\x08\xa6w\x14Y\x87;\x96\xb5-\x8c\xc8{_\xe8lb\xb9\xea\xda\xbf\x8b-`x\xff\xfb\xd2d\x8e\x0cF//\xc3\x13\xbf\xd9Pv\x85\x18\xeawI\x86\x17\xc8\xb7\x0cN\xffh\xc1\xc8\x13\xa3u\xd7\x9aX\xef\x8c;7\x13\x14\xd6\xef\xda\x92\x10v\x04\xe6\x0e\x12\x8b3\xbd\x01i\xa4\x16"N\x85\xce\x00\x0f\xa9\xfc\xcd\x00<\n8\x07\x84\x00CU\t\x12\xfe`\xb0>`\xd8Hc\xf3\x0c\x7f\xd1\xfef\xd9\x04i\xab\x98a\xa0=\xd6oT\x07\xc8`\x9f\x02v`5\x80\xb4`\x1b\x00\xe6`>\x82pb"\n6`\xda\x03\x12aY\n\xb6u\xd2>\xe0b1\x02\xaa`\xea\x02\xa8c\xb4f:\xb4h\x8b\xa4C&L\x1a\x83E\xad\x1e\x03qR<\xb6\x05\x17\x0c\xa1\xd6\xaf\x10\xbf\x0cCg\x04\x92\x85\xefd7f\x8arV\x16?\x1a\xcf\xa2\xce\xf5l\xed/0Rt\x0f1\x94\xaa\xdd\xeejUV\xbcf\xbc\xe6z\xdd\xfd\xd6\xb5\x1a\xad\xdb\xfc\xc3w0\xe5\x80\xd0\xb0.\x1a#\xa5\x8e\xdbu\xf7\xf2C;\xa5\x12=#\x1d\x16\xa6\xd8\xe4\xf7"\xd5-K\xc5\xf6\x7fx\x10\x00Tv \x044\xd2S\xb5\xdd\x00\x80\xc1\xc0@\xa8@L\t\x98&\n\x18|J\x18\xa0P\x86\xa4\xa6\x16\x01  TD\x16\xa8\xf9\x8cA\xa0\x08l0\x14\xe7<\x97\x82\x0c:\x85\x01\x93\x03\xc0\xf0\x00\x00\xdb\xbb\x02p\xe6P\xa7\x16LZ\x8f\x07t\x92\x16#\xc0\x02\xc2^[2\xaf\xaa\'\x03yi\xe12\xd3\xcb\x01\xbe_}\x9aI/\x18]\xe3s\x01%\n\xadn\xc5;\xbfZ \x00\x10\x00^\xc2\xa0\x04\x86\x05XaF\x03\xb0\x06\xc3\xa0\n\x98\x03\x00\x17\x18\rAm\x18\x80@\xc4\x98& /\x18-`\xfa\x18wN \x9eh\x02O\x18L\x00\xad\x98\x1e\xe0[\x18\x0f@=\x86\x012c\x89\x88`a\xd6\x84Ta\x8b\x92\xa8q\xaf\xe8&a\xdb\x85\xe0`\xfa\x82p~\xfc\x06Xnie\x80\xe3\xc3\x0b\x1f$111\x80q\x808}2\x01\x86\x06\x18*\x9a\x8aV\xc8\xe0f\x90\xb2\xd0\xf0\xe1l\x13\x11\x88\xae%~\xbf\x1ew\x10\x08\x02W;\x07Q@\xf0<\t\x0f\xad\x102\x04\x83\x19t\xb2v\x9e\xad\xfb\x13\xd4P4%\x9aE\xea[\x94g\xbb\x11Rb\xb2\xb57\xe5\xd5\xd4q\xc499\x199\x93\xe0\xe0,\x184\xf8\x102\xe5\xc9\xa2t\x9a\xe7\x10\x99\x1c\xa5-b$HfI\xfe\xcbg$\xcb\x07"\xe8I4]\xb5L>\xf1\xc2\x00BY\x17\x81j@A+\x0e\xba\xe0\x93\x01.0\xa2p\x8531\xc601\x14CU\xa0\x190=\x01 \xa0\n\x04\x01p\x8c\x0c\x8c,DT\x90\x01L%\x01\xb8\xe5\xb9\x10\xcc!\x02\xc0\xc0x\r\x8d\xcdHmN\xc2\xa2P\xd1@\x9a\xcc\x06\xd3\xda\xf3d\x7fl\xee\xfd5\xbbRP\x84R\x0bt\xbc\xaf\xcb\xa8\xbbw\x9c\x9e\xe6;\xfa\xc9]\xabT\x88\x10\x06i\x99&\xfd\xc9\xfa{\x05\xaaP\xb6\xef\xbf\xff\xff\xd6\x18\x00\x0b\x06\xfdZ\x06\x02@\x12`~\x02\xa6\x05\xc0\x08B\x11\xa6\x0b\xc3\x1c`\x9a9\xa6\x02"L`j,\xa6\x08CP`\x9eR\x06\x1a\x8eVo\x98\xc7\xa6\x11\xe4\xe8a|3\xa6\x1a\xa2\x8ca\xe8)\xa6\x08\xe0.c\xec\x03\xa6W\xc3\xaejc\x00\xc6\xb0aJeP\x05\x87\xc11\x9d\x80\x9cr\x12\x99\xbb\x08\xc7\rB\x9bt\xbel\xa2\x91\xab\xc9\xa6\x96"\x1b\xac\xfelC\xe1\xaf\xff\xfb\xd0d\xe7\x80\x07\x0b9B3\xfb\x1c`{\x83\xb8\x86o\xdaF\'\xb1A\x1fOs0\x81\xa4\x91$u\x9e\xb5(\xca&\x8c%\x19\xbc\x92d\xf1X\x19\xc0\xc2\xd1\x11>\xcceP\x08\x88h \x18 BX\x88\xa1SH\x1c\x0c\x9d\t\x89n\xa1\x8c`.is\x13\\\x04\xaa\x8b\x05\x01\x04\x88\x00\x1c\xc6,\xc50\xc64\xc7(\xde\x94\xdfx\xdad\xd7H\xd2$\xcc\x14\x04\x12\x12Y\x13;R\x04C\x91 $\xf91\xe4H\x11.4\xa0\xd2cF\r\x16<\x02#\xac\xf6(\xf7C0CKZ\nV\xb4\x16\x82\xb7\xa9B\xd3Z\x0b\xcd\x904\xb7\x82\x08\x95\xd8\xb5)\x89>\xae\x93\x82\xcaYT3\rC1\xa8\xcc\xba\x96\x97-\xf2\xfd\xea:)\xf9<\x9aG \x9f\x9c\x9f\xb1o\xbc\xcbxgR\xbdJ\x95\xeaW\xa9v\xe0\xb3\x00@\xb0,\n\x83 \xc9\xa7\xe84l\x13\x04\xd3\xe2\xa2\x82\xc2\xcd\xf9\x83O\xfd\xa0\x08\x02\x00b\x84\xfbm~\xe2~\\\xa7\xa64\xe8?Et\xc8L0H\xbe5\x08\x00\x01\x06\x86\x05\x80\x00\xd01\xaa\x98\x00,,\xa1\xc0\x8c\x9e\xfb\x0c\x16\x8c\x0f\x04\xa0\xe7\x1ab\xa2\x0f\xa3zr\xbfl\xdaL\x1b\xdf]K\t\n\x7f\x91O\xfe\xc8\xd7uQ\x99\xa8\x98T,.\xb9#\x1a\xfb\x7f]\xc2\x9b\x96/\xacY\xf6\xbc\xcf{\xad`_\xff\xffq\n@\x00\xa9bM\x98"\x07\x0e\x80\xa0@p\xc00\r\x00`\x90L*\x07\x03\x83\xd1Ah\xcb\xd1L\xc7\x11X\xe72T\xc8QT\xc2\xd0\x8c\xc2\xf0\xec\x1c7\x83\x0c0 \xeab@\x0e\x86\xd1\x80\x88V\x07\xa6\x0b\x80F\x10\x05\x02 \x13\x05\x01z=$\xb9T\x04A\x80\x14\xe5\x93\x00\x02q\xb1\xb1`\x0b}\x97\xa3\xb7\x1e~\xe1\x19\'\xf54\xb2a\xc0l\xb5(\x19!0\x03\xd3\xd6\xe6Q\x89dz\'f\xfd-L.\xcb\xec\xc1O&\xb1\x8eC\x13|\xa3\xbd\xdcc\x92\\i+\xe1O\xab\xb6\xb7\xbb\x10\xa82 A\xf3\xf4s\x95U\xeb\xf4k\xf0?|\xfd\xb5\x7fK\x9bu\xa6P\x00\x00\x03.\xd5\x14\xcb,\xec\x98\xa8x\x18#/` .\x8d\xe1\xc2\xd2\x10@(~a:\x19\xedEF9\x17\x8b\x02\xc0\xa0R\xa00\x1a\x12\x08\x11\x18\x18\xf4~\xb7\xb9\x85D\xe65\x11.\xb4KPE\x14A\xd5B\xb4\x1f\xf8\x11u\xd0\xca!\xcb14\xf4\xbe\xcb \x81\xa0-\x1d,i\xe7T\xf1\x87\xec\xa8\x08\x8bC\x0f\xc47,\xbd\xda\x90\x0f\xd3P\xcc[\xaf\x1b\xdc\xfb\xef.\x92\xd6\x88W\xa9s\x0bVnL\xcd\xd6\xa9I\x85\x8c,o\x98w\x1e\xfe\xae\xb0\xfb\xf6\xde\xbe\xaf\xd9\xcdv\x7f\x15\xd4O\xfe\xa7\x98 \x85a\x80\x08\r\x98"\x80!\x81\xb8$\x18\x8b\x00\xe9\x83\xc8y\x18b\x86A\x9e\xc1f\x18\xef\rq\x91\xc7d\x18x\x0b9\x9b\xab8\x9aj\x8e\x91\x8e\n\r\x99\x0b\x8eq\x89![\x18\x1b\x05\xf1\x84\x02!\x9e\xcc\xafI\x84\xa0\x89\x1d\xe4#\x91\x84\x90\xd7\x9d7\xaa\xb9\x8c\xf0*\x18}\x07y\x85X}\x98W\x82\t\x83@\x8a\x98T\x02\xf8\x84\x1cL:\x02\x04\xc6\xacCL\x1a\x81\x98\xc0\xa4\x00\xcc\x03\x80\x10\x1c\x00 \xa0\x19\x16\x08\xb3\x01\xd0\x17-+30A\x03p\x105\xb0@\x80\x03G\xc0`\x11An\xdd \xd0\n\x16\xf4\xbb\x1b\x82\xc3\x00,\x0c\t1\xff\xfb\xd2D\xf5\x00\x05S.E\xbdw\xc0\x00\x98\xc6)\x1d\xaep\x01\'\x05\x91\x06\x19\xef\x00\x05>>!\x1b=\xe0\x00$\xdf_M\xb3ke\xa9\xbb\xd6\x9b\x0b.}\x1d\t\x15\xa4\xc1H\n\xd0#\x89\x9d;\xff\x03\xd2v\xed\x97\xc2\x07\x9e\xbd?v\xb3\xcd\r\xd2\xbd\xf5\xa6q\x8d\xea_\x7f\x0c\xe9*\xde\x85\xdd\xbf\xffv\x9f\x1eH\xa5\x95\xa5\xf5\xa5\x92\xc9}\xce\xef.\xe1_\x0ew\x1e\xea\xdd\xeco\xe3\xcd\xf7,,n\xbfs\xd6\x1b\xdc\xbf/\xee\x7f\x971\xc3\xff-s\re\xcd\xffp\xee\xfb\xde\xf3,\xf5w<\xb0\xc7\xf3\xfe\xdb\xf6\x04R\xa6\x9d&@\xa1\x7f\xdc\xf1w\xb4i\xa3\xff\x99\x08\x9b\x0f\x81E\xce\x81`\x00GQ\x00\x00\x140+\x19c\x04\xb0-0Y\x0c\xc3\x02a\x0c\x1e\x19\xd3\n\xd1\x840|\x04\xf36dm2D #N\x8b\\08\x19\xf3N\x15c5U\x16s4\xc2\x021\t\x08#"qU1\xf0\x0cs\x1c\xa1J4H]\xa3\x15\x01\x043\x85A\xd3(0\x9e2\xc0u# \x11>0\'\x01#\rpz0 \x03\xd3\x05\xe0\xa50<\x0c\xa3\x05\x10.1\xb5\x02\xb3\x15\xb0\xd70P\x07\xe3\x04\xd0\x19\x03\x03\xe1\x80`\x07\x05\xc0@p\x18\x0b\xfe\x95-\x98\xc0\xec\x06@\xa0\x0e\x18\x01\xa1\xc0\x16`\x02\x00\x01\x00\x9e\xbb\xa2i\xd4\x02\x02 \xe0\x8d\x0c\x01r@\x06(\x00\x800)\x98\x0c\x80\x836O\xd2\xe9=\t{\xc6\xd1\xc9\x97\xbfO\x1bn\xdb\xdb\xccH\x01\x10$\xea3\xc8\x84~\xc6\x7f\xcc>T\xf8O\xd3\xd2a\xbb\xbd\xba\xfa\xd2^\xc2\x9a\xe6s\xf9\xeb\x0c9\x9cZ\x9a\xb4\xf6\xe7r\xd6R*\xd2\xfaz\xd6$\xd6\xe8\xb9\x9e\\\xbd\x8e\xf0\xb7\x9e9a\xab\xbf\xaf\xfc\xff\\\xa5\xa7\xfb_\x8e8Q\xf7=j\xbf\xff?\x9c\xde\xf3\xef\xff9\xaf\xc7\x7f\x9d\x8c5\xbf\xef\xf7\xf0\xa4\xefm\xe7\xf8e\xdd\xef\x7f\xfd\xcfZ\xff\xc7\xff\xbc\xfd\x7f\xff\xff\xff\xff\xff\xe3\xfd\xde\xb7\xfc\xd6;\xff\xee\xaa\xfe\x07\x04X\x1b LD~1\x05C|2C\x02m0n\x8100\xb3\x00~0T\x81\xd60)\x01A5V\xd3\x7f8\xda\x8b\xb10\x03\xb3\x074\x02\x8a>0nu\xb13WH\xb33\x8bE81\x9c\x03\x851\x10A 0\x1e@\xdf0\x1bA\x9a0X\x01\x872\x8e\x91\x0b8\x91\xe0\x7f1\x8f\\\xbb?m\xd2h2\x7f"\xd18F\x19*3!E\x082\x10\xc4\x8e1\'\x81?1\xc4F\x0b0\x15\x01\xeb0;\x80l0\xcd\x03M0=\xc0J0\x05\xc0"0\xa8\xc0\xdb03@o00@E0/\x00\xba0\x19@]0\x02\x80\x810\x04\x80b0\x07@D0\x08\x80\x0fr\x89\x82\r\x07\x000`B\x01\x0c`P\x81\x8a`\x05\x80|`\x13\x80$`\x16\x00d`\x07\x80`$\x00\x99\x81\\\x00\t \x05*8\xc1\x93\xf0\xc0\x91\x00\xc4\x08\x00\xc4\xb0\xc0)\x01<\xc0.\x01l\xc01\x00\xc8x\x05\x80p\x06\x02\xa0\x0b\xca\xc7\x00"H\x91\xd0\x02\x15Y{0\xf3\x00\x04\x01\x17\x16\xbd\xed\x11\x00<`\x16\x80\x00\x18\x02A\x80.\x00JZ\xa1q\x80 \x00AnYK\x81/\xaa\xe2\xac\xa9\xb8\xd5=[9f\x04\x00 \n\x00j\xd8F"\xe0\x05\xc0\x01\x02\x00\x06[d\x80eP\xa6\xff\xfb\xd2d\x9f\x80\x0e@{B\x06\x7f\xe0\x00\x94\x04\xb8\xb0\xcet\x00\x1c\xec\xc9\x10}\xff\x80\x01\xc7\x95$\xab\xb7\xc0\x00S\x11\xa4\x87\xa9\xdf\xd8*\xd4\xfexk\x0bYz\xecU\x15^D\x00\x12"(;\x92\xd4\xd0\x08\xb0\n/\x12\x8b:0\xcc\xc5\xadJd\x92\xa9\xec\xff\xec\xfe\xbb\x97\xe7\xc8y\xb7`\r\x8dAY\xb3$\x82\x1d\xd6\x0e\xcb\xd8d\xae\x12\xd6\xe236%V\xa8f0\xb5\x1d\xab\x84\xab]\xe6\xffy]\xff\xff\xfc;\x86\r!\x95;/\xdc\xae\x1am\x1dG.bF\xecJ\xdd\xd8=\xf8\xff\xff\xff\xff\xff\xff\xcf\x95\xae\xdd\xa5\x95V\xb7KK\xf9S\x07\xbf3N\x1f\x99*\x82\x83\x91\xc3\x01\x01\xd0h\xa8\x80\xb2fD\x1c\x1bU\xfcc\xf2\xc1\x99\xbf\xe64\x10\x9c"\xa8h`1\xa7\xbf\xc4U\xf3\xc0\xa5M6L#(\x9f}\xea\x18\xd0D\x9c\xe7\xb5\x85C\x93?7\xe3)\x84C\x10BS\x02\xc0\xf2@\x10\xc3P\xe40\x1fLp(x`H&\r\x02\x84\x81J\xf3r\xd6r\xaco\xdb\xf4\xb2\x95\xf4\xb9\xe0~\xe1\xea\xd6\xe9\xf0et6\xea;\xadr%\x9d\xdea+\xe6\x1f\xf8U\xfe~\x16h\x884\x12{\xa6k\t\xec\xa9*\xb7O\xff\xff\xff\xff\xfb\x7f\xff\xff\xff\xeb\x008\x88\x00\xc0x\x00},L\x02\xb0 \x0c\x1a\xf0\x00\x0c\x04p\x01L\x0f\xe05\xcc\x1e\x00\x9fL7\x80\xadL\x19\xe3\x84M\xff\x10\xdb\xcc0P\x04\xcc.`Q\x8c\x0bP\x03\x0c\x0c\x00\x04\xc4 \x1b\x82\x00\'0\x0c\x00g0(\x80\xcd0&\xc0\xc2\x02\x05\xd6a\x14\x06\xe2b\xa9M\x1ab\'\x8a:b,\x05>`\xc4\x02~`m\x00\xe0`"\x81<`#\x00\xba`\x0b\x80l`\r\x80 `\x03\x8028\x00Y\x08\x01i\xce[\xb4\x8eM\xc7\xd0F\x00\x01\x80B\x02P(\t\x94\xa9\x842\xaaH\x15\xa8\xbbT\xce\x1b\x110\x00\x00\x0f0\x08\x80,Lg\x14\x98\x00\x95\x85ue\xb5[\xbcF\x92\x190\x01\x00\x11"\x00\xcd\xda\xabZ\x06\x8c\xcb\xac\xea\xa4\xb2Y\x85w.{)\xff\xbf\x85\xec\xbf\x9d\xc7z\xd6\xf9c\x95\xc1\x81\xc1s\xe6\xa2\x0cb?gOk\xff\xa5\x9f\xfd\xa1\x80\x00\x00\x17\xb0\x01\xbd8\xcc\xbcX9\xd9-\xb1\x86\x03\x18\xdb\xd9\xc7\x1b\x1b\xab\xd80(\x14B:,,\x18\xc1\x10\x8d\xa2\x98\x08\xf4a\xa9y\x81\x0f\xe6 /\x19\x10\x00L`0\xa0\t\x01\xe9\x04\xeb\xac\x97z:\xe0C\x12\x9a+4\xdf\xff\xcb\x1a\xaf\xbeg\x85\x8b\x16?\r\x7f\xe7\xfa\xfdk\x0e\xebZ}\xf2\xa7\x86\xe8&\xf3\xcf\x1d\xd3\xe7\x9e;\xd5\xd00<s(5g\xd1\xfa*\x02\xe4\x12ay\x8a\x81\xe2\x81\xe3o&\x0cdN\x02\xadM\x15*;\xafL\xc5\x9c\x18\xb0\xe3\xef\x0cP\xc1\x07\x02\xe4\xc2\x96\x05\x14\xc0i\x00<\xc08\x00\xd4\xc0\x10\x00Th\x03\xb3\x01H\x05\x92@\x1a\x8c\x10\x10\x19\x0c$p6\xcc"\xf1\x11\r\x08\xa9\xa9\x8ce\xb0\x9e\x0c\x08\xe0"L\t\x90\x19\x8c\x00\x90\x0f\xcc\xc3\xd3MThB\x03X\x81\xa3\x12\xa7\x0b5J\x97s)t\xd2\x14\xc3\xc1\x17\x1b\x01A\xf6\xa5\xf2\xda\xae3ub3e@\x06\xb1\x1b\\v\x11-\xee\x96F\xe2\xb0m\xc9r\xc3\n\x1cD\xa9\x0b\x7f\x84\x0c\xedRV\xfe\xd7\xa5\xb1\xfc\x82\xa5\xba\xa5\xc6\x9b\xff\xfb\xd2dT\x8cF33D\x13\x9f\xd1\xd0r%\x89*c\x88>\x16H\xb5\x18n{GA\xe0\x95\xe3\xcd\x9e\xa4\xf8\x98\xd7\xb7\xbc\xf1\xeeVw\xda\xd9ePx\x8a),\x82\xc3\x87}_\xbf\xef\xff\xee\xb2E\x955A\x00\x00\x00\x9f\xd0\x01\xaaX\xf2\xd0\x15\xbeF\xf1\x05\n`\xc6y\x93A&\x1eD\x81\xa1\x85\xdd\x0e\x14\x96\xd8\x08\x0f \x0c\x17\xb4`|kVA\x80\xce&\xf7\xf7\x99Lj\x80\x93\x0e\x07@ \xe4\xbd\x1a\x03+z\x94\xb2V\x9a\xf2\xc3U\xb1\xb4\x93\xea\xd6H\xb92\r@XAP\xef\xbe\x1e\x89\xa3]\x88\x18\xf4\t\x870.\x87\x9bM"\xd3y\x15\xa9\x05\x84O\x93\x17-$7\xb2\xa0\x04\xd1\xa9\x1f\xa5300\xa0\xcb\x88\x10@\xa0DK2!\xa8\xdc\xb8\x13).J<UO#\x05\xa0\xed0>\x00\xe1\x80\x190"\x03a\x10.\x06\x01\xa9\x80\x90\x10\x18 \x00y\x80 Y\x98\x0f\x87\xe1\x87\xf0\x97\x9f\xfc\xe6)\xa0`[\x98C\x81q\x81\xd0\x12\x87\x041\xac8d\xc8\x17]w/D\x8b\x8f\xbb\x0e\xb4#9\xa8$fJ\x96\xc3X\xd0U\xca\xac\xba3\xdc%\xc4W\xe1u\xebV\x97\xc8\xa5Z\x8f:\xf2\xa1\x94Ji+}3\x8c\xbb{\x9c\xa9\x9d\xc9O%s\xb3\xd7\xf7\x18\xfeaj\xe6\xc9 L*\xc6=Y\x13\xc6\\\x03k{\xb6\xfa\xe4\x9d\xb3lR\xab\x0f\xda\xc71K\xeb\xa0\x05}`\n\xf2\xf0\xb0\xc8B\x92I\x88h\x10\x14\xf8\xc7\x03|M\x0f0\x1cq\x01W\x01\x81\xf1\x82\x00H8\x13Ib\xd6\x87\ta\x00q\x9a\x04\x89\x84C\xe9\xce\x03q\xad\xe0q\x8f\x00\x89\x82\xc0\x13M+\x04\x0b\x90\xa3*:\xbb!\xf7\x02\x06\x8c\xca\xa9\xa7\x00\xbb\xd4\xa6\xa0\x15#\x9a\x01Y\x92\xe3Y,\x83\xe6F\xf5\x97\xb2$\x08\xc5nq\xc5\x18rp\xb5q\t\xb6%\x93r\x83\xa4\xdc(~\xaf\xd1LAME3.100UUUUUUU\x02@\x00`\x14V\x00\x18\x0e\x17\x9cn\x1e\x18h\x03\x98\xd2"\x98\x98\x19\x18g\x0e\x98\x0cT\\\x1b\x14\x86G\x18\x8e\x010\x98\x04\xa0~\x18\x1d\xc0T\x98\x07\xe0 \x18\x08\x00\xbe\x98\x07\xe0e\x18\x06\x00o\x87\x01t`\x05\x80\x8eaW\x02\x12a\xea\x80\x94u\x06\x1d\x16e:\x83\xaaa\x12\x00\xee`~\x80\x12V\x03\x81\xa4\xaf\x9a\xe1\t\x91\n\x18\xf0`8,\x84\x11\x17\x0b\xe4,\x0cX\x00w \x85\x071jsU\x01[\xaf\x1c\xa2 \xfe\xca#x\xb8/\xd0\xc0\xa9\x9d#;\xba"\tl\xd0\xdd\xabP\x14\xc4\xfc\xb4\x88,x\xe6\xbd\x8c,\xc7,\xfe6w\x86\xb5\x86\xf2\xbad\x0bs$\xb2#\x91c\xa2\x9a_RzR\xb6\x0btP\xb2\xfa\x17\x98\x8bn\x16\xebb\x1c\x91v\x8b]\xf7\xd2\xfd\xc9\xa8\x08\x00h\x00q\x91\x80\x04\xa1\x9a)P\xd0\x0e\x16\x05\x0c\x02\x01Z0@``q\x1c\x02\xf6\xcc>\x15M\x12\x03\x93\xe8\x04$*\xa20\x98\x10\x0b\x03\x82\x1501dB0h\x1a6N\xb29`\t\xb4\xb4qY\nk,e\x8d\'i\xf0\x13\xdf+\x94\xdcf\tz\xd7I\x97\x0c\xb0f\xb7(\x8aI\x8a?\x18\xfb\xe7\xa8B\x945\x0f\xe5\xb2\xe6\x9d?\x0e\xa7\xcc\xb5VT\\\xd1\xd2\x8b\x90\t\x90\x81\xe5\x80P4\xce\x7f\xc7\xd1\x81\x8a\xa6\x16M\x19=\xff\xfb\xd2d\xab\r\x06~)\xc2\x93\xbf\xd9\xd0tEi\rw\x0b\x87\x18\xa0\xa9\n.\x7fGQ\xb5\x93\xe3u\x9e\xac\xf1\x92o\xcfQ\x8b\xe2\xdda\xef\x14:\x01\x8a\x8c\ri\x80J\x04\xf1\x80\xb4\x049\x81\n\x021\x80T\x06a\x81\x02\x02I\x80\xf8\x00A\x80\x9e\x011\x80.\x03\xa1\x83\x1a\x04\x99\x83\xfc-\xf1\xc23j\x81\x92d\x1a\xc1\x83B\n\x99\x81\x80\x06Q\x80\xd2\x04Y\xac@k\xc7\x01\x9d\x82\x94\x00\x83#\x8882c\xa5\xdc&]\x08c\xc6\x90\xf0\xdf&i?\x15|\xe5\xd1j\x95\xe5\x0e\x98\x88\xa1\xd8\x82\xae!\x85\x9f/\xc7\x9f\xf6*\xc4GN\xb2Z\xd5l\xe3\x01\xf3]\xed|;\xab\xb8\xefVDW\x1d\x96<T\x93\x91\xfa\xaf\x17\x10,t\xffO\xa4e\r\xa6X\xecY\xf4)\xd7\x8b\xd9Qdk\x12\x97\xf7\r\r\x800\x00\x00\xa5\x80\x01\xa6d\r\x14\xdeh\xc6&X!\x00\xe9\x84\xc3\x87\x90\xe8\x10|\xc2\x80\xa8\xd0\x80\xac,#\x18&=\t\nH@\n\x04\xc2\x01\x03\x00\x0335\x87\x11RL\xc4?|\xc7\xe0\xec rF`\x10\x04\xb2\xd1\x1e \xca\xda\x02\n\x12\x8d\xceCq\x08\x86\x9a\xed3el\xe5\x14\x14\xees\xe5\xd3h\xdb\xc1\xfb/\x94\xa6o\xe7\xf5\xd5\r\'\x9f\xf7\xaa\x80\x00\'\x7f\xb1\x19\xa9I\x84\x86\x19\x12Q\xa5\x04\x19\x10`0D\xe0r\xce\x9e\x8c\xc7\x9cON\xc7\t4\xc3\xb8R\x0c?\x82\xd8\xc1\xf0\x10\x8c\x04A\x9c\xc2L,L*\xc2|H9\xcc\x17\x01\xe0\xc3\\D\xccD\xc3\xb4\x02\x01flV\xc6b>)\xd0\xd5&Y"\x98\x14(c\x81a\x90\xc3\xe6\x1f\x0e\x86\x04\xdb\x81m\x0bH\\D\xc0\x840\x04$\x16\xc0\x10\x16jN\x1a\xefX\xee<%\xc3T\xe9\x0e\xb1\xd9\xdb\xbc$:r\x19\xdb\x13\x85\xbe\x8a`\x98\x8b\xa2M\r\xac"\x91\x8eN>\xeb\x9d@\xd7{\x8f:\xe9\xac:c\xacx\x1e\x00a\x8b\x10\xb7\xeb]\xf4P\x04\x02 \xe2\xe8\x93;i\x08\x80D\x88i\x91\xf53Et\xc3q\xe0\xb5\xde\x98\xea\x9d\xc7\xa3}\x19\xc3\x10]o\xdc\xd3X]\x8b\x11\xaeYv\xd6\x11vF9^\x1b\x87\xe3v\xf3\x95\xc6\xe1\xf9~U#\x11\x89}\xfa\x91\x88\xc4b\xc6\xe9\xe9),s:zz~\xd7\xa7\xa7\xa7\xcfXRX\xcf\xba\xc2\x92\x93\x91\xc0\x1c\x1e?0\xf3\xf0\x11\xe0\x06t1\xd1\xc7\xf0<\x06Ug\x99:>\x1a\xca\xa4`\x15p\xb8\x06\xdc\xa6\x02\x88$a\x96\'\x86\x03\x11A\x89B\x97!\xc0\x10\x06\xb0\xa2\xc8\x0f\x05F\x0e\x86FW\x96\x86\x1e\x80g\x82u@g\x88\xc0\x00\x1c\xc1\x90\x19H2F\x1a\xba\x1c\x88~L\xfd\xbf\xd1;\xd4\xfa\xc9\xe2\xb5\xbc3\xbf\xbf\xfe\xdc\xeeo6\xff_\xfa\xdf;\xde\xcag\xff+xe\xabA\xd0dI0\xe5}\xa8\xfd\x1e\x8a\xb6\xff\xaf\xd9\x8e\xd9\xff\xfa\x80\x06\xff\xaa0h>1\x8cn1\x144-\xf9\x85B\xf9\x8f\x849\x8f\xc3\xd9\x87\xc4\xf1\xaa\xe21\xa1K\x11\xb0e1\x8cE\xb9\x99\x06\xe9\x9b\x85\xe9\x8e\x00y\x87dq\x97&!\x9a&Q\x8a\x00y\x8b\xe8!\xbc\xb5\xe1\xe8lA\x9b\xe0\x91\x86d\xb1\x97d\xb1\x8d\xa2\xd1\xfaB\x19\x1a+\x1ag\x19\xa1\x17i\xe6n(\x9aY\xd2\xef#\xf4\xbd|\xaaUJ\xea\xc9\x172\xedb/\xce\x12\xff\xfb\xd2d\xff\x8c\xc8\xaeT\xc8\xbb~\xe1\xc2v\x84\x98\xa2g\xdd0\xa1\xe9W$n\xe5\x93\xcaL\x90\xa1E\xafp\xe0\xa7i\x9dOn\xb44\xd6\x9a\xf4=]\xd9r\\\x98\xd5\xa9K\xfa\x91+\xa6+\x01)\x92^\xa4K\x05\x94.d\x86H\xa6]6\x82b\xc9\x16\x890\xa0\xf7\x05@QU\x15X\x94\xfb\x01BIxS\x06\x05iH\x9c\x8a\xa9\xd3\t}\x96\x19S,g\x1a\x9d\xc2XeL\xba\xa0h\x05aU+\x11\x97GD\x10DE&\xd0\xe8B\x10DS\xd6\x84 l\r\x8f\x92\x8e@\xd8F>\xb9\xc9$I1\xb6\x9c\x98\x98\xad\xa2\xe3#\x15\xb4h\xc8\xf9w\xb2\xb8\xc9s\xda\xb4\xc4\xf5\xdcAM\xc8%\xc1Cq\nx(\xaf\x057 \xa0I\x8f\x17\xe0X\x10\x1e\xf9\x00\xa5\x9ca\x8c\x80 \x98j\xb5Q\xbfq\x08\x18j\x02q\x83H\n\x06\x04`\x14\x01\xc1\x00\x1c`\x0e\x04\xe1\x00|`L\x03F\n\xc0\x18a\xe0\x1e&\x0f\x81bmrT\xa0y\x01\xa4\xc5\xa4\xc4\xb4\x05\x98$\x04\x00\x07\xa2\xb3iH\xce\x98\x8b\xf3j\x01\x87\xe5t\x13\x18\xd3\xc70\x95\xda\xc6\x9bV,R\xa2&\x1c\xc7]\xe7\xf3\xf0\xd3\xd1|c\x9b\xf0 \x84{d\x82\x0frv:\x8b\n#B\xac\xee\xb3\x81\xec7\xd2\xab\x11\xfd\xa9v\xd5\x96\xd3\xedw\xa5\x96\xfc\x85@\x00%\x1a\x05\t\x05`\xf0!\x98!\x01\xf0\xd0\x15\x18\x04\x01\xf1\x10l\x18,\x84Y\x89x\xc1\x98\xf5\xa9\xc9\x97\t\xf5\x98\xff\x89\xd9\x87hy\x98\x00\x80\x19\x82X\'\x98\x0b\x811\x81\x082\x98 \x83y\x81\xf8 \x02C\xa3\x13\x08\xa30\x97\xc3\xf8\x81Sb\xc2\xd3\x08\x00\xb3\t\x83\xc3\x07\x82#\n\x81\xa0P\xae\x0c\x02\x17\xea\x1c\x1bEH\xf7\xbf\xac\x99E\x1b\xc5\xf0`\x10\x13N\xc3)+K#\r67I)\x97&\xd3[\x97Xr\xe8\xe1R\x9d;}\xec\xeb\xaf\x16\xbd\xddH0\x88}7&X}<\xd5{\xfa\xa7\xfa\xd8U\xce\xed\xea\xd7\xa69\xf9\xd3\xdc\xbd\xbbw{_U16\x17\x13\x87\t\x8a\xa7\x99e^\x82(@?R\xac\xf8<\xb1\x89E\xecp\xb5\t[5\xa0\x00\x1a\xb1\x04\x9d\xf5~\x01\t\xc4\x80\x86\xbc\r\x05GA\x93\x0c\x85A\x04\xfc\x7f\x826iQ@aXJc\xb8\xaaU\x14\xcc\x87\x15\xc0\x01\t\x84\xe1\x91\x80 \x99\x86b\x11\x96\x06Q\x9c\xc1\x91\xc9\x99\x89\xb8j\xd9\x8e`\xb8\xe8``\xf0\x06`X\x08\x10\x0b5\xe0\x00\x0c\n\x02\x1bY\x1b[\xa5\x97[}%y\xe3.}\x1e\x18}\xa4\xc0\x0e\xc3\xb6\xe9\xbb\xf2\xa7\x06\xcc\x8e\x1b\x97X\x87\xe5p\xfc\xfc\xe4\xae5\xcbs[r)^\xf7m\xd7g\x15"\rrjn\x96\'M?I\x8d%[Y\xe5\xba\xb6\xac\xd3\xd0R\x95\x02\x04o\x13\xa4 \x110\xfd\xff\xf6!\xe8w^\x9fM}_\x99D\x18A\x80\x00\x00\x00\x06\x05p\x08F\x05h\x11\x86\x04X6\x86\x08P9\xe6\x14x\x7fF\x06\xb0\xacf\x07\xc1\'fBH\x03&\x16\xe9\x1ef:8MfN \xd5F\xb5DMF\r\x08\t&\x03\xf0\x05&\x0b\xc0\x17F\x07h &\xab\xf1Qf\xa6\x19\x94\xe6\x13a\xa4r\xea`fa\xc8\xeaoZq\xc0V\xb1;h\x1c\x83\x15\xd0u\x1e\x08\x93\x01\xc0\x181\x83\x12\xb3\x16\xb0\xc10\x1e\x07\xff\xfb\xd2d\xf8\x00\x06I5\xc4={\xa0\x00\xb0\x86(\xa7\xae\xf4\x008\x12)\x0c\xd9\xff\x00\x03l\x18\xa2s;\xe0\x00\xc3;\xb1*2#*\x03\x11p\xa3\x04\x80p\xb0\r\x02\x00)j\x983\x00\x91\x83`!\x18\x18\x00\x99\x80\xd8\x05\x98~\x03X8\x07L1\x80\xe4t\x18\x14\xb0\x14\x04f\x00\xa0\x04\n\x00\xe5\x80\x10\x80h\x18\x0b\xc1\xc0\x18\x0e\x01p`\x07\x18C\x03\t\x82(7\x18\x0e\x80\x99\x81\x98 \t\x01\xfcY\xfa\x8aR\xcfC\xc4@\x18`$\x00\xc8\xba]2\xd3\xa93\x01\xe0+\x11\x00\xd9\x81p\x0b\x85@\xa0\xbb P\x10g\xd7$\x19[\xb3Z \x97h`\xd0\x03\x00\x12\x01ha\x80&`\x0e\x03\x01\x00\x16`\x18\x00a`\x03\x03\x00i\x08\x04Ov\xad6\xe7g\xbb]a\xdby\xc7\xbd\x9cB\x16\xa4\x1a\xdb\xa0\xe8T\x01\x0b\xb6\t\x00\x05\xd6\x83\xab\x02[\xd1\xd0\x00\xefo\xe7\xfa\xee\xbb\xfe\xd6\xe4vdnD\xb1\xa6G\xe4o\xfd\xf7\x15/\x98\x9a\x195\xf4\xe9Z+Uy?*\xdd\xfd\xe6Ye\xcd\xff\xfe\x18\xf7\x92\xc9\xe8\xc5\xe8\x12\'/\x87\xf2\xb1RY\xf3\x94\xec=a\x9fw\x15\xa4\xb2V\x050\xce\x9e6\xb4\xf4\xbd\x8c\xa6)\xff\xf9s\x9f\xbf\xd7\xff\xef\x9d\xff\xff\xff\xff\xff\xff\xbf\x0f\xdc\x96F/v\xed?o\xd2a,\xa7\xbf\xff\xff\xff\xff\xff\xfe\xe5D\x9cg\x86\xfb\xb2\xfa;0D\x0e\xedK\xe1\xd8\x06C\r\x10\x00\x08\x00\x04\x01!\xe2\x00\x00\x00"\xc0A!>\x17\r\x8cd\x0c\xc9B\x03\x12\xc0\xf3)\xe7\x03\xb2\x07\xd3\x18\x91\xe3\xd6\x06\xc3\x04\x15\xc3\x89\x88\x93B\xd03\nG\x93\x11\x013\x1f\xd2\xe3\x16Gs1\x81\xf3\x08\xd0\xfe4\xb1\tc\r\x10\xe72\x88\x16\xc3\x0b\xb1\x8c1:\'0h8\x98^\x83\xa1\x82p\x1a\x18\x80\x02\xd80\x06\xd4\xd0\xc0\x00\x1a\x8c\x11@I%\xc2\xa0J\x15\x00\x94\xedL\xb4\xc3&\x004\xf6X\x16\x01)\x90:\xac\x11\xa2\x89\x00\xd3w\x7f`\xa0p\x07\'\xc3\x86\xec@T\x0b\xae\x97ub\xef\xfc\x9e5H\xe5\xd4\xef\xd9\xad\x8d\x0c\xc6U\xb7\xcd\xef\x1d\xe3j\xd7s\x96\xe5g\x1b\xf6l\xf3;\x10@\x166h\xb9\xe4\x13\x9e\x110\xa2\xdc\xce5\xb1x\x94\x9a\xb3\x16\xef\xeb_\xaa\xd9\x13R\xdag\xaa\xff\xfb?\xae\x8e\xa7*@\x00\x05\x11\x04\x98\x12\x80/\x98\x03\x00\t\x98\x01\xc0\x1b\x98\x11\xc0 \x98\x19\xc0\x9f\x18\x1a\xe0w\x18\'\xa0\x7f\x18y\xa0\xe3\x18JaB\x98\xa1b\xbd\x18\xd7\xee\xd1\x1a\xb6\xc4\x8a\x98\xdf\xc1\xa6\x98 @\xd4\x98-\x80\x9d\x98@\xc1\x8e\x98e\x01\x1a\x1bW\xcb\xd0\x9e\xa1b\x9f\xae\xc5\x198\x82\x99\x84\x8f\x9d`\xb3\x99x\'\x15A\xb5\x15080J\x16\x92`0\x0e \x00\xdb\xb2\x8c\x0b\x0c\x92\xa6\xea\xc4\x97 T\x021T108\x05s+\xbao0\x882\x0c\x1a\xe1\xe7Y\xd2\x97\xc3Ap%\xc1\x85;s\xb3\xb0L\xa2=&\xab\x04\xc3T\x93\x92\xe8\xa3\xf9\x1a\xad\x12\xceU1=,\xa1\x88\xcc\xdb\xa9V\xee=\xbb~\xb6?\x86\xffyk/\xfb\xfd\xeeX\xfd\x9f\x1eaJ\x0e\xdf{2[ir\xbap\x92=\xfa\xf8\xdd\xac\x1f\xacP@\xc0\x00\x00\x80\xdf\xe0\x05\xd9Qi\x01\xc3r\x86\xac\xd7\x0c8T.\x8a~\x00\x00\x026\xbc\xccW\x91\x80\xff\xfb\xd2d}\x04F\xce6\xc4?\x7f\xa0\x00vf\x19=\xed\xf0\x00Y\xf8\xe7\x0eM\xffeA\xd6\x18e5\x8d\xa4\xfd\x00)[z\x96\xe6\x10\x017C\x03\x02\x8do\x06\x0cV\x84\x03\xa3\xcc\xaa\x1d\x86\xa1\xb8\xa5\x8b\x12iE[\xb6\xf0\xcb\x98\xe5\xbe\xdf\xc3\x9c\xff\xff\xcb\xfe\xcd\xf8\xfd\xbb\x93|\xee\xb3\xb3j\xe65+Nj\xad6\xec\xfd>3\xd6(0\xa9\xdc\xef~\xf3\xaf\x97q\xce\xdcl\xae\xd2-\xfb\xfc\xde\x01R\t\x99\x01\x98  $Q~\x1fx1\xd8\'\x18\x1e`\x01\x98\x8c \x1f\x18!\xc0\xf4\x98T\x00\x91\x18(\xb0\xcd\x18\x1c\x83\xc1\x98\x0f\xc0b\x18\x0b\x80\x06\x98\x16\xe01\x18\x01\x00\x0b\x18\x05`*\x1cm-e\x18*b\x83\x18\x01\xa0i\x18\x19\x00\x85\x98 \xc07\x1c\xd2H8\xe0\xc6\xc6\x85\x95\xd0h\x02\x0c\x00\x1fS\x11\x004p,Tb\x80\xf2\t#rgI|l\x86$\xc4M+&2\xa7$&\xc5\x19\xd9\xc4\xdex\xec\xa0P2j\x1f\x95P\xbe\xd1\xc8\xe4\xdcb8\xdc\xdd\t\x14\x1c\xfcN\xc5)\xebW\xdc\xecnURn=,\x98\x9c\xca\x93\x0c3\xa9\xcc\xa9\xe7\xb9\xdcr\xde\x19\xea\xaf\xe1\x95\x9c\xb3\xb7\xaf\xfc-\xe0\x90y-Z\x9e\x93zwk\xdf\xfe\xcd\x9d\xcdvS\xa3\xef\xaf0h@"-\xac\x01H\xda\x01D\r\xa4}s\x9c\xc0\x19s\x07C8\x01\x134t4\xb6\xb3#\x0e,\xf1\x88\x92\x8e\x88\x91\x0e\x1dB\xa1\x84\x8d\x90\x80\x198\t\x88\xd6\x98\xc0\xab\x11\xba\xd2\xa2\xf0|v%\t`\xd0$\xe5H~S$\xe6\xe9\xd5NV\x96\xc3/\xe6\x90\x11\xa1\x81v\x89V|S\'\x1b#:=h\xd0\xa2b\xca9oP\xb6\x1a\x92q\x9f\xf5-V\xc2R\x84\x9d\xaf\xa5\xba\x7f\xb5LAME3.100UUUUUUUUUUUUUUUUUUU@\x00\t\x10\x04\x98\x00DcPq\x8fL\xd2\xb3KjLT#0\x14\xc1?1\x05@\xf40\x13\xc2\xe30\x12\xc1\xa90\xaf`\xbc5*E\x0b0 \x00\xb2\x10\x81\xae`\x1f\x80\xee`,\x80\xa6`B\x02\xdcq\xe3+b`~\x8b\x9a`X\x81\x9c`c\x80\x92`$\x07\xaa\x00\x14\x01L\x01\x99\x8c\x80\x0c\x14\n\x9a\xc8\x06Wk\xc0p\x04p\x10\x0c\xe72\xfb\xd36\xab\xe0\xced\x102U\xed\x1d\xcf\x15 &\xdao\xae@\xd5c\x84\x01\xb1\xab.\xbe\x9f\xa9\x044\xcea\xc6\xf6\x8eR\xdd\xd9s\xff/\x80\xe9\xe5\xf0\xd5#\xa5\x06Z\x94R<\x91\xcb\xbd\x99\xed\xae\xee\x9e[\x8c\xb7\xf9R\xb6\x15\x05I=\xa0W\x0c\t\xce\x12rv\xbdi\xb9\xec5\xac\\\xdf2\x9a\xf5X\xab\x10\xba\xf1s\r\xff\xffX\x80\x00\x00\x00\x83\xbe\x80\n\x8d\xc8\xc2`\x82\xc8\xa1\xaa\x13\xcb\xe2!\x02\x01\x11\xa6d\x17\x19\xbc\xacv\xb0i\x82\xc2f&\x01\x98<\x0ea\xd0 b\xd8\xb8r\x1b\xca\x1c\x82\x8e\x01\x89\xda\n&\x0cU\x03\x15\xbe\x818n1g\xf6Otq\xe3\xd1&+e\x16\x8f\xf0\x08\x98\xe2KJ\xe5\xf8\xa9\x88$t\x80S\xa3\xc9\x03\x82&Z\x8b#\x05U\x0e\x15\x8a8\x8b\xe9\xa3e\xf6\xadJ\t\xba\xfe\xc7E@\x162\x89G\xe4\xb7MQaD\xc5\x04\xf8\xc0\xc1\x14\xc7\x95D\xec\xf3\x18\xcf\xe8\xf4zz0\xfd\xd6\xa06\xff\xfb\xd2d\xb4\x0cF\x851C\xbb\x9f\xd9Pv\xa5\xe9\x1ds\xa6f\x17|\xbf\x10n\xffh\xc2\x16\x15\xe2\x9d\xed\xb1\xd9\xfbD\x0b0U@\x100N\x00 0#\xc0:0\x1b\x80n0\x1b\xc0\xa58X\xd1009\xc5\x9a\x0e\x01\\\xc01\x00pd!cE50\xb3\xc0\x119(J\x02\x9b\x02K\xbfJgB\x96\xe1\x8e\xcf\xf3\xc9\x02@\xe9j\x05\x91k7.\xb0\x9a1\xd0!ljh\xb5\xf9L\xf8\x14#/^\x8e\x1bM\x7fi\x1ac\x0bX\xb1\xa8\t\x9fLF\x9e\xe8\xdb\xbdGEV\t\x9b\x94\xe7\x84\xec\xa6\x7fW\xabas\x1cr\xa4\xbd\xba\xd7A\xe0\xb17\x81.\xa6\x9bffYY\x16=\xa4\x1c\xf6l\xd5\x1a\xa6\xde\xb9\xae\xba\xb5 \x00q\x90\x03\x12vL\x03\x80 \x04\x02a@\x18E\x82\x1070 \x01C\x04\x81;0\xaa\x04\x82\x02\xb93E\x03c\x02 >\x00\x01\x89\x82\xf81\x18(\x86\xa1\x830Y\x99\xe2%\x11\xc0\x18\x1a\x02\x19\x90\x8d\x99*h\xbe\x11\x87\x822\xb5hAR\xf4\xb6t\xd6o\x19\xbc\xb9\x8fF\xa55\xdc\xb872\xe5\xe8\x9e\x13\x05\xc7\xd6\xad\xe0]\x1ct\xdc\x85"\xaea\x88y\x83\xb7}\xd7\xb9\xea\xd7\xe2U\xb5\x9e\xd8\x1al\x0c\xaa+\x82\xacu\xb9\xff\x82LAME3.100\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\x02@\x00\x00D`\x00\x1e^P\x108kx\xbac@\xe6a\xac\xd6u\xcb@h\x91\xbek\xb9~bP\xa6\xa4x\xb6\x84\xa6`\xf8\x80\xc0`\x82\x00t\n\x05\xc8\xc0\x12\x05,\xc1&\x06@\xf3bW\x84\xc1\x19\x1f\xac0\x0e\xa3\x03L\x05\x13\x01`\x08s\xa9\x00LLD\x18\x00\x18@2`\x80\xa2!\xb6\xaa\xd5/Zb\x11\x18P$\xd2g\x1cIz\x1c\x8c\xe0\x98\x0e\x116\xaf\xd2d\xd1.\xf2\x89\xd5\x1d>:\x92\x18H\'E\xa4\xd7\x87\xe69\x0e\xe16\xfd\xc1\x18Y\x8do\n\xfa\xbfOM(\xff\xbfz\xd8<\xf0\xc8\x14@Z\x84\x0fD\xdc\xc0\xaf\x9fj}\xbfx\xe7\xfb\xf8\x83ZP\x88C\xd1\x1d\xc7\xa5/\xd5U\x8b\x90\xea\x17\xec@\x14\x0b\xab\x89\xc5\x19P\xc0\t\x88\x14\x0fk \xc0\x04\xc4 HBF\x87\x14`\xd8\x8c\xdd\xd0l\xc4 ,\xc1\xa0<\xc0\xd0t\xc1\x00@\xc2\xb10\xe7~\xb4\xf3\x88\x85B\x0cdX\x02De#\xc9\xca\x8bq\x08~isRYqP\xee\xc2\x96\xeb\xec\xe2\xe7\x856\xb7`0\x12:\xed5Y\x17B\xc3\xd2D\x8e\xceIe\x1cq\xe1\xb2A\xb5\xa0\xb1f\x87\xa6<\xc8\xad#\xa1F\xce$\x02\xea5\xf1eWo]\xaa\xff\xb3\xeb\xb3\xff\xa8\x01\x10\x00\x83\x01\x00q\x18$\x86\x02\x80\xd9\xa1\x8a\xb9\x8bc\x886\xb70\xf9z28/5\x90;1)\xc3\xed=\x0f\xc0\x1b0\x91@;0W\x80\x180\x17\xc0\x1c0-\xff\xfb\xd2d\xba\x0cE\xe8(B\x93\xbf\xe24\x82\xc5\x98\xd7whv\x17\xa8\xa3\nn\xffh\xc2^\x11\xe1I\xbfd\xe0\x00O04\xc1\xd5=\x1cQj0-\x08,0.\xc0f0\x13\xc0Q0\x07\x00Y9\x01s\x174\x00\x8e\x00\x86\xcb\xae\xc2\xd0u\x90\xc6\\dU\x12\xc4q%\xb2\xd9\x1a\xe0\x1f"+\x16{\xaf\'\xfb\xe4*6Fe?*\xa3\xecl\xc7A\xa7\xab\xa9d\x1d,\x95Fc\xb0T\xba\x18\xb5*\xa6\x99\x96s;\xf9\xe5+\xcf\x0c3\xca\x9f\xb3\x963\xbc\x043\xd0\xa6\x1e\x8b\xc0>rEj\x01FZE\x8d\xb9\xe5\x96G\xacoID\xf4{z\xb8\xafR4\x13\x02@\tpp\xda\xa5\x16\x114\xc01!\xf3(\x18=\xc4\xf1\xc1\x8d2c\x07\xa3\x06\xf7\xbd1O\x16`\x10t\x85\x01\xb0\xc1\x14\x1f\x8c\t\xc1@\xc1("\x8d\xe2\xae\x90\xc5D7L\x18@\xf0X\x1f\x00\xa00\x13\xc8\xd6\xa1\x87\x98\xc5\x9a\x04\xa6\xe2\x86\xb6\xef\xf3\x9d\x01\x8b0\xfe\xf6\x82\xe4\xa5+\xb5n\xb5\xeb\xe8\xbcL\\\xe7)\xec\xcc\xc3\xd7\xa9\xafgZ\xb4\xbe\xcf\xda\xaf\xdc,\x7f.\xe7\x07\xa3C\xea{\xaf\x8b\xae\x99\xde\x8f\xd5U\x8d\xc5\xf4\xb1\xd4\xddF\xea{\xd7Z\x1a\xcb{,(\xab8\xff\xba\x95\xd4\x8a\x00\x00\x00\x03 ?\xf9\xa0`\x0e\x02&\x01`\x08`\x84\t\x86\x00\xc0\xbea2\x01\x06\x04\x81TaT\x1b&\x13a\xca`\xa82\x067\xe2\xb8g\xcc8\x87\x02l\xd0d\xec&\xa6Bb\xa2a`;\x062\xc1RfJ\x9b\xe7f\r\xb6\x7f\x13~l\xda\xeec\x92\xech\xd0\xd2h\xe9\x86a\x91\xa8e`\x1ee\xa9:b\xc5\xa8z\xc8\x1eu\xd5\x80c$zsiFd\xa1Xa@\xdad8nb\xa0\xeca Zc\x004b\xcd\x81\x81\x1a`i\x8e\xcc\x1b\xab\x94\x92\x05\xc4P\xa4\xd7/b\x94\xa2:&\x17\xf5$\xd2\xac\xcf\xb09\xc3\r+\x10iad\xa1\x85\xcc @)S\x0cD\x05,\xcf.\x02#6\xa0M3 \x02Sb\x04\xcf*1&\x02$\x18\xf2\xe2\x11\x04\xc5\x01\xc1\xd2\xa17T\xd88y\x80\x10"\x0e,|\xc5\x10\x14\x1a,\x9c\xc5\x10\x18\n<\x80\xc2\x87\x1d\x00P\x00\xb8\xeb\x00\xc3Z\x93\x10Z\x0c\x85Q\x97\xf1TS\x8c\xbb\x8a*\x99\xe8K[Jp\xb1\xdb\xa3\xf2\xf3\xb9\x0f\x1b\xb2\xdb\xc3\x11\xd9\x1b\xf9\x1d\x93\xbf\x91\xe94n\x82v\x9e\xa5\xdbV\xe5\x15g\xe3\x144q\x8a\x1b\xd4\xf7/[\xc3\x1e\xe1S\x1bu*\xdb\xa4\xabn\x9fW\x82\xc00\x8aB B`\x90\x0c\x86\xa2\xec\x1ca\xa3xX\x06@.k\xd0\xd1\xa9\xbf\xd4\x90\x19\x10z\xa2\xed\xe04\x00a\xb2\xd26\x18\xc04h\x81\x18\x10"u\xd2\x01\x83\xe2z\x9ar\x04\xa1\x80@I\x98\x05\x83\x01\x82(\t\x18\x04\x01\x99\x82\xe81\x1a\xef\xc3\xe9\xb1h\x18\x98\xb8X\x18\xca\xa2L\xe0]t+z\xe2c\x8e\xbb\xe5\x1b\x83aM\xd1\x12q\xdev\xab\xabm\xbcr\xaf}\x85\x13\x05\xe3\x97u\xd8\xaf?{\xe6\xb5\xbd\x7f\xef\xf9\x8d@\xa0\xb0\xd0\xd0\x14\x0e(\xb4\xa6>/\xd7g\xc5wW\xabk\x9d\xff\xff\xfe\xad\xdf\xfd.\x86\x80\x00\x00\x9e\xb7\xfc\x00\x83\x98\xc5\x88\x98<\\-J\t\x03B3\x11%X\xf6d\xc9\\\x0f\x18T\xcb\x0e\x8c\x9cLY\xff\xfb\xd2d\xff\x80\xca\xb4R\xc7\xeb\xdd\xd3\xb0\x82\xe4Xrs\xdbD\x15\x91#-\xac\xed\x89\xcaw\x96a\x89\xafl\xd8\xa4\xcf\xc6\r\x18\xfcB\xa8c\x8cF\x82:g\xc0\xe62\\#\x01\x07\n\x82A\x04\x80\xc0@\xa8qD\x84\x1eY+\xf1A\x99\xebz\xc3\xa0\x85|\xce`\xca;9\xd9\x950?\x15O\t\xc52\xc0\x84U3\x01\xa4"9\x8c\x0f\xce\xae.\x9e\x08\xc5U\x04\xe4\xaa\x16\xc1\x1a\xd8?\xbe\xb0\xd1\xe6h\xb9\x97\x17A\x1b\xb9\xfd=j<\xb5\xc5\xc9V.9mkW\xae^g\xe1\xa3\xcc\xb8\xf44\xe6\xaf[o}w\xad\xb4\xb5y\xecZ\x9f\xfd\xccU\x11\xa4\xb4/\xa0\x10\xdbBq\x96q\x8b\xa6c\x91\x08\x0e\x0e_0 \x0bC\x11P\x8b0J0\xd3\x85A>\n\x04\xc9\x868/\x98#\x82\xa9\x82h#\x98q\x8b)\xa3\x14\xcd\x03\nCA\x04\x04\xc1\x1a\x01`SN\x00,\xf1\x82\t\x190\xd0)\\\xbd\xe8.\x8d\x8a6\x1c\x0ea`\xe5\xd3\xcaQz\xca\x95O\xca\xe8\x1cJT@(&\x80\xdf\xf9\\\xbem\xa7\xbb\xf2\x08\xc4b\x92v\xf6\x19[\xb1\x85\\\xeaS\xcfF1\x9c\x80\xdf\xfbU2\xfb6\xff\x0b\x1f\xfc\xce\xd8\xf3\xe0\xf8\x13\xdd\x9bvV\xd5i\xdf\xad\xdf\xf4\xff\xaf\xb3\xff\xbf\xf5\xa20\x00\x00#te\xa4\xb1V\x03\x02\x02\xc0pNB\x06\x18 \x19\x98\x1a\x00\x19\x1a4\x98\xeaK\x99\xb8\xc9\x1a\xcc\xe2\x19\xfb-\x98p\x15\x18\xf0\x12\x8d\x12\xa60\x02fADG5\x07\xa0\xe0\xa7\xbe\x89\xd5\xb2m\xfd\x99\x05\xc1\x0e\xc2\xc4\x0c\x19\x91\xee@\x14\xc6\x14\xfa^\x01\x05\xe8d\x8a\xf8\x14\x16\xf3\xa0\xf0\x04\x19\x7f\x8c\xb0X\x9b\xd3~\xac\x9e\x0es\x9fy{\xb9(\xdd\x99C;\x1a\x1c\xfd\xc8\xa5/\xfc\xb6\x1b\x8d3\xf7\x11\x9d7\xea\xed\xa5\xad\xfa\xac\x9e\x03\x8b\xce\xb5v\x83?L\xfd\xb9\x14\x16p\x92\xcb\xe9\xac\xdf\xb7Z\xfc\xd69\xf7\x0f\xa9\xdb\x1b\xc3\xea\xd3W\xbb^\xb6\x02\xa1\x92\xc3\xb3\x1a;\x0c/C\xc7\xbc\xd1\xd6G-\xef\xf5\xfe\xd6g\xda\xb2\xd0\x00\r\x7f\xd6\x9b\x82\xe0D\x19\x0b\x01\x86\x10\x03Aa\x10\xc0 0\xc3\xf1\x1c\xc2\x10T\xc5@\xe8\xcb\xa8H\xedft`\x9a0\xa8\x051\x18\xb60x<4\t03\x039\x0e):$s-81\xf5\x04h2\x000s\x988\xed:\xc3\x03\xda\xc9\x84\x05\x00\x84\xc6\x85C\x85\xd7\xfa\x94\x17\xf5$\x00\x81)\xb6\xad\xec\xee\x1aw\x9c\xf0\xb8\r\x94Kt\xd8\xba\xd3k\xcf"\xe5\xb7>\xcf\x04\x80\xe1\xd6[\x16\x7ff\xa0\xf7\xba@\xd2\xdc\x05PZ\t\xf8\x9e\xed%y\xc1\xcc\xca\xec\x8e#*\xa9\x95li\xab\xd8\xa1\x95\xcf\xc4\xecfIBy!\xe7\xc4\x08\x12\x10S0\xb8\xf7\xd3\xf8\xfe\xbc\x8f\xfa\xf5\x92i\r\x02@\x00\x00a\xfa\x1af&\xe3\x06`"-\x06%\xe3\xd8`\xe4\x15\xa6\x10\xc1\x04b. &\xc5\xa6\xe6cE)\xc7BT\xd8jV\t\x87\x08\xd4^d\xde &\x06\xa5pe2`\x86}\xa8\x04`\x8e \x06\x13\xa4\xeebF\x87nb6\x86\xe2`J\x16\xcab\xe2\x90Ha}\x0b\xcei\x06\x07\xe0`\xb7\x80\x06`\x8d\x81\xa2`E\x80\xaaa\xaa\x83x`$\x01v`[\x016`\xe4\x00B`\x01\x00"\x10\x029\x80\xa2\x00\xf9\x80\xc0\x01\xff\xfb\xd2d\xfd\x80\x06\x047\xc5Uw@\x00\xb2\xa5\xc8\xda\xae\xec\x00/\xcd\xf1\x1cy\xef\x80\x02\xb9\x94\xa2\x87=\xc0\x00\xa2\x04\x97y\x80\xbc\x01\x88\x10\x00p\xc0\x00\x10\x0e\xb6\x17\xf0\xa0\x05\td`\x14\x00T`\x15\x00H\x02\x00\xc0\xc0+\x00d\x1c\x00\x9b\xd4\x9d\xa0`\x08L\x01\xf0\x03\x00@\x0bF\xe9\x0c\x00\x10\x00\xd8uP\x80\x04\xcc\x010\x06\xcc\x01\xd0\x03\xc6\x80\x0f\x07\x00.\xe5\xb14\xca0\x02@\n0\x03\xc0\x12@J8\xce\xb3\xecs\xdf\xd4EpH\x00a\x80\x01\x98\x02\xc0\x03\x16\xf1\xf8Q\xa2\xf2\x98\x00\x00\x00\x97\xc6\xb4\xdb\x83\xff\xcek\xfd\x9c(\x03$Sw~~W+\xec\xaa\xba\xd1iMz\x8e$\xc3\x92\xfb\xff\xff\xff\xff\xe5\xf9\xfd<n^\xe2F,RF\x1fXv\xa4\xa5\xfd\x96\xfe\xea\xf6\xef\xff\xff\xff\xff\xff\xceF\xed\xf7\xff\x92\xfb}\xafOnYb\x19\x95K\xbbZ4\xffU\xb3\xaa\xb6nU\xa5\xff\xff\xff\xff\xff\xff\xff\xfek\x0f\xc3\x0eaIb\x9f>\xfe\xb0\xff\xff\xff\xff\xff\xff\xc7t\xb1\x9a\xd6\xb7\x96WkSw*j`\x00\x1d)\x0c\x01\xc0\xf9\xe00\x11\x01\x08}v\x01A\x04\xcd$;\x0c3B\x98\xc2\xc14L$\x03\x10\xc5\xd0p\x8cn\x00\xd8\xc8D\x94\x01\x00\x1aa\xf2\nf:`\xd2b\x1c\x06\x87z1\x03G\xa7\xdc(\x19\x94\x98u\x00\xf9\xb1\xc0\xe6\x08\x16\x18|:\x91\xe6#\x06\x98\xe4@`\xb0Pa,H_N\xa5\xab\x9d\xbfl(6\xdaE\x9aC|\xa9ld\xd0\xe5\xb5we\x96D_\x98\xce\x9c\xd7N-/\xc2\x97\x0b\x13\x1f\xff\xb9\x9b\xd4\xdf\xff{\x1b\x19\xf3\\\xb4B\'6\xd0\x80\x0f\x153:KX\x84AyV[\xef!\xeb\xde\x87=\xb5\xca!uo\x15\'\xa1\xa8\xff\xff\xff\xfa\x9fLAME3.10\x00]bP\xc1@\x08\xcc\x07\x02\x90\xc0D\x04\x02\x01\xac`\x00L\r\x81t\xc3\xa0-\xcc\x07\xc8\xb4\x04-\xc6\x08\xef,\x7f\x02<\xe6Dc\xa8b\x1e\x13F\x13 \x08\x15\x02\xf3\x03\x00\x0f0H\x0c3$@\xa30.\x8090(\xc1$0uAN2\x98Si0\xf5\x84!0\xb0\x01U05\x80\xa10\x07\x00T0\x1a\xc0:0\x05\x80Ea\x89\x0e\x15\x00A9\xa6\x18\x0b\tv\xd4\xbe\x9a+y\xa5\x18\x00\xe0\x0e\x11\x00\x13v\xe4&\xb5\x05\xdb\x96\xa20\xe10\x08\x90\xf3^k\xb1w\xca~]\x06}0\x14\x010\x80\x01`\x9c\xe8\\\xabmr9n\x1e\x87\xecc\xfd\xc7\xbd\xaf9Kg\x93U\xa7\xeca\xabZ\xb1\xcf\xcf\xb57\xbc\xe6\xe9\xf2\xddA91Z\x94\xe2Mp\xdee\xf4\xff\xff\xee^eo\xd7\xac\n\x80\x00\x00\x00_\xc0\x05\xc9\xc7r\x14_\xc3(,Bp\xc4\x120B\x8c\xa3\xc3\xc9\x90\x078\xde\x1e.y\t\x11\x91f\xa0Q\xad\xc6e@\xc6(8\t\x1c6\xe8@\xc5T\xf0\x05\x01\xcf\x96\xb2J\xf1\xa9{\xe7\x1b\xa6\xb3-\x9d\xc7>\xe1\x8e\xff_\xdf\xde_\xdc+\xef\xba\xb1\x86\xff\xff\xfb\xfc\xe4r?\x07\xbf\xf04\xd4\xa2\x9e\xd7\xdb\xdfyv\xb5\xef\xbbI*\x8av\xbd\x8b}0O\x9f\xdd\x10\x00.\x10H\x047\x00\xa0f\x0c\x06&\x1a\x80\x06\n\x82\x00\xe1\x94\x02m\x98o\xef\x98@ \xa2\x18d\xe2\x1c\x1c\x1b\xa1:\x98@\xe0\xff\xfb\xd0d\xb9\x84F\xa67F\x9f{\xe0\x00ue\xe9=\xedl\x00Z\x10\xdb\x12\xee\xffGA\xe0\x97\xa4\xe9\xcc\xa6\x11\x97\x18(\x80.\x98\x07 \x05\x05\x80\x950\x16\xc0N0\x0f\xc0c0\x96B\x060+@N\x11\x02\x16`\xf8\x85\xe8lx$\xdcd\x1a\x81\xc0`t\x01\x1e`)\x80,`6\x00(\x7fM\x02 \x87H\x00\x151\x81\x8c\xd0 \xa0R\xcc\xabe\x87\x9d\x8e4\'\xf1m\x99\x1e\xe8\xfb.\x9a\x8dI\xdd\xfd\xc2\xf2\x7f\xc8I\x08\xc6\xbc\xcd~#O\x96\xf3\xdd%\xc2\xa8\xd6\xfeH\xd0 \xb8\x84\x05*\x81\xe2\xb2\x98\nU\xcdvS)\x8eF!\xe7v\x06\xc1\xd3u\xe2\x92h{\x97\xa9\xf1\xfd\xe3\xddc\xca\xbc\xc6\xbd\xa2I\x0e\xd3\x16,|g\xebe\xffO\x7f\x7f\xd3opP\x00.\xd4\x01\x93Z\x87Tt\xbfe@\x00(>\x0e\n\x18$\x00b\x021\xc1\x86\xe6\x99\x13\x98\xe0:\x91j(\x18+&\r\x9a\x18\xbcb \xc9|L`I5\xec\x14\xd0\xec\xc4\x94\x84"\xd2\xab\xe5\xd4\xba\xe5\xab\xd9\x839\xf2\xaa8v\x9d5\xd5\xee\xdf\xb2\xb5\xd8\x8a/LJS0\xd3yIzx\xb6\x81\x02\x10\x80\xd8$\x88T\xdb\xa3/\xe3\x05$\xd9W\xb0\x9bjS;\xdf\xcd\x01\xe1\x9b\r\x99LAME3.100UUUUUUUUUUUUU\x10\x00\x00\x00\x027\xd5\xda\xd1L\x0e\x8e1\x00\xb5\xb5\x938\x01\x08\x10\x82\x04T\xc0\xe8\x0eL%\xca\x04\xe8d\x13\x03\x8a8\xc0\x88\x00\x06@T\x00\x03\x85\xdd0\n\x00\x13\x01`e0\x19\x00C\x02\x10K0<\x07\x83m3R<\xc0\xa0\xcdas\x0b\x08\xa5\xec\xe9\x8aH\x1b\x1bP_\x92\xf8j\x17Z/\x85X\xe5\xa2`J\x8c\xde\xde=\xfe\xcdow\xca\xc0\xf5V\x93\x9b;\x95\x1dx\xed\xce\xb3Q\xa0TQ\xafv\x01\x80,D$SSs\xfc\xb3\xcc;\x96U/\xd3\xd1V\xa9Ar\xdfTpx"H\x1c\x1a\x0e\xa5\xd2T\xc8\xff\xfb\x18\xed\xe4\xb1O\x1f\xff\xc5\xcb\x00\x00\x00]Zq\xa2\x98\xcfAc\xc0\xc0F\x18\xb10\x81\x18\x16\x98\x1a\x0eY\x85\xf0\x1b\x98\xd7\xa4\x99\xfe\xa8e\x05@\xf4\xc0\x94\x01L\x0c\xc0\xb8\xc0\x1c\x13\x0c\x0b@\xf0d\x0cABX\x06\x01s\x01pM0\xfe\x04C\xd1V\xfe3\xb2\x0fc\np50N\x01!\xd0\x13)\xa9f\x93\x05s\x89\xa1\x92\xb3\xc5an\xccB\xc4?bn\x8c")g{9\x8aj\xd8\xea\xae\xa1\xb1\xb9HS\xd2W\x0cBi\xb3\x89\xd6\x95\xab\x92)\xcc\xbb\xef\x9c\xa6\x1f\x86e\xcf\xbe0\xcc\xff-\xeb\x0eU\xb97b\xa55J\xd6\xe9\xa5\xe0cI$\xa9\x94\x06\x9dn8\n\xd4\x7f\xa5\xbe\xb6\xfb=h\xc8\x8f}\x9f@\x04\x80%\x11\x9e\xeb\xe6\x16\x06\x98\x14\x8cP10\xb9\xf8\xc0!\x03l\xc0\xc8\x12\xe4\xc3\xbc\x04\xf4\xc2\xbbR\x8c\xe9\'\x08P\xc3\xe9\x04\x80F\x00\xe80\x03s\x01(\x16\xb3\x01\xf0\x08#\x01\xec\x04#\x06\x80\x17C\x00D\x07\x13\x00\xbc\x0c\x03\x05\xacB3P\x02KS\x1cT03\x05\x08\x0fc\x03\\\x03\xf3\x01\xa0\ncm5\x07\x7f\x18A\xa1\x85\x89\x1a\x90z0\x97\xd4\xc0@\x92\xbd\x91\xa7\x93#bI.\x91\x86\'4Z\t{\xeb\x17\x9f\x81[\xcdD\x9cb\x12R\x01\xe7\xff\xfb\xd2D\xf4\x84EB/Hk>\xe1P\xb3e\xd8\xdak\xd8,\x1b\xa0\xbd\nN\x7fe\x83E\x97\xa2)\xdf\xe8\xe8\xd9Xb\xf4YT\xdd\x0f\xd3\x0c\x07E\xa3\x92\xa9T\x13C3\x00\xd8\x8e\xca\xbbs{\xd6\xf3\xa9\x7f\x0b3\xb7\xf2\x96\xe5\x85\xa3\x02\xc7\x8b\x07\x8c\x01\x83 \xdbjkFO.\xfd+\xa1\xf2\rt=Rn\xe8l~\xca\\\x13S\xab\xa1n\xd7{\xb8\xbb\xca\\,t\xd1\x00\x00\x0c\x84\xa4\xa0\xe6\x1a\xa0\xa6\x19\x85\xc6\x0e\x06@@\x9c\x1a \x18r\x0f\x98\xb1\x92\x98a\x80\x11\x18G)-\x9b{\xa1\xa4\x18T\xe0\x11\x98\x0f@3\x18\x08 \x06\x18\x06\xa0P\x98\r\xc0\x05\x85\xc0{0\x11AC\x10\x00\xae`\t\x82p`\x82\x86~i\x0b;Bb\x01\x85\x02`x\x01\x18\x02\x03\xfc\xc0$\x01\xd8\xd6\xbd!Be\x01\x98\x02BP\x0b\x8e\xfa\xa3\xe3\x16\x911i\xb8\x12,\xc6\x01\xbb\x96\x12o\xb5nI)\xedG\x9f\xe2Q&Pu\xc5\xbb\x16\xcb\x0f\xce\xbd\xaa\xc3\x01\x9a\x95X\x84N\x0b\x84F#\x0e\xf4\xf4\xb3\x99kZ\xa93\x11\xa5\xa5\x8e\xd2LF\xf1\xbb9d\x1d;\x8f\n$\x93\x9a\xff:\xa2\xcc\x8f\xd6\xf4\xc9T\x922+\x13\xbe\xa7\xbe \x80\xde)\x8c*\x06\xa6\x97\x7f\xfdhLAME3.100UUUUUUUUUUUUUUUUUUUU\x02\xe0R\x81\x90\xc8\xc5\xd0\xb9\xa6\x01\x00@\xd1\x0c\xc2\x80\xe0\xc4ql\xcf\xcf\xac\xc5\xd0\x01\xac\xc1\xdf{\xbc\xe2\xcd\r\xf0\xc1\x8d\x02|\xc08\x00|\xc0\x17\x00\x00p\x05c\x02\x94\x00A`E\x0c\x17pF\x0c\x08\x90 \x0c\x01\x10_\xcc\x01!m\x8c\x1a+\xdf\x0c\x0f\xd0\xf2\x04\x00\x80\x83\x00V \x01\xcc\xd5@\x06\x164b\xcd1\xc3\n\x14x\x1ah-(\xdb1\xb7\x03[\xa2V\xd3{\x94J\x0b\xe7&\xc2\x97(\xa5<\xd4\xf2<\x1f +\xf9\xa2\xc5\xa37\xbbAM~\x80.\x90x\x06qG\x9a\xb7t\xfbHj\xee\xae\xb5\xf9\xfe\xec\xca\xf5\x95\xad\xf2\xd565PzK4\x96~\xcb\xfd\x7f;1Of\x9ai\xe3>\x88\xb3\xbf\xabP\xb7\x00#i\x8c~\x02\x11\x13N0\xa8\xe36@\xd7c1\r\x04\x93\x05\x86b0\xa1\x17\xd3\r\xa0\x8609\x03\xe3\x00\xf0%0\x13\x00\xc3\x01`\x15\x1e\x01\x83\x13\x90\xf90\x11\x000h\x0b\x982\x089\x96\xb3^\x98\xab\x04+\x94U\x00\xd58\x03\x01\xd2G\xa1\xc1LPL\x87\x96\xf6Cf\xc7\xea\x11:\x91\xd8\x88\xad\xbc\x8e\xa5}}\xb7/\xd0h\x80\x81\xb4m\xe7\xa5\x7f\xbdX\xd1\x9b\xdd\xdb\xdegPbG\xdd3\xfd\xb3\x8bV\x97\xf0([\x7f\x1d\xfa\x7f\xd9\xff\xd8\n2\x84\xa0\x05\x18\x03`X\x98\x06 ,\x98\t \x02\x98\n\x00U\x18\x15\x00\x10\x18\x13 j\x98\x06`\xef\x98r\xc0n\x18<\xe9L\x99\x8a\xa1e\x18"`\xd4\x98\x1c A\x18\x16\xc0\x17\x02\x80\x83\x06\x804`Y\x01\xec`X\x01\xca`\x9f\x02 `\x03\x02\x1a`\xc6\x86\x16e\xd3\xa6vb\x1f\x04\xaaa,\x81\x96`Q\x01\x98`Q\x00\xf0dE\xe7\x04\xf4\nu2\xd2\xb3G\r!\n1ab`\xc3\x03\x11\x05\x0b\x90\x82\x98\x88j\x0b\x18P\x810!\x80"\x98\xf8\x08\x88\x08\x1c\x08\x9d\xc5\xa0qT\xcdu\xd1\xff\xfb\xd2d\xf1\x0c\xc5\xe5/C\x93\xbf\xd1\xd0\x8bE\xa8\x82k\xcf<%}Y\x18O\xed\x93\n;\x13"\t\x9ft\xc0\xbc\x00\xc1\x83\x01\x13\x03\x00@\xa5\xd7I4\x8c/\x83\x19.;\xbc]\xf4\xd7@c\xa8\x9c\xcd\xfc0-\x95\x04B\x98\x1f:\x04\r\ta\xe0\xf6;\xa40\x89\xb5\xef\xa7\'\xae\x10\x11\x08e\xb1\xc0<\x1c\x04D\xa2Z5\x8b\x1c\xb9\x83\xa4\xb3r@\xe8_\x06\xeb\x80\xfa\xa3\x07\x1b~iOa\xc6\xcc\xda0uz\x86\xdfa\xcd\xbd\xe6\xf7\xc5\x95_\x1a\xc7\x169\n\xfc\xa7M\xe9\xad\xfa\xc7\x1b\x7f\x17\x84#k\xf0F\xd1\x12\xe3\xc4O\xef\x92<\x04\x08\xdaw\xfbDK\x18`\xfd\x7f\xcf$|\xe0t\x07E\x9f\xf1\x0bIT,\x10r\x85\x9fJC\xf7\x90\xe220qhc\xfe\xd7\x935\x83\xe3\x0e\x01\xb0(2\x82\x12@H,\x05\x81\x9fS\x02\xc13\x02\x05q"\xfc\xce\xee\xe0\xc7\x90\x88\xc0 \x98\x04\x13\xbc)j#\x02ReU\x06\x80\x87]\xcdb\x10\xf5>2\xba\xb9\xd4Kigy\xbcoj\xfd\x8e:\x03@\x8c\xf4\xff\xf3\x9d\xfc?\xe0\xb9\x0f\xd6\xb9\x19\xd56yMU\x07\xc0\xe3\xd2,\xc1gIz\x7fR?e\x0f\xea\xf6\'\xba\xe4\xad\xac1h\xfb\n\xbd\xceT_\xfe\xd5 O\xfd\x84*\x06C r\x02\x06\xd3\x03\xf0\x840\x91\x04C\x05\x80\xd70\xee\tr@\x9a0a\x15#\x1a\xa4+<)\xd92(\xfa5\x04\xbc0\xd8\x9b1\xe8\x131d\x8c14O2@\xed1\x9c\x895\xd9\xbd5\x08\xc33\xf2\xcf5\xb8c4m\x884\x84:1\x90\x912\x00O\n\x07\xa6#\x05\xa2\xc0a\x81`\xc1\xd2\xb1t\xcc\xe8M\xe1\xc40\x1c\x0f\x97P\xd3Phs\x18\xb2\xde\x18\xe8\x02\x96\x1c\x0c\x0c\x13KE\x18:\x1a\x8d;My\xf3\x8e\x99\x8c\x86Bc\xb4n\x8c T\xdcDP#M%`,\xd2\xbf.\x08*V\x14\x89\xc6\x08\xc4\xc1\x18k\x1b\xa5\x08\x1b:\x9f\x06 v\xd4\x02l\xe4\xb4j\xc3R0v \x14\x00Q(\x99vYl:\x8e\xc6\x00)\xa0e\x9c$\x19\x98\xb8\xd3&:\xc0i\x82\x89\x99\xe1\x15\x032\x83\\\x85\xb6l\xef\xeb\xb2\xad\xaf\xd9nS4* AB!@J\xa2\xe1\x8e"\xd00\xc0y\xd6\x16\x05\x86\xa3T\xd6\xdfg\xe9\xe1]/B\x83?\xe9\x8a\xea)\x8bz\xca\x9dh\x8c;\x86ST\xb7\x1f\xeaw&@\xd6\xa0gE\xfa\x88\xbf4\x10\xf6t\xb8\xe3\xb9M\x88jD\xfa\xc0\xb0\x13\xf5Z\x9bvy\x97\x7f\xf2\xee8\xd6\xb5v\x96\xe5.\x14\xdd\xc7\x9a\xff\xfc\xbb\xbcukvwU\x13\x7f\xfc*H\xa8\xd3N\xff\xf9b\xc2\x85\x16\x94\x18\x06\xe9\x13\x86J\x06\n\x01S\x020\xad1C\x05\xa3\x0bWJ7\x7f\n\x93\x04@_? 4F\x19\xac\x1c\x18\x0c\x86FW\x92\xa6\x15\x02\xc0\x00`\x04@\x9c"T\x9b\x08\x17\x18\xaa\x01\x98b\r\x03A\xa4<O\x1b\t\xe2\x89/ceh\x12(\xa4B\xcd{3b0\x0e\x13\x9e\xae\xd4\xb3o\xfb\xc4\xde.\xdf(\xf9\xbc\xb0\xd7\xf7o\x8d\xf1\xc9\x82\xba\xdemZ\xfb?_\xed[\xd1\xff\xfe\xfd?wC}\xe8\xff\xfa\xd6\x84\x00\x08\x00h\n\x0c\x06\xc0\xe8\xc0\xac\x01\xcc\x0e@<\xc0 \x0b\x80\x00z`\x04\x10\x86\t\x818d\x1c&\x86\xff\xfb\xd2d\xff\x80J\xeeh\xc8\x1b\xdd\xcaR\x7f$(`{=P\x17D\xc7\x0e\xd5\xee\x80\x02F\x19c\xea\xbb\xb0\x01t3\xf6m\x18c\x86=\xc2\x80$\x05\xa2\xc0k\r\x18\x05\x00)\x80x\x01\x987\x01\x99\x87\xc2\x89\x88\xc3\xb1\x92\x88\x91\xad\\\xc1\xb5#\xd1\x96\x80\xf0\xc0\xa8b@\x1a\x02\x11\xcc4\x05\x89\x82\xd8)\x00\x8b\xb8\xb5\x10\x94@\x94\x92\x80*\x14\xb0\t\xfe\x8eh\x9c\x88\x8eL\x8e\xd3\x97\x8dN_\xbe\xa7n\x93\xb6\xfeE`\xc9\x99\x89l\xf5\xc8\x7fPe\x9e\xe7\xaf\xefn\xdb\x8d\xc6\xf3\xb9E\xcc\xf0\xbd1\x873\xee\xe6r\xa5\xbf\x9ey\xcb\xf2\n\x07\x93D\x1fPDNO\xa1h\xe2\xfe\x84F\x7fg\xff\xab\xff\xff\xf4\xeb \x00\x93\xfa\x00%\t\xf8\x8e\x85\xa8wL\x01\x00B\xa0\xd8\\\x07\x1e!\xcc_Y\x8e\xa1\t\xcc\x1d\x02\xc0\x80"Z\xaa$\x1c@y\x84\xc1\xf0\xf1\xc1\x98\xac\x9a\xee\xd9\xe6\xeb\x981\xf9\x10q1\xf1g\x08\x00Yk\xa1\x0eC\xb0\xfb\xf77M+\xa4|dV/Fb\xc9\x81I\x1a\x9d\xe5>\xf3\xdc\xd2\xa2\x9d\x8e@\x94\xb2\xfc\xe5r\xba:\x94\xb3\xf9\xd3Ff#\x13nC\x10xd\xf0\x02\xec\x8c=\x92\xe9D\xe4Jr\xce\xabgw\x9a\xa7\x94Jcr8s\xf5Q\x06\xff\x96\x00\x80%e@\x00\x00\xe0\n\x01\x00\x00\x000\x14\x00\xa50\x02A\x880\x10\xc0\x870\x0c@\x130NA\xd10nA^0>F 2$\x80g0\x8d\xc1\xf90\xed\x82E1\x92\x81L38N\x1f0\x8b\x80;0$\xc0\x9a0\x0e\x80P0&\x00\r5\x0f\xd7\xf15\xa1K\xeb1K\x14\xe3\\R\xdf1\x0f;s2sp:\x8c+cY\xa4\x131p\t\xf2\xd3\x98\x08\x82\x91\x83\x88;\x18\x19\x80\x88`g\x992\x8aY\x86\x08l\x81\x02\x98*\x02`\x006&\x01r`8\x08\x00T\xec\x0b\x00I\x10\x04\x18\x17\x01\x88`\x98\x98!\x801\x83 \'\'8\xb0\x01\x92\x00\xc88\x0eD\x00\x08\x10\x04o\xa3\r.\xd9f\x80 \xa4`d\x00\xe6\x04`\x02`:\x02f\x01@D\xc7\x95d\xb7\x17e\xba \x91z>\xf9\xc4\xe4\xc6\x01\x00\n\x02\x05\x90\xc070\x10\x00\xa1P\x0e0\x00\x00\xb4\xe7\xb1\x14\xdcC\xe3m&\xb5\xbb\xd5\xa6"a\x00\x1e\x80r\xf6=e\xf9B2\xec<\xbb\xfaX\x8c\xc4\xe6\xb9+\xc7z\xafz\xceZdL\x85{\xadt\xbc\x82\xd5\xcb\xce\xb10\xca\xfd\xcc2\xfc\xaf\xf3\xf2\xb31\xbb\xdc\xd6V\xbb\xa6\xc4\xe0\xb3w\xed\xacG\xdcW\x9d\xc8}\xa2?\xdc\xb7\xcf\xef\xfe<\xe7\xff\xff\xeb\x9f\xfd\xcf\x7f\xfb\xd6\xf6\xfd\xbb\xef\xa5X\xac]\xfc\x89E_\xb9\\r\xcc\x82\x1f\xc7\x9f\xbf\xfe\xeb\xff\xba\xd7\xef\x7f\xff\xff\xff\xff\xff\xff\x9f\xf3}\xff\xfe\xf7\xf7\xff\x8f\xff\xff\xff\xff\xff\xfc\xc4\xba\x8a\x1f\xa1\xa6\x96RM\xf6~Qvv_H\x00\x130\x00\x00\x00\x01\x80\xa8\x04\x81Bu\\\x02B$\x1a\x04\xa6\x00`hc\x10\x1c\xa6k\xe6D`\xbc@\xc6\x9a\x02^b28fv\xa5\xf6bD\x18&\x07@\x8aa\xec\x0b&\x1b\xa3\x1ea\xc2\x03\x86\x15\xc1BaX$&\x97\x02\xfcb\xdcx\x06\xd2\x04\xba`\xa6j\xc6\xf4\xa8\xfa`j\x10\xa6\x0c\xc0\xf4`B\x04F\x1dA\xbc\x06\x01\xb2\xa0\x03\x18\xff\xfb\xd2d\xfb\x00\x0c_\x8aCN\x7f\xc0\x01\x0f)hv\xcfx\x00(E\xad\x0c9\xff\x00\x03(\x18\xa2K=\xe0\x00`\x82\xb9\x83`\x06\x18\x02\x80\t\x80\x10\x11\x01\x80\x11\x18K``\x1a\x02F\x03\x00\x02\x16\x01\xa0@\x05$\x1b3h\xe0\xa0\x18B\xe7\xba\x86@\xa4\x14d8\x01\x8a\x80\x14\xd3\xcb0\xdaPC\xf0\xf4\xa1:\x9e\xc8\xbcnP\xefF \x19W%\xcf\xb2\x83S\xd4\xd5Z\xd0%\\p\xa4\xa5\x89\xc4lU\xb9b\xed4\x8a7;\xf3\x1a\xb1s/\xbfR\xcd\xec\x7f\x99\xfe\xea\xda\xbb\xben\xd7\xd5\xadw\x1f\xfe\xef/\xff\xc3\xf3\xc7,;\xce\xf7\xb9\xe7\x86\xb9j\xe8\x01\xc4\x845\x07\x04I\xd8\xe1\x9d#\x93#l\xd4\x94i\xd1\x8a\xff\xa1jn?\xf2\xc3_\x1a\x92\xce\xc0\x00\x0c\t`.L\x14 D\x0c\x05\xc0\n\x0c\x050U\x82\x00$0\x02\xc0\xc20v\xc560\xfe \xe50\xb0\xc0.1\xab\x1e\xcd0\x07C\x990\xf8SG5\xdf\x14\x8b7\xe0\xd7(:S\x0c\x87<h\x8b8;\xf2\x16z99\x15\xd33\xfds\x036\x02$2\x13s\xf3\x18"\x032dH\xd3n\xf0w0\x93\x0f\x13\x02\x00\x1d0>\x02p #\x11\x00y \x0f\x986\x03\x98\xb0L\x98\x01\x00\x00\xc8\x03\x98 \x80\xb1\x80\x98A\x983\x02\x8a\x96\x18\x10\x80\t\x83\xd83\x18\'\x83\xd0\xa8\x0c\r\x000(^L\x08\x02<P\x0f\xd2 \x80\x04H\x00\x04X\x06L\n\xc0\x8cx\x04\xd6\x1d\xd8X\x86\x07\x00 \xa8\x99li\xaf\xa2\x14r7E\x065\xa8}\xab\xbe\xb36f\xe1\xac\xa71\xaf\x035WfB\xffCR\xba\x91Hg/\xcf\x19\xf9U/q\xafr\xdeR\xe8f\x19\xa2\xa6\xa0\xafrU\xcegj\xef9\xca\xbf\xde\xdd\xca\xd7\xe1\xa9t\xcd^V\xad\x9e\x1a\xcb\xb8\xd4\xd6\xbf\x9a\xfe\xf3}\xbd\xfa\xfd\xff\xff\xd5\xabf\xb6\xae\xe1\xfd\xbb\xbb4\xd6\xbb\xbd\x7f7\xff\xfa\xdf\x7f\x9f\xff\xaf\xfdo\xf7\xff\xbe\x7f\xf3\x1d\xeb\x1f\xc7]\xedP\xd0\x89\x1f\xa7\x08\x96\xb3\xfaN\x9b"\x1a\xcd\x90\x08\x00\x00\x01\x80P\x08\x08\xc1d*\x02b K\x04\x81\x18\xb0\x10\x98\xcb\x04!\x98\x89\xa9\x18[\x99A\xa3`\xba\x98R\x87\xe9\x80p\x9e\x98.\x03\xc9\x81\xa0\x18\x00\x86\x00t\x1f\x0c"\xc0T\xc2\xdc\x15L.\xce\x0c\xe3\xbc_\x8c)\x92\xd4\xcb8\xf4\x0cK\x82\x9c\xdf`c\xccXAE-\xd8\x99\x82\xa8\x1b\x98\x1b\x80b9\x98m\x00`\xc8\x10+\x02\xb4\xc1\xb0!r\\a\x10\x01.r`\x0c.\x04\x16[\xb7\x96b\xcc\xcb\xdb\x19A\x9aw\x8d\x9a\xa4\xcb\xb1MK\x1f\x7f\xb7O\xbd\xda\xa6\x86\xa7\xf3\xcb\x18\xd3\x97;1\xc9vs\xf8w\x1de\x8c\xce]\xdd\xaa\xbf"\xee8v\xd8\xa9\xe6\x84d\x16X\xe3\x9a\xd2\xb1\xf6;\x02\xa3:h\x9b?\xfe\xc7\xd9\xbb\xff\xd3\xfd\x06\xba\xff\xf7* \x00\x00\x00\xe5\x8d\xb5\xaa\xea\x16\x94@\x03E\xba\x02\x018@W\x98\x17\x00A\x83`\x1d\x18^\r\xa9\x8c(\x86\x18I\xada\xf3QY\x99Z\x07\t\x8b\xe9D\x1a\xf3\xe2\x80\n\xecL\x1e\xc0\x90\xc4C\x93\x08\xd1\x8c~\xf4=\xcc\xcc\xd1\xca\x13\x0f\x02\xcb\x80\xa4X\xba\xa1}\x1a,n\x00\xa7\xa6\x7f\xa1\xb4\xb5\x96\xb9B\xa1$\xbd\x8a\xc9D\x01\xe5\xcd\x07C\x8cO\xf9\x9eY\xff\xfb\xd2D7\x04EX2\xc6\xd7{\x80\x00\xae\x868\xb7\xef\xf4\x00\x15\x04\xc3\x12n\x7f\x88\x82\x91\x18"\t\xcf\xf1\x10Z\xdev\xf1\x94F\xe8\xe2W.\xc6o]\xb9Sz\xa9\x8c\xd4\xafU\xa9m\xcb\xaaG\xe71\xa1\xe7>\xcf\xd6\xb9v\xfexj\xdd\xcb\xba\rE\x0b@\xe0\x90\x88\x17\x8b\xb3{=\xdak\xef^\xad\xbf\xdb\xe9@\x00\x04\xe2\x00\'\xca\x01\x0c\x00p\x01\x01\xa0\x08\x00@\x020\t\x80\x010\x14\xc0\x15\n\x00\x98`\'\x00\x0c`x\x03\xb6`\t\x01\x8c`m\x8d\x94i>\x05\x8ea\xae\x02\x86`$\x87\xc4d!\xa0\xa0d!\x01\xee`H\x80\xf4\x00*\xcc\x96E\x8cv\x0bN"\x8f\x8d\x17H\x8cu\r\x0c/\x08\x0c\x06\x01\xe3\xa4@\x93\xc4\xd0\xd9++\x81!\xf7\xfaD"\x00\xdfg\x88\x1a\x10\x17\xb5\x92\xb4\xc3\x01\x02\xe4n\x8a\xc4\x13\xef\x970\xff\xbd\xbchd\x18D\xb5~MZ\xddZ\xf6\xb5[8\x95ND\xa9*\xde\xb31R\xac\xf5\xab}\xa7\xbb\xdc5v\xce\x1a\xe55\xecC\xfa_\n\x94q\xb0\x02\x88\x80\x12\xf0`\x12`\xa0Y\x08\x00\xc2 \x82\xcb\x9b\x14Z\x06z\x185<b\x0c\t\x83\xc4\x0ey\x81\xbaqQ\x906K\xf9\x82\xb6\r!\x83\x00\x1d\t\x8f&\xae\x99\x90\xe0\x19I\x80\x8e\x04\x91\x82\n&\x89\x87\x1a\xf6\x1cz\x01\x81\x8bL\x067\x0b\x98$"b`\x1aI\x90\x02U\xb9\x945\'\n\x1b\xceY#\x1d\x083\xaa1\xd1\x00q>8\xd3\xcc:\x1bL\xd8\xc4<V\x05\x95\xd8\xd6x\xd4\xe5\xc9U\xbc\xea\xd1\xea#M?IK\x01s8\xccN\xfe\x16i\xe8;jY\x977\x96\xf9\x96\xff\x99\xd6\xc7<>\xb9\x89\xe7\xa8\xfd\xe5\xabO\xebW\xff\xff\xffH\x0f &\xe1g\x89\x00.\xe9n\x8cj"8\x984\xd1B\xe3.\x96\x8d\xda\x8d0R\xc290G\x0f\xe40\xcf\n\xab0\x19\xc2\xe60K\x03\xef2\xef]\r1\x9f\x83;0_@D2I\x9c\xde\xeb\xc3]\xc0\x8f[P6px\xc8"\x81\xe2Q\x84\xc1I\x80J\x03LW]\xa8\xb8\xcbW\x8c\xe5\xcd*\x86\x19s\xc0!\x15\x13\x1b\xda|\x08c0yX\x12\x18i\xc4Ah\xb4\xef1\xed-\xc9\x8bR\xd9u\xb9|\xa6\xb54\xf6\x1d\x80\xa5\xdfZW~\xe6U\xaf\xe37-\xa6\xb7\xfd\xdeXe\x95\x9cr\xeeWrQ\xf61\x82R :U\xd7\xd7\x02\x90\x1e\xbaE\xbe00a\xc1\xb2\x10\xa3-\x9c3\xe8\x90W\xd9\xae\\\x98y\xc0\x96\x98\xaab\xa2\x1c4\xa0\xeb\x98s\xa0\xe8\x18\x0c\xe0\xe2\x99\xa1\xcc;\x99\x93!A\x98,\xc0o\x19\x94\x93\x1a+\x11\x98\xfe\x7f\x9b\x1a"\x19\x1c\x06\x98F\x11"\x08\xf0\x00$\'*\xb2\x12\xa32w\t\xedwi\x9b\xe0\xa8J\xd8\xe1\xb0\xb8\x0c,g\xb2\'L\xc3\xa0tx\x07\x86\xcb\x00+*\xa7\xad\xaf\xac\xec\xda\x82\xe9\xa5\xd2\x97\xf2=\x1d\xb1g\x0br\xbb\x97\xeb\xde\xe5\xec\xfb\xdc\xab\x18\x1c4\x1d7pz\x02S\x9f\xea\xa1\xce\xeb\xff\xff{\xec\xae\xce\xef_\xd2\xdd\xfe\xd0\x03\x8c\x92\xa7U]\x12\x01\xa0j(b\xa2\x07\x16\xf8i\x04f:\xa6d4\xc6\x07\xe0\x13\xa6\x16i\x02F\xadhVf\x0e\xb8,\x86\r\x98,\xe6qB\x07\xa6Z\xd84\xa6\x0c`\'\x86I\x16\xc66\xc0f2\xa2&2@\xff\xfb\xd2Dt\x04\xc5$\'C\x93\x7f\xea \xa3%\xb8\x93o\xfdD\x12\xbc\x9b\x16\xed\xffh\x82]\x14a\xc9\xbf\xf1\x10f=\x08(\xf0P\x13 \x88h\x1bLvd\xcc\x9e)\xa8\xdci\xf9\xa1\n\x80\xf1\x8aU\x0e& \xe0\xde\x98D\x15\xa4\x1c>\x8e\xef\x85{\x18\xf3\xb6\xfe\xdcf\x96+OAj\xb5\x0f\xde\xb51\x95^\xd2gcy]\xca\x9a\x9b-RZ\xcb_\x86\xfbPLP\x80<\xaa\xee\x95E\r\xb7\xee\xf4U\xff\x983\xfaz\xadS\x00\t\x1bm?\x8b\xb5\xba\x975\xc61\xc0\x83\xa2&\x1a\x926\xa0Q\x16\t\x82\x18\x08\x11\x82\xaaS\xd9\x97\xe2.\x91\x82B\x0b\xf9\x81\xd2\x14\xc1\x8b\xfc\x99q\x89\xaa\x12\x81\x800\x02y\x94\x83\x1dF\x99\xc0@\x8e \x9b\x10B!\x16\x9dJ\x98\x0b\xfc\xe2\xbfuii\xaaj\x94(\r[\x01\x90\x11\xe5g\xed\xea0\x13\x07\x12Q\x0e\xaa\x0b?\xfb\xd5\xfd_\x9f\xadK\xa9\xa8\xf5{\x15\xaecr\xfe:\xb7\x97\xdb\xce\xf2\x01\xbb\x1e\x8a\x86\x89&\xa4I\xbcQ\xa0.\xeam\xd0\x9e(\xfa\x19\xdd\xfb;\x1b\x9b\xb2\xb0)P\xac\x0c\x00\x0b\x82\x12\x80\xac\x08b\t\xd2:\x1c\x1a)\xc8\x10\x98!\xc9\x82\xf8\x08A\x85jS\x19\xae\x1a2\xd1\x83~\x11Y\x81~)\xd1\x8c\x990\x01\x8dN#Q\x81\x10\n\xb8F\xdc\xed\x8f\xf3\xa1;LG\x1c1\xb9!0@\x802\xfb/\xc8\x8a\xb8w\xdc\xc6q?bi\xfd0\x10*\xac\x90t\x0e\x1c\xaa\xb4\xa5\x023\x938\x8c,Q\xa0\xa5\xec\xaa\xeb-n\xb5\xa9Mj\xd3V\xe7\x7fu~%\xbf\xc3:\xb9k}\xc6\xa5\xff6Kl6\xd4&\x8d=\xdai\xee%\xd3\xfeco{\xff\xfa\xdf\xa1\x18\x00\x00\x01\xabM\xb6\xd5\x95\xb4\xa6Z:\x022pT\xda\x82\x934\x92\x8c\x9cD2\xf4$\xc1\x0cv\x0cu\xb74\xfd\xaa%\x0c0\x86\xcc\xc8(~\x0f\xb2\xf1\xb0\xf2\x80\x81\x0c\x80\xc4<\xc3\x0cCL/\x88\xc8\xc1PK\x8c\x02\x81t"*\xeb@sI{\x1a\xa4\rR\xfd\x9a[\xfd\xb4a\xc2\xceP\x0c\xab\x0c\x95i\xd12\xf3Vme\x0e\x1a#\x86\xff\xf2\xcf\xe5V\xa7\xe2\xd2\x99m\xb9m\x0cW,$\x92\xfao\x81\x7f+\xb7\xd2\x9fmW\xec\xb70~\x8b\x05U8\xcd\xf1Tmf\x96\xc6\r\x1d\x1f\xfd\xf7[C\x85\x8c\x02\x1e\x80<\r&T\x9a\xef8\x84\x04L\x06\x80\x84\x90\x08\x0c\t\x00\xac\xc1\xf89L5\x00<\xc6`\x94OJ\x86 \xc5\x105\xcc%\xc3p\xc7Q\xd3\x8c\x88\xc3\x08\xc0\xcc\x00\x07\x11\x1aH&\nh(\x00\xb5\xc1a\xc2E\xd5\x99cX\xa4u!\xa9\xea\x0c/O\xa8\x1dYJ\xa8\xbd\xcf\xec\x8c\x0c\x15\xef\x12\x86L\xbb\xe2O\xd4\xf1SEl\xe2\x87#~\xb26F\xa9"\xe4\xdeI\x1d\x88\xff\xbc\xa0\x00\x12\xb2\x000$\xc0A0\x18\x81\x040\x96\x82 0 \x01\xfb0\xddC\x970\xa8A"0\xab\x83@0\xbe\x81\x140\xa3\xc491c\x03\xda0TG\x812\xb3R\xb98[\x93\x8b2G\xc2\xa71d\x89\x0242)a5\xa9\t:1\x98\x82\x860\xde\x04\xac0\xf0\x83\xbc0w\xc2\x950\x98A\xc7:\x1b0\xf7\xde#\xb3#\x8dG5:\xab\x94\xcd\x07\xd3m\xb5\xcd"\x192A\xf8\xfeR2\x06\xcd\xfc3Z,\x10P\xff\xfb\xd2d\xc9\x84D\xda&ES\x9e\xd20v\x84\xc8\x86{Hx\']\x15\rO\xf3PB\x14\x8ca\x95\xbfm\x10Bt\xd2\x83\x11\x165\x8b\xce3a\x83\xa6\xd5(h\x93"\x18\xd2\x9b!$`\x00\x03\x86 \xd9\x85\x02\xb8\x8bp]\x86\\f\x95\x1a\x01\xc4\x02\xcc\xfa0s0\x01c@i\x03L\x81\xa3(\x10d9\x95&4h\x00X\xcc\nCS\x1a\x1c\xc7\x02QS\x16< x\xc0\x03\x14)\x16\x01"Lx\x16r_\xf5\xae\xc8\x12!\xeca\xeb\xaeys\xb2\xf8\xf2\xecu\x1d5\xdf"\x86!\xfb\x8f\xe4\xe4\xae7~Q,\xb5,\x96]\x8d\xdf\x94K9I9\xba~\xd4\xb1\xcc\xf0\xc6\xbez\xa4\xe5{|\xafl@\t\x87\xc1\xf1\x00\xd0\xf8&Pi\xf0@q\xc0|@0\xe0}N8]\x03Z\xba\xda\x9b"7\xba\xadm\xa1}\xdfQ\x03\xcb\x85\n\xb4\xcaA\x00\x86.\x1an\xe3\xa6HX\x1c\x96d\x11\xe6\x1c\x82*cq\x00\xc7\\\t\xb2a`\x19\x86\x03!\xd4h\x9a\x9c\x06l\x80\xe0`\xda\x0c\xa6Z\x0ef\x95\x86?\x10kH\t\x86\x18R\xc5^WsS\x9d\x91J\xebE\xa9\xae+\xcc\xa6G\x01]\xcb\x10\x10\x84\x8a)\x84\xed\x9d\x07\x87\xa46\x13\x05J\xcf\xd1\x950"\x1c\xab\x8f\xa7jw\x9c`\xc5\x10\xef\xa2\xbf\xb3]\xd4\xee{\xa2\x01r9mq#\xedf\xdf\xfe\xbd\r\xa9\xd0\x00\x00)7\xfa\xe34t\xc9\x07\x11\x882d\x88@\x99"b\xc4B\xac\x0eI\xe3G\xb0\x0e\xac\xcf=:,%\x0e<\xc6B\xa3"PS2\x88\xb3\x03\xc9\xc2"T\xc4P\xa8\xc1p( *0X\x17\x16\x05@\xa008\x06[)\r\x03\xaeV\x0b\x1ck\xd2(\x8cf\xfb\xea\xfc\xd8~\x1d\xea\x15\xf6\xfc\xc0nL\x86\x1a~\xa9\xe1\x99\xdb\x92\x94E\x05h(I@,$J\xc0!%\x00\x87\x1cIdB`\x92E\x92L\x14\x8c\x12H\xb0\x9d4\x8e\x1cK\x91E\xc8\xe1\xc9<\xe3NU<\xe5\x1c\x02<\x1a,\xf3\xc0\x12\xd3t\xdc\x8f\xbf\xfd\xd6~\xabC\x83%\x14\xcc\x80-0\xa9\x80\xcf\xa7c\x06\x9cMP\xcd7\x01\xac\xd0\xb2\xe3\xbb\xb7\x0e\x0b\xd82\xa7\x11#"\xa9\x1d\x19OC\x0eP\xa30R\x1fc\x17U41\xb8(\x13\x0f\x92\xa2=\xd0\xe0\xe30c5\x9f\x0c\xea"5c\x14\xcdA3)\x9a\x8c\xea:\x10\x0cLv,\x08\x15\x98HBb@Y\x00\x10\xc1\xe0\xe4..ihb\xe9\x92\x95\xa8p_\xc8=\x01\xa3"\x98\xbd)\xd3\x07:L\xbaV\xd6a\xd8\xf3\xfbE\x12\x7f\xaf\xc30\xed\x03\xfdzU\x0f[\x8c\xc6nF\xa7\xaeF\xaf\xd2\xcbp\xa6\xb5V\x9b\xb4\xb4\xba\xa6\xb5\xba\\\xaa\xd2\xf2\xb6Y\xd2\xe3\x8d\x90\x10T4*\x02<\x1a\x14\x18\xf2I{\x1bD\xad\xfeH\t\x00\x0c\r\x80<\xc00\x03\xd6\xc8\xb0E\x0f\x00\x99\x85P0\x98+\x03\xe1\x88\x00R\x18i\x05\x11\x87a\x1a\x98\x8d\x92\xf9\x8f3h\x9fq\xcd\xb1\x8b\xc0B\x99\x86 \x01\xb4\x00\xa2\x1a}\x9e\xa9\x95\xb8L\x9aa^vQy\xa2\x8c\xe6\'R\x83\x88\xc6G\x1c\x99\xac$a08\x14\xb6``\xb8XL*\'\x0e#\x06\x05L\x06\tN&\x04\xd6\x93\x15\x08\xdaBT\x11\x06_\xf2\xea\x14\x05_\xb8K9\x83b\x10\xecZvQR\xab\xff\xfb\xd2D\xf0\x84\xc5*:\xc9\xd3]2\xf0\xba\x86X\x81s\xdcD\x1a\x80\xc9\x06U\xee\x00\x03\x88\x18\xe0\x82\xbf\xc0\x01\xb1\x0b\xa4\x80\x9c\x86\x97\x83\xbf\x02D\xe18V\x98\xbf,\x94[\xbdR\xbe\x14\xd7\xa8\xe9-\xf7\x99\xf3\x9f\xbc?<\xb0\xd6\xf5\xde\xdd.\x05/P\xb9\x15V\xa1d\xa9k?\x1a\xc0\xa9\x83\x11\x87\xc2MB\x12\xdf\x19:\xd4/h\xbd\xf3\xc2\x8d[\x18i\xec\x8a\xbf:\x14\x0c\xee\x92\xbc\xc02\x00T\x90\x01\xd3\x00\xb0\x03\xe3\x01\x1c\x053\x00\xc0\x00\xc1\xa0pL\x04@\x19L\x06\xe0\x17\x83\x81\x150)\x01\xff0\xd9\xc0+0h\x0e\xb74K\x84b1@\x82\x100 \x03U0\xa2\xc4L1\x99\x82\x920\x1f\xc182{\x0c\xf3FSq\xb2\x0cR\x984\xf0P\xd0\xe4#D\x16\x8c\x8cR\x0c\x1d\x18\x14na\xe0\x80\x10`\x08\x0b\x82\x80@ M08\x10\xbeW#\x0eU!\xc0\x10\x91\x9cH\x15\x0e\xa1\xc5\xa7\xb5v\xc2\xdc&\x19\xc49%\x88\xd4\x88\xcb"\x95\xae\xd6\x9d\x92\xea\x82\xdd,\xfd>\xf3\x97\xe1\x8fhk\xd6\xdet\xf6/\xf7{\xef\x7f\x1f\xe6\xb5\xcf\xd6\xece\xde\xbe!\xc7\n\x8e\xee\xad\xda\xc5\x8d\xbc\x9f\xf7\x7f\x90\xf9\x16\xc4\x13v\x81\x1e\xf4\xd3]o\xbf\xcd\xa6\xed\xe5\x85\xda\xfc\xf5;\xdf\x1b\x81_\xce\xbf\xd6\x1e\xf4M?\xae\xf2\x92L\x95\x06\x04\x14`k\x04\xdeaB\x8c``\xdb\x13Na0\x02\x0e`\x13\x02:a\xf9\x83\xbebs\x8c\x9ee\xaa#\xd4s\x1f\x92Ja\x9154q\x90\x88\xbcd\x11\x0b``,\x81\x1ef\x9e\x03\\k\xf1\xad\x82a\x86\x0e\x16hT\x19jc8\x04\x9cae\x85Jq\xf1\x00\x16`\xdc\x8cTp\xd4\x0eR`\x8c\x01\x88`\x0e\x81\xd8<\x08\xb9\x81\x10\x04Q\x86\xce\x19\x19\x84>\r\x91\x81\x18\x07i\x81\x1c\x01\xb9\x80\x82\x02y\x10\x06\x81\x80,\x18\x11\x80&\x02@=0\x12@\x050)\x80\x890*\x80\x8b03\x00q0\x0c\xc0\xd4\x1c\x01`\x04\x07\x8a\x98\x98\x05\xa0B\x98\n`\x1c\x8f\x00D\n\x00!\x12\x8c\x00\xa0\x04\x0c\x03p\x06\x8c\x050\x13\x8c\x02\x90\rL\x02p\x15\x0c\x02\x10\x08\xcc\x01\x80\x07\x1eQ\xd0\x05\x96|\xb4h\x00\x83\x00x\x00b\x10\x00C\x80\x0b0\x01@\x03O3\x01\x10\x01S\x00p\x03s\x00\xa8\x00s\x00\x04\x02\xe00\x01&\x00\x88\x04\xd3Q\x0c#STl\x11\xb6@#h\x10\x00B\xdbR\xf3\x004\x01S\x00D\x01\xa0\xa8\x00&\x00`\x00\xa1`\x02\xcc\x01 \x00B\xa0\nJfokz\xac\x83\xee|8\xf3,$\x08\x95\x8f[Om@ \x03\x17|\x02\x00BC\x84\x00\n\x16\x00\x04\xbd"\xa0\x01j\xd5\\y\x96\xb2\xc9w\xc2\xe3\x13\xceD\xe3\x04\x80\xdf\xb6\xbfF\xcbKt\x90\xe5\xc2ei\xd2\x9e\xa9"\x91\xd3\x89}\xae\xe3\xbee\xde\xf7\xbd\x9c\xa6\x7f/:\x91\xf9\x1b\xbfM,\xa9,\xec\x9a6\xc0\xd3\x99\xb9\xaf\xd5mf\xabJ\x91S0\xb7)\xba\xbc\x8b\x96\x04\xc7\x1f\xd7\xfe\xb2\xee\xf7\x8f\xeb\xe7\xe1\xfa\tdb\xf5\xba\xf2\xff\xbf(\xc2)Oo\xff\xff\xff\xff\xff\xfd\xaf:M9\xb8\xdag.\x83\xb2\xf1?m*7\x02\xb80s\xb5\xfbP\n\x87J\xa1\x87\x00\x00\x00 \x82\x00\x00\x15\x01c\x03`\x81I\xe3\x04\x10,E\xff\xfb\xd2d\xf5\x80\x0e\xc2|C\x06\x7f\xe0\x00\xc1\xc4\x98x\xcfp\x00\x1b4\xc5\x10}\xff\x00\x01\xe1\x97\xa4+\xb9\x80\x00\xf0h%\x98\x19\x05i\x85\x89\xfc\x98\x12\x80I\x87SD\x98\x16\x85\xa9\x87\x02\xfa\x9c\x03\x90\xd1\xac\xa9\xbf\x1a\xdf\x82Q\xa4\xd8\x87\x19\xa0\x8a\xd9\x89\xf9\x0b\x1b|\x12ppQ\x9aDfT%\x18\xe5*g\xe1\x01\x9dM\x00P2[\x98<\x92a\xe0zw\x01\x83e\xa0A"\xb6\xa1Qn\xcc"\x06d\x8f\xaau\x0f\x00Z\xc48\x99\x8a\x14\xf0+\xdc-\xc9\x14~n]O\xeb\xaa\x1f\xbb\xcc1\xb3\xcd\xe3\xa9U\xca\xf8\xe1\x85\x82\xefX\xc6\xb8s\xc9\x16k\x07\x14\x8a\xcd\xf0\xc5b\xca4\x8d\xb3\xae\xa2\xc8a\xecQS\xa9\xa7\xa0^\xa7s\xa1\x8e\xc5\x8a\x91|\xf5\xff\xec\x17a\xc5\xff\xce\x1bro\x01V\xc8$\xc0\xc2\x06\xc8\xc0|\x0008\x04S\x00\xf8\x03\xf3\x00\xd8\x02c\x03$\x01\x03\x03t$\x83\x0b\xac*\xe3\n\xfd\x97\xa3#P\xc6#\x14l1#\x06\xfc\x1e\xf3\x0cH\x13\x83\x03\xf0\rS\x01\xe8\x0f\x93\n\x1c\x043\x0c\x98Y3\x12*3\x030\xa5\x8b5\xe0:0\xe3\x140\x87\x08#\n\xf0\xb6\x00\x809\x80 \x1d\x91\x01\xe0\xb0 \x18\x12\x01q\x808\t,2{\xa9R\xe8\x8c\xb1\xe3\x02@\x8e\n\x00\xeb9j\xcf\xc4\x89\xd4A\xd0@\'\x83\x00X\x98\x00Pu\x1f`Y[\xec\xed\x05\x80\x8d\x96\xb2\xe5D\xbb\x9b\xbb\xad\x04,#\xa2\xcc\x19c\xd94\xf6KjY\x88\xc4;f\xdd$c\xebN[\xed%\x8a|\xab\xe5\xfa\x95\xea\x93\x1a\xbb\xca\xab@f\x821h\x80@2\xfdl\xff\xccu\xfb[\xfb\\\xaff\xef\xfd/a@\x00\x04\x1b\xac\x00SC\xa8\x010H\x14@\x13\x06\x0bL\x00\x010\x104\xc5\x05\xc3a\x9cLBM2\x16\xdc\xd4\x8aC.\x85\x05\x07\xe6pT\x98pbeaI\xb7\x02\x0c)2A&r\x10!\xbb\xae\xd0\xe2R\xa7R\xcc7O-\x9d\xdd\x06\xfb\xae\xfd\xdeaI\x87\xd8\xef\xfe\xfb\xda\xd659\xdb\xb4\x93\x99~[\xc6\x7f\n\xff\xc8\xc4S\x9fSxc\x86\xed~\xbe\xe7?\xb8}q\xe1\xf8c\xcb\xea`\x04]\xfd\x80\x14\xd8\x0fC&\x05\x04\xbf\xc2L!\x81\xc9\xa6 j\xd4p ?\x06\x1b\x00\xca\x08\x0b\x13\x12\x80_\x05\x02\t\x81@\x00\x98\x00\x02\xe1\x80(\x10\x98\x99G\xc9\xcb\x0c\x98\xe1I\x86\x07\x90\x08\x93\x07\n\x81\xb7B\xd4&\xfb\'q\x9c\x17\x93Qj\xf2\x800\x121aOV\x93\x96S\xb4\x98\x11\x949\x8e\x84\x13+\x84J\xc0!\x11\xe8\xb2\xfdvm\xc0,\xe1\xafM\xc3\xef\xdb\xebfnO\x13\x8c\xba\x94\xef\xd5$J\x9ef\n\xba\xec\xc0\x11\xc9|NS/\xcab\xeco\x19FXrw\xb4V\xa9\xb3\x8b\x8dey\xd6v\x0e\xfew\xf4\xa5\x9f\xff\xf3\x90\x00\x00\x04\xbbV\x01\\a.\x03`*\x1ad\xaef\xf8k\xbag|b\x0e\xafGBD$a\xf0\x13\xe6\x0f\xa1@a\xf0\x06 \xe0(\x08\x02\xb3\x08\xa1!1\x0e\x08\xe30\nU5\xfa\x93},\x01\x17\x18@9q\x8c4\x10\xbe(\x0ebp\xda\xae\x83\x1a\xf7)w\x02\x00A\x08\x80\xacv\x96\xf55\xc5Q"\x00j\x8c\x97\xbd\x86"q\x10H\x05\x07Z\x8c\x05\xd9|58\xf2K#\xf1Z\xb2g\xde\xff\xfb\xd2D\x8f\x84E12H;\x1e\xd9\xb2\xa7GH\xfag\xdb6U4\xc3\x18m\xff\x86\xc2\x98\x98\xe3\r\xbf\xf0\xd9zX\xffMIn\xde\x85;1\x98\xf3\xf3\x1c\xbd\x8d\xae_\xa4\xa7\x95\xd3T\xa4\xaf\x8fnV\x97j\xb5/\xe5\xaf\xc6\xf6}\xc7\xbb\xce\xae\x16\xc9\xdf\xf3\xb2\x80+#@\x18\xdf\x89\x8e\x05\x87\x0f\x03\x0c\x80Cf\x16\x1af\xee\'=|`\xfe\x80\xceh\xa0\x00\x0c`\x98\x00*`\x05\x80F`*\x00\xa6`\x03\x80\n`\x11\x00\x86`\'\x80\xd0`j\x00\xce`}\x9eht\xd0\xb1\x87\x82f\x01!\x81\x05\xe2\x800p\x81\xf7A!p\x0c\x16\x08x*\xc5\x1f\xcaX\x1a\x1b\x11\x8fWd3G\x95[\x95\x17iA\x15\x99F\xe2\x94Wo\xd9\x03\x01i+\xc8\xac8\xd1\xc6\x996\xf3Ct\xd0\x8aX>\x9a{\xb1\xcb\x95-Z\x96N\xee5W\xb8\xdd\xd5\xdb\xbc\xa2\xce\xd5\xac\xac\xd2\xef\xb5\xca0\x0crta\x17\xb0\xb9\x04\xbe\xd6\xe7\xab\x02[X\x00\xc7|@G%\xf20\xa0\x03\x1130c\xe3S\x819\xe9\xa3\tt73C\x00!\xf3\x03\xc0\x02\xf3\x00\xdc\nc\x01\xdc\x07\x13\x000\x02\xc3\x00\xc4\x00\xe3\x00\x14\x04\x83\x01\xfc\x153 \x14\xe7c\xa6\xe4\x8c\x0cW0\xb8P\xc1\x01\x85X\xbd\x82\x02\x08\xda\x8c\x85\xea\x92P;\xcf\xb4\xbaX\xdcA\xa4w\x8a3n\xddjys\xc2P8r\x99L\x85\x8d\xd1D`\x93\x08\x01h!-\xf4\x11\x16\x81\xa0W\x8e\x82\x07\x7f3\x96D/\xce\xde\x97KkU\xe4\xb3\x1eNPj\x9a\xd5=L\xebP]\xb9n\xb4\xfeUs\xca\xef\x96?\xbe\xda\x17m\xcc*LAME3.100\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa0\x00\x00\x19\xeb%38M&\x9b01R`P\x10y\x93\x0c\x1a\ny\xb4m\x18\xc1\xc4\x89\xd0\xb12\x98\x1a\x02\xd1\x80\xa0"\x98_\x832\x0f\x92\x80\xc9\x83\xb0G\x98\n\x86A\xaa\x16c\x98\x80\x06\xc9\x82h\x10\x03@A^\xab\x95"\xc7\x9c\x95z-\x0b\xf9\x12\xce\n\xec\xa1\xcb\x03J4\xecj\xcd\xe8\x8d58\xa0\xc3t\xa4\xb3_\xb9\xddJdg\x18\x19J\xd2\xe1\xc1\x80\xe21g\x15\xfb\\\xd0\xd4^\x1e\x94\xcc\xf2\xbbY\xb3z\xd5\xd9\xa9T\xcc\x92\xd5-\xa0\xe8$AGDP\xe2\x1d\x9ep\xac\x95\xbe\xab\x9a\x9d\x8f\xe8\xa5\xab1U\xc2\x8b_\xcf\xc8\xebV\xe3\x90\x00\x02\x9f\xea\x00\xd3\x9c#h9\xe4/1@2\xc3\x01\xb8`y\xdcw`0b`\x0eX\x03\x82\x04\x90\x80(p%0x@\x01\x05g\xa6\xac&:\rD\xc0i \x14\x91\xa2@*6D^E`$\xaa\xb3\x1d\xdbp\xa9\xe6\x90\xd4\xdaR\xbe\x8b\xb147\x9b\x16\x9b\xf8R\x8fH\xcd\xcc\x97\x1c0\xd1\xba\x1a\xeaU\xacCu\xc9\xd8\xd8a\xebk<\x88"($8\x13\xf5T\x07\x00\x06\x8bn\xc6g\x8c\xc6\x08\x06\xa0\xe1t\xc1p4\xc8\xc1\x18\xc4\xf4l\xd0\xea`\xc23\xb4d\xcf\t?<\xc3#\x0cH\xc0\xc4\x06\x9c\xc0\xe7\x02P\xc1\x18\xff\xfb\xd2d\xa5\x04E<)G\xd3~\xc9\xc8reY\x1ag\xac:\x1a\x10\xa7\x08N\xff\x87\x02\x00\x13\xe2\xe9\x9f$\xf8\x00\xfc\xc0\x7f\x01\x98\xc0-\x02\x88\xc0?\x05\xac\xdc}\xd2\x80\xc3m\x11\xd0\xc0^\x02\x14\xc0V\x014\xc0\x17\x00P\xc6a\xd0`\x88\xb4%\xd70\x88,\xcf\xe3\xd1\xe0"\x9a\xb9\xef\xd5+\x96J\x100%\x08\xc3\xa14\x16\x90\xb4fF\xff:\xe1c\xa1\x99\x80\xac\xb9(\xe2\x13\xd6;)\x0e,\xc5-28~Q\x12tg.\xab\x9b\x90\xb9\x9e]\x98\xab\x07_\xb7\x8f\xc6\xea\xe3AM-\xfb\xc4\x82\xe0\x03\xc6\x9a\x15\x92<\x03c^D\x83\x9e\xb5 \x9ed\xc3\xddK7\xd7\xd6\xea:\xcb0\xf5HZ\x8a\xddB\xb4\xedB\xf6\x94k\x1f\xbe\xf2\xb2c\x80\x00\xb1\xa4\xd3u\x04\n\t!\n\x02)\x12\xa0\xc3\x1c\xf4 \xc2\x1c[\xcd\xa6\x82L\xc1\xf0\x08L\x03@\xc0\xc1x\x05\x06\x80(X\x11\x0c\x11\xc1\\ 1\r\xcf\x91\x18\xc1\xb0IH\x81\x18\xc0<\x05R\x8cH\x05Kl\xb8\x9127\x11\x8a\xcb\xa47o\xd4\xeb#\x91\xa9\x195\x87\xd4ao\xea\xb7\x99\xb9\xbcU\x14\x8f`\x8d\x9c\xabE7\x7f:\xb8\xa7\xe4\xe3\x81\xa4!\xe1\x83\x01T\xb1=\t\xa7\xfb}\xd8\xb78\xa4o\xff\xfdu\x1f\xe8\x03C\xc6\rl\x1f0x\xc0\xc7\x81p\x12<\xca\xc4 (\xdc\xdb\xa03\ri"\xd3t\x14M\x93\x0b\x84\x13C\x04\xc8\x0b\x93\x01\xb4\x07\x03\x01\x08\x06S\x00\\\nA\x80\x1a\xcc\rP\\\r\x17\xe6\xa7L(\xa0\xa5\xcc\x14\xd0\x1cL\r`,\x0c\x08p-L\xda\xa8\xc9"Mu\x18\x1d\xa2k\xe2\xa6j*a\x88F<"f\xa0\xa64H:Ba\xa1\x05cF\xae\x12\x11\x0e`\x01\x85\xf1\x08\x0b/\xa2\xb6\xa6xYh\xb0\x02\xac!\xc4e\xccITF\x08\x00\x06\x80\x83\x9d\x91`\x1c\x10_\xf5RR\xd5F\xb0\x8f\x8b\x95D\xca \x97\xcd\x9c78i\xd4y\xe3\x91g\xe1\xff\x80!\x98=\xc8\x80\xe2\xd0\xfcBfzY+\xa0\xa5\x9f\x8d\xca,\xcf\xd2]\xb5c<s\xb1_+\x14\xf7,\xceS\xd4\xab~\xc5z\xd7\xacW\xe8\xd6>\x04&4\x88E\x81bad\xaf`[p\xab\xff\xff\xdb9\xbf\xffg\xab[\x00C\xe6\x94C(\t0\x10s\x04\x030\xf0\xb0`\xb1\tI\x99i\x18q\xa8y\xb0\x10\xd6\x82\x81\x80X"\x8cI\xc2\x15\x12\xc1 \x06`\x1a\x08f\x04\xc0hq\xca\x9b&\x07\xe2\xd8\x10\x13Ap!v\x80\x00\x02\x8a\r\xe3Wu\x10\xa2\x1e\x95K\xeaV\xb1]*b\x97g\x98\xe6\x9a\x8d>v\xc6\x0f\xf4JZ\x82\t:\x8f)h\x8b\x126*p\x15\x06\x1a\x10\xb8m\xab\xd6\xcf\xe8\x9eb\xad\xfe\xd5#TY\x94\xdbw@\x06K\xff\xd4A\x808\x0c\x98Y\x03\xf9\x82\xb8Q\x18\x00\x06y\x83\xf0f\x18\x8b\x82\xd9\x8c\xc0^\x98\xf1\x911\x92\x03\xd9\x9b\xed\xb31\x998\x96\x99\x08\x04Y\x8b(x\x18\x88\tI\x86\x98\xc8\x183\x14Y\x86r\x8d\x1cS\xd0a\xad\xc0\xad\x99\x8b\x90Q\x8aP\xf4\x98\x1a\x0bq\xc1T\xa7(!\x9b\x8d\x94e\x06\xf9\xb0\xb5\xc7b(\x1e\x05|pI\xa9\x88d\x06Y,\x84AL\xdaN11\x94\xc5\x80\x83\x08\x03\x8d\x88c,t\xaaH8\x98\x08\x88\xa8@\x82I\x14`\x01\x95F\x0b\xff\xfb\xd0d\xff\x88G\x8d<D\x93\x9f\xd9\xc0~\x048\x96o\xc6>(\xa9+\x1dOsP\x8a>\x94!I\xbf \xf8\x1b2\x81L)\x81\t1d\x82F\x8c@\xb0\xb0\xd3d\xa0\xe7\x807\r@-\x0c\xb8\xf3P\x0c\xc8\x9c\n\x99"Tf\x8b\x85R\x19\x11\xa0\xea&\x8d\x10!Y\x8e$-<\xd2\x940\xc8\xc1\x05\x05\x99\x99`\xe0\x12\x01pe\x04L(\x01\x08$\x07\x84\x11\x02\x88\x1d\x0e, \x0cX\x00,pPp\x00\x82\xc6\x009(B\xf9\x89\x05.\x12\x7f\xba\x8c\xb5\xa5;nk\x12g\xaeCB]\xac\x85\xc0j\xecE\xb9>\xef\x93\xbc\xe8\xc6\xe0Zk\xb6%\xd2\x9a\x96\xe5\xd4\xb3\x16\xec\xd3]\xb1j\xb6w\xa9\xaa\xe1~\x96\xb6\x17\xf1\xad\x9a(\x88\xa6\t\x94\x16\x184\xc9n\xdc\xacNKM\xfb\xfd\x8dsM\xef\x9f\xff\xdf*\x01\x00\x81q\x15cQ\xe7 \xc1\xc5\xcc\x90\x88\xc0\x91\xcc\xa3\x10\xc2\x16\xa4\xcc\xf1N|\xc4\xac\x1e\x0c\x17\x844\xc8\x94*\x80@\x1e\r\x07s\x08\xc0[0?\r\xd3\xe6\x08\x080\x19 \x91\xa0A\x04\x83!sL\x02@Y\x06\x03\x00i\x13\x9aK\x8a\xef@\xd9\xca\xe5\x1d\x9a^\x10\x87E$\xa0\xfcC\rB\xc4\xde\xe1\xe5&\xdb\xdd\xfc_\xe8>\xe6\x0b\xba:,pa\xae\xb5\x11E\x12\xc5R\xca\x89:S\xad\x03\x7f?\xd1U*%\xd3\xa0\xf2s2NR?\xdbz6\xd8()~\x95\x01\x90\x03\x04`{02\x00\xe2\xff\x88\x00L\xc04\rL%At@\x04&\x17aVbX\xd6\xe7\x8f\xe1(a\xb2\x08\x06\n\xe2\xb2a*\x0eF\x07\xc0*`\xaa\x0e&\x1aa\x16a&\'\x07|\xe2\x96t\x9b\xe1\xbb\xaf\x87\x0e"\x1a\xb9$c\xc2\x01\x85\xca\xe6\x05\'\x19\x00xc\xc1q\x85\xc1\x06\x11\x02\xbeh\xd0\xc9\xc0 \x94\xae0p!4\xc3\x03\x17\x9b\xbbS}$\x97\xd6\x15(%q\n\xb9\xbb\x17f\x1d\xab1\xd7.-7j\x92\xeet\xf65KO\x94\x82WO\x1b\xbbZ1b\xa4\xb2\xbc\xa3x}\x8c1\xcb>\xee\xc7p\xdd\xb2o\x17<\xb7\xac\xa1\xc4"\xa6\xa9E\xf5_S\xfejU\xfc\xf8\xcd\xcf{=\xea\x04kU]\xdf\xd5\x8d\xa4@@\x00\x00\x0e\xd6\x92F\x00\x06&\x02\x00\xc9\xb0\x94\x05\xb30\x84\x1b,\x05\x869\x13\x06eiG9\x06\x06\t\x04&\x0c\x84\x86 \x8c\xa4\xc2\x184\x040\xf0\r3\x05\x997\x83\xd29\xa53kO2S\xb37!0\x11\x11#2\xe4\x96\\ \xac\xb9n\xf2D"\x84\x1a\xd0\xdae\xd8\xab\xe4\xd7\xdf\xfbs\x14\x98\xb6?\xa0w"\x10\x8a\x95\xe7\x19\xbc\x89\xff\xa0\x83$2\xba\x93\xb1\xbaxrr\x8a\x9e\xdco>eOZ\'O\xda\xfa\xaf\xfc\xc2\xdf\x10\x11\x93\x06\n\x13\xa2\xb6\xfe\x99\x1f\xf4\xae\x8f\xff\xe9\xa2\xce\x8e\x80\x00\x13\x00\x000/\x03\x03\x010\xa70h\x02\xa3\x03\x10&0\xa1\x0eC\x1d\x82\x940z\x0f\xf3e\x91\xf61z.\x03A\x90\x142\xbeEc\x07\xa2>\x0c"\xd3+\xc2]0\xe6\x0e\x03\x12\x08f3=;\xd3F\x93\\\x03\xc6\nd\x0c\x14\x06\x80368@\xc6x\x11\x03\xfb\xe3\x8c\r\xeb>\x000\xf0\x1a\x00P"\x01\x880b\x06\x1e\x83\xe0\x18C\x08\x00`\xe4\x1a\x81\x98\x01\xca\x06\xb9\x8e`\x18\x8a\x0b $\x13\x01\xff\xfb\xd2D\xec\x80\x06\x17/\xc2\x95{\x80\x00\x98\xa5X\xba\xae\xec\x00)\xde\'\x0e\xb9\xeb\x00\x15H\xc5"+=`\x00\x82\xf0\x1a,\x900\x00\x05\xc2 P\x1b\xc2@\xc5\x10\x0cP\x83\xd01<\x1b\x00\xc1\x80\x12\x10@\x1b\xc2\x16xfD\nY\x06\x80\x14o\x86Y*\x87\xec\x00\x80(\x0c\x16\x03\x00\x0e\x0b\x01\xec\x07 K\x8fLA\x89\x12 G\x13\xe6E\xd2\xe9\x80\x83\x00\xc0\xb8\x0f\x00 &!\xe0`\x1c\x00\x83g\xcdL\x16yi\xa8\xa0x\xfb\x9a\xcb\xc2\x0f\x0b\x80\x1c"\xc6\x01@\x00G\x86\x8e\xe6\xcc\xbavR\xdd\x9e\x962\x81\x97\x04\xe08\xc9\x82\x08\x1f8\xa0\xc9?S\xfd4\xfa\xf7\xb0\x82\xe2\xcb"d\x10\xd4\x9f\x12\x81\x10D\x8a\x0c\xa6\xef}4\xd7\xdbd\x17k{H\x82d\xc18A\xc9\xf3\xe36A\xcf\xb1|\xaeD\x11\xabn\xd6R\x99\x7f\xff_\xd3g\xe8\xb7\xff\xe6\xe4P\x9c4"\x85\xc3\xcep\xd0\x9fS\x13\xe6\xe8\x00\x00\x00A\x18\x00\x00\x00\x00\x02A\x80\x10H\x18\x10\x00\xb1\x82\x90\r\x12\x041\x85\x08M\x18\xa7\x13\xd0Uq\x0c\xc4\x88\xc8\xc45e\rL\x00L\xc9\xa1]\r\xe6\t \xc3l&L/\xd2|\xc2\xe4FL)W\xf4\xcc\x9c\xf1\xcc\nF\\\r\x05\x9e\xa01L\'\x00\xd3`\xc8\x03\x1aA\x08\x0e\x96\x9dP6D\xd4\x00\xc1XZ\x01A\x08\x06\x18\x80\xf8\x18\xb1\x05``\x8c\x03\x8c\xc8\x18\xe6\n\xa0j\x10\xd4\x01\x88 z\x03\x01\xe8\x16\x03``\x18\x01\x03`\x00`\x00\x19\x81\x80\x80\x122b\x90\x03\x12\xa1,\x0cG\x05\xe00`\x02\x03\xa1\x13x7\xf2\x04\r\xd0\x16\x819\x01\x80 \x04\x0b\x00\xe17\x8b\x80\x0c\x02\x00\xe004\x0b\x00\x18$\n`z\x85\xd3$\x88iH\x9dQ\x91\x03$\x8a\x06\xe1\xd2\x01\x80\xf0\x16\x01@,F\xe0\x04\x00\xc1\xbb\xd3=[\xd2/\x1a\x17\xd1]\x85\x8c6\xc2\x029\xe0\xdbA:\x17\x13c\xe8\x18\xd7Z\x08N\xa2\xda\x86P@AJ\x0e2\x818%1e\x95\xde\xddJ\xd6\xbe\xaf\\Yc6O\x90DM\xc5\x90N1\x14 \nZ\x9a\xba\xdf\xd9\xd0\xea\xd7]\xd6\xcb\'\r\xcb\x86\x84\x1c\x9fq\xcf"\xe7\xd0)\x9b\x93\x88\xf6\xd3\xea\x7f\xff\xffekV\xff\xff\xd3"\x85\xc3\xc4\xc1p\xd14\r\r\xec_7u0\xd0DV0\xb6A10\x80\x00\xc00\x1a\x02\xd90\xb2\x80a0B\x01\x960\xd7\xccy5\xddh\xf50W\x87\xe86\xe7\x8362U\x01Y3E\xf0\xc62\x93\xc8p2A\xc7\xd24`\xc0\x8e0+\x83\x9d1\xff\x04*0\x05D\x151\x85\xd9.3\x99Z\x1322\xc4\x06>\x1d\xc110\x80\x1c\xaf6\x08\xd3\x1a1~\x84F0\xdb\x84\xdd0\xe3\x0231\x92\xc1U0\x13@6\x07\x01,a_\x87&`\t\x00\x12`\x07\x80P`S\x01\xc8`[\x01\xca`<\x00~`O\x00\x86`\x1a\x80D`\x00\x80,\xb4\x0c\x06\x10\x12L\x03\xb0\x04\x96+7\x1a\x030\xc0y\x02\x08\xc0q\x00X\xc0\x1a\x02\xdc\xc0\x13\x00\x98\xc0\x19\x00\x18\xc0\x06\x00Y\x92\x8a\x00\xb2\x06\x01\x8d\xb6\n\x006\xdd\x06\x00G\x0c\x02\xfe\x14`\x03\x80@`\x04\x00\x00`\x00\x80H`\x1a\x80d\x97\xad\x92.\x02\x00>\x13\xcb\x97e\x02@\x04\xd1\xd7\xca\x80\xb9\xc1`\x02\xcc\xff\xfb\xd2d~\x00\x0c\xb0nC\x06\x7f\xe0\x00\x87\x04\xc8\xe9\xceh\x00\x1bd\xd7\x19]\xff\x00\x01\xd3\x16d\xeb\xb7\xa0\x01\x01`\x06\xc9\x80\x15\x06\x00\x0e\x02\x00\x14\x08\x00\x1e\xb0\xa1\x9f\xc3\xb8g\x95\xdbxs\xa2\x10\x00\x02\x00\x02\x14\x00,\x12\x00!|\x98\x94e`\x80 \x02g\x86;\xe6\xb5\xdc\xff\x95;\xcf\xd7\xfbY\x942\xa6B]\xd6*\xc0U*\xc2\xb4\xa6\x9d\xaf\xfc\xbf_\xbe\xf7\x9f\xddo\x7f\xdd\x7f0P\xd52e\xd4\xdaiJ\x05\x8c4\xe5:,E\xf4i-w\xf3\xef?\xba\xfes_\xado\xff\x9f\xcd\xf3\x7f\x97\xffw\xa8v\xb4\x95r\xca\xa8_\xd8\x93\x95\x13t\x9d\xeam>\xce\xf7\xe2\xc1s\x81\x00\x98]\xe9\xfc?>=\xf1\x8b\x00\x00\x00\x00 \x01\x02_\xbe\x82\x8c.\x1aX\xe8>\xcbD\x01\xf3$\r\xcfV^\x0e\x0b\x1b-0`\xe3h\x80\xdac\xe1)\x8cE#F\x135<\x8cH\x1b1\x13(\xfc\x14:\xceNt3@\x8c\xe7\xb5\x04&%T\xb1\x0b\xac48\xac")\x99\xa1!\xc3\x01\xc2\x9b\x8b\xcd\xca\x14\x83w2\xf8\xcb\x92\xefX\xb1vQ\xae\xe5IE\xddP\xea\xfd\x9c?\xf7\xbd\xff?y\xef\xf1\xfc.\x9f\x7f\xddN\xdb\x9bO\xb1\xd5\xf7\xa8\xda~\x8c\x0e\xde\xae\xbf\xb7\xea \x00\x00\x00\xadi\xb3\x02\x0c\x08\xb3\x00\xb8\x02\xb3\x00\xc0\x00\x91\x18\x03 \xd0\x11\x8c\x06P\x1f\x0c\x070<\x8c\x16\x104\x0c\x17\x10,\x8c\x110k\x8c-\x12\x88\x8dJ\xe0\xdb\xcc?\x00\xadL\x1a\xa01\xcc\x06 "\xcc\x02\x10\x12\xcc\x07\xa0\x19\xcc\x0b \x18\xcc,\x02,\xc6P\x91L\x93\x8c\xc4\xf8#\xce\xcd\xa1D\x80\xc3\x08.\xcc\r\x82\x84\xc1\xf8\x06L\x12@\x18\x04\x07\xa2\xc0&L\x01j:\xcd\x88@\x15w##\xae\xf7\xbb\x95\xa1\x89\xf9\xa6D\x05\x03"`\x08\x92AT\x15\xab]\x99\x96\x95\x00\x00\xc04\x01\x91\xca\x1e\xbfWyW\xaf* \x00\xa8M\xa8\xd5{\x14pe\xcb\xd7\xa3p\x1d-[u2\xb1~\x1b\xbb-\x9e\xce\x92-z9\x87\xfd\xff\xcf\x0ek\\\xee\xaf\x05\xda.p\xc1F\x0b%\x1fy\x9fJ\x9b\xbb\xb5\xff{\xbdt\x9b\x00\x00\x01;P\x04\x16\xeb\xa2\xb10t:\xdc\x05F\x96\x99\x83\x97\x84\x87\x19\xa5\xa1\xc73\x01\x92SxB"``\x81R00(\xa2\xa3P0\xca1\x13\xe4<@\x050i\x82?\xa0le\x92\xa4Z\xe3l\r\xa5y\x1c\xbev\xa6\xf3\xc7X\xdb\xd6]\xed\xeea\xf7,\xef\xf3\xff\xff\xff\xe7\xff3\xa1\x98\x81+\xe3?(\xd6\xae\xfe\xb2\xa9\xdcs\xe7u|\xb0h\x0e#\xfa}\x9d~\xbf\xf6\x00\x18\xd0\x00\xd0\x01\xe8\xc2`<\x08\x19\x18\x16\x01\x85\x82\xa3\x02D\xa3\x13\xcf\xc3\xadL\xb36\x8c\x83\xc3GC\x03\xc9R\x83_x-\xf3\x00\x1c\x08\x83\x00\xfc\x03\xd3\x01\x10\x03#\x01\x9c\x07\x93\x00|\x0b\x03\x01t\x02s\x02\xc8\x01C\x00,\t\x13\x03x9C#vC\xc3\x01\x18#\x83\x02L\x083\x00P\x08C\x00\xa4\x01\x13GX,\xc0\xdd\x8a/\x8d\x00\ty\x80\x16,\xc1)Y\xec<\xe8\xb5\x9b\xf2\xa9\xa9)\x9b\x8aD\xb5\xba5H\x9dv\xf6fzX*\x18\x1d\xf1\xb5\xce\xbe\x1c\xbf{\x18\xca\xc3%\x85VM\x0e\xbf\x11\xd9\x97\x9ejI\x0f:\xfb\xc6u\xd1\xa6\xb7\xcb\xb2J;q\xe8\xff\xfb\xd2dW\x8cF,7\xc4\x9b\xbf\xd2@xe\xc9=g\x8cJ\x1a\x84\xc5\x0cN\x7fe\x81\xe0\x17$5\xae\xb1)\xcd\xea{7\xbb\xcd\xf7\x1dc\xadv\xad\x9d]\xa6\xad\xd4U2\xa4[\xfe\xa1"\x00\x00\x00\x0e\xff\x00\x11\xd7E)\x02\x88\x8e\x14<\xa8r\xa4\xe5\x18;\x9a\xe9\x19%D`\xd0\xe9\x80B\x84\x80p\xc0\xf0\xd0H\xc3B\x13\x06\x99\x84@\x80\xb8H\xc6\xa3sH\xf2\xcd"\x13\x06\x04\x8b\xda<)U\xe9\xe2\xc5^\xb9X\xc4Im\xe4uw\xbf{\xd8i\xd5\xeb\xccIFR\xcbf\xfe\xcd.\xcd.\xc4_\x8c\x95K\x89=\x11\xd1\xf7umm\xefib\xfa\x1c\xa1\x1f\xb2\xbe\xa6\x86\x9d\xcc\xd2\x01\xc0\x07\xa3O\x8b\tA "\x84\x80 8b0q\x81\xb6\x08a\x89J\x01\xa9\x80\xd8\x0f\xe1\x80\x1c\x0fI\x80\xa1"A\xa9(3y\x81<\x0fa\x80\x88\x03\x99\x80\xfa\x05\xf1\x814\x04\x99\x80\xfe\x01\xe9\x82\xde\x0b\xd9\x80\xdc\x08)\x82\x1e\x0b\x81\x84\xd83i\xaak\x90\xe9\x8a \x1c9\x82n\tq\x80L\t\x89\x80@\x02\xb1\xb1\xa3\xa1)+\xccDD\xc9\x03\x83\n\xc1\x00\x83Z\xaa\xa9\x16Z\xeb\xc2%(\x80\xe7\x17y\x97C\x81\x92\xd4\x1e\x19r*DY\xab\xf6\xee\x08F\xccP\xa6Q\xda\xd5p\xcb\xff\x11\x91\x15\xfb\x93\xf1K\x10i\xb6\xe5\x11\xeaHf\x18\xb9bv\xc5\x164\x1f\x8e\x1f\x9dj\xd5\xf1\xadS\x1e_\x1c\x0e\x8a\x15\x14e\xdb\x80)`\xb6\xae\x8a\xaa\xf7:\x17]J\xce\xff\xeb\xf4:\xf6;\xd9\xf7n\x0e\x00\x00G\xe8\x00\xb6\xfb,Q\t0\x08\x01\x82e\xd7\x01\x17\x18\xb6nU\x02\x03\xd3pB00F\xd0\x86\x840\x00B`(\x06\n,k\x8b\x01\xe6\x06\t&\xccf\x83\xc7\xb08u\n\x00\xb3\xa1\x00\x12\x00\xda\xf2\xc3\xd3\x13\xd6\x93\x87\x82\xaf\xbbO\xbdd\x16PuoX\xbe\xf6\xef\xb6~\xcc\xfc\xce\xb3k\x90\xca\x05\xe2\x9b\x07\n_~=\x8ai\x94\x85+\x8b\xd9v\xd8\xfe\xa1G\xf3\xce\xc1\xbfW\xbc@\x00\x1c\x12wa\xb2\x89\x18L\x1a\x16"\x06\x05\xc3\x8e\xa0\xe0@\x8cD0\x08\x0c\x0f@\n\x8c\x03pJ\xcc\x13\xf8,\x8cp\x91]L\x10\x90P\x8c\x02\x90\x11L\x05\x103\xca\xa09\x18\x01\xa0\x12\x18\x1e\xc0\xb3\x18\x1c`R\x18\x19\x80\x88\x98Ka\xa6\x1c\x1b\r\xdc\x19\x17\xe1\x05\x18(@=\x91\x03\x0c`#\x00\x18\n\x9c\x9dft2\x01\x99\x08\xd0\x12\xa1\x00\x80(l\xa4\xe5lV/)\xbfU\x95\x19\xeeA\xcc\xa0\xb7fUIB\xffK\xa1\xb1\x00\x11\xf9lZC\x975\xdd\xf2\xe8\xe0\xd6\x0f\x8dj\x91\xeb\x12K\x16l\xdc\x87\xf1\xd5\x8a\x99\xe3\x9e\xadv\x9f|\xa5\xe5rO\xc5\\\x93\xdd\xe8\xd1B\x15\xda\xc4Rp\x95\xc9n\xe9Qw\xdd~M\x1e\xab\xf4\xfb;\xbd\x9dbP\x00\x00\x00\x93\xfa\x00\x17\x83\xe4\x018\\\xa4\xd5\x1d\x000=\x95\x8c7<h\x0c%\x0bF\xbc\xa3\x07B"\xa0"\x91\x82\x80\x19h\xccQ\x0eA\x80\xf0\x18J\x06\x02\x87\x1e\xa1 \xe3\xc4\n\x01\x8f\x02 P\r\x8e.E\xd5\x0fAq\xb8vO\xab\x9f.\xfc7\x8du\x0f\xde\x9dhVg\x05\xc6\xce\xdb\xfc\xd4k\x8c=\x128\x91\xa3\xb7q\xf0\xf7\x9dZtj%\xd0\x1dY\xd4\xd6\x9a@d@\x14\x1c\xf0\xd0\x05)F\x93\xff\xfb\xd2d\xa2\x84F;.\xc3\xb3\x9f\xd1`r\xe5\x99\rk\xa6N\x19\x98\xb5\nO\xec\xd3\x01\xcb\x92\xe2\x9d\xdd\x9a\x19\x03@\x19\x98\x05\x00\x1c\x98\x1a \xb8\x98\x9d\xa0v\x18\x1d\x80[\x18\t\x01-\x98Us+\x1b\x86b\xcd\x988\xe0\xa5\x18\x0f\x80?\x98\x00\xa0\xcb\x18\x02\xa0A\x98\x03`J\x18\x15 \x1e\x98\x15\x80\x05\x18%\xa0+\x98l\x01n\x1d\xa4\xa8\x0c\x19\x90\x80\x82\x18O R\x98)@\x17\x18\x16 \x16\x9cba2\x08\\\xdcH\xf2\t0\xc0\x12\x11\xe0uz\x1bTru\x1d\xa4\x8aC\xea\x00g\xaf@\xe6\x84la\x0f=Y|\xde.\xc80\x90\x94\xc1\x86\xcb\xa7i\xbe\xecv\xe4\xa8\xbc\x05\x03X\x92/\x03\xa4v\xd0qW\xeb%\xe4\xa61i;\x9fM\xa3\xe7Wv#Y\xee9)\x0c\xbd\xeb\xf2V3\xd9\xf57]\xa6lv\xfaw-\xceE\xb7\xee\x17m\xaa \x02#\x00\x02\xe3\x96`\xbbK\x11;\x95p\xe0\x1ab0\x16\x10\x0f\x98\xc6G\x18f\xc7\x9f\x9aC\x18V"\x98\x1e\x18\x18F\x04\x08\x01\x06\xb4g`\xd0\x08\x07L\x11\x03\xccw\x12O\xf4\x99N\xb5<dH\xc2\xc2J\x80\x84C\xeac"K\xd6\xa9/w\xdcy<\xfd\x0c\xdc\xcd\xac\xf0\xba\xd3[\xf1\xe4T\x83\x8d\xbe\x06G\x1b\xf7\xff\xf2\xabN\xa0#F\x18a\xda\x94b&\xcd\xa8\xafw\x02\x00\x00\x00\x00\x0e\xda0a@\x04\x86\x08\x00\xa0`\xac\x0b\x06\n\x80xa\x94\x10F\x02!\xb2`N\r&%\xa1\x8abj"\xa6B\x85\x04eQ/\x07`$\x8adF\x1f\xe6\x0c`2`2\x04\xa0\xe0H0\x15\x00\x13\x010\xa70\xe2\rC\x13\xe1\xee2b&\xe3\xaa\x0c\xdf3\t)\xd3\x12\xb0k0_\x04\x90\xb0\x1f\x1b%\x07^)\xb3bl\xd1\x99Q-\x08\xc4 &\x8f\x18:8\xde\x15~\x9a\x00\x02\x1a\x14la\xa8\xc0`\x84ao\xbe\n\x00\x8a\x8a\x08\xcb)YZ\xf7\x1f"\x01\x11QtH\x1fu\x87Lt\xc3SD\xf4\x97\xbbf\xf9\x9d\xeesy\x9c+\xfc\xbc\xe6\xb9\x9ev}\xe9\xe6\xe6\xf3\xa0=\xb0\x17 \xceS9@GCw\x88\xb7\x06#\x1a\x14j \x19\xea\xc6\xdd\x0bPb!\x98\xc6b\x01\x88\x95\x8f\xd2\x98\x17\x00\xb4\x88\x00]\x12\x953/\x18\x08\x05\x90."tA\xcd-\x13\xcb\x96]\xb4\x14e\x97_v\xb6\xce\xd9\xdb\xbf/\x9bv\xd9\xda\xefbn\xfc\xbe\xe4a\xcbr\xdd\xf9~Q\x07a\x9c5\xc8~_\x94\xa2\x18\x7f\x1f\xc8rY\xda\x92\x88\xc4bY\xca\xf4\xf1\x88b\x1c\x96X\xdd<n6\x00\xc8xx\xe8\xe1\xe1\xef\x0f\x0f>\x00\x18\x7f\x80\x00\x1f\x80\x00\x07\xc0\x00\x11\xf0\x00\x1d\x98`\x03\xb3\x0f3\xf3\x0f\x00\xe0\x02`\x15\xfa\x9bPf\xba[\xe3\x03\x00S\x11\x01\x83\x01\xc6\xc3\nD#\x1bm\xf3\x95O \xe0\xfc\xc1\xa0H\xc2\xd0\x94P\x020p\r5\xe4O02\x03c\x010I0@\x05#>v\xca0\xf0\t\xa4\x970\x0c\x01`0\x0f\x8a\x80"=0\x85nN6X\xd1]\xf8\xd3\xf1\x7f\\\xee[\x8f\x12\x00$\x0c\xd9\x84Z\x96lV\'=\xdf\xfdQ\x12\xba^X\x98>H(\xcb\xd8\x038%\x15\xaf\xb3\xfd\xf5\xb5\x00\x00\xb9\xbf\xfb\x82\x96,\xd1\x7f\x80!\x1c5\x1e6\x16\xe8\xc7H\xcb\x19!\x0f]\x0c\xfa\x06\xff\xfb\xd2d\xf5\x84J\x90U\xc7\xeb\xda\xc4\x82|$\x88\x82w\xcbx\x16\x01\x0f=\xac\xe9.\x8aD\x10\xe2e\xaf\x198\r/K]dI\x8c\x01\x11"K\xc2a\xe0\x1b\xfc\x00\xab\xe6h\x89\x84\x02\x02\n\x80Vu\x03]\x94\x8aIY\xa5\x88A\x10D2K\x19,\xb1\x08\xa5\x9cX\x88T*\x15\x18DD*\x15\n\x89\x91J\x96D\xd3VB)\x04EB\xa6\xba\xa4"\x91H\xa5\x16\xaa\x84R\x85\x98,B)\x14\x8aP\xe5"D\x85\x0cjH\x91"E\x94\xb2$H\x9a\x97\x94\x96\x94\xbcUB\x89\xa9x\xc5T1:()\xb0AA~\x10/\xe4\x14w\x85\x05?\x81Gb\x0c\x14\xf8\xa0\xa7t\x14\x17\xe2\x82\x9b\xf8\x86\x00\x00\xdd\xaa\xe8\xa3<\x95\x01\t\x99\xd0\xe5a\xcd\xf13j\xe0\xe4\x8f0\x0513\t \xe00N\x00U\x0e\x00\x80h\xa8\x00\x08\x80\x84\xc4\xb0\x13\x8c\x02\xc0\xf4\xc0@\x10\x8c\x16\x81\xf4\xc3\x01\xdaL,\x81\xb4\x02\x06\x85\xd5M\xc3\x01 \x04@:\xc9[P<a\xae\xc0\x12X\xbc\xc4\xa2\x8a\xbd<\xbe\xba\xf6\x83\x98;\xde\xee\x13(\x05~\xff\xfb\xb0r\xb9\xca\x17\x87\xc6\x87\xc2\xed>_\x0f\xc8y\x08\x9fqu\x8b\x81\xcd\xa4{\x13:\x82\xd4l\xa8\xe3\xf6\xbe!s"\xab>\xec\xc9\x04G\xaa@\x00\xc1\x85hE\x05\x00\x8c\xc0\xf8\t\x8c\x07ADt\x0cL\x1d\xc1\x08\xc0\xc0\x0f\x0c\x0fB\xcc\xc2\xbc\x1c\xcc\x7f\x05\xc8\xc60\xbbNt\x85,\xc0\xcc/\x81\xa0B`@\x07\xc4\xc0>`\x16\x00\xa5P+0B\x03P\x80\xa505\x0c#\x1fu\xca1\xda\x1e\xc3\t 5 \x04qP3\x0c\x05\xe3\x03\xb0\x0b0\x1a\x03\x00\x10\n\x16v\x06.bx\x90\x00js\x85\x80-g<A\x00H\xacHuG\xf4\x05\xc0Q\xc7\x07;\xb0\x05\xb8\t\xffH\xf0\xe0\x01e\x92\xa8\xb47\x1f\x825R\xcb\x87\t\x9e\xbb\x94\xe5\x89\x9dX\x96I]~i\xfc\x8a_\xd645\xea\xdb\xb5vS\xb9U\x8d\xdc\xa4\xcaY+\xb7\x96\x18\xe5\x18\xa7\xc2\x92r\xa5\xdb\x93\x99\xee\x8ft\xfd\x1ap\xc8X\xd0y\x9a$\xc5+ \xd1\xc4\x90+\xdeg\xc6\xff\xfat\x84\xee\xfb\xde\xfa\x10\x00e\xb8\x81\x08\x0c@\x19\x81\xa0\xc9\x80\xa00\xb0\x1a`\xf0X`P$\x18\x0c\x98 \x0c\x18\x9c"\x99D\x1d\x1f\x80\xca\x19\xa4\x0f\x98L\t\x80@\x03\x03@S\x01A\xa31B3\x06\x03@R^b\xc3Xr\xb6xqH\xfaf \xbcc\x90\x1a\x16\x0c\x81\xa0\xb9q\x90D[\xd3\x01@\x15\x14yU\x85:\x10Q\xe7\x0e\x01\xd6\x15\xb7o\x0c\x00\x00\x07@r\x801\x19\xd7\xec\xb2\x0b\x95LCp\xfc\x02\xe51\xd8u>\xec\xb48\x82\x9a>\xb2\'\xdd\xa5\xc9\xa5\x96\xe6d,\xee\x91\xac:/Tb0\xe9\xc6\xec\xfcO\x08\xe4\xaf\x1a\xd32\x88\xc5Y\x9ca\xe9L1\x11\x88~\xeao\xb65\xbf\xff\xdew\xf1\xaf| N\x86\x90\xc8?\xe6\xa8gN\xe7\xd6@\x00\x00\x00\x10\x02\x04 \x00\x08\x00\x00\x00\x06\x05\x90\x0b\x06\x00\x88\x06\x06\x0e\x18G&\x18\x18n\xa6\x000F\x86\x06@L\xe6\x02H$&\'8I&&\x98Qf\x99\xc1\x82\xc6&\xe9\xfb\xe6RJYf\x05\xa0\x11\xe6\x04\xb8\t&F\xb0\xce\x86.0p\xc6\x04\xf8\xb9F;j\x96F\x02\xe8?\x01\xff\xfb\xd2d\xfd\x80\x06\xf2<C-{\xc0\x00\xc2\xa78\xa7\xae\xf4\x009\xf2)\x13\xb9\xff\x80\x03!\x19\xa2\xf7;\xc0\x00p\x94M\x16\xb2\x84\xcc|\xb0/\x8d\x98\x90)\x0c\x1f0\x8eL\x01\x00\x1f\x8c\x08\xa0"\xc4\x80v\x1d\x01(\xc1\x1b\x03\xfc\xc0\xe1\x02\x94\xc2~\x08\x94\xc0A\x01p\xc0)\x00yT\x0c\x00`\x04K\x88\xacF\x03\x18\x03\xa6\x02@\tF\x02`\x07\xc6\x01\xa0\x03\x02 \n\x8c\x01 \x1a\x0c\x01P\t\x0c\x02\xd0\x11\x02\xc0\x04\x82\x80\x19\x04\x80Z\x04\x00\x04\x90\x003\x00\x14\x01\x03\x00\x90\x02a\xe0\x13\x0c\x01\xf0\x06\xcc\x02\xd0\x0b\xcc\x06@\nL\x02\xc0\x07\xcc\x00\x80\x0b\xc1\xa0\x04\x02\x80\x0el|\x9e\xa4\xbdF`\x10\x80\n`\x13\x00$\x10\x00b\xd4R\xf6\xc0\xba\x93(\xc0\x01\x00\x10\xc0\x05\x00\x18\xbe\xa6\x00\x00\x00t\xda\x9a\xc2\x86\xee\tX`\x06\x80\x16`\x05\x80\x0e,\x00\x19\x80\x0c\x000\x18\x00\x05,0\x01\x00\x07kR*X\xf2\x99\x17\n\xd7*cS\xba\xe6Ns\x0cu\x14\r\x15\xd5\xda\n8\x92\xc5\xa2\x98)\x8a\xfbK\xb5\x12a\xcb\r\xbc+\xeb\xbf\xcf\xc7\xbf\x03\xca"\x8b\xbd\x89\xba\xecA\xc8~$r\x87\xd5v\xac,\xaa\xfe\xabCMj\x01r\x7f\xff\xff\xff\x9f\xff\xfa\xff\x9c\x86\xdc\xb7\xed\x96C\x92\xc8\xbd\xbf\x95\xbf\xf2\xf7\xf1\xfck2\xaajk\x91\xa8jR\xfe\xbb2\xa9t\xabx\x7f\xff\xff\xef\xff\x9f\xff\xff\xff\xff\xff\xff\xff\xff\xf1G\xee\x9e\xdd\x8d\xe7(\x8cNF\xe3s\xf0\xe4\xb2\xc7\xff\xff\xff\xff\xff\xfdj\xb1\x98fj4\xfbU\xa5\xa5\xcb\xba\xd5\xabH\x00\x00\x00\x00\x80\xa0@\x10\x00\x00\x00\x00\x92\\\x83\r\r\xc3\x00\xc0\x83\x0bD\x14\x9a.\xa0\x19\xfa8\x16\xa50Th7\xb1\xcd\x0c\x00\x0c\x9c\x99\x0c\xdc\x0e\xcc"\x0e\x0c\xb9\x00L\x06>\x8c\xbb\x04\x04\x04A\x90\xb2\x873\x1a\x88(FT\x9c\x16;\xc6Ay\x99\xc1B#\x00\x18<$\x01\x17\x0b\x08\xd4D\xd1\x02q 46`\x00\xc088a\xd0\xea\x10\xaf\xe5\xfbQ\xbf|!\xe7}\xd2\x01\x05H\x01\x85\xfe\x0c\x00\xa3\xdb\xc7,\x94Dj\xbbT\xd1\xaci\xa1\xb8\xab\xba\xedK\xe0\x17\xe6b\xc5z\x9b\xca\xedm\xf3\x1a\xdd\xf9f\x18cf\xe5{\xdb\xb3\xdb\x1b\xfec\x8e_\xab\xaa\x16\x0c @\x0f\x14he\'\xd6A\xfa\x02\xe7)\x7f\xb3\xafH\xaa\x9f\xf5\xf1\x9f\xff\xff\xff\xffE@\x17\x10\x04\xc0\xa8\x00\xac\x84\x01\xc3\x04\x1c\x0bs\x00\xc0\x02\xd3\x00\xf0\x08\xd3\x01\xe8\x0eS\x06\xc0!3\x03h6\xd3\x03\x00\x19\xa3\x08\xc0q\x13ztO\xe3\tL1\x03\x04t\x0b\x83\x02\xa4\x04\xc3\x00|\x02\x13\x01d\'c\x11dO\xe3G]\xe0SB\xf6\xa25\x056\x83 \xd0\x191\xe8\x15\x03\x07\x80Q\x0e\x12S\x00\xf0\x10m\x01@d<\x00a\x00\x18\x0e\x00\xc0\xc0h@\x8a\x1e\x03@\tY\x90\xf4\x80\x01\x0c\x0b\xc1\xa4\xc0\x10\x01R\x02q\xcfw\x98\xd80\x08AA:\x0e\x00\x17\x163\x16\xafH\x0e\x00\xcb\xf5\xea\xbdp\xec^\x9a\xd6\x9f\xda+q\xbb\xb2\xca\x7f\x8bK(*\xd1\xc4\xe0\xa9\xc9e\xdb\xb0\xdd,\x8e\xa5k\x92\x99\xda\x18\x9cGr\xe8\x854\xa6\xbe\xb1\xc6\x93W5\xf6\x7f\xb7yPLI\'\xd1W\xff\xff\xffO\xca\xf7\x7f\xd7X0\x00\x04\x19\xff\xfb\xd2dq\x0cF\xed8D\x9f\x7f\xc0\x00w&):\xed\xec\x00\x19\xa0\xc9\x0eN\x7f\x85\x01\xc4\x9a%u\xb4\x8e\xa1\xb4\x00Kg\xdeF\xbe\xf5\x8b\x01\x15\x04\x85\x86\x0c4t\xcd\x9b\x8e2P\xc7\xc6A\x00\xa20\x12\xef\x86\x03\x8c\n\x0f\x10\x17p\xb6\x06\x06\xe0t\xf1\xc00\x10`\xd2\x81*\xba\xc2\xb2\xa7\x1e3E-\xca\x1e\x8d\xdf\xa0\xbf\x9d\xeec\x7f\xf1\xa9\x85\xde\xf7\xf7\x9f3\xed\x8b\x14\xd4\xfa\xab\xccy\xdeSK\xe7\xecKi\xec\xcc\xe3Z\x9a\xc7\xd9\xc7\x961\xc2\xfe\xbf\x1c\xb1\xee\xfb\x97).\xf24 \x05\x80\x0c8q1y\x14\xeaMS>\x91\x0c~\x1b2J\x18\xc0o\x03\xd4\xc0\x9e\x10t\xc3h\x00\xe8\xc5\x0fO\xbc\xe7\xbf\x08\x18\xc0\xdd\x07-\xd6\x04\x00*`\x1f\x00\xaa!\x00\x94\xc0\xc8\x08\x1c\xd0\x8a\x91\xe8\xf6\xfb\xb3\xaf\x18M@2>I\xb8\xde\x88\x91\xc1\x89\x8fJa\xc6\x03\x0b\x80\xcc\x16\x120 lP@b \xfb\xe2\x9ai\xaa\x16\x04\xb3$r3!\x90\x1a\x06Z*\x85\x84\xcb\xdb\xd2\x11\xc93FT\xd3\xef\xb5j(\x91\x83@p\xc3\xbf\x06jn?\x1f\x81\x1f\xb9\xe7\xa6a\xfa\x9f\x91\xcd\xda\xb5M^\xe4\xa653\xaa\xd0<b=\xcaJ\xb3\xf3\xdb\xed\x1c\xd4\xfd\xce\xfc\xaa\xed\x9a\x97\xce8L%\x0bD\xa7\xcb\x90r\x1a\xe6\x1dK\xe7\x1c\x8e\xcf\xfau\xfd\x0c\xb7\xd7\xec\xb7w\xa7\xa0\x08\xc0A\xfd\xf0\x02~@\xf3L\xa6XPtH\xbc\x08\x14\x8e\xe0\t#\x88z4\x10\x93\x01\x10le\xac-\xf8\xc0\x19\x93!\x99(Hb\x11jL\x92\xd4\xaaN]\xc7\x95\xe3j\xb3\xf0l\xa2.\x04\x93\xd8\xa0\xaa\xd6\xad\xfa\xf5di\xaa\xdc\xd6\xc4\xe1\x84\xa3\xc2D\x03B\x92#H\xce&\xc1\xc5\x12Gj\xb9-\x92\xe9f1\x06:\x1c\x0c\xdc\xdd5\x8c\xffq\xec\xd2,\x7fD\xaeLAME3.100\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\x03\xe4\x03\x0eB\xe3\x05D#?\xdb\x83\x16\x80\xe3\x11\xc3\x93\x06\xc03\t\xcb38\xb2S\x15\xd8 #\n\xbd\xe9\x13\x87\xdc>\xe3\x02T\x0b3\x03 \x01\xf3\x00H\x02\x83\x01X\t#\x00\xb4\x07rPB\x0c\xce\xf9NLC\x00=\x80@A\x98!\x00H\x98$\xc1<\x9c\xb0\x87M(0\xa8H1@H\xfe[\xe0*`rt\xde\x86!\x82\xa8fS\\\xff\xa1\x0e\x0bOjm\xe5\x93\x8c\xcb\x1fs\x19|\xe0\xd8\x16\xd5\xa3\x00;r\x12\xf8\xb6\xab\xb2\xdc\x03H\xff\xb3\xb9s\xd2\xdf\xde\x82\xa0m\xd2d\xfbY\xa4\xe4\xb6\x8e\'\x956\x19\xda\xca\xf4\xed\x99\x9b\x1fKR\xdcv\xae\x17\x012\xa7\x0e\xac\x120l\xd0 \xb2[i[uP\xe6&\xe9\x84\xa6\x9a=\xcb\xefr?\xfe\xab\xb9\xaf\xde\x10\x08\x00\x02\xfd\x00\x186\x060\xf4\x18\xb8q\x83\x82\xc3\x04D\xc1\x87\xc6\xc3\x98 \xfa\x03\xd7\x18H\x19fL\x18\x08pb0\xbc79L\xec2DN\x01\x05\xab\x8c\xc5\x81\xe8\x04U\x06\x00\xf1\xe4.dm=\xc1\x97\xd6qb\x98\xafs\x97"u?\xfb#&\xe7{\xba\x0b\xf2\xceR\xb5\x94\xebT\xbf\x06-qR\x12\xa4wC\x81\xfe\xb1W\xe2\xe4\xd6\xd8\xac\xba\x90\xb5\x7f\xfa]\xab\xca\xee 3\x1e\xc0\xd2"R\x0b\x10\x01\xc6/*\xae\xff\xfb\xd2d\xa7\x0c\x06_1C\x93\xbf\xd1\xc0w\x06)\x1ao\xacf\x16h\xc1\x14n\x7f\x86\xc1\xe2\x15\xa3\xe9\xdd\xb1\xd1\x1c\x081\x10\xa0\xc4\xe5\x93Xf\xccK\xe0\x16L\x15vPM\x10\x10\xbb\x8c\x04P7\xcc\x02\x00\x12\x8c\x01\xc0\x16\xcb@` \x80\x10`4\x00\xaab\xdf4\xdcr\xd7\xe9\x97\x87f\x1a)\x1a\x05\xb0\x04\x07\x98<0` Rk+\xf5\xac\x90\xb0\x10\xb1\x18\xc0`\x045\\\xe2\xa0v\xc2\xa8\xcc\x9c\x13Q\x18D7r7@:1(4a\x8d\rM\xcc\n\x80\xf0\xbe\x96Je\x1cqd\xaf\xd2\xf1mh\xe2\xad6#-\xa6\x96B\xb2\xab3R]\xacq\xbb!\xa3\xec\xa6\xcd~\xe7A=c\\\xa6\xad\xa0S\r$b#\x9f\xab\xdb\xca\x7f\xf6\xea\xf7\x10\xfd\xebe\xf5\x06\x00\x00@\x9e\xc0\x04\xd3+D\x16x\xd4\xc7@A\x18F\x1c!\x8d\x0f\xc0\x018\xdc\xd1\x8c\xc9\xf0\xe0\xb4\xc0 \xf1\x15\x82\x00\x93\x0e\x83#\xec\x0e\x13\x83\x950\xd0\xb3\x06\x0495\xa1\xa1\xe2\x80\'\x1ea\xb9\xbd/\xe3~\xd4\x07\x14\x87s\x17\x05\xcc@\xf5r%\xa3%\xbb_\x9f\xdb\xca\xea!@_=\xaa\xcbB\xeb(K\x92Y1\xab\xc7{S\xe2\xae\x9a\xbb\x8eK\xa0\x96\xb8t#\x8f\xfe\xf6\x8dh\xef\xe5LAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU B\x00\x00 \x94\x06\x88\x06\xb0I\xc0!\xa8\xc0`\x00\xc6\xc0 \xcaP\x14\xdc%,\xca\x18\x06\x04\xc1\xac\xd2\xb4\xcf[\x19\xb0\xc0\xb3\x05\x04\xc0\x94\x02\xa8\xc0O\x01\x14\xc0\x00\x00P\xc0\x04\x04$\xc0$\x07\xa8\xc3\xa1\xc4\xa4\xf8`\xac\xc4\x00\xa8\xca\x02\x1c\xc5sT\xc0\xb2\xa0\xc5\xf0\xa4\xc0\x00\x08\xa0\x1aT)\xc6\xae\x87\x01\xf2b\xbd\x01\xb1\xb6\x9a\x14\x02\x9et\x942$\xb0\x08\x02\x1f\xa8\xa3\xdd2\xdc\x87HqcVrKk\x19TLT\x1e\x89\xd3\xa5\x03\xd9V\x10\xda4w\x967\x00K_\x89u>9cZ\xf6\xec\xef\x98\xd6\xbd\xcb\x9e\x11\x1a\x90\xc04\xc5g]\xb1sqe\xfdzSV\x02#\xdf\x8fc\x0bz\xdeJI\x94R\xc2^\x01P\xcf\xe2\x17\xbb\xa0\x98`\x00\x04\x0bcm\xc1$ N\x94\xb8\xc3\x01\xc5ADAf\x04\x92J2i\xb6\xa6p`\xd2a\xa2\x06\x89\x1a\n\x00\xb0\xa8\x08\x17\xb4p\x15\x8d:\xc1|\xc0P\'\x80\xc0<\x97&\x01\x80\xee,\x00\x84@\x1c\xc4)\x90\x17F\xf1C\xce\xec\xbbr)Um\xaf=a\x97,\xd5\xf0\xca)\xde\xbc\xfe\xfbn\xa7b\x8e\x1f\x1d(\x86\x98\xb7\xa2\xdc\xc6\xb5\xec\xb3\xfb\t1\x81\xe3\x0cX`\x02\xdd\x7f\xf6\xdb\xdd\xfa>\x7f\xeb\x0b\x02\xc6@\nD0\xbay\xb3\x08\n\n\x0e1\x81\x8f\xa6i\x0b\x1d\xda\xa0c\xf7\x02\xb6`aQVe\xbb\n(`>\x82\x9a`\x16\x01H!\x00\xac\xc0\x0f\x00H\xc0%\x02\x90\xc0\\\x07d\xc5=\x94\xa0\xc2\xcf\x03\xc0\xc1\x18\x00\xf8\xc0\x9b\x01<\xc0M\x04xF\x1ad\x05\x01p\xa0\xff\xfb\xd2d\xcb\x88F-)\xc2\x9b\xbf\xe9\xb0|e\x18\xdao\xccN\x1bL\xef\x0e\xee\x7fg\x02l\x11\xe1E\x8flp\x11a\x82\x86\x98h\x1a"\x10\x9f\xa4\xe4\x04\x89 \xa0\xe4\xdb\x16\x1b1q\xb3.\xad\x0c\x03k\r}\xf8\x9b\x83\x86ZG\x9dZc\xb7Rf\xe5\x80@l\x82\xc0\xb0<n\xfb;~\x98\x8b\x1eW\x8a\x81]\xa5\x03\xefb_9L\xfe\xddu\xdf\x88\x9d\x05z\xd3\xb1\xbc\xec\xf6\xaeUb\xd1W\x9e/\x14\x91\xd2gg\xb7\xb2\xb7c<7\xac{\x879\xfd\xfdc\x9d\xeb\x1d\xe6\x01\xc5*\xda\xc0\xa6\xc3.J^\xdd\xd6M\r\xe3\r7\xdfJ\xf6\xbf\xf7\xfd\x03\x01n\x00\xae!\xc9I\xd1\xc9\x9d\x98\x13\x03\xb9\x80\xd0\xa4\x98\x84\x029\x86\xba\x9f\x9d|\x8a\xf9\x8dx\x17\xa8I\x81\xd8\x18\x8b\x04\x91\x80\xe0\x0b\x181\x8a\xc1\xf4\x01\x12\x18X\x90i\x81x,\x97\xec\xc1<<\x8e!x\x04>\x1c\x04\x17\x06I 0\x03\x9eH\x05<\xf2\xc8\xb5\x0f\xcb#A\xc2\x0eu\x1c\xe4fCI\x01\x93\x01\xe1E~\xe5\xcc_\xdb\xd9\xd6\xb9~\xee3\xb6oU\xaff\xce\xeba|B\x14\x10\x01@&\xdd\x149\xc4/M\xd5\xda\xefU;S\xd0\x9aF\xaa\x9fKo\xf8\xf6\xee\xf4\xd4\xd5?\xec\xbdU\xfdJ\x00 \x0f\xfdl\x19\x13\x19\xbd\x96\x1e4I\xc7\xb2\x1d\x93\xa9\xec\xc1\x18\x86\x03\xe9\x8b\x88Z\x19\x81\x08\x99\xa6\xa4\x96\x9c8\n)\x8c\x981\x18[\x00\xaa\xcf\x05\tq\x890\x0c\x19\r\x85i\xaf\xd3\xde\x9aY\x80\x81\x91\xc0!\x18\xb3\x82\x19\x88\x90\x0f\x18`\x81\xe9\x84\xb0\x18\x186\x81\t\x82p\x0c\x1d4f\xc4H:\x00a3 \x04F\x00\x90) \x81\xd1b\x83\x06\x05"\xd8TaPI b\x10hpFu#\x00Ap\xe4-\xe5m\x99\xaa)2\xd5\xd2qU\x1ceg\rA\xbaJmP\x1a\xa3\xa6\x8c\xd1\x94&c\t\x85H\x15\x08\x85\x08\x18R&0q\x95\x1ef\x87\x19\xf2fly\xa2\x18hD\x9a\x00\xc6|\x18\t\xa09x\x92Acc\xc4\x83\x02\x96\x88\x10\x04*\x18@,F8`\x88\xc9\x01\x19"\xa12BD\xa4G\x06\x0e\x8b\x18\x0c#\x06\xc0\x1c\x06\xbe\xda56\x82\xbf\x97\xaa\xb1+\xd5-R\xe5-WJ\xe5u1\x16t\xe4\xb8/\x14\xdc\xa2W\x0cCo\xe3\xff\x0f\xc3\x90\xfc9\x17\x8aE\xe7\'\xe7\xa7e\xd2\x99T\xa6%\x11\x89D\xa3\xb1\xe8\xec\x92\x86\x82nb\xa5=\x8btTtS\xd4S\xb3\xd3\xb3\xd3\xb3\xd6i\xac\x92\xaa\xa8\x85\xc0\xc0\xc0\xd5Yd\xa1!@\xc0\xc4\xaa\xa6\x98``\x01\x81\x8b,\xaa\xaa\xaa\x85*\xcb\x7f\xd5U@2\x01"c)\x98\xbb\xd0\xb4\x0c\x01\xa6\x00\x00\x06`(\x18f"@\x86a\x82\xbaf\xe9\xa14b\x06\x03\xe5\x80\x03\x04\x00\x18\x84\x00\xc1\xc0>*\x0c\xa7\x83#\xb2inR\x85\x98P\x8a`g\x08at\x08\x1b\x15\x02\xbe\x8cMG\x9f\xd6H\x89z\xa5\xc6s<\x0bMb\xac\xb3Ul\xb64[\xcb\x0b<\xee3\xd8\xe4H\xeeE\x15\xa12I\\\x10\x88\xc2\xd4\xfd\x8f\xedwb\x13\xaf\xa3g\xab\xfd\xdb>\x87\xff\xfc\xc7w\xdb\xd6\x15H\x06\x11 D`:\x07\xe6\x06`l`N\x04`\xe0g\x11\x80a\x85p\x96\x18\\\x0b\x01\x90\x91)\x19\x99\xb4\xc9\xe8\xc1d\x19^\xff\xfb\xd2d\xff\x88\xda\xb3U\xc8;~\xd1b\x7f\x84\x98r{\x83z\x150\xbd\x10U\xed\x80\x02\x98\x17a\xce\xbd\xc0\x00\x0e\xa1\x89\x90T\x16T\xc0\x84\x16\xcc\x19@\xb0\xc2\xe8X\x0cX\x12\xbc\xdeL\xc4\x8f\x8d<\x8c\xc9\xac\x8cL\x1c(&Y\xe4\x00\xb0\xd5r\xcc"\xed\x1d\xde\xbc\xd6\x1e\xd6\xbe\x9c\x83\x81\xec\xe2%\x08\xa6\x99\xa4E\xf8\xcc\xae{\xe5wc\xca\xde\xfb9\x0f\xfcF\x07}*\xca!\xb8\xc5\x05\xbc.^\xbfV\x9a\x0b\x92\xd6\xed\xeec\x95&y\xe1\x87?Z\xcf\xb59\xbb\xe1\xb1\xa0\xea\xcd\xa8L\x11\x159\x08\xa1\xec`\x93\xfd\xbf\xa5T\xff\xfd\xa4\x17\x1c\xb5*0\x05\x00f\xaa\x82\xe6\x02\x80l`|\x05\x86\x16\x00\xa4d\x98&\xc6*mbh\xdaG\xc6\x18\x00\x94`f\x02\xab \xc0\x18\x15\x8c/\x03\xd0\xc3p\x11\x0f#\x87 \xfb\xc7\xf30\xceN*?2\xd00\xc2b\xc3)\x06\t@\xe9\xfe\x8ah\xae\xdc\x9d\xc2`;akoB\xb8\x80\xe5\xa1`\r\x16\x13\xd1\xca\x181\xc1\x1a\tX\x98\x96W\xfa\x8ef1\x87\xb2fb\xedy\xf9&\xecZ\xcf\x93\x90\x1b\xf7\x9ep[\x0f]\xf0>r\xb8\xbc\xa2\xee\x18\xdb\xfb\x7f\x9dNa^\xd8\x11\xccq\x93\xfa\xe8\x102\xc5i\xfb\x7f\xd3\xff\xff\xbc\xbe\x9f\xfd\xfd\x150:\xc1+0:\x00\x0e0E@\xcd0*\x81\x150)\x00\xa70\x19\xc0\x9d1\xfd\xca\xd45\xf2\r\xf70\x17\xcb\xf35A\xc3\xcd0\xde\x84\x1e0DH\xd20\xa7\x00\xca0\x07\x88\x060\xd0\xc1\x820D\xc1 0E\x80E0z\x01\x182+\x01\xf3\x07`\xac0}\x1b\x03\x14\x10K4V,#\x03\xa0\xc80f\x00\xf3\x04p\x17\x0e\x02s\x06 e\x01\x02\xa2G\x98\x01\x001\x85(-\x98\x1c\x00\xd1~\x08\x00\xf8\xc0<\x02\x95\x94\xc0X\x0bB\x800\r\x01\xe0@\x03\x96\x9c\xbdl\x88\x0c\x01\xa4@\x01\x00Ak\xaa\t\x12\x01G\xd5\xd6&\x01\x17\xc8 \x14\x17\x1aZ\xaf\x952_\xcc\xb6#\x1b\x82U\x1a\xe3~\xa52\x86R\xfc0\x193q\x891\xc8MY\xbbUg#sK\xca\x15\x0cR\xb7\n\x1bv\xddxf\xb2\xd7}#\x16\xe0\xd8k)U-\x9e\xdb\x85P\xd2<\xb4\xb1Y\xeb\x960\xce\x18\x94Q\xee\xad\x1d\'m\xe7\xa9\xdb\xff\xf6\xf1\xce\xe7q\xc7*\xf8\xdd\xbf\xdd\xd2]\xa1\xb7\xcbr\xfd\xf3\xba\xc3\xee\xe3\xbc\xbf\xf5\xff\xbd\xf7\x9f\x9e\xf5\xceo?\xee\\\xee\x1f\xcb\xdf\xbb9\xe5z\xdeY\xef\xbd\xfd\xf2\xa6\x1d\xeeW1\xd7\xe7\x87\xe3S\xff\xff\xff\xff\xff\xff,0\xbb\xf8\xe7\xcd\xef\x9a\xee[\xcf\xff\xff\xff\xff\xff\xff\xbb\xd7o\xee@\x14x\x8c\x00\x08x\x00\x03\x00\xc8\x01\x93\x01\xa8\x05\x03\x01\x14\x04\x93\x02H\x05\x00p\n\x06\x08\xb8&f\x110\xf4\x06l@\x9aF\x198Z&\x16\xa9/\xe6\x1e0\x89\xe6U\x18\xf3F\r0G\x86\'X\xf0\x86\x0bh \x86-\xaa\x13\xa6\x0b\xa84f1\x12 \xa7\xe8&\xc4aJ!\xa6\x16\xe7Da\xc0\'g9\x81\x96c\xb0\x07"\xc1\xea` \x06f\x00\xc00\x02\x0cs\x00\xa0\x0bf \xe1)\x11\x00{\x07/\xe5\xc6(`\x1c\x02\xe0@(&\x02p\xb0\x05\xa2\xf9\x80@\x03\x18\x14\x00\x19\x800\x01,\x0b\xb8\x8f\x89\x84H\x01J\x06\x10\x00\x83\x00\x0c[\xff\xfb\xd2d\xfc\x80\n\xb0\x85A\x86\x7f\xc0\x039\xacxE\xcf\xf8\x001\xf9\xed\x08\x19\xff\x00\x02\x89\x95#\'=\xd0\x00\x17\xe4\xb5\xa1\xc00\xd8\xdd\'\xb5\x12\x18\xbd5:\x895\x87\x8a#\rj*\xe22\xe4\xc3\x8c5\xa7\x19\xe6v\xa9\xe5y\xc8&e0\xec\xfe\xe8a\xe8\xd4\xcd\xa7\xce\x9e&\xe5J+\xd9\xb79c)e\x9d\xdc\x94s\x1a{r\xc9\xee\xe7kWe7f\xff\x95\xf9\xccr\xff\xef\xd7\xe6\xff=\xd9\xc3\xee\xd4\xad\xcf\xdd\xcb\x98\xe3\x9e\xb3\xfb\xb7\x7f\xf2\xe7\xf3\x99\xeb\xf3\xde\xb0\xefo\xf3=\xff\xe5\xce\xe1\xdds\xbc\xdez\xe75\xac;qa\xc0t\x0f\x1c\x1ehjs\xe8$\x15\x01\xda\xf1\xa7~\xb0\xe0\xbd\x84Z\x17q\x8b\xf8\x12!\x8d\xaa8\t\x85\xce"\xc1\x814\x15I\x84N\x06q\x800\x089\x90\xc8p!\xd9*\xdf\x19\x88\xc0[\xc1\xf92\x15\xf9\x8c\xb0\xe6Q\xdf\xdeO\xb1\xa6\xf1\x1a\xd1\xb8@Z\xa1\x8f\xd2\xb9\x01\xf4\xfe\x8b\xf9\x8c\xce\xd0\xd9\xear\xeea\x9d24\x9a\xdd\xa7\xd9\xa4\x84K\x1a\n\x88\xc1\xa1\x0c`\x19\x9d\r\x91\x94A\x89\x18\x8e\x8e@\x04C\xcc\'\x03<HL\xcc\x0bA\xb0\xc1\x94\x1a@B\x9c\xae\x8c\x0c\x02X\xc2\xec\x03\x0c(\x03\x90\xc1 \x0f\xcc#\x83d\xc0p\x11\xcc%\xc2T\xc0\x0c\x03\x8cM@\xd8\x08\x07\x06\x16\x81\x00D\x02f\x17\x00\x9e`\xc2\x03\xc6\t\x80\x04<\x08\t.\r\x03\xa3\x00 \x01\x0b\x00RaI\xc5@\xf5\x1aY;@v\x0c\x06@\x0c \x14\xcc\t\x80P\xc0d\x06B\x80\n\xdb\x08\x80\r\x1b_\x89\x1ce\xd5\xb7\x08\xa7\x93\xd8\x8d\x98\x00\x00\x11\x00\x06\n\x80\x98\xa8\x00\x00\x80)~.v\x8c\xe1=\xcc\x06f9.\xa1\xf9\xeazi\x1d9wK|,\x00\n\x10\xc4\xe7\xd8\xba\x1a \x1e\xfcE\xb1F\xa4q\x99MJ{v\xbe\x9a\x9b/\xd5f\xef$r\x19\xe2\xdbn\xcal\xf6\xc3\xee\xcbN\xa1\xab*\xad~SV\xb5\xbf\xab\xf9a\xda\x979\xff\xfe\xbd\x1b\xc7\xfe\xbc]\x9c2\xb7F\xb4\xb2H\xfa\xc8\x9eh\x12j\xb5\xfaZ\xba\xff\xe5l\xb2\x99\xc7\n\xd7\xb2\xff\xdf5\xbc\xbb\xfd\xff\xbf&~\xdc\x89$\xdd<\xdczM\t\x97\xf2~1\x1b\xff\xff\xff\xff\xff\xff\xa6\xd7*e\xdd\xee\xec\xaa\xe6x\xdeO\xe3\x87\xa6\x14\r\xc3@\x00\x00\x03\x00\x10\x00\x00\x02/\x01\x80p?\x08\xc0 0\x07\x13L\xc0D\n\xcc\x0e\t\x80\xd3X8\x8cT\xc6\x9c\xc4\\\xc3\xccO\x85\x84\xd0\xdc\xa2\x08\x83\xf4\xc3P/L\x18\xc1\xc0\xc1\xc8\xce\x0c\x02@\x14\xc3\x0c\xa2\x8eV\x1f\xcc\x1e\tL\xc7\x05\xc0\xc1y\xb5\xa1\x19\x80`\xf0\x14\x07o\xf00T\thP\xb1\x10$\x82\xed5\xdf\x8d\xda\x8a\xb9Nn\xde\xe8r\x01h\x0f\xa5-\xf9\x06|\x9c\xddi\xcb0\x97vR\xea\xb5\xdb\x9c\xcb\x1eg\xbb\x18\xe3I\xff\x8d\xda\xbc\xab\xde\x7f\xd4\xf5\x02(\x14$\x0e\x81\xdc\x14\x16\xaf\xdd7\xb3\xff\xfd\x9d\xbf\xff\xa5\x01M\x1al\xc0\x84\x00\x06\x000\xc0\xf8&\xc9@\\\xc0\xd0\x04\x89\x80\x9c\xc1T1\x0cKC\xd0\xc3\x8e\xa0\x8cP\xceP\xc0\x08S\x8c,@\xfc\xc0x4LP\x05\\\xc5\xc8\xdc\xcd\xba,\x94\xda\xc4[\x0caD`\xce\xc8\x8cS\xd4\xd0h\xcc\xe9\x14\x04j`\x00\xeb\x955\x99An\x1f\x07\x02\xff\xfb\xd0D+\x8c\xc5>.F\x9f{`\x00\xaa&\x08\xb3\xefp\x00T\x14\xc1\x12N\x7ff\xcad\x17#\x8d\xbfl\xd8\x18\x840\xd1B\x11\xe2\xa7\xe9\xdd~`\xca\x00\xc2\xb5\xab)\x9a\xa4wQ\x05[)\xa5\\\xc6\x1a\xed\x98.%j\'\x1e\xb9vj\xed<j\xf5\x1dy\x9c\xb0\x9a\xd6\x11*\xf9Lc{\x7f\x7f\xf1\xee\x15{\xf5\x85\x84n\x0f\x82"\x16\x98h]\xc4\x97\xf6\x7f\xb7]\x9f\xfe0\x04\xe4@\x03\x03P\x020\x17\x01c\x04\xc0\x9d0\x11\x02\xb0\xc0P0+\x01\xa3\x050\xd21\x8f\x12\x03\x19\x9d\x140\xbe}\xc34\xf1N1Q\x013\x04\x00{1f\x1cs#\xc3\xc39\x9a\xeas\x95\xd101\x96%\xe3\x88\x1fL\x9d\x7f1K\x1c\xca\x85\x13\n\r\xc4\x80e\x03"\xce2@\x00A\x9e3\xb6N\xe1\xad\x10\xa0\xd4Xt\xf3\xb6j\x92h(\xc4\xa0\x14}\x8cN\xca\xda\x00\xc0\x15L!\xe9\'s}\xa6\xeb\xcb\x9e\xec\xf5\x19\x96\xd3\xd0\xd2\xca\xe5S\xb3\xb6\xe53\xd2y\x98\xedk\x93\x12\xea\xf9\xd7\xd7i2\xaf\xf7o~\xb7c\x1a\xbd\x08\xb0~k\xfc\xbb\xbe\xb4\x05\xf0\t\xf8c\x10\x80\x8a0\x18+\x10\x10\x8c:&3`\x08\xc2\xa9#\t\\\xe5\x03K Q\xc3\x0c\xa0\x15\xd3\x03\\\x07\xc3\x02\x9c\r\x03\x00\x9c\r\x93\x05\x040#\x19\x11\x83\x03\x1c\x9c\x1c\xc3\x0b\x80\x14\xf3\xb5l?\xed\xd3\x9c\x9d+Y@p\x88\xe8t\x0c\x188\x93d\x02\xb2\x96j\x8e0S\xfaH\x8eD\xdf\x01D\xa3r\xd9)\x98\x08\xb1x\xd5X\xd4\xba"<!\x9d%\xacoQrG\xc9\xfax\xbd\xca\xf3Xn\xac\xff*cKY\xf9\xa9\x8fn\xe7gt\xb4\xb6f\xec\xde\x9b\xb5wz\xa0\xcb\x0f\xb8\x96c\x13MR\x1e\xc1\xff9`\x1d\xf5\xb8\xda\xca5\x19,\x80\\\x19R\x19\ta\x8c\x8b\x8bN\x98\xbe\xb5\x91\xd7\xa1\xc5\x18"\x00x@_\x18\x04\x00\xf1\x81 -\x98\x0e\x8d\xf1\xa3\xf6\xf7\x197\x8b\xb1\x8ah*\x99\xca1\xc86\x9cB\xf9\x97\x8b)\xba\x82\xc1\x88\x8e\xcb\xcb\xea\xda\xe5/\xceLT\x15\x1e\x0b\x9c\xab~\xc4\xd8\x086GcT\xd2\x98\x0c\xac2\x1c\xa1\xb3\x9c\xfc\xae\xdd\xa9fpMZj*ZM\xd5\x94\xc7\xa2pU\xaa\xb0$\xfc\xae1\x12\xa3\x9f\xa2\x8c\xff7\x9e\xadU\xed\x9e\xd8-IZ\xd6\xa7?V+}\xdf\xd9\xff_\xff\xfe\xb5\x00\xc8\x81$D\x02\xa8aY)\x83A\xa0`@\x88,d\x92\xf9\xb8\xb0\xc6\x1ch_F\xd7 G\x06\x13\xd0\x19\xe6\x07(\n\xa6\x06 \x12\x86\x08h\x1a\xe6\x0e\x80BFZ\t\xc8\xc6P\xe0O\xc6\x08\xa8:\xa6U\x91\x9a\xeb@ehq\x87\xc7c\x01\x03\x08\x03K\xb2\x8aB\xc0@\xc1\x13\'\xa3a\xae\xb4\xc9P\x82<\x9f\x7f\xa7\x1b\x0b\xb2\xf0\x18tq \x99\xc2\xbd:\xb6\x0b\x02e\xb8N\xd2\xce]\xe4\x8e\xf62\t\xfc\xa2\xb4r,\xe5\xd1\xb8w\x1aY5\xd9\x8c\xe6\xb1\xb5[}\xa2,\x91u\x9f0\x14{\xea\xff\xee\xff\xeb\xe8\xec\xff\xf5\xf5\x03\xf2\x02\xd8Gc\x07S\xc6\x8c\xa0\xa1\x91\x8bH\x06gJ\x9bK\xc4a\xb5\x85\x1en\xbd\x00\x82`\xb7\x016`V\x80\x14<\r\xc1\x81b\x08\xa9\x83\x80\x11\x91\xa1Je\xa1\x9ad\x02\xc1\x81\xf0\x0by\x81R\t\xa9\x81T\x121\x80\x94\x0b!\x80\xff\xfb\xd2Du\x0c\xc5\t(\xc4\x9b\x9f\xe1\xb0\x9d\xa5X\x82s\xfa8SD\x9d\x10n\x7f\x86\xc2D\x12\xe2\xcd\xcf\xec\xd8\x12\x02k\\\n\x8b3`\x0b\xaa\x0e\x00i\xc8.\xe71\xcbxh\xc9$\x93j\x8d\xe2\xb2ia\xa3;\x01\x92F\xa9w0\x9f\x81\x80kY\xca?s\xb7\xe9\xe9mOcc\x95\xbf\x18\x95Il\xf5>\xabY\xb9^\xcd\xaf\xbd\xac\xb5\xcb\xdb\xde \xb0\xaa\xb1&~\x86#\xbbV\xef\xff\xf0\x03\x1a\x04\x02\xe6\x89\x00\xcc\tT\x06\x0f\x8cR/1\x01\xb8\xd3h\x93|t\x8c@\xb3\x90\xcd\x89\xc0\xd7\xcc\x10\xc01\x84\x81\x0f\x06\x00\x18`h\x82D`>\x07\x82cG\xb8\xdacN\x07.`\x9d\x84\x90dA!\xd7\xe1\xc6\xe5F\x19\xe0\x064\x0eFu\xc4\xaa\xc1\x01""\xc4:\xb7 \xf9\\d\xa8G\x1ae\xbc\x95Y\xecU\x9f\x81\n\xf1>O\xd2\xdfO\xc1 \x1c\xf4\xb7\x1e\xd9\xc3Qk\xf7 \t]\x8aIm/\xc61\xd4\xabX_\xb1\x95\x9ej\xa3\x0e0$\n\x8a\x15\x14r=v\x7f\xf6\xad\x7f\xfd\x9f\xff\xd6\x01\xd5\xa4\xcb\x15-\x81\x80[@\x00\xd1\x8cD&:\x16\x18\xad2nj\x01\x84\xb2Yi\x9d\x10\x17\xf9 \x05F\x02\x10\x08\xc2 \x13L\x000N\x0c\x00`\xbfL%\xb5\xc5\xcc  \xa5\xcc\t\x90 L\xc8p\xf0R\x8e$xJQo\x14\x08\xaf\x954p\x08\x89gb4\xf5m\x96\x08\xc9\x94\xf5(\xbb1%\x141\x8e\xff\xd6\xcd\x8d#^\xac\xdc\xef1\xf9}\x9c\xde+U.\xd2F\xae\xc0\xb5m\xe3CK^\xad%V\x12"D\x89\x079#oV\xef\xf2j\xfe\xcdu\xd1\xff\xff\xda\x02@\x03\x12@\xe2\x10d\xcd\x9d\xec\xc3\xe1\x88\xc42\x04\xca"`\xcc\xb5\xec\xdfO\xa0\xc4\xfd\xd6\xcc\xc5\xf7E\xcc\xc3\x03\x0e\xe8\xc2\x98\x06T\xc1\x85\x00P\xc2d\x02\xc8\xc5W\t\xf4\xe4\xeeY\xe4\xe0\x0b\x0c|0\xad\xc3\x07\xf8(\x03\x05\x0cX\x93\x02\xdc5\x93\x00\x90\x0b#\x01\x8e\xcc\x00\x12\x00\x82H@\x86\x03\x0e\x99$\x8e\x84\xe9\xd6\x8c\xd6e\xe1E\x99H\xad\xfd\xf1\xd0\x1b-@\xa3&<\x13\x19\xfd\x8a7KJ\xde<\x8el\xf4\xb2\xfa\xb2\xe9\xfe\xd5\xce\xa30\xa9o\x9f\xdb\xce=\xda\xdd\xe7n\xcen\xd8\x95A\xe2\x80@\x804(\xb0\xc2\xae\x17d\x1b\x88c\xdc\xcbj\x1b\xd6\xd6\xb5\x0c;\xa8p\xe3hm[\x8d$\xf6\xb2*\x1e\x95GT!}K\x1d\xaa\x1a(\xa7\xa4{Yz,\x08\x000\x05\xa3\x00\t\x10\x8c\xa4\xceO\xc17\x9c\xd6@\x00\xab\x8c \xc4\xb8\xcf\x18-\x8c\x13\x80\xbc\x1a\x06\xc6\x00\x80N`F\x04F\x02\x80\x8ad\x96\xab\xa6I\x812`d \xe1a\x86\xee!\xa5@\xcf\x910\xbb\xac\x18T5+R\xc6OW\x1b\xb7Qn\x97\xf3\xbb\xa7\x8b\xf1\xdd[0\x05\xdb\x9f\xbf\xb3\x97\'\xab\xc3\xb3\xb5i-\xc6u\x9d-\xaf\xf5#\xc5\xcd7\xd5\xd5\xad\xffO\x04\x01\x9f\xd6\xc3\xc4`\x00\x00 `5\x01\xf0`3\x00\xe8`L\x01 `4\x00h`"\x00\x00`{\x83\x96`\xad\x97\xd2f\xe4\x85\xf2a.\x82\x96`]\x81\x86`\x1c\x80\xc4`F\x00h`>\x02\xd8a&\xa2\xb8a\xab\x83\xb8`\xaa\x02\xc0}\xdc\xb9\xd4x&\xd5m\x9bU2i\x12\xa9\x84\xc2FB.\x19\xd9\x0cf\xc2\xe1\xff\xfb\xd2d\xd0\x08\x06X%\xc1\x93\xbf\xe1\xc0rDH\xbac\xda6f%W\x1c\xef\xf3\x0e\x81\xf7\x92!\xc9\x9fh\xd8\x9e\xcafY&\x98\xf4Za\xb0J\xaf\x0b\x00[\x07r\x16\xb0\xb5\xe5\xd7BZ+\x9c\xf2\xa1\xe5\xcbA\xf5v\xc9\x14m\xb3\xa9\x9a\x12\xd0\x0e\x8a\xea\x0e\xc4\xd9ax\x10\x08\x83\x89\x88\xc1%\xab\x9d\x00\xe6!\x19\x08d\x10\x08\x07\xa9\x1a\x84]\x87\x92\x1fg\ra\x96,!u\x0c\x043 \xd8\xc3b\x0e+3\x94\xb7\xec\xde\x08LD$\x17q\x14\x10\x06\x80t\x03\x97,\xb2\xe5\x93-\xba)\xc3\xf5_vv\xbb\xd6\x1dw\xb3\xb6\xbe\xef\xbf\x8f\xe3\xf8\xfeF,W\x86\xdc\xb5\xd8\xbb\x1f\xc8r1I\x86\xfb\xf8a\x85$\xa21\x18\x8cF\xe5\xf6\xff\n\x94\x94\x94\x94\xf4\xf4\xf4\xf4\xf4\xf4\xf9\xfet\xf4\xf4\xf4\xf4\xf4\xf9\xe7\x86\x18a\xcd\xe7^\x9c\x10\x04<\x00\x08\x060@\xe5:\x81\xf0\x7f\xe2p\xff\xfaC\x00r\x00\xc3Y\x00C\x04\x04\x16\xbc\xd1\xc8B\xc1\xb1\xc1\x85\x18\xf9\x9a\x9a\x04X(\x80\x8c\x10\x00(\xc0\xb4\x00\x8c\x00\x01\xa0\xc3\xecHM\x1c\x1cT\xce,3L \x03\xd8\xf3.;\xfb\xcd<\x95\x87\x7f\x11\x81\xd2\x81\x9cv@\xf0\xbe1\xecq\x8e\x943\xb3\x9cw\xbe\x9d\xf4\xf5?\xea\xd07\xffW\xbf\xfb\xd7{{.\xd5\xe5O\xfbY~[\xfa\xc0%\x8a\x0cjlf\xa2\xfd\xdf\xfa\xb8\xbf\xee\xff\xf5Z\x9d\xf4\x7f\xf5\xff\xfe\xeaj\xa0\x00\x08\x01\x7f\xffA\x800\x08$\x1c\x06*\x82\xcc\x14\x111!\x14\xcb\x85\xd388N\xd9\xdf=9\xf0*\x0e18\xa0\xc3a\x03\x05\x86\xcc\xf4\xb35\x12\xe8\xda\xee\xe3P\x8f\x8c\x0c\x1d\x18\x15\x19\x0chb\xf1a\xe7\x81\xdf1\xc6\xd1\xa209\xa4\xb61L4R5R,\xd1x\x93\xa9\xa7Z\xfd\xe3\xb8\xec\xb7\tT4\xfe\xb9/\xec;-\xc7\xf2\xcb\x17u\xddrY\xca\xed]\xab\xb5\x86\xbb\xd2\xec\xe3+\n\xa9U*\xedg.\xd3\x94\xe53\xa6t\xd7\x9d\xe9t\xa4B\x02@\x04\x00@\x18\x1b\tG\xcb\x99ek\xbc\xd1\x90\x84\t\x02 tE&\xad\x9b.\\\xb5j\xd3\x93\x11$I\x12LW}V\x9c\x98\x9e\xadZ\xb9r\xe5\xcb\x97=\xac\xae2222\\\xf5\xbeffl\xd2\xe5\xcbV\xd6\xb3\xf6\xb5\xabZ\xd6\xabV\x82\xb1(*w|J\r\x03^\xa0h\x1a\x08\x18"\x0b\x91\xd6 \x00Q\xb3\x83D!3\x970\xf3S\xb3/\x02\x991w\x08\x83\x06\x00.0{\x04\xc3\x03\xa0\x8d03\x1d\x03?m\x944Y\x17\xe3\x0e \xed4\x15Cr\xa93\xa7\x93_\r\x10\x8f\x82\x94\xd3\xb1^&\x91\x81\x88\xaa\xb3u\xf8\xecm\x94\x13-\xc3r\x1az\xf6\xcb\x99\x1a\x88Y\x9b\x9c\x95\xa3\x1d\xcb\x19\xd8\xc7\xbf\x9e\xb5\xcds\r\xe1\x8f\xfd\xbc\xb0\xe5\xads\xbc\xfdaS\x87\x82\x00\x833\x02\x87\x87\r\x1e\xdbw\xf7=\xb7T\xd42\x96\x9d\xb5\x8e~\xf9=\xce~Y2V\xe4\xa8v\xbc\x03\'K\xec\xae\x80Y\x05\x08\x07@@\x06\x18I\x01\xe1\x80\xa0\x16\x98\x0e\x81Q\x81\xe0Q\x98*\x80A\x82\xc0\xd0\x19\xa6&\x81\xd1Y\xee\x13\x18i\x85 R\x18\x10\x02\xd9\x82\xb8]\x98P\x8f\xa9\xaf\x19\x05\x19\x96\x03\xf1\x88hS\x1a\xb6\xf1\xaa_\x1a$q\x8c\x84\x18`Q\xad\x18\x18\xe1\xf1x\x0c\xff\xfb\xd2d\xe9\x80G T\xcb\xd3\x99d`\x9c\x85\x18Ag\xdb6\x1a\xe8\xe9\nU\xed\x80\x02\xab\x98\xa2^\xbb\xc0\x00\xe8\xd0\xd1\xc0L\x98\xe0\x148b\x82\xcc\xc0,\x06a\xa1f\x12\x02\xe3\xb2\xd5v\xc8\xd8\x90(\x11|8\x94\x0e\xa3\xa0\xa0+~R\xbc\xf2\x87\x1di\x99\x97\xf2\x92[\x14\x8eC6\xb7:\xc3\xdd*\xf3\x12\x8a\xb8\xd0\xe5\x8d#\xb1!\xb5\x1c\x9d\xe7\xe7b\x93Y\xf7\r\xf3\xb9\xe3\xff\xddX\xaf\x9d?\xf6\xc6\xf3\xd6\x18k\xf7o\xee\x8e\x07\xf3/\x16r^\xc0;\x85\xce\xc2\x83G\x9f\x8d\x01\\\xc4\xee}\xcfO\x03\x98\x05\xe8\r\x8a\xb3~\xcb\xd1\xba\x896%\x00R\x8c\x82]6h`P.`\xb8.*\x01\x18N\x15\x98\x1a\x1d\x98R4\x98\xe5I\x9a\xda^\x19\xa6D\x85\xc0C\x0c\x81c\x12\xca\xd3\x1c\xc0\xc3\xd9\xf0c\x93\x1c\xc1d\xb4\xc9(\xa3\x93)\x07\x82\x84\x82A\x819\x91\xc2\xe63\x01\x00\x81\xa6\x1b\x01\x11\r\x8b\xa4`\xe0\x82"\x80@\xe9D\xe7\x14\x01\x9f\xc9{\xa7\xd8\xda\xcf\xa3f\n\xda\xd3\xd8L\xa6$\xc1\xdd\xbak\x90M\xaa)\x8b\xb4\xd6sv\xe1\xfb\x11\xba\xf2\xbbr\x88\xd4\x03\x0f\xceJ\'b\xfc\xa7}#\x15gexJ\xa9;{;\x18\x7f\xf7xgMD\xb1\x01~\xb5\x02(\xee\xe7\xfe\xbf\xdf\xfd?\xff\xff\xffe@\x00\x00\x00,\x06\x00\x00\x000\x14\x00\xe60\x0b@\xaa0\\@\xa10Z\x03\x960<\x03\x1e1\x08\xc4X03\x05\xfc\x08\x1e(\xc42\x1d0\xc1t\x0ex\xc9o94\xdcSX\xf4\xc1X\x02L\xc7r\x03`\xc1\xac\x0b@\xc2\x84\r\xb4\xc2J\x11@\xc9\xb7\x14L\xc0\xa4\x04d\xc0\xd0\x00\xac\xc2\xf4\x0b\x90\xc3V\x04\x98\xdfw\x14\xd4\xcb\xe6\x1b\x9c\xc0\x06\x01,\x04\x02h\x90\x01\x06\x0e\x983\xa6\x11`+F\x01\x90\t\xa6\x0c\xd0ZF\x0f0Q&\x0e@\x1c`\x10\x00\x19*\x1b\xab\xd3\x01\x94\x02\xf3\x01\xd8\x06C\x01\x98\x05\xa0\x10\x0e\x06\x04\x00\x03B\x80>\x18\x07`V\x98\x19\x80\x8a\x97\xf4 \x01h\xfax\xa8\xe1\x80D\x01A\x80h\x01\x90\x18\x04\xc3\x00D\x00uk0\n\xc0B0\x19\xc0/0\x06\x00%\n\x80\x10`\x18\x80M/w\xacV\xd5a \x01\x0c\x03\xf0\n\xcc\x01\xf0\x02S<\xbb\xe6\x00\x18\x01&\x02X\x06\x00\x10\x03\x0c\x02P\x0c\x0c\x03\x10\x0c\x8c\x00 \x07L\x02\x00\x04\xde\xaa\x95\x7f\x1dV@\xf0\x80\x00!\xd6nY\x84\x024\xc2\xa0\x01\x00\x00\x04L\x00\xc0\x01R\xb7K\xe4\xc0\x00\x006\xfe\x1a\xde\xf1\xcb\xfdb$#$]ryax\xd8\x9c\xfa\t\x98\xb2\xd1ZE\xdeG\xe8\ta\x92\x1b\x7f\xde\xf3\xf9\xf9\xff]\xb6\xb6\xe3\xb8\x931v \xd7\'\x1c\x87!\xa4\xb0V4\xa5*\x0b\x02\xe2\xfa\xa5\xeb\xa5?\xbf\xfc\xb5\xbf\xef\xff\xff\xfe\xe2\x92\xfdN2\xf8\xbe\xa1\xf7\xfe_\x8c\xae_\x0eR8.\x93:\x81\xa0&\xb4\xe5JgZS\x82\xfc\xdc\x94\xbb?\xfb\xfd\xf3\xf1\xff\xff\xef\xff?\xff\xff\xff\xff\xff\xf3w#\x18RF\';Ib_\x9d\x88~\xde\x1f\xff\xff\xff\xff\xff\xee\xee\xe1\x97fU.\x80_hz\xbc\xaa\x1a\x97MCQ\xa6\x00\x01\x00\x1c\x8c\x00\x00\x00\x00\x00\x04h\r\x0c\x08B\x84 \x02\x8cA\x01\xb5\x04F\x0b hb\x8c\x1b%@h0\xff\xfb\xd2d\xf8\x00\x0ed\x8aDN\x7f\xe0\x00\xe4\xa78\x8a\xcfp\x00\x1bL\xaf\x0e]\xff\x80\x01\xdc\x17\xa4\xb7\xb5\xa0\x01S\x19\x13\x03\xc0\xe10\xc0\x14S\x1c\xa1\x001\x02\x05\xa3\x8f\xc2)0d+#"PI0s\x1e\xe3\x1bPn3\xff\\\xdals\xc0\xaf\r\xde17)$\xc8\x81\x11fy\x8f\xc9L\xe8\x04\xb50\x18e\t\x86c\x00\x19\x0cXP\x0b1h\t\x07\x90\x92\x88b\xc3\x84\xb0$\x08\x0c\x01X\xeel=n\x81\x02\xa6\x15\x14\xc3\x8d!J\x9f@PI\xab\xde]\xcc\xc9\xf9\x86\xa9\xbb\x95<\x9eYV\x91\xd3\xdc\xa7z\xb9\x94\xcc\xb6\xde\xf0\xa2\xce\xa5\x8e\xf6\xff{1\xdd\xfe\xef\xd2\xf3\xb8\xeb\x0f\xe6yw\xfb\xfb\xdd\xff\xfej\xeaI\x85\x14|>Y\xccQ\x00\x98\xb8g\x92\x8c\x90:\xba{R\xe9W\xebL\xf2Z(\xf4\xb9\xeeW\xfd\xcdZ\x7f\xf9\xb53\x0c\x00\xe8\x01\x80>\x05a\x81\xd0\x02\x19(\x02\x81p\x14\x08\x0020\x1f\x01C0\x8f\x02\xd90\x91\x82\xe50S\x06\xbc0\xbb\x98C8\xca\xc8\x861\xf9\xc4\xca0\x93@\x9a0#\xc0!0U\x01\xc71\x14\x81\x0c1\x03C\x810\x9aB\xe61\x08\x025:\xa8\x08p0\xe5B\xfe\x04\x836`\xbc\x01\xe2`u\x00\xd6`(\x01H`=\x80\xa4\x16\x00\xe0\xc0\x08\x00\x04\xc0\x12\x00\x1c\xc0\x07\x01H0\x05r\xe8\xa0$F\x00\x04=(\xa5^\xd0A\x80~\x03\x83\x04RO\xdcA\xa0\xc3\xae\x99 \x00&\x00`\x03`\xa0*\x8b\x8d\rc\x95{O\x1a\xf1\x05\x00q.\x8b\xc6j\xd2\xe57vW\x0fC2\xa9E\xdf\xbf(\x8d\xe7+\x8d@\xd6\xbf\x972\xba\xa0\xf8\xf2k\x18\x04\xc3\x8er\xc4\xcd\x1a\xce\x8c\xb3\xbd\x1f\xfe\xcf\xff\xee\xfa\x7f\xaf\xfe\xe1(\x00\x00\x00\x0e}@\x18\xec\xc1\x0c\x10\x91\x18\x04\xa6\xe0\x10!F\xb6O=\x92o\x03EUX\xc1\x08\x10\x8c\x02\x8d>\xe7Mp\xf3 X\xe3\x1a\x03 \x10\x00\x03\x01"\x0e\xa2\xd1\xb6F\x95\x92\xc7\x13\x1c\xe8h\xa8\xf5\x979\x84\xe4\xf6=\xb5O/\x87yS\x96r\xdf;\xfa\xde\x1b\xd5\x9d\xe1\xab\x91\x99\xf9>\xa7n\xef:\xdc\xa5\xa3\xa0\xe6y\xcf\xd6\xd6\x1f\xdf\xfe\xf6\xe8p\r0\t9\xdf\xdf\xec%@\x00\x0bl\x00\x10\x84\xc8\xa0\x05\x87\x00\x19\x80X\x08\x08\x00A/\x01\x80\x1cH\x1f&2@\xf6b\xc7\x1fg\x0c\xe0H`\x1c\x03&\x05\xa0J\x06\x01q\x00"\x189\x82Q\x88\xb8\xc1\x18=\x821\x86\xe8\xd4\x1eY\xb3\xc9\x8dH\x1c\x18@\x02\t\xf7g\xa9\x07`\xd8@\x18\x0b\xf2\x8fM\xa8\xd7\xa3p\xb8Lf\x97;vA\x99\xb75\r\xcbb\x96\xea\xe9h\x15\x8e\x8b\xf7\xac\xe5\x0ez\x8e\x05\x86\xfb\xd4\x9e\xae\xe2>\xf4\x95\x1c6`6\xda3%\x0f\xc4BhR\x1bLyV\x8cl\xe5:\x9aY\x8fa\x02<\x97\x83\xe7\n\xc9\xc2u\x95\xb1\xc4\xa2P\x00\x00\'\xff\xa0\x05PaC\xf1\x10\x08\x89\x00\xf8\xc8\x01\x98\x06\x00\xe84\x00L\x10\x81\xac\xc48\t\x07\x1a\xec\xd7\xe42\x8c\nAL\x0c\x02\x81P\x17\x15\x02#\x03\xd1:0\xc3\x12\xe0\xe0v%\x00\x93\x8dsi0M\x01c\x02@\x1f#\xc8\xd4D\x9a\'\x9d\x0bS\xfdL\x94yc\xc3\xd0^\xe3\xf5-S`\x16NA-\xce]3_\x1bK\xe1\x16\xae\xf7\xff\xfb\xd2D\x86\x84E\x0f;\xc7;\xd8LP\xa5\x87I\x1a{&\x8c\x14\x88\xcf\x19M\xfb\'\x02\x8b\x18\xa3\x1d\xbfd\xe0/\xdc\xd4\x95e\x0e\x07\x18\xa6k\x8e\xdbr\x80c\xae\xbc\xfd\xb9\xd8\x12U\x84\xf4\xcc\xba\x13\x0f?\x90\x97|}\xe96\x042\x0c;N\xb3\xcd8u\xc1\xe5z>\x93\xbb\xa8\xd2\xdaS(M_e\xc4\x80\x002\xb2\x01\xb0,\x19\x98r\x13\x8cd\xe0\x04Fa\x82FrFnU&]\xc0Ta\x8b\xc4\xa6\xcc\xa4\xb0`\xfe\n&\x07 DD\x04f\x01@Z`\x1a1\x86$BJ`\xa4\x13&\x18\x03zxQ\xb1\xc3E8`H\x05\'\xa1\x07\xf9F\xa4\x00\x80\x12\xc1"\x05BzG\x8e\xa5p\x1d\x98rn\x82\xe5 \x86\xc8\x8d\xb8?)u-\xfa"\x05\n\xc3\xbb[.\xee\xad\\\x12\xca\xde\xa8%Wq\xa9\x8c\x0b\rN\xf7\xb9\xd5\xc3\x98[\xa5\x8d\xd0\xda\x92\xd6\xb7\x0c\xc4q\x99\x9d\xbf3M^\xa5\x17\xd9\xfe\xdf\xb5\xc3\x0ehp\xddl7\xedP\xa3\x00\x05+@\x1b\x02\xc1\x98\x80\x00\x03\x9c\x02\xa8\x81\x84\x10\x01\x86\x8e\xc2l\xcc\xb0$\x8c\x07\xfd\xf4\xd7,o\x0c\x10@\xdc,\t\x00\xc0\x130\x1e\x00s\x01\xd0\x8e1\x8e\x1c\x93\r\xc0\x910\xf0!S\xf8\xebL1n\x03\xf3\x07\xf0X8\x1a0V $\x9b\x02\xef\x0b\x1e@\n\x08\xc5\xa7v\x9bi5\xfa\xb6\xec\xf8\x86\xc9\x17r\xbf\xc8\x94\x96\xf0\xe3\x04KW\xa6\xcf\xbc\xabbx\x88\xa9\xe9u\xba\xb8\xebT\xaf\xcc"w\r\xd6\xb9\x9d\x9b\x155Z\x96\x96U\x94\xce5\xb3\xab,\xa1\xa5\xe6x\xe5\xba\xa6M\xa4\xf8\x94Zm&\x8e1,\xb8\xaan}JLAME3.100\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa"\x00\x05\x11%\x1b6De`\x10$\x18(\x052\xa8P\xc0\xa3#\'\x86M\xf0\xda1\x9a\x81^0"!\xd51q\x84\x860!\x01#\x08\x00\xac\xc0*\x00@\xc0\x15\x00\xc8\xc0\x91\x07p\xc3c\t\x88\xc1k\x02\xf0\xc1\xc1\x0fP\xd4\x95\x80\xe4\xc0\xad\x05h\xc0\xb4\x03t\xdc\xcf\r8\x14\xcaO\x0ch$y\x01\x8c\xb1C\x06+L\x06\xf5S7X\x1aA=\r;\xe4\x904\xb3\xf3\xb2\'\xe5\xfe\x87\xde"\xa3qo\xa7\xaeM\xe1~\xdcY2LH\x1a\x19\xa6\xa7~\xabW\x89\xe17\x18\x87!P\xba\xf4S\xf1\xacv\xfdgOf\xa7\xe7\xcd\xd2\xe3\x9e\x1f\x8fyv\xf1\x82G$\x19R\\\x91\x8fV\xb2(\r\xb6\xb5!t\xb3\xb5=\x88c\xec\xadW\xaa\xf4\xe8\x0e\x80\x00\x00\x01\x1e\xb0\x01v.a\x80\x99\xd0\x80\x10\x01\x1e\x8c!#\x14l\xaa\xac\xd1\xca7\xd5\xcc\xa2\x10\xb8qb,\xd0\xe7\x83\x10k\x1a\x0c4\x03\x9e\xa0\xc8\x98D\x03\x98\x04\n\xbe\xc1\xc0\xdb^PE\x9e\xc1\xe2\xad\xaf\'\xab@\xf7\xf1\xde\xb5j\xf5\xab\xfa\xdd\x98zq\'\xdae.\xed\xe3\x93\x8eZ\x15h\xba\x96Z\x088ea\xec,\x84\x904e\x81\x9e\xe3\x05\x8d\xad@\x18V\xcaR\x81\x00\x06$\xd2\xa6\x02\x05`\x10L\xc2\xe0\xbc\xc4Pd\xc6\xc0<\xc7Pd\xd9\xad\xf8\xc9\x8c\x03\x0c\xc4L\xc4\xa4\xdcJ\x14\xb0\xc0\xcc\x04$\xff\xfb\xd2d\xb1\x00F 0\xc4;\x9f\xd9\xc0s\xe59\rk\xa8z\x18p\xab\nN\xffg\x02\x1b\x98\xa2i\xcf\x19\xe8\xc0\x8b\x02P\xc0\x08\x01\x94\xc0n\x00\xf8\xc0\x9d\x0bd\xc7\xac\x01\xf4\xc2\xae\x06\xac\xc1J \x8c\xc8\x1a\xc7X\xc1\x9d\t\xcc\xc0\x8b\x04X\xc0*F\x0f\x8cMd\xc2\x84\x80\x85j\xce42B^f\x83\x8d6\x1b\\\xf7\xdfZ*\x15\xe4c\x9a\x10\xa8z=E\x1d\xc2\xebH\x19\xae\x05,K\xe3\x16\xff\x1e\xdd_\x06 \x03\x00\\\xb5\xad\xdd\xbd\x8d\xc9\x88\xa5\xab\x95\xf7\x85\r\xea\xb2\x0bU2\xff\xbbb\x93:\x99\xa3\xc3\xd6("\x97\xd5j\x96\xc6\x9fio\xbeKP\x97\x91\xb1(\xd8\xfe=O[\x9a\xbe]\x02<\x86\xef\xb5\x01 \x00\x11\x80\x03\x88!\x0b(\xa3\x86`\xc0\x81\x83F\x83D\xc3\x0e\x9cL0/5\x8d\xc8\xe4\'S\x0e\x0f@\x00\xa0\x10 \xc0\xa0\xe3J$\x8c6\xfe\x0b\x8a\x0c@@\x08\xe4d^\x8c5\xc0x\xc0\x90\x02\xc8\x81\xd1,PL\xfe\xb2\xc4\xc90\x00\x00X1I:\xd1\x18~\x82k\xf3\xb8\xd2j\xdd\x95Kj\xdf\x88\xd7,\x00\x0c\xce;\xc7?\xf4\xf3\x9be\xa4\xd9\xc7\x98\x077\xa65I\x03\x92\xb3\x8c\x9ah\x9f\x98\xdbX\xccU\xff\xfa?\xff\xff\xff\xff\xfa\xea8I\xec3D(0 \x0c"\x17HC\x13\x10\x01\x93\x02L\x06\x83\x06\xf8h\x03-\xd0"\x13\x1as\x82\x13\xd60h\xe3\t\x08\x1e\x93\x02\xcc\x07\xe3\x02\xb0\x060\x10;\xc6\r\x90C\xe6D\xd8\x98f\x19\xf84\x86\x04\xe1G\xc7\x19W\xb1&\x19\xc0\\\x06\x04X\x1c\xa6Rp\x19\x1c\xfeb\xc0 \x8c6`"\x01\x84\x81\xc4\xc0\xe0\x00(\x1d)m\xd9\xb2\x838T\x11\xae\xac\x934\xc2\xdf\x86\xe5\x1a\x95C\xf1\x19KX0*\xc0\x15$m\xe9m\xceU\xb7D\xd6\x82\r\xee<\xe7jc\x8e\xb7\xb9E\xee\xffw\xfb\xc7\xe2\xe1\x13d\x03\x04\x01Rr\xaf\xb1T4\x9b\x14E\xa5F.\xb3\xf2\xa5\xd8\xc0\xe0\xbc\xf5#\xaaJ\x18\xa8\r\xc0\xe2YC\xae\x8c9KZ\xd1\xad \xec"\xc0\xcf\x1e\xa0\x18\x89!e\xd4\x90I\x05C\xf2\xd38\x00\xd0\x03V\xf00\x1b\x18\x07\x82!\x81\x98\x10\x98\x1d\x05\x11\x8b80\x1a\x03\x81\x088(\xcc\x00@\\P\x07\x0c\x06\x81@\xc2D?\x8c8\x03\xb4\xc1\x00\x13\xcc7\x06\xcc\xe8\x90\xe9\x8cZ\x80\x94p\x04\x82\xb0\x01\xbcA4 SeSR\xa5\x8e\x9eP-+\x93"\x9d\xc3,ev\xf2\xc2o\x1b\x91\xbbd\x0fU\xd3\x97l\xeb4\x91\xf3+\xc32D<\xdaB\x1cp\xa0Dk\x08V(7g\xf6W\xb5\x1e\xba\xd2\xedz\xed{\x9d\xe9\xef\xfbQ\xdd\x1a\x00\x9f\xd6\x80\x8c\tc\x00d\tp\xc0G\xcc\t\x00,\x8c\x03\x80&L\x0f\xb0"L\x0e\xe0e\x0c\x06\x00(\xcc\x17\xd0\xa5L\x1dc@\xcd\n\xc0\x9fL20\xbdL\x10Pr\x8c&\x80K\x8c\x140\x85L\x17\xd0\x10\x8c- \x9c\x0c\x110\x98L=\x80\xcd\x8c\xe03\xbf\x0c\x12\xd0\x99\xcc!\xd04M\xe5d4\x92\x9c\xdb\xa4\x138\x1e\x8cD7\x05,\x0c^)*\t\x8c<\x11\x01\x96h<\x16\\[\xf3a\xa1\x0bD\xda\x1b0\x822M\x10\x12\xe1b\x10\x02\x108T\x14fE\x90R\xe3R7U&\x82E\xf2\x9e\x06\xfcd\xb0\x02\xbd7\xff\xfb\xd2d\xff\x8c\xc6\x8c\'\xc1\x83\xbf\xe1P\x8cd\xf8r{\x03\x88.Y\x8f\x1ao\xf30J*\x92aE\xec\x0e C%HY\x93DPaE\x92\x160\xc3\x0cpCx\x93\xdds[\x839\xf3\xed3\x87\x90\r\x01\xb4\x1dw\x90\xd4&I\xca\xc82\x00S n\x0c\xb5\xc6T\x12\x94\xdb4\xc0x\xc8$\xe1\x0c\xcex\xc5H#\xc3U\xb1\x1aD\xd4\x1ag\x8c$\x18j\x0b\xa3z\xab+B\x0f\xa3\xa2\x9a\xa0<\xbc\x8b\n\x84\x05\xd7P\xe4\xa0.\xfa\x89/\xd4\xebZ\x0b\xb9~9oD\n\xe3\xba\x0f\xeb\x8e\xd2\xdfg\x91\xad\xc1Ps\xbf\x04N\xc0\x90\xdczB\xef\xc0\x10\xeb\xf6\xfaF\xa2\x90\xdc\xd4\x827A;/\x9b\xa6\x9c\x95\xd0N\xcb\xe6,\xcb%t\xd2\xc9]i\xcaz\x99a\x9e\xafgs\x94\xf7{b\xbeV3\xd70\xdeXg\x973\xd5\xf2)\'\x03\x16E$`\x00p\x14\x93\x96T\x8aI\x8b#\x90\xb2\xd1\x91\xc8\xd8@\x86\x8bm\x18W\x10\x90\x07\x88@ \xc0\xa4\x02L\x07\x02\xd4*(F\nAVij\x12f\x06`\xc8\xd0L\x0e\x00`\xc0l\x03\x8c*\xc4\xf4\xc4\x9cG\x0c3A\x90\xc3$d\x0e\x15a\xfc\xc0\xfc\rA .\xd8\xce\x8d5\xa0 hHCTNC0\xc1C\xd18\xaf7\xf5s\\\x94\xb3\xb9wW\xadf\x87\x12ck\x7fw+X\x0e\xf4\x15k\x8a\x91\xa8\xa7\x0f*-I\xece;So\xe9U\xe9\xfeC\xa7\xb1\x0b\xb2\x9b};w\xe6\xab\xa2\xa5|\x9b:\xea\x90\x80\x00\x00\x0bd\x92@b\xd1\x00\x18,``\x98\x00\x00^"\x00\xb9\x82\x80\x06%\x18\x18p\xaed@\xd1\xc8\x83\x83H\xa3,\x8c,\x88Y1\x94\x1e\xb6\x84\x87\x191G\x02\xe8\x8c\xc0\t\xf8\x19((2\xcbuY\xd3\xe9\n\x8c\xd3M\xceK\xa6u:\x9c\xc9\xce\xa2i|\xdc\xd9\xab.n.\x1c\n\xed"\xfb\xe4\xffA2\x07y\xf06\x0c\x91\x13\x92\xa2\x9b1\x86\xb8\x89S\x06\x86W%-4(\x91\xb2\xb2M\xb2\xb2\xf8\x8a\xf1\x94\xb5\x94\xa7\x19&\xdce<D\x9b(\x92z\x14\xb62\x9ccS\x8c\xae\x12Vl\xd0l4R\x92\x9a\x942\x92\r+40`\xd2\x89e7\xaa\x00\x00\x00\x02\xe2r6\x0c&\nB\xa3\x08\x07@@\x84\x16,\x03\xc0\xc1\xc3\x1e\x8f\x0cP]\x05\x00\x0f\x842\x03\x1c\x8c(=\x10\x87\x05\x89a\xc1P\xc1P\xd1|\x12x0V<\xc1\x02\xa3\x10\x80\xc1\xf93\x99N\xd7\xe3\x02\x82\x1e\xf8\xcc\xba\x03\xa2~\xa22\x8932t\xdd\xd6t\xe9\xc1\xce\x14\x036\xf9C\xc9\x96\xa2\x10\xf4\x138\xffAI\x8d\x14\xe8\x9dr\xed\xb8H\xb4\x02\x81O\t$\x9a\'Z$\x8cZ\'Z\x89\x16\xa4J\xd2\'Z\x8e6\xd1%h\x92-A@K"u\xa2TV1*\x88\x1c\x184,\x1aV&*\xcc\xa4\x96\xa7\xc2\xc9LQ,\xa4\xb4\x80&V\x81$\x00"(\x00\x86\x00\xc00`8\x01b\x00\'(\x05\x93\x01 V0H\t\xa3\x05Pi1W\x17\xa3Y!\xb90\xbe\r\xc3\x08\xd0\xbb0g\x05c\x06\xd0{0\x0e\x06\x81@\x19\x06\x86\xa1\xa13\x19\xae?\xc1\xbe\xc7\xf1\x93\x02\xe0\xa8"b8\x02\n\x05L\n\x02\x0c\x14\x00\x13\x054\x10\x96\x1c\x04)\x92\xbc\\O\xf4j\x1c"\x00\x10\x9e$\x02Q\xb4\xa6\xff\xfb\xd2D\xe1\x84E[@\xcbk\x9aJ\xfa\xa8\x879]s\x06\x89Y\x1c\xe5\x12\xf5\xee\x80\x03[\x1c\xe1\xce\xbd\xe0\x00\x92\xfc\xb5\x89\x14\x85\xd0\x10\x011hn\xbd\xc7\xfe\x1cd\xeb\n\xe3\xb1\x87ua\xa9!,\xe2\x1f\x84\xd9\x8e\xc6\xa6V\xa4\x81\x968\xce\xb3-\x89F\x1c\xb8\x15\xaf\xcd\xcfL\xca0\xc2c\x960\xb1\x1b\xa6\xad7\xcaK\xb6r\xee:\xb9\xbf\xef;\x86z\xacH\x01[\x95\x7f\xe9v\xae\xb6\xed\xd3R*\xff\xa4\x90\xa3 \x04u\x06\x00\xc04\x04\x85\x82e2\x0c\x0e\x01P \x02\x0c\r\xc4\x00\xc1\xf42\x8c{A\xb0\xd7p\x97\xccN\x02t\x88\x0fL\x13\xc0L\xc0\xe8?\x07A\x94\xc6\x00\x13\x8c*\x04p\xc9l\x0f\r\x98\xd7\xb8\xc7$]\x0cC\x03\xe0\xc0\xa0\x10L\x16\x00H\xc0\xdc\nL\x07@\x0cH\x07E@5\xb8\'\xc0(\x02\x8bj\x8f\x1d\x05\x00a\x808\x05\xb4U\xe2\r\x00\xb4)\x86\x90\x90\xe55&{^K\x04\x8e\x80Z\xb4>\x91\x98&#$kl\xa9\x9em\xc0\x9ep-\xc1U\xe50\xe2\xc25\x8a\x8c]\x94\xbf\xcd5\x86-\xb6\x1c\xfb\xc6\x1dF\xbf/\xce\x9a\xe4\xe4\x1b\x1b\xa7\x89\xdd\xab\x1f\x9d\xbdb]G_\x95\xf0\xbf\xbb\x95lr\xc5\xde\xd9\xc2\xfe\x02\xcba0x\xb0\xd2f\xc6[\xf2r\x17\xddE\x89\xe8\xff\xff\xfe\x8a0`\x00Q0\x03\xc1\xb30d\x84\x8518\x85S0M@T0WD\x150\xf8B\xdc6F\x12\x001E\x13s:\t\xe4\xa321H\xc67\x102{2\xa1\x85\xf53\xbbG[7\x18\x9fy;l\xa3D2\xdaS\xb2?\x8d\x95\xb14\x03\x83\xa51R\x03\x962\x16\xc0\xa01\xc1\x84\x891w\x0fI0\x9eA30\x85\x00\xaa0\x17@\x13\x10\x00 a\xbb\x07\x06`h\x82\xec`\x91\x80\xe0`\x06\x00d`\x11\x00\x12J\x02\t\x80`\x001\x80\xaa\x02\xa9\x80\xb2\x02h\xd0\x06\xc6\x02X\tf\x00X\x04\xe6\x07\x18\x0c\x86\n\x08\x16\xc6\x03@\x01F\x01` \x06\x00\x18\r\xa6\x00\xf0\x06\xc6\x04\x88\x0e&\x01\x98\x05f\x00\x98\x01\xae\xf9\x80*\x00\xd9\x80X\x00\xe8\xf0\x03\x86\x01(\t\x86\x00\xc0\x07\xe6\x01\x80\x05b\x10\x16"KY\x99f`\x11\x80\n`!\x00T`\n\x00\x08\xb7\x0c\x01 \x04\x0c\x00\xe0\x04\x86\x80\x1c0\x00\x80\x0b0\x04\x00\x170\x06\x80\x1dBr\xb7\xb57}\xe2\xbd\x1d\x80\x83\x00\x14\x05\x00\x06\xc4\x96\x10\x04\x00\x9a9\xcf\x98\x01\x00\x10\x98\x00 \x0b\x18\x02`\x06"\xda7\x18\x00 \x04\x18\x01\xe0\tKe\xba\xb39_2\xe3\xa0\x1d\x7f\xc9\x96\x9a\xd7\x03\x00\x10\xa0\x92\x04\x04\xab\xd4\x11\x17\x94\xb2*\xc2\xfa\xa5\xe9wm}j;\xdf\x97\xdbT\x89\x08\xc1\x18\x9d\xa8\xa2\xebq\xfa\xba\xd9\xdb*\x8b\xa0%\x1b\x90y\xcet\x92\xf8\xbb\xce\x0c&\xefugZ\xfc\xf2\xd7`yk\xee\xeb\xa9\xa3\xb9a\xae9\x11J\x91\x89d_\x06D\xc0V,\x81\xf5a\xacF\x9a\x01S\x16\x94\xd7\xa2n\x92\xee\xcb\xb9g\xbc?-k\x7f\xcee,e\xee\xfc\xfc6\xff\xc5\xefW\xa7\x96W\xb6\xd7%\x98\x7f\xff\xff\xff\xff\xff\xbb\xda\x899R\x9b\x0c\xa9\xc1we\x10\x0b\xbb;)va\xdf\xdb\x06\xca(\xa1\x85\x80\x00\x00\x00\x04q\x01\x00\x00\x12\x80f$\x01\x8b\x98\xc0\x10\r\x04\xff\xfb\xd2d\xf7\x80\x0e\xd9|B\x06\x7f\xe0\x00\xbdEx\xab\xce\xf4\x00\x18L\xc5\x18}\xfe\x80\x01\xdf\x17\xa4\xb7\xb7\x80\x00\x86\x06\x03\x86\x1d\x92f\x8d\x8c\xe6\x0f\x0e\xe6|\n\xe66\x13\xa7B\x92&\x1b\x03\x06Q\x15\xc60\x84\xe6n\x16FJ\x83\x06j\x82\x86\x90L\xa6%\x83\x86|2F/\x07\xe69S&H\x07\xc6\x1b\x17&!\x05\x06\x07\x00@\xd0\xe0\xc2\xe0<\x1c\x00\x99\x0c\x1c\t\n\x0f\x92U\x17\x11\x817\x05i}\x96\xfb_\x88-\xc4\x83\x975F\x9d?3\xa8\x9d\xd8\xd5\xc9\x1c\xf6S\x12(r\x1a\xb7^\xbdo\xc7Z\xb7\xbcs\xedJ{9\xda\xbb[\x97y\xfd\xb8\x18\t\x0b\x89\x82\x08"\x10\x1aXqeV\x156eB\xa2\xaaI\xfdz\xd6\x8f\xd1\xfe\xde\x9f\xd3s\xbf\xfd\xbf\xff\xf1\xc09cM\x86\x00\x94\x06\x00y\x7f\x82\x80%0\t\x8070\x1f\x80\xa30$\x00\xdd0\x16\x00E02\x00\x930\x00\x81i0\xcb\x02\xd55JA\x070\xddC\x1e0\x94\xc2\x9e0\xb6\xc4\xee2\xff\xcd 2\xc1\x82\x1d0=\x01\x011\x9d\x0c3\x8e\\1\x1db2\xa4|1\x14>(\r\xde\xb0 \x06^\x88j\xb3\xf5\r\xb4\x97tH$}\xa2l\xc0\x04\x05\x06\n\xabF"\xf2\x184\x0b\xb6\xd0\xea\xbe\x06\x81\xc6\x01\x00l\xb6YC,\xa5\xca\x92\x9d\xf5\x86"\xf0\x14S-\xccC\x10\x05\x157 y\x0f)\xef\xde\x82\xe4\xb3\xfd\xa7\x97n\xa7\xd6\xfa\xd7\xf2\xc7[\xb5\x9ex\xd6\xbd\x9e\x1c\xc0\xa8\xe1qe\r\xbe\xef\xa2\xa2\xbdwjJ\xbe\xff\xb9Wh\xa4@\x00\x00\x00\x02\xdfP\x04\x7f`\x10abY3\xa6\x18\x0e\x16\x0e\x11\x8d\x1aV9\xab\xb4\x9b\xfb\x19\x9a\x8a\x80\x05\x0c\xe18\x15(h\'\xe6\x10"\\\xd3\xda\x06(\xb8\x05\xac\xd2\xdc\x99|\x1f*\xb9\x18\xc2\x93Vuj\xee\xab\xf3W\xe5r\xff\x98\xcej\x97\x9c\xdf/c33/\x86n\\\xb9\x8d\xdf\xed5>u>r]\x1f\xfcuIE*\xc7\x1c\xf5\x86\xb3\xcf>\xe5\xaf\xb0\'\x13\x90\xb8\x8d,\xae\xea\x01\xb9X\x00\xaa\x08\x16\x05B\xa0@\x01\x81\t\x18\x88i\x99\xce\x9d2\xd1\x81\x08\x98\x91\xb1\x89Ca\x9f\x14\x8d\xc1\x8b\xe8\x05\x18$\x05\x91\x80\xa0\xe0\x99*\xfc\x19\x95\xf0\x7f\x98\x19\x82\xe1\x81`>\x18\xb0\x85\xa9\x818\x15\x18\x0b\x000\x16\x00\xe8\x17\x8dE\x11E\xfcn\xceS\xb2\xf5\xaf\x04-\xb1r\x84f%\x19t\xb7x\xcb\x0c\xa6Y\xcao\x14\x19\xa9\xcb!\xdb\xd8j)\x1a\x86\xb0\xa5\x97\\\xbd\x1b\x9f\xed\x9b\xfc\xafZ\xdeS\xb6\xf3\xb3\xbf\xa2\xc6j==\x9c\xb6\xc5L;\x85\xfa\xfc\xb7\xf4\x16\xeaeX\x0e\xd2,\xc1\x18\x08\xea\x00\x017\x19\x00t\x11\xc2xG\x8a[\x99\x9a\x90\x1a\xce\xf9\xcdX\x188\xe1\xa4j\x18<\xa3H\x99\xe7`a\x18\x18`h\x81\x00\xae0\x1d\x02\xa51\x02R\xfb0\x8d\x82\xb10\x0c@\xd60\xfcB;|\\2\xcc:1\x80\x15,\xe9\x83\xc0\xec\x04\x8b\xac\xfd}(T\xb66\xf7\xaa\xb2$\xca!.\xc8\x84\x1d\x1a\x08a\xea\t\xc3\x03\xc1Ie4\xa1|!}$;.\x96\xeao\x904~\x82\x92\xbeq\t\xaa\xf8\xe13\x95\x8a\xb8\xdd\xa9r\xd5/mO\xde\x9a\xc2\xbeU\xeb]\xd5\xcb\xd5{f\xc6\xf7\xfb\xd5h\xb6\nIP\xa1Es7\xff\xfb\xd2D\x9e\x0c\xc4\xdd2F\x9b~\xc20\xa4\x06H\xc7o\xfdDR\xfc\xc5\x16om/B\x88\x98\xa2\xcd\xcfq\x10\x9f\xff\xfa\xd0\x01\xc8\x82)\x94\xe1\x96D\x10\x00\xca\xa8`2\x06&\x13@\xcec4\x0e\x06\x02`|\r\x0cc\x11\xdc\xef>\x0f\x1f\x83\x05\x10i0b\x06C\x15\xf1\x078p\x7f\xb3\x89\xd1y1\n\x0bcL\x9e?[\x93S\xcb03\x01QDZ@X\xb0+\xc8\x9dLB\xad\xf7\xdd?\x8b\xa71b:Bv\xd3`\xdaz\xa6\x10K\x0cQ\xd8\x9eF)\xf9\xdc\xb5\x8fn*\x8c\xc9\n\x08\x11\x1d`>\xaa3\xcc\x99\x8e\xe1)\x1a$\x96\xd2\xf0\x81X\xdb\x90>v\x9f\xad\xa5bT:\xd3\x96\xd0\xea\xe8\xff\xf7\x7f\xff\xff\xdc\x80\x0c\xb1\x16\xdb\x12\x88\x98\x00\x1e\n#\x8a\x03\x0cV;1\xe1l\xef\xc3c8\x91\x0c\xc8\xb60\xcf\xb4\x13\xe3r$\x0b\x82\xd9\x87\x10\x08\x18\x97\x84Y\xdd\x01\xb3\x9c\xcc\x86\xe9\x8d\x10*\x18\x90 c\xe4\xd9\x91\xe0aA\xb1\x81\xc0\xa9T\xd1\x9a\x19r\x9d\xf6\xad#\xc6\xea\xda\x1a\x01\xcbw)%\x1f\xc12\te)\x83\x03\xf4\x94S\xac\xccx\x15=\x95Lq\xbd\xa9\xba\xb3\x8e\xcd\xb8vgxR\xd2\xccQ\\\xa2\x8cV\xa7\x95K\xad\xda\xb1V\xa5^\xdf\xcf\x1b\xfd\xcf\xbc\xca\xce\xf0\xc3U\xa9R\xe5PE)\x90m\x1f\xfb\n\xf2O\xfe\xbae\xdb\xd3MLAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU \x00\xfa\x08\x1e\x12\xd8\x85\n i\x18\x80z0.\x81\xad1\x0c\x00\x960:@$0\x01\xc3\x120!\xe0\x893\xf4\xc4\x8801@\xd70\x01\x81\xc70\x14\x07\x14\n\xe1|`\xf2\x8a\xf0`M\x83R`}\x81\xe2ae\x03f`\xd4\x00.`p\x80\x02.\xb0\xc7\x8c3\x84H\x05\x81\x8e\xa7\xc4Q\xad\xa9\xf8\x92\xbb#/\x04\xb9\xb1\xf3!\xac\x1e-\xe8\xbf\x05\x1a>\x0e\xa6\xdf\xc2\x02%\xb8\x85\xd1IocgY\xbf\xcf\xd4\xbe\xfcr+Z\xcb\xb0\xf8[\xa6\xbf\x0b\xd6[\xe4\xba\xad\xda]\xd5\xf0h\xe1\xaa`\xd8.\xc7\xdb\xd8o\xd3\xfeg\x8a3\xad\xba\xf1\x7f\xfd\x94\xf5\x10\x00>\x00O\xd9R\x17\x91\x12\xa6)\x91\x86\x19X\xf9\xc8\t\x99\xf9@\x90\x81\x83\xf9\xa9\x9a\x15\x05\t\x80X\x17\x18\x0b\x82\xb1\x87h\x7f\x9auJ\xb9\xa4\x98v\x98{\x03\xb1\xbe(\x1cL\xc8\xf4\x98\xa1\xf2`\x98H0@sn\xa2\xa5\xfdNV\xa2\xedD\xfa\xdfJ\xe1\x13,\xfdP@\x16.?0\x1d\x8a\xb3O\x9d\xfaN\xe3j\xb6\xe8j\xda\x98\x8c\xcby\x12\xadv\xf6\xb0\x94\xdd\xcf+\xf5o\xf7\xea\xd3w>U\n\x14c\xda5\xce\xbd^\x8f\xfd\x00\n\xc9$\x97\xe8@\x01M\x91\x18\xc1\x869nL\x050A\x8cE`\x18\xcc\x0b\xff\xfb\xd2d\xa4\x0c\x05Q(\xc3\xb3\x1f\xd1P\x85E8\x86o\xdbD\x16\x0c\xa3\x0em\x7fEB"\x10\xe2]\xafi\x10P\x11\x0c\rP\xc1\x0c\x1d\x88`Lmad\x0c\x0e`6L\x1b\xb0\x0e\x0c1\xe0E\xcdg21M/\xc01L/\x106\xcc\x0b\xb0^L\x14\xb1\t\x8c\x06P\x86\x0c\x03`\x18@\x82\x84J_\xa7\xed\x9f,\xb8\x129\x10\x8e\n\x9d\x05\x02S\xbagx\xc7"#T\xda\xd0ILgx\xccZyd\x8f4\x9d\xb1\xfd\xc7\xba\xa3\x90\xd1\xcf\xbb\x11{\xd3t\xad\t\xf9\xbbZ\xac5\xdf\xe6v\xb0\xb5z\xed\xfaV!dgI`G\xb6\xa9\x05u\xbe\x8dV\xbc\xb7\xb3j6\xa2\xefM\xf2\xaat\xdd(w_\xa7\xa4\x00\x80+E$\x87D\x96B{3(\x06\r\x06d`\n\x19\n\xc91=\x8c[\x02\xbc\xcfx\x00L\x19\x00\\\x00\x07\xa6\x07\xa1`f\xa5:\xc6Q\xa1Pa\x08\x08\xa6_i\xe6\xf6\x7f\xa6\x8d\tu_\xb5b@4\x1c\xebS3\xe7\xe7\x97\x7f*\xb6\x96[\xa9vw\x8e\xb4\xf56\xab\xbc\xda\xc7Z\xff\xd5\x1c\x8aD\xfc\xc3\xb7\xa0\x98\n317P**\xb1@\xe1#\xa7N\xb2\x87\xee\x97\xb7K\x10\xb8\xf3\x15\xbd\xf6\xff\xc9\xa5Z\xa2\x9d/\x8f\xb5U\x97bU\x04[C\x14\x81\xcc\x1cL2\x10`\xc3d\xd3:\x9aL\x14\x9a:\x12\x10\xfc\x84\x93_\xaeE\x9d&\tj\x05&f`\x84\xc6\x12\x00\x1a\xe6\r\xc8/\xe6\x10(b&)\x02\xf4\xa6\x18H\x84f\x0fh\x08\xa6\xed\xbc\x9c\xf5^`Sq\xbd\x14\x85\x83\xd9\xaa\xd2f+#\x1a1\x18d I\x9d\x8f\xc4I\xd3 \x96L\x86\t0\xa0\xe0\xc6\x80\x83\x03\x06LJ\x17/q\x86\xc1\xe1Q\xe0\x8c\x0c\x1c\x00x\xd1\\\x1a2S\x05\xa8\xd5\x00\x80A\xa1\nU\xa5z\xf8A\xc7\xd5S\xb9\x8e\xdb\xf7\x10\x87/J\xe3yCq\xb9\x87\xf2R\xce\xe8\xda\xc4\x08\xfa?\x140\xfd\xf9D\xb3\x94\xf2\xcb\xb1\xbbP\xc4\xe4N\x1f\xb8\xff\xda\x8cX\xafO\x95%\x8b\x91\x8b\xd2\xb9|\xc4c\x18\xdd\xea{u)1\xa7\xa7\xd5=\xb9Db\xec?j1E(\x96]\x95\xf6\xa5\x8d\xd7\xb1v\x9f*K\xd2\xb9}\xca|\x83\x00\xf8\x80``>\x08\t\xc0c\x82!\xf25\x9f8\x18J\xbc\xbd\xee}]\xadG\xd0@\x00de\x0f\x8b\xfd\xa4\x85\x0b\x850\'\x01\xeb\x0c\xa81Q&\xb7q\x82\x00\xcd\x19\x97\x06\xa8\x00\x18\x0c"\xc0\xac\xc4\x90$\x8d\xa1\xdb0\xd5`6\x0c\'\xc3$\xde\xd9\xcc\xcb\xe0\x1b\x18\x01\x03*\x02\x01\x84\xd4\xc9\x91\xab\xd9k\xb7)\x8fQ\xdd\x83\xaf^\xf4\x9f\x87r\xce\xc3\x1d\xb1\x9dh\x0e\xe1Ct\xa4\x14Q\xb3n>\xf1Sn\x05\xd6\xc1[?z.\x8e\xf5Ms\x97\xd4\xe5T\xb2p\xc9\xad6\x0b\x1dZ\x94\xfdV\x7f\xb4\x80\x00\x17j\xd00\x0e\x05\xc3\x06p,0L\r\x93\x0f\xe0\xc3 \x07c\x0c\x90\xea0\xb9\x073\x15\xa1\xdd12\x08\x83\x18\xe3\x175^X\x13k\x85\xc93^\x1bs\x10\xa0\xcb0\xc3$\xc3+\xd360\x85\x10\x03\x1f\xd2\xc0=B|\xd9/Cn\xa4\x0c\x88\xf593\\\xc1\xcaCs\xb0\x0c\x8eU52\xcc\xc8 \xf39"\xc1L\x13$\x9b\x0c\xb6\x161\x014\xc9\xc20\xa8\xa0\xc5\xe1\x82\x10a\x88CBA\xe0@\xff\xfb\xd2d\xff\x84H\x1fIF\x13\x9f\xe2 ~\xe3\x08vk\xdbD\'\xc5Q\x1dOs\x0f\n\x8d\x8f!\x05\xbf\xe9\x10\x0c\xbd.\xec\xafK\x02\x84\xa6l\x95)\xaa\x9e\xc8,\xd5Pu\xac$)\x19Mt\x05y-K2\xae^\x80H\x91\xc4.ch\x88B|\xd8(\x87\x7f\t\x88\xcd\xd3h\x04I7\x15L\x0c RKE\x00\xab\xf5#KB\xb9\x0cfK A\xc3\x12#\x10\x19Kh\x04&N_\xd5anJ\x0c\xeb:,:.\xad\xac\x95y&\x13eEW!@[\xd6T\xcb\xa4\xadvv$\xedN:R\xe9\x97\xf6\x91\xfe\x91>\xb1\xa9\x98v\xa4j\xd5Z\\)e\xb5#W\xe33\xb2\xa9u\xc9vt\xb6kZ\xee9gK\xca\xd6\xae\xd2\xdc\xa5\xe55\xacl\xa28lXIR\xb0t\xdda\xb3F\x8d\x8b\x97\xfe\xb2\xc5\x17\x0ew\xf3\xfc\xe3f\x97_\xff\xac\xba\n\xa3<\xa2\x8d\xea\x1d\x15\x05\x08\x1cxI\xc9\x87\x863\x98\x8d\xb1\x80\xde"\xc1\x818\x01\xd9 \x0c\xe6\x02\x98\x1b\x06\x02\x90S\xe6 \xfa\xa2\xa6\x16 Ff\x00h\x11\x87[\xd1\xe5\xce|\xeb\x06\xb8M\x80\x08V\xb2^\x05-\x04\x00p\xe1t1\xe7\xd1~\xc48\xfc$\xac?f\xec\xe21gS)\x972\xf5M\xe5\xae\xe7\xacy{\xce\x9c\x0e\x08\x8b\xc2\xe5,\x00\xc3\x00b(:\xf0\x9c\xb3\xc5\xdfBY`\xe7\x80\x91y\x9b\xc0\xa6\x9aq\x8e\xdaFf\xb1JP#\xb9$X\x03:i\xa3\xda\xb2A0\xb3\x02c\xb5(k\xca$\xae\xfa\x96)H\xa2U \x00\x00\x05cE2!@*\x00\xa1 \xc0\x80\x18d\x0f0\x94\x15&\x05L9\t\x0c\x0b\t\x0cDC\x8c|\xcf\x0f\xa3eL\xa1\x04L=\x12\xccc\x00\x0c\t+MN\x10\x8cn\x1a\x01\x8d\x8cE#\x0e\x80\xce\x02\x00\x06\x01\x11.`\x8c\x18\x08\x98\x18\xc2\xc0\xb3r\xe4J\x0b\xe8\x94\x10\xd3j\xb1%0S\xa9\x9c\xa1\x8e\xd7\xbf\xd7^v\x8a\xf4\x8e\'(\xaf\x1dq\xe9$W\xabRv\xb4?\x1cg\x14\xf7\xf3\xc3\xb3{\xd6X\xd7\xcfv9\xfa\xe6\xb0\xe7\xfew\xb3\xb1\xaa\xf9C\x91w\xd3\xa7\xfe\x8f\xa3\x7f[\x18\x9a\x19\xfd\x1e\x86\x1b\x8c\x00]\x15t\x9f\x0c\xfc\xc04\x05\xcbn\xe4\x18\x14\x809\x80\x00\x08\x18Y\x06\xd1\x88\xa8\x8c\x1a\x07\x92\xb9\x90\x18\xaa\x8a\x03\xf1\x80\xe0g\x1bP\x14\xf9\xa7\xd9\x05\x98\xa1\x81y\xc3\xa9\x9a\xeb\x99\xa0\x1f\x9a\x8ai\x95\x9b\x8f\x0e\x18\tQ\x96\t\x18\tz\x06\x98p\x90@C\xc2\x01\t2\x90\xd2\x80\x82"!\xa2\t\x98\x05\x83\xd7\xc2.\xce]\tb\xe6qY\xca\xd7\xa1r\xe3lM\xc8\x94F\xe1\x88s}\xdc\xae\xdc\xc63v\xa0\xc7\x86$\xc3\x1bN7\x06\x99\x9eR\x8b6-T\xb31b\xae\x12\x8d\xe1\xcc\xb1\xb5cak\xba\xbb\xf8\x11\x9f\xb5\x7f\xf6\xfa3\xdd\x1e\xc5k\x88\x00\x00\x00\x04\xc3\xae\xe4\xa4\x05\x00@\x00\x00\x80\xe40\xa0\tq r0F\x02c\x19\x11\x9d0\xb1\x1d\x81\xa0\x181\x04\x15#\x000\x8f2/\t\xc38B\xc6:\t\x80\x93\x12\xb0d0n\x13\x93\x01\xa0\x011\xbf\x02\x9340\xf31\x18\x0f@0\x16\x80C\x00 $\x80\xc0>\x00\xc8\x04\x80 \x06+\x88\xe6\xa0d-\x8d\xe6\x06\x01`\t\xa0`\x00\x80D\x1b\xa0\x12\x02\xa0\x18\x07\xe0%\xff\xfb\xd0d\xdd\x00\x04\xe4.\xc5\xd5w@\x00\xa9\x86\x08\x83\xafl\x00-\x06)\x1d\xb9\xeb\x80\x05\x1a;\xa0\xdb?\xe0\x00\x81\x80v\x00X\x18p\xa0P\x81\x83\x92\x06\x88\x18\t\x80n\x01\x80T\x00\xe8\x06\x00\x08)\x85\xd00\x08\x80&\x03\x00\xa0\x00\x00p\x03 \xe0\x03\xc0\xc10\x00\x10\x0c\x0b \x05@\xc0m\x00L\x0c\x06\x80\x19\x04v\x16\x96\xa0\xc1\x04\xa0\x18\x03\xa0\x04\x800\x00\x00\n\x00\x08\x0c\x002\x1ep\x17\x01X\x0c\x03\x00\t\xc0\xc0K\x00|\x1bL\x0c\x00\x00\x04\x1c\xb4\x89q\x89\xe1(\x08\xf0B\xe5a\x9b4\x00P\x08@\xc0H\x00D\x0c\x03\x90\x01\xc0\xc0&\x00\x80\x0c\x00P\x05\x00\x00\x00\xf4\xedVf\xa4\x8b\x8dL-,\x06\x00\x0b\x00\x80\x00\x85t-\xe4;`\xdd\x8df\xab\xa6\xdd\x9b\x12\xc1H\x89\xccd\xc5h:\xc4\xea-\xe2\xc8\xff\xee\xde\xdb\xc8q\r$\xc8\x99\x00:DJ\xe4\x10\xb0L\xff\xff\xff\xfeO\x97\xc9\x83\xa4\xe9>\\/\x17I\xf2\xf9@\xf1\xe2\xff\xff\xff\xff\xff\xff\xff\xf9\x81x\xf1|\xc5#D\x0c\xdc\xf9\xa2f\xa6\xe8\x00\x00L\x00\x00\x00\x00!\x01\x98\xc0$\x02@B\x01I\x80\xe2\ra\x80$\x00x`#\xa6\x1d\xe01\x866A\xcc\x06\x03\xe8=\xa6D\xb8\x93\x06\x14X&\x06\x19\xe1\xb3\xa0c`\xcd\x9d\xd0U\x8cE\x02k\xcc\x0cB\xbf\x0c\x15!m\xcd\x00 *\xcc\x8d\x10\x00\xc4\xe0:L\xbb\xc6\xfc\xc98<\xccT\xc4\xdc\xc34S\xc0\x80\x8aa\\\x1dF\x19!\x0cb\xa0\x0cA\x00\xec`^\x00\xc6\r\xa1nap\x06\x86\x05\xe0\x86\x16\x05\x00p;\xc5Q\xe0\xc1 \x01A\xa0L\x91\xc0`\x02\x1a\x07\xb3\x00`)Z)\x94\x81\xc3 \x1c\xb4\xcbR\xdd\x05@$\xc0\xac\x05\x929XY\xf2H\xb5\xc4\xe8iwb\xcd&\x1b\x94\xba\x90\xecR2\xe4+\xa9\x1eP\xf5;8\x7fb\x13\x13\x99M\xc6\xa7\xf0\xbb\x19\xb3\x04\xc1\x95\'-}\x1c3;R\xf63SY\xd0\xe7V\xc6V\xb7nSV\x97\xe9\xf0\xbdv\xb5\xcc\'\xf7\xcc.\xf7Yw\xbf[\xbb\xe6\xabo\x97\xf9\xbb\xb5\xf5\x85Z\xb6\x7f:\xbb\xff\xfd\x7fr\xee\xabs>\xffq\xfd\xf7{\xfeo\\\xe6yg\x8e}\xe6\x1f\xf5u\xdf\xc7\x9f\x97q\xeez\xfc\xbb\x87-\xef\xfbwY\xf7\x1e\xf3\xff\xff\xff\xff\xff\xff\xb9\xe1\xccn\n,\xa8@\xff\xe2\xa1\xa7\x8a\x8d,\x17B\x85\x00\x00\x00\x03\x08\x80.S\x06\x00\x1f\xf3\x05\xa8\x13\xf3\x00\x94\x07\x13\x040\x0e\xf3\x04\x88\x04\x93\x008\xa8C\x99L}C\x0f\t\x10c\x8b\xe4_C\ta\x81cwL,s\x06L\x1c\xb3\x17\x18=3\r\x80\x0f\xe3\x05\xbc\x08\xf3\x0bx\x1b\xf3\x04D\x06s\x16Y\xa6\xf3A\xe9\'c\x1c\x88?s\xc6`&\xe3\x00\xf1\x82\xc3Z\xa9\x07\xd3\x02\xa0VS\x01p\x16\xd3\x05\x80\x0c\xf3\x15\xe0\x13\xc1 ,\x8c\x04\xb0\x05\x8c/\xc0\xb3\x83\x80\x12\x10\x00`2\x05\xd2]\x18\x14\xe0\x00\x18\x03`\x16\x01\x00\x19\x00\x00B`.\x00t\x82\xa6\x00X\x00\x81`\x03\x0c\x08\x00\x0cS`t\x01C\x01\x04\x02\xa3\x01\\\x06"\x80\x03\x8b\xb0\xdb\xba\x06\x02@\x07\xe0@\x00o)C]0!\xc0,\x02\x80\x18\xf2\x02\x80\n0\x00\xc0\x05I\xd4\xcd\x86\x1f\xa8p\xb2\x90\xdd\xcf\xb32D\x00\x14\xff\xfb\xd2dr\x00\n\xefmC\x96\x7f\xe0\x00\xc2\xe5\xe8\x99\xcfl\x00\x1b|\xef\x16}\xff\x80\x01\xd9\x16\xa5+\xb9\xa0\x00\x0bb\xdd\xb4&\xabkQ\\\xd1*\x17\x8b\x95\xaa\xde\xb3\xaf\xed\xdb\x14\xbb\xcbq\xe7\x19\xb8\xc33\x91\xa9U\r&<\xe6\xff?\xe7w\x8ey~Z\xe6\xabO>\xb1\x1a(k*\xf3U\xa5\xd9\xfe\xbfy\x7f\xf3\x9f\x9f\x7f\xf5\xcf\xfe\xff"37\xa5U\xae\xf3\xf2\x94\xd5\xb3*\xad\x9e_\xf9~\xbb\xcf\xfe\xfe\x7f\xbd\x7f\xf7\x9a\xfe\xff\xeb}\xff\xc7\x1a\xd9\xe3\x8c\xd5kT\xb5p\xadpK\xff]\x86\x9b\xfb\x83\xc8[\x9c\x00\x00\x00\x05l\x00\x00\x00\x00^C\x01\x90#Xc\x05\x80\x0c\x19\x00\xa3\x01\xe0"0\x08\x00#)b\xb0\x03\x08!\x8e\x8al\x18W\x85\xc9\x97J\x87\x98\xd1\x95\xf1\x93\xa1"\x98\x85\x141\x97(\x8b\x18\xa6\x04\xc1\x85\x18\xa0\x05F\x0e]\x0c\xe7=\x8c4\xb8\xd1\x8c\x8d%\xdc\xc9HB\x03\xd51\x87\x91\x1a8\xd0\x18-/L\x9c\x91\'\x0c\x04P`\t`\x82\x00L\x1c4\xc6\xc1\x92\xb1f\x90\x18\x18\xa8ka^\xeeT1AS\x07\x99S\xbc\xb0\xe5\xe7\xe2]\x0cR\xe7\xaeT\xb3c\x0b5\xf3\xa5\x9d\xc2\xbd\x98\xa66\xff\xf9\xdc9\x8e\xf1\xfcq\xdf>\xdf\t\x05Mv\x88Er\x08-!j/\xd5\xb7\xbd?\xb1\xba\xe8\xb7\xa1\x9f\xff\xfd\xaf\xd6\xdf\xe7X\xbe`\x00\xe4d\xa3\x01 \x00s\x00(\x01C\x00\x10\x01\x83\x03H\nS\x00\xb8\x03\xa1\xa0 \xcc\x08pW\x8c\x1b\x90p\x0c\x18\xb47\x8c_\x01\xda\x0c2\xd0)\xcc\x0f\x100\x0c\x050\x1eL\x04\xe0\x19L\x05\xe0\x0fL\x14\xa0\x16L\x10\xd0D\n\xc0\xe1\x02\x01\xe4a\x1e\x85\\aA\x87\x90h#\xa1\xd4c\xe8\x01\xd6`^\x81\x0c`-\x80\xe8`T\x80&2\x00\xd8\x04\x02#\x00\xb0\x00D\r\x14\x00\x1e,`\x00\x00\x08\xc9\xd3=\x82\xb4\xead\xaa\x00\x80\x94P\x01,\xb6\xd6t\xd1\t\xba\x94\x12h\x05t\x81\x80\\\x98\xe4\xdc3;\x19\x95\xc6\xa5\x91GDd\x01\xb7._\x17\x833\xbdGj\xff_I\x9c\xf7\x10\x96wTq\xba\xf1\xbc%\x95\xabc_\xbb\xa7\xd6\xecS\xf6\xe6]\xa9\x8dls\xef\xfeu?\x0e\xf6\xddf\xf4\x7f\xeb\xff\xff\x7f\xabA\xc0\x00\x00\x0b\xb5\x00i\xb8\x05\x80\x05\xd9Vf\x00\x0e\x0c\t\t\x0c\x0485\xe8\xa4\x19\t\x02\x8a\x94\xa9\x7f\x90\x03\x0c\x06?00d\x1a\x02^\x06p\xa9\xb1*}\x04\x9aRf(0\xf2\x85\xe0\xc6`v\x1c\xd1U\x1b\xc17\x84\xb6\x86\xf5L\xb0\xfc\xb7s;<\xde\x1b\xb7\x979\xf9^\xd6\xeb\xdc\xe6Y\xe1s\x0b\x97&kn\xed6\xfb\x95\\\xf7\xf5\xec\xf3\xbf\xadY\xba(\xb0\x10J\x19\xea\xda+\x03\xf4\x03\x02\x90\x04\x82\xe1S\xf9\xd7\xc1\xa6S%\x05\x0cFgj\x9a\xc2da\xe4\xa2\x1cp\xad\x0bxa\xb5\x05b`\xdb\x81\x8c`\x0b\x80\xee`G\x80,`\x17\x00\xce`\x8b\x86\xc0`P\x81\x84`\'\x80\x1c`/\x02*`\x00\x03X`\xc1\x88\xf6e\xb5QV`7\x06\xc6`B\x824`>\x81.`%\x00<\x0c\xaefh\x83\xc6\x06\x13B\xe0sd\xa9B\xe4\xf0[mi\xad\xbe\x864\xb0\xf9\x87=\xfe\x8d\xc6oL8\xb9\xc2eh\xbcd\xd4\xc3U\x06\x85,\xe76\x1b\xa8\xce\xff\xfb\xd2dH\x84F[/\xc4\x13\x9f\xd1\xd0v\xa6\x19\ng\xa6>\x16h\xcd\x1f\xad\xfb\x87\x01\xd8\x16\xa45\xce\xa5\xd8\xd9\xece\x89\x16\xb4\xa1\x13]|$q\xb8n??\x97\xe5\xf6\xf7\xc7\xfa\x95\xf5\xb979\xde\xcb\xe5\xbc\x95g\x7f`\x88\x08\x90U\xe1Qap\xf9\x92\x02\xa9\x01\xea\xd1M\xbb\xbb\xff\xfe\x9f\xfe\xfd@!\x00\x00\r\xac\x01y\xe8a\xab\x88\x14\x9b\x153\t:\x9b1\xc1\x1a5\xb4\x1a ?\xccF\x03\x16h\xd0F:\x1a \x14\xc3\x10\x1c\xc3\x10P\xc1\xf0\x18H\x1e0X83J\xfa\x08p\x0c+\t\xc0A\t\x81A+\xf6\x18\x01\xa5\xf4)\x8f\xb9\xad\xfc5\rOU\xbb\x87\xe7\xf9\xa4\x0b\x05g=?\xf6\xb5\xdd\xb4\xdf\xfb\xc8\x04\x98\x06<iseW@\xf6\xa5\x12.g[7d\xb2SDz\xad\x02\x00\x08W\xeb$w\xd4hT\\\xd7\x93\x8c\x8c\xe4\xb0lb&\xe6\xcd\xacc\xfa=\xe7\xd0B\xbaa\xc4\x0cf\x03`RP\r\xa3@<`\x14\x02f\x07 \xe2`\x1c\x08f\x01\xa0\x18`\x0e\x00F\x02@\xbaa.5\x86\x9b\xdd\xccw\x96\x01\x8a\x87&\x19\x0f\x18`.\x06\x01\x16\xf9\x84\t\x02V\xea\xe2\x8aK\x9a\xc5\x8c\xe5\xb1\x11\x18\\x\x13\x7f\x99\xe5K\xdb2\x99e"\xf31H\x19\xfb\xa7j\x10%i\x9a\x1b\x19\xeb\x11@\xd2\x92\x8f\xd0\xc4\xa53\xb2,,P\xd0V\x96\xde\xe5\xfa\x18\x8eX\xf7\xf3\xab[\x96q\xfc\xb3\xff\xd7*\xde\x8a!\xc2\xe1)\xf0\xf3\x99\xf7\xce\xba\xbf\xa6\xfa\xb4\xff\xa1\xde\xaa\x85\xa0\x00\x0c\xfa\x00%UA\xa33B\x07\x04@F\x18\n\x13\x02\x85FG\x88\x1eA\xb0e&\xc8\xb0\x84\xc2 \xd5lK H\xe8H\x94\xac\n\x1a`@\x04``\xa6k\x9dFh`\xa2\xc4\x8c \x02YZW"L\xf3\xd9r\x82\x11&y\xabn^Q\xfb\x1a!c1\xf4UO\xcc\xce\xbe,\x9c\xd3R\x95\x1a\x15\x06\xdepj,\xb3\xd7 9\xb1]\t\xd8\xad\xabP$tiG\xa2f\xda\xd5\x08\x00\x01!\x84\x80\t\x82cQ\x9bJ\xe9\x81"i\x96\xc3a\x99)\x99\xb8\x1dA\x8aF\xf19\xc5`V\x99\x80\xdc\x08A\x80\xca\x07\x19\x80\xd6\x01I\x80F\x01a\x80\xbe\x08\xa1\x82h\x03\xa1\x82\xca\x03q\x81|\x01Y\x81p\x04\xe9\x82\xf2\n\xc1\x85,$\x99\xcb;$I\x91d\x16\xb9\x83\xf6\x03a\x82 \x06\x19\x80\xbe\x00\x99\x8a\x1f\x03\xb8L d\xc4\xc4\n\x08\xc3\x83Y\x82\xc5+\nl2u\xb4\xa3\xa3\x1b\xa6\n\n\xf4F\xde\x88v\xab\x83I \x8c\xed\x07N0AZ \x89l\xa6\x9a\xd6\xa3\x95\xaf\xd4\x15\x14N\x0by\xd2\xd0\xc1\x94\x1c\xa3\xad\xab\xd8]\xb5O\xaa\xa2\xe2&\r\xc2a \xd8\xe5?Y\xa4\x1a\xfc\xf1U\xd6\xb7\xfbV\xf9\x8d]IW\xfe\xd1\xca\xa3cp\xcc\xe7\xe9.4\x18\x00\x00\x00\x00\xbe0\x03XFq\x10\'\xb0b8\x01\xc5\x94Bo\x02a\xb9\xa8{0Ha\xb1.c\x00LP\x03+\xe2@\x84\xc2\xb08Hf\x8a\x88\xc0!\xa0\x8c\xc2p(\xe5@\xb0\xc6\xb0\x9c\xc3\xe0\\0:\xa8\x8c\xab\xa1=\xdd\x1b\x80>\x04I\\\xd1\xcc\x05\xf2\xe3-\x9d\xeca\x18\x04s\x1a|\xc9\xb2\x96I\x00<-\xc0*#\xe4f\xcd+6\xd4\xd5Xo\xa8\x0f\x14R+L(@\x06\xc6\xff\xfb\xd2d\xa2\x84\x06f)\xc2\x8b\xbf\xd9\xd4u%(\xedg\xa9<\x16\xbc\xa9\x14\xee\x7f\'A\xca\x94#\xf5\xde%<\x9a@ \x8c8`P\xb9\xc3\xc9F# \x98@LdR\t\x9e\xa5\x06\x08\nefDh\xc9&\r\x08-F\x03\xf0\x12f\x03\xc8\x04\xc6\x00`\x08&\x00H\x12\xa6\x01\xb8\x1d\x00`\x05\xcc\x02p\x01\x01\xc0;\x18\x18@\x1a\x986 *\x9a\xc1\x81\xf7\x98\xc8\xe0\x1a\x86\x04\xe8`>\x80\x0c\x18\x02A\xa7Y\xee\xb8\xe2\r)^\xbc\xb2\xd5\xa8\xd0(;\x946aV6\xdc\x83\\\xbbn\xa6\xa9u6J1\x9b\\{\x02\x87\x97\xf4\xb5\xce\x8e\xc4\x1e\x08\xeb\xeac\x92R\x0cZ\xac\xf5\xa7\xa6\xee\x19v\xc7s\xcf\xf3\xe6\xef\x08\x02F\x1d"\xae\x93\x8b\xf2\xfeZxS\xad\xec\xf7\xd7\xd9f\xda\xfcf\x84"\xcf\xa8\n\x00\xc0\x00p\xb5\x80\x05f2\xe0\x8d\x04\xe3\xa0\xb9\x80@\x90T\x0b\x0e\x00\x0cI.Nx\x1aL\x12+\x07-\x0cT\x10\x14\t\x18P60\x1b0\xc8\x19\xe3O\xa4)0\xa1\x10\xeb\xbc\x83\x0c\x0c\x0c*\x0b\x88\xbe*\xb5\xd8y(d\xcd\xd2~\xac\xd6\xfa\xe0<"\x805kk\xb1\xe8\xe4\tn\xfbU \xdf\xe6\x8b\xc6q\xd4IY\x19\x83[k\xdc<U\xb9n\xb4Y\x97\x0eRb\xeaLAME3.100\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\x00/Y \xc0h\x01\xd8\xc0v\x01H\x94\x0eS\x01\x84\x16S\x05<\x08\xd3\x038\x1e\x83\x0bx+ \xa8k\xa6#\xda\x90&\xad\xe8\xa2F\x1f\xf0\x8f\x86\x1d\x00A\xc6\x0182f\x12HH\xe6\x0e\x98\rf\x06 )\x06\x11\xb0C\xc6\n0\x0bF\x0f\x80qF\x1f N\x86\x01\xc8l&\xbc*\xeb\xc6\x1b\xa0 &!\x18\x85f\x14x\x0f\xe6\x08\xc06\xc6\x0e %\xc6\x00\xf8\x1d\x86\x08\x00\x1bF\x03P\x07\xe6\x04\xa8\x10\xa0rF\xea\x00\xd3\xd3B\x84\x04\x18\xd1\x9b\x02\x864J\r\x11\xe3\xce\xa4 \xd1\x9eT\x10\xf0\xc3\x954\x01\x86D\x98\xf1*d`\x00-\xc4\xab5+\x0b\xf0\x96\x80&\x02\xa2\xcc\x98\xb1PF@r\x14\x98q\xa2A\xc2\xe0A&\xc0@\x10\xa0\x12\x8c\x15\x0c\xc2\x10+\x1cg\xd1\x83\x9a\x9a\x96\xe1\x95\xcc\xe3\xc3xX\xc2\xb17\xebA\xa6\r\xb2\xe1!F\x100\xf0B\xff\xac\xf6A\x00\xa9\xba\xf8.:\xda0\x00\x15\xc9\x81\x0e\x84a@A\x02\x1e54\x8c\xb5\xf9\xe8\xc67\xe1\x89\x03\xe8\xea:lN$\xbb!,\xad\xd7\x80\xdd\xf3\x90\xfe\x1c\x9c\x83\xac\x10 \xb0\x1d\x00\x131\x07\xde\xfablAB\xc9\x98BHE\xdf\xed\x18d\x16OH zy\xbf\xfa8>\x026\x8f\xb7\xcf\x9aB#\xc05\xdb\xf2\xc2+\xc1\xce\xff\xb7\x91|\x93\x90\x00\x81\x8c\xa4\xa3M\x88\xbe\xe0F\x87\x074\xd4\x00\xa2q b=\xa6j\x01\xd6U\x02\x0cR\x15@\x80\x12\x9c\x18.\x08\x188\x0f\x18\n\x03\xa1\x01\x10@^\xa1QT\xcfm\x8c\x10\x06\x96\x01dfH\xa7\xe1Xdl\xf9\xc9o_I\xe8\xad\xce\xa0p$\x83(\xd5%$\xb4l\xb63\x1d\xcb\xb6\xfdrmGY\x8d\x8cZ\x95\x0c\x9ay@\xa7c?\xf5\xbb\xff\xeb\xfa\xffC\x84\x00K\xae\xc9\x01\x89\x87\x18\x88\xd1\x91\x92\t\x1d\x98\x80\xa9\x8c\x06\x85P\x8d|\xff\xfb\xd2d\xee\x84J\xa9U\xc4\x9b\xfa5bo\x84\x88\xb7g\xad>\x15\xa1\t/\xad\xe8\xcd\xea.\x91\xe2\xa9\xae\xec\xe0p\xdb8\xcc\xbaD\xe4\x11\xc0&FRD<.a\x84f\x888\x14\xf1\xafl\x10\xe4\xdd\xf6;`\xcf"p\x06c\xc6p\xcc%2\xc0HA \x05\xa4(4\x0e\x97\xaf+\xb5>\xfe\xcd\xb5\x98\xc3\x0e\xa7e2\x17\xd9\xde\x83\x18\x94m\xdd\xa2\x86\xa7\x9f\xd9%\x13\xec\xe3Al\xe6P\xd6\xa4n\x0cZ\x19\x87h\x12|\xab;H\xa2pQd`\x14i\xc9>S\xa2Y\x18\x01,\x14iAPKg<\xb5a\xc9\x16F\ti\xb4\xf3\x9f\xfe\xf5\xb3,\x96(\\7\xe6\x8b\x92RC\x06\xfb\xb2DTPQp33e\x13/Xt0;PL\xd1\x83\\\xb0\xc8&\x0b\xd5\x10\xde\xa7\x89\xa7\xa6O\x87\xe6\r\x05F\x02\x83 PU`\x02\xa08p\xa00\n\x07\r\xe6\x01\x07&\x1d\x8c&fp\xc7f\x04d\xe7\xa6\x06\x19F\xa1\xa8\xde\xe14\xe9\xe5p\xec,\xc5\xc1O\x01PR\'\xe4\x83)\xb7~.\xfeC\x97\xa9\xae\xe5pHV1\x1bgs\xf3\x97%u\xe3\xf0<\xa9r:\xfa\xb9\xac.\xa4\xb9\xf0|\xf8\xa0`. \x9dK\xcf\xfe\xdd\n\xaae\xfa\xde\xaf\xe9\xff\xff\xfa\xaa\x18\x03\x8as\x02@\x11\xc1\r#\xcc\x10\x15\x8c\x96\'L\x04/\x0c\xc8\t\xcdB\x90L\xe4\xf5\x07\xb1\x93\n\x0e\xc3"\x8ac\'\x803\t\x85#\x05\xce\x83\x11\x81\xf3\x1dDC\x01 \xa70\'\x0c\xd3\x0f\xd0\xc92MSS\x16P[1\x04\x02\xb3\x03\xb0\xcf0O\x05\xf3\x04 R\x00\x01\xb1\x81\xe8\x19\xdf\x1e\x01\x89y\x7f\x11\xcd\x0e\x8e\xa2`\xb3 \xb0\x00\n\x00\x19X\x05\x17\xc1\x9d\xb78\x16R\xd6\xa1\xb7N\x06\xeb\xe0\x92v\xe2\x8aB\x9er@\xfb\xb2\xe8b\x04r\xd6\x01\x93n\xcd\xcd\xe1c\x1c&\xe5\xd0u\xbb\xae\xe4\xcc\xb3\x9a\xbd\xff\xff\xacu\x87\xfe\xf5\xaek\r\xff\xf3\xf0\xd7\xff?u\x9c]\x97U\xff\xeb\xde\xf4\xd9w\xd4\x7f\xb3/\\f\xba\xa7JO\xe8\xda\xfd\x15\x10\x06\x15d\x00\x0b\x9e`\x02\x00f\x02\xe0\x1c`\xae\x06\x06\x04\xe0\x90\x01\x06\xc3\t\xc0\xe80\x8e\x02\xe3\x17\xc1i5\x13\x1c#\x13Pv0g\x0b\x13\t \x8e\x06\x00i\x85\x98#\x18O\x06\xc9\x82x0\x983\x80\xd8\x91jh\xfaTl\xa3\x1au\xed\x00|\xb1\x18\x15E\x8dX\x12\x0cv \x01"\xc0\x90TL\x06\x98H#\x01\x01\xf3\x03B\xc6z\xb8\xcc\t\x00\xc0  8\x17hm\xcd\x93\xb3U\x86M\x17\x91\x8f\x93\x01\xef\xdc\xb1W\xc9\x1a\\)\x04\xd4\xd1EQ.\xf3\xe4\x82\xa5\xabP\xc5\xca\xca\x17\xb0\xc8\x10\xad\xef\x9d|\xe8e\x12\xa9$f\x04\x8b\xcf\xc9\x9f\xb9\xbc\xebo\xf7\xfa\xd7\xe1\xdf\xc7\x9d\xee5\x1c-ee\x18K\xeb\xa4\xe3\xbd\x9d\xd4\xf7\xdd\xf7f/\xfe\x8c\xed\xbd\x0e\xe8\xf2\x80\x00\x18\x04\x00\x00\x00\x18\x08 g\x88B\xbe0\xa9\x81\x811\x15\xc2\x140<\xc2(02\xc150\x9b\x82\xc80\x88\x02)1\x9aLE1\xd4\x97\xc12l\x85\x1d3\xb1\xb1P0\x14A\xdc0\xdc\x81z6\xa1AL3:\x00\x942,\xc4\xfa0\xda\xd1\xf30\x14\x04\x8f0\xf7\x04<:k\x93v1\xa9\xc5\xdd;\x97\xcd%0uAV0\x9f\x80\xb00\xff\xfb\xd2d\xff\x80\x0699B\x8dw\xc0\x04\xcdF(g\xaft\x008\xc9\xf1\x0c\xd9\xff\x80\x03Y\x98\xe1\xe3;\xe0\x00s\x00\xca0$\xc0\xb51\x8c\x80E0\xd3\x83\xa10 \x81\xa40\x1e\x00\xa00\x16\xc0\\0\x0f@%(\x02l\xc0i\x00\xdcT\x01\x80\xc0\x06\x0c\x1b\xf0\x17\xcc\r\x104\x8c\x06\xf0\rL\t\xd05\xc6\x80\xe5$\x00|\xc04\x00\xd4\xc0\x81\x00D\xc0\x1c\x00\x90\x88\x02Q \x06\xd2T\x0c\x009\x80\xde\x02\xb1\x81\x14\x04(\\\x04#\x000\x00\xb3\x00@\x01\x06Z`\x06\x81\x08\x8d\x8c8\xc0\x03\x00\x1d\x11\xc0@\x19\x92\x00\x00\x1c\x00\x00\x18\x00E\xf8`\x18\x80\x9c`\x03\x80\x98`4\x808`\x18\x00\x96\x0c\x00\x0c\xc0\x12\x00vI\x1a\xbd1z\x8a.\xc5S\x1d\xefG6\xe8\xcb\x0bX`\x04\x002\x08\x00\x10h\x01\xa0H\x00\x85\xf2$\x00\x16=\xae\xcc\xe3\xaa\x15\xd8\xf9C\xf6\\\xb9\x1a\xd7z\x1dD~\x04\x00\n\x80\x84\x12\xbb\t\x8c\xa2\xc8T\x84\xdb<\xadZ\xbf\xeb\xfd\xaeQS\xce\xbf\xf4n\xfc\xc4Q\xdc\xb3>\xb0\xadq\x1eYB\xfe\\\xcd9|\xc5\x96\x17\xf1\xd6]\xc7\xf9W{\x9f\xdc\xbe\xfc?(\x9c\x87*\xdb\xafoW\xe5\r!\xac\xc1\x0e\xb3rs\x99L\xcb\x92\xf0;/\x13\xf6\xe1K\xffZ\xe7w\xcf\xfd~Y\xe3\xf6"\x97m\xcb\xf2\xbdr\xc6\xefW\xec\xbf\x0e\x7f\xff\xff\xff\xff\xff\xbf\xb1\xd7\xe6\x02\xc1\xfe\x89\xbe\xd0lR\x19\xa4\x8bD\xa4\xf0\xcf\xf4\x160\xa4\xb4\x98\x00\x00\x02\x18@\x00\x02 \xb4\xc4\xd0\xec`50hz\x19\x0bL4\x00\x0c\x83.\x8f\x011L\xbeP\x0c\xedY\x8cM}\r\xec\n\x8c2$\xcc\xfaF\x0c\x16 \x8c\x055\x0c^!\xcc\x83\x18\x02\xa3\xf0gDF&%\xe0to\xfaSf\x13\t\x86l\xceP\x063\x80\xae`4\x04\xe0P\x020Y\x0cC\x03p*\x08\x00ph$\x98\x1b\x81ik\xc4\x80\t\xe4\x08\nP@\t\xa4%:\x11\xb0\xf92\xb1\xa1R\xc11t6\x87\xb0qV\x12Q$\x8b\xf1\x95\xdcv\xecNA\xf1|s\xdfa\xd8\xad\xef\xc2\xbd\x98\xb7;ct\xdf\x87u\x9d\x9d\xe3\xce\xeb\xfb\x8f;\x97>\xdaR\x1e\xb1E\x88\xbc\xea\xcd\xd4+.\xb1\xf7hX\xe5Z\x83\xac\xa5\xcb_dQ{\x1eb\xf4\xb5\x83\xd4\xe6 .\xcf\xab\xcb\xb9,\xff\xee\x16\x008\x89$\xc0c\x00\xd8\xc0C\x00\xa8\xc0\x85\x058\xc0r\x00\x0c\xc0?\x00@\xc0\xaf\x03\x18\xc1\x19\x02\x80\xc3\xbf\x06\x80\xc2\xcd\x00\xc0\xc4\xad\x1aH\xc6%wh\xd4&$4\xc6\x8c\r\xdc\xc1R\x04\x0c\xc0\x86\x03d\xc1\x02\x04<\xc2p\x10<\xc0\x98\x04\x98\xc5\n\x15\xe4\xe3\x9eR\x88\xc4\xb9\x12\xf8\xc2=\x07<\xc0z\x03\x94\xc0\x82\x01\xdc\x04\x05\xa1\x80T\x02i\x80\x1e\x00!\x80\x10\x00\n\x1d\x19\x823%\xab\xb2<\x03\x0b\x04V\x85\x1cx\x1eg\xf2"\x04\x01\xc1#\x99\xb3\xb3\x07?5\x1b\x02\x04\xc2\x00\x91W,\xd6\xfe\xa2\x11a\x10\x01\xa0\x90\x06\x964.]\x15\x93\xcb\xe0\xd9\xfe\xd5\xb7,}\xdd^\xd6\x81\xa3v\xaaO\xd3\xf7\xb9\xe1\xf5>\xefjx\x18*)\x1cdr\x16\xb2\xed%\xea\xbfF\xca\xf9jS\xd9T\xa7\xbd\\\x9f\xb7\xfd@F\x00\x00\x04\x14\xf8\x00*\xddf3\x81QA\x80\x80R\xb9\x88\xff\xfb\xd2dw\x0cF\xd3.D\x1f\x7f\xe0\x00x\x85\x89\x1d\xed\xf0\x00XX\xc9\x14n\xffh\xc1\xc7\x96$\xb5\xbe1\xd8\x8c\x1a\n\xb9\xbaG\x99\x80)\x9d\x16\x19\xa00\xb0\x00\x18a\xa2\x82\x03\x00L&0\x1e\x0f!\x0clI7$\xa4@\x121x%\x14Ta[Y\xec\x95k\xc2\x98\x84"fUS{\xb1-\xde\x16\xeb\xdf\xa7\xb3V\x7f\x0b\x17kPs\x1d\xd8\xbb\x85\xcbyr\xad\xeeOK>\x92\x92W7/\xee\x19\xd0Q\xdc\xe6\x18\xeb\x97\xee\x97\xef0 @U\xa0\x90T\x1a0`\x151\xc570@\x1f0\x94\x0f1\x8831\xa4\x1c<Dh2\x89\x837}\x070^\x96\xf40\xe3CW0+\x81\x020\x19@%0\x01\xc0\x900\x0e\x80\xa90\xa7\xc2\xaa0VA80\x81C\x005\x96T?0\x99\xc0`0t\x01.>rs`I3PP!h\x18\xf0\x90L\xc3\x80R\x05X\xdb\xd3\x00\x12G\x16\x0e\xde?1\x18\x01\x9d8f6\x9e\xf2R\xc1\xd1\xa9\xe7\xeeX\x17\x19&U\xadO\x9c\xe5\x1e\xdf\x82cYnu\xa9e\x92\xaajfX\xfe@\xf18\x8cSq\xdb\x14\x1d\xa5v\xa1\xfa{\x16)\xacW\xfa\x96;O\x97\x7f=\xe7v\xab\x1cXp\n(\xf2\x07\xbf\x8c\xdf\xdd\x15\xedG\xf4n\xd1\x7fP\x10\x00\xc2\x9a\xc0\x05xqS\xc3f\x1a\x12\n\n\x0c\x19\x01\x01\x99uhc\xb1W\xb0\xee\xde\xcd \\ |\xcb\xc6\x8c@8p\xfc\xd5\xc0L$\xa4=\xc3t\xcd$c"\xa3\n\x0e\xa4 \xe2\xf9\xa9\xca\xda~\x1ey\x03.V&\x0b\x8c!\xb6~\x9d\x9c\xbaw\xad\x02\x88\x93\x9c\x04\x8ak\xd4\xe6\xb3l\xfcNQ\xde\x97\x12\xb4\x84o\x03\xb7\xff\xea\xe5g{2y\xb52Y.$\xaaLAME3.100\xaa\xaa\xaa\xaa\xaa\x01\x80\x01@P8nu\x81\xc9\xb3\xc1f:\x10\x98PV`\x8b\x826b\xa3\x82\xf0`Z\x01\xa6`\xa8\x00\xfaa\xeb\xd1\x1cn\xe7\x8d\x92a-\x82\xa4`,\x82z`x\x80\x84`\x11\x00\x94c6\x06ba\x14\x01\xc2`\xc5\x10\xcalm`\x88a&\x01Fa\xc8\x85\x88ft\x87j\xd4(\xfek#a\t\xea\xf5\x1a\xd5h\xc8\xe8\x80L(,j \xef\xfb^u \xfa\x8c\x85i\x1b\xf3\xb2\x8c\xc2#ONO\x16\x00Wq\xaa\x16\xb4\xfeO\xd9\xa9e7\x8cD65c\x1b\x0e\xdd\xfaiLf\xecrfW\x19\xc2\xefs\xb7{sy\xe1S\x99\xe5\xdd\xdd\xdbT .4\x02\xd5\x8e\x1c\x01\x8dJG\x9c\xbd\xe9I\x92\xcb\xb2\x85"j\xcbM\x11\xde\xcf\xbbu\x85=\xba,/\xaf\xb5\xadGP\x15\x80\x00\x00\x83, \n\x91\xc7\x8d\x1f\xc7\x02\x0e\xc8`\xfc\xc0B\xe3\x14!\xccv52\xe9\x8c\xef\xe0\x90` x\nL70\xb8@\xaaR\x0b\x05\x8c\x11\x13\xce\xc55\x95\xe1\x84\xe4*\x1b\x03\x81a\xd0-\x96\xa4\x03j\xd8\xde\xf9qh:\x10L\t\x1e\xb6\x1e\xa1\x03\xa9\xac\x9c\xd6\xe1\xa0m\xfdjA\xdeh\xdb\xcc[r(\x14\x08\xb6\x85-)6\xcb\xb2\xc6Y\xa7\xda\xb5\x9e\xbenF\xc1\xac \xbf\xee\x03\x05\xa6\x03\tF2\xe0\x86 \n\x81\x01!\x81\x05\xe9\x80\xc2\x15)\x88\xde\x10\x01\x81\x14\x0e\xb9\x81\xe0\x12\xe9\x88\x83\x13A\xe5\xae&i\x86J\n\xe1\x81x\x00\xa1\xff\xfb\xd2d\xbc\rVu-\xc2\x93\x9f\xd9Pxe\xd9\x1ds\xacu\x1a\x0c\x93\x08\x0e\xffeB\x04\x18\xa35\xdf\x19\xe8\x81r\x00\xb9\x80<\x00Y\x8f\xea\x06\xc9\x83\x8a\x04\xc1\x80(2\x81\x86M\xc1\xf9\x80l\r\x91\x81 \ny\x97\xf5\x15HL\x90\xa4.\xa2c\x05\x06\x06Ta!\xe6H\na\x80\x03\xa1!BSc\x02}\x92\xa1\x16=\xd5\x8b\xb3S\xaf/\x1a\tv\xdd\x96$\xde\xbe\x91`\xbd\xc89U\xf4\x95\xe1\xa9\xfc\x14<\xc7@\xa3z\xe7*\xce\xe7?\x856W\xe9\xef\x82\x81\x98\x88&\x13\x11\x99&\x11\x12\x84,\x14@\x01\xaf0\x16\x16\xb0Iq\x0e:\xd1\xaaKZ\xe4.\x97\x91\xa9*z\x87-\x8e\xa7Z\x99^\xbd\x1c{3\xd3\x8bS\xd6.\xfd\xa0*\x01!\xe9Cp/\x00\xb0\x07\x1d\x0e\x08\xccN\x08\x8c\xfe*IL\x92#8\xc4\x8b\x0c\xd9\xb40\xc3\x92,\x00\x13\x98\x0e\x04\x08\x01\xb3\x0f\x0f\xb1\x00ra<\x08\x06\xe1\xc1\x06`\xc0\x05&\x07\xc1 `\xce\x01\xc6\x04\xa0\x16\\\xc2\x80\x17\xbaB\x01K\x19\xf7w\\(\x93w\xec\xbb(\xbd\xc9\xb8\xa8\x84\x00g/\xdb\xde9\xceP)\xedV\xd7\xc30\x1eI\x16\x93\xa7\x00$\xc5\x162\x10Zm\xc8\x95Z\x97\xbdJ\x8d\xdfU\x9fy\xd5LAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\x0e\x11\x8c"\x0fMWzL\xcc\r\xc3\x00C\x02\nS\x08\xf1\x13\x92\xdb\xc3.\t\xd31\x06S\x18U\x14\x83\xe2\xfc\x11\x13\x0cL\x04\xc3\x04\xd0\x06\xf3\x00l\nC\x01t\x12\x93\x1b\xa0B\xa3\n\xb0\x13\x13\x00\x94\x80\xb3\x80w@c\x0eL"S\x03\x10\r\xd3\xad\xb13\xa0"\xef\x19I\x11\x83\x90\xd4H\xd3\x00\x05\x0e\x05Yc&&8 \x95\xb0\xcc\xaf\x08bP\xbf\x8e\xb8\xcchM\xdc\x80u\xb9u)V\xe4 \x1eQ\xcc\xf0\xce\xe3I\x07*=\xb7o}\x05Jk|\xcf*k\xb7\xfb\xdc9\xce\xfe:\xff\xdf?{\xc7\xbc\xdf\xff\xeb\\\xff\xc7\xff\xee\xb5\xe9pOY&\x0f_\xbdLS\x8d\x8e\xbbJ\xeb\x02\xbf\xbd\xea\x7fd>\xd5\xae\xdd\x99F\xe6\xda\xf2z=\x01\xc0\x00\x10\x8d\x814\xfb\'q(\x08\xc5\x0bz\x86F\x06\x01&9\n\xe2\x02l\xc8\xd0t\x11 \x9al1\x18X\x06\x180\x05\x01\x82\xf3\x02\x81S\n\xcc`0\xbc`\x10\tF\xde$\x12`\x8a\x00\xc2@z`v\x04\x82\x10\x03f\xc9\x0e\xc4\x9bY\xc8\x06\x07x\\\x1ce\x97\xa9\x90R\xe1\x91\x11\xb9\xb9H\xf9\xa8\xaf\x85Cdj\xd4\x97ZUJ\xc5\xb4\x13Q\xd5\x90\x01\x9f\x00\x9b\xb8\xfb%\xdf\xff\xff\xaf\xff\xa9?\xf5\x7f\xd2S\xcaH\xc88\x02\x81\xc00`d\x13f\x07\xa0 `\x80\x03\x06\x07\xa0\xbe`4\n\xe5\x01\xd8`\xfe\x07f\n \xcab\x96Q\'\xf4`Zbr\t\xe6\x12@\xe0`Z\t\xa0\x00\x1e1\x8d\x17\xb6\xcaa\xdcB\xc7\xc1\xd7\x86a\xf8\x19\x86\x11@Xs\xebf<\xecgFf\xa6&b\x83\xc6\x12\x08$@ab\xa0\x90\xa0q\xe1\x83\x8b\x98p\x10p\xc2\t\xda\xea\xc7\xff\xfb\xd2d\xd9\x0cF+5B\x03\xbf\xda0~\x84\x98\xcaw\xd0v\x1e\x9d;\x1com1Jf\x91\xa1\x99\xbfi\x18j\x8c\xd1\x81\x99\xd9\xb0p\x02{\xb5r\xd3\xaa\xb2\x06\x17\xbc\x914\xa0\x9d[\xdc&\x98\xca\x18)l\xc9C\x8c\x10M\x81\xafr\xf61\x12\xfc -c!\xa0\x8c\x980#>\x1b8`\x8d\xa4\t\xb6\xa1\x10\x90FL\x18\x07\xc5\xc1\x05A\x81\x1a"B\xe6\x85\x07O\x85\xcb\x12\x17hPu\xe8\x16a\x1c\x89\x17y\x03$\x84m M\xe8\x13y\x1a\xcc/$\t\xec*\x0b\xc9\x02oR,NP\xbf\x0b\xd9\xd3\x16\x92s!\xc0\x9c\x05\x9d]\x9d\xc9\xfd\xff\xf7h\x80\t\x11g\n\x1e\x01#@\xa0\x10\x81\x86\x11\x03\x0b\x0eQ\x94\xdb\x08\xcf4d\xc3\xb8\xcd\xcde\x83\xc8\xc0\xb0\x0e\xcc\x08\x00\xb0\xc0\x00\x07L\x19@\xc0\xc4\x80e\xcc\x1c\x82\x04\xc1\xc8eN\xdd\x9f\x08\xc6@\n\xc1\x02x\x0fJnD\x10\x86d!\xc7Q\xd1\x9e \xb2\xd5y\xa2jE\xa6\\\x97\xda\xce\xcd`\x83\xf0\x99f\xfe\xc5\x9b\x03\xa2\xc8\x84\xdb\xa6\xfe\x7f\xeaw|\xcb|\xcfY\xe7\xf5\t\x02"\x13b\x11\xc9\x13"\x9a\x94\xcdw%\xf5\xf4\xf8\xa3\x9b{\xbb\x18w\xda/\xa7$\xba\xb1\x9c\xc3\xa2\xec\xf4+\xfd\xd7)\xaaLA \x10\x07\xb5h\x0e\x84\x01\x80X4\x98%\x02q\x85XP\x18\x02\x07y\x86\xf0\n\x18T\x83\xc1\x85\xc0\xaf\x98\x8f\x05\xc1\x90\x00\xef\x98|\x9b\x91\x98:=\x19f\x84\xe1\x88\xd0\x84\x85C@\xc1\x1c4L<\x84\xc8\xc8\xac1\x8c\xafWP\xdf&>\x8d(\xc0@\xc9\xc8s\xcc\xfb\x888\x19\x84\xe1\xcb\xb3"\xb5\x8d\x1a[5\t\xb0\xc6\xc8\x93&\n\x0c\xce44T,\xd3\xc6\xa3c\x9b\x8c\x9c\x9d2\xb0\xe8\xccC\xb1\x18\x94)aT\x04\xbd\xaa\x02\xaeR9\xa6 \xf2n\xaa\xd56h\xee\xa2\xc6l01\x7fYal\x94e\xc5Uf\x9e\x8a*\x1a\xad\x08\x06U1\xb4\x9b\xe4#HHL,J\x804\x84CF\x00(\x13\x9c \xa2\x11 <\xc6\x02\x01\x93\x14\xc2$\x1b\x16($I\xce_\x92\xf6\xafD\x1eQ\xb5z\x8fLM\x14XS\x98\xa0M\x1d~\xa9\x93\x86\xb5U\xb9\xcb]M\xd5\xecgP\x1b\xaa\xe1C\xec\xb5\xe1{a\xa9\xb8\xac5O\x15\x89X\x8dP\xce\xca\xab\xcbf\xa7\xe3T4Q\xa9\xb9\xd9U<\xb6\xad\xeak\xb6kgf\xb7)\xae\xde\xa6\xaff\xb5{UyM\xbb\xd5\xb3\xb31TS\x14m\x14\xc5[\xcab\xa8e\xb9V%\xbb{\xb9&\xe5\xbb\x18\xf9\xadMo\xd5\xdf\xc20\x00\x00\rI\x7f6\xff\xb9oY\xe4\xfb\xe1\x1dZJ\\\x0c\x07\x07\xa6?\rz\x9a2\x02\ni\xc4\x82G3\xe2\x84\xa1PP\xc3\x8dR\xc1x\xab\x8b\x93\x16a\xdbx"\xfd0T\xb7O\x9auRK]\xcc\x7fz\x7f\xf6\xbb\xd9\xe3&\x95\xaa\xc76\x9c\xa7\xbf\xf3\x9b\x98\xd1\x80\xc3\x00\x01\xc0\x80>`\x82\x1bf\x03 Z`\x06\x07\x06\x11A\x04`\x1c\x11\x06\x05AX`\xa8\x00& !\xbca\x16\x13G\x87\x00\xbc`\xbc\x08\xc6\x0c\x00\xa2`\x96\x01\xe2\xc1\xc6cr)&4c\xa2e\xc0\x7f\x87B\x17\xe2e\x92Kf=\xe0\xb4`x\x01\xc6\rAL`\x80\x01#@\x84\n\x04C\x00\xd030#\x04\x13\x02\xf0\x19\x02\x80\x92\xff\xfb\xd2d\xfe\x84\n\x0cU\xc7\xbb\xdc\xc4"R\x039}m\x87\x85\x1b0\xfb\x085\xef\x00\x02\xc2\x98\xa2\xea\xbb\xe0\x00$\x96nq.\x0b~\x87\xe9&\xed4\xc7\x8c\x10\x01\x0f\xd3\xd4\xfc@n\xb4\xb1\xae9\x8d\x0eQ\x0f\xe1#\x96N\xcf\xb9_\x10\xbd\xb7\xd1\xfcq)\xed\xd0\xdb\xfa\x0bVr\xec\xae\xdd{_\xddo\x0f\xc3_\xcb|\xc3\xbf\xff\xcf\xe7\xe5\xcc\xf3\xce\x9e\xdf\xff\xefy\xe7\x9e\x1d\xc3\xf0\xfdT\xc1\x1f\x87\xdfS"\xe8@\xaf\x16M\xe8MS\x89~m\xe3\x11\xf5\xd5n\xf1~v\xd2b\xe84\x00\x00\'tI\xa9\x05\x19(\xac\x00\x06\x0c\x0e\x07\x04\x81\x13\x04@\xa3\x07A\xf0\xe0\xe8\xcfc@\xcb\xc4h\xf8!L\xca\xc2\xa0\x04P\x05\x81`H&c@r`8*`\xc6*f\x1b(\x9c`\xa2\x16\x06\r\xc0\x18\x85\xa3\xc0t\x0c\x02\x13\x02\x10\x1f\x12\x051\xa0\x17-b\xa4LD\xe4^\x8d\xbb,\x7f\xe3\x12\x1bt\xfd\x07\x00U\x86w/i\x90\xfd+/ \x00w\x92\x91\xfc\x9b\xa5\x95;\x8f\xe4\xe5H\xa4\xa2r\xcd=>r\xe89\xad\xb2\xb6\x9e\xeeC\x12\x98\xbcn\xd4\xec\xba\xcf)\xe60\xc7\xb9\xd8\xcf\xb8g\xac5^\x9e\x98\x99(\x16\xbc\xc73\xb3c\x96\x9d\xfd\x17\xeeO\xdb\xe8\xfc\xf5\x00\x00\x00\x03\x0b\x00\x00\x00\x000\x82\x08s\t\xf0\x98\x06\x05\xe9\x84\x98E\x98\x1d\x06i\x8f\x99\x11\x98\x07\x86\xb1\x84\xf8)\x98\xb5\x87\x99\x8a\x8a\xca\x98\xb0\x8ei\xf2\x06 \x0b4I\x91\xb1i\x98/\x05y\x90i\xcd\x188\x94\x89\x87\xa15\x9b\xbd\xb0\xc1\x80\xf0\xbb\x9cn)\t\x8aX\x04\x1f|\x9aY\x9fY\x9f\x18\x13\x82y\x82\xd8?\x18\x17\x01\x18\x84\x1d\xcc\x14\x80\xb4X\x11M\x87\x90\x18\xd5,\xef\xcc\xa1\xc6,\xc1D\x05\x8c\x08\xc0\xd8T\x02n\x15@M9D@\x0f\x171\x11\x07S\x07\xc0,0\x01\x03S\x030\tX\x12\xe39\xcd\xc5\xbc,\xa9y\x98\x890\x0b\xa6\x19\x81\xc0\x18\x02\x81\x11\x9a\x18\x0c\x80y\x80(\x02\xce\xcb\xfe\x8f\x18\xd4\x07L\xff\xd3\xdd\xb2\n\x00\xb3\x02\x00\x140\n\x00d\xf8l\x80\x00\x02\x8cK\xacY\xb9\xadD\xaeO\xef/\xc00\x00\x0c\x03\xc0\x14\xb4l\x1e\x19a\xf0\xbbx\xdf\xdf\xd3\xd5\xc7\xedc_-\xf7_\x8dJNWv\xdct\xc0e\x91L5\xbew\xf7\xde\x7f\xeb\x99\xe1\xcf\xee_\x97\xc4\x19C\xa8\xb1\xdd\xf9\xfa\xf3\xfd\x9f\xcf\xff\xf5\xff\xfc\xff\xff\xfew\xf3\xff\xff\xff\xde\xfb\xfc\xc7\xfb^\x1b\x8b\xb5\xc8r\xc5H\xc4\xe4\xae\xde\x7fS-\xf3\xff\xff\xf2\xfc5\xfd\xef\x7f\xff\xff\xff\xff\xff\xf7\xff\xcf\xef\xff\xe1\xcf\xff\xdf\xff\xff\xff\xff\xff\xff\xd8\x7f\xe5\xf6\xf3\x95\xcf\xd2a\xcd\xe7n1,\xb0\x00\x00\x00\x00\x00\x04A\x80\x98\x07\x189\x071\x80@\x0b\x91\x05I\x80\x08\x0c\x98F\x83y\x83 h\x9b2\x97a\x99\xd8\xb7\x18\xffay\x8e\x00J\x1a\x97=\xe1\xb0`Y\x18\xe5\x83\xb1\x87\xc0x\x98\x03\x151\x9c\x98v\x18\x89\x98\xb9\x9f\t\xc0\x992\t\x11\xaa\xd0\xc8\x98\xbc\n\x11\xb6\xe8\'\x0b\x14\x01\x87H\x11\x98\x04\x051\x82(&\x98v\x86\xa9\x81\x98-\x18\x06\x80\xb9\x83xb\x07\x03:\x96\x18\x0b\x00(\xb0$\x03\x00Uy\x98\x1a\x81\xc0@\x14\xcc(8\xd0\x004~\xadu\x18~\xa1\xc7\xbeT\x98&\x01`\xff\xfb\xd2d\xff\x80\x0b7\x8aC\xce{\xc0\x01\x11\'\xe8T\xcfx\x00q)\xdf\n\x19\xff\x80\x02r\x12\xe3\x1b;\xd0\x00\x02\xcae."\xc0\xa6\x03\xbf\xc8&\r\x7f\xe55)\xa3\xf43/C\x83Z^\xe0\xd9\x9c\x8ec\xaa\xb2\xea\xf5h\xb0\xa9\x14\xdf\xc5\xe7jg;AE=[]\x9a\xb5\xce\xd5\xe7s\xc7\xeb\xd6\xafg\x1c\xaa\xda\xce\xb5\xdb\xb6\xbf{\xa8\xd3Z)G\x87\xb9u@a\xdc\xd2A\xd0\xd2\x0e\xdfS\xc9>\xf0{\xe4].\x9a\xd6\xfb\x9e\xc3\xbf\x172\xe31\xa7\xff\xff\xfca\xff\xcc\xff\x9d\xff\xff\xffwS\xb4%m\x0c0\xb3\x83)1P\x06u\x03\n\xcc`\x9f\x86\xfa`\xc0\x01x`W\x84\xfcbO\xa0:ot=\xbec\x9b3\xba{s\x86De\xca1\xd4tq:\xd4a\xed\x03<b7\x8fhcs\x80vaC\x06\xc6b]\x03\xeaa\x03\x86\x10e\xb16Z{\x9a\x83\x0eb\xf7\xbd\x82`"\xad|f\x8c\x1f\xbe\x7fE\x11\x0cb \x86\xb6`\xe2\x84d`\xbc\x81\xbc`\\\x87"`T\x80\x8a`\x1c\x80.cJ\x01\xbc`-\x80\xaa`=\x80"`m\x81\x90`\x11\x006`*\x80\x06`(\x81\xa8`\x10\x80\x10\x90\xc0\x901C\x00\x190\x04\x80\t\x19\x00\x14\x00\x05\xb8`\x0c\xe6\x02\x00\x10&\x03\x90\n&\x01\xf0\x07F\x02(\x01\xa6\x00\xd0\x05)\xea\xc5\xcc\x02p\x10A \x06C\xab\x91AL\x00@!\xc5\x80\x94h&\x01\x80\x06\xa6\x00\x98\x03E\xc6Ut%\'S7\n\x00/)\x95\xca\'\x1e\xd0\xa0\x02\xd0\xf4\x1f\x9d\xf1\xc0\x00PL\\\xa4\x8a\x80\x8b\xac`\x02\x80\x19\x84\xb2\xcf?,5Ov\xb5\xfa\x99\x05\x80\x01-\x0bfZ(IA\xd7\xd9\xfa\x88\xe5{\x99w]\xb7\xfa\xe79\xf8\xeb\xfb\rO3\x16\x94\xcb\x9f\xa9S*K\xe6\x92\xd7\x7f\xb9\xe3\xf9\xef\x7f\xf9\xef?\xd7y\xbf\xeez\xa4\x86\\\x98\x17\x95e9L\xb2\x97\xd9\xde\x9e\x9av\xbf\\\xfc\xbf\x9f\xff\xfc\xd6z\xfe\xef<\xf9\xff\xcf\xff\xfd\xfb\xb5V\xf5lk>\xd1\x18v\xf4\xa6\x19\x96\xdd\xabg\xff\xff\xff\xff\xff\xff\xf9\xf9\x7fnM\x81?\xad\x82sf\xa6\x02\xc7\xc0\x00\x10\x85\x01\x14U!\x07\xc4\x84A\x90\xd4\x0c-\n\x85`\x104\xc0\x80\x84\xd4\xb9P\x88\xb31\x92w0\xfc{\x19a\xc5\xa6C\x02D\x03<\x83\xf1\x01\x82e\xa8\x10`bXpb$\x01\x16\x0e\x055\x8c:\x14N\x98\x11L\\\x03L\x06\x10L\x1f\x01\x90\x0cb(.\r\x04\x87\x80\x93\x06\xc0\xc0\x08\x00\xa5K\x96\xc4\xaa\x81\x91AXK\x1f&\xba\xf0\xc3P\xd5\x1c\xe5-\xc9l\xa6\x8b\x1b\xce+\x85/\xdeYcW\x99kw\xec\xf6\xff\xf2\x86\xf0\nM\xe2\xcc>L\xa9T-c\x1bgB\xf3u?\xfd\x7fJ\xff\xfd\xdf\xb9\x02\xa4\x03\x01\xa4\x03C\x05D\x0cs\x01\x08\x040\xc02B\x806\x18\t`\xae\x18C!j\x18J\xe1\x99\x18Y\xa1\xda\x98*jm\x1c\x06\xc1\xda\x98\xe7B\x89\x989@\x85\x98\x18\x00\x04\x98\x18`\x94\x18\x13 `\x18\x1f .\x18\x07\xa0=\x98\x01`\xf2\x18=\xe15\x18pb5\x1b\rq)\x99\x1e\xc4\x81\x98\x9e\xc1.\x985\x00\x82\x98\x02\x80f\x18\x0f T\x18\x04\xc0\x1b\x98\x10\x80$\x18\x01 \x04\x85\x80&Cs\x00\x04\x01U\xff\xfb\xd2d@\x8c\x07-;\xc4\x17\x7f\xe0\x00x\xa6)\x17\xeep\x00\x19\xd8\xc7\x0eN\xffgA\xd5\x14\xa4i\x8e<\xf4J\xa5\x10{\xcf\x06F\x9a\xa9\x7fL\x04 \x01\x8c\x02\x90\x00\x994\x85\xdci.L~\x06\x86\xda\xc8\x80\x01\xd0h\x05I\xaa\x18\x00\x0b\xfb \xa0\x94C\x0f\xb6U\x86\x80\x0f&\x00VWb\xbd~\xd4\xabZ\xd4\xc4\xe7\xd6\xa5\xce\xb6\xf1\xbdM\xdds\x9f\xdd\xe3\xcev\xd6\x15\xff<u\xbe\xfe\xbf\xff\xff>\xf7/\xb7\xfd\x1f\xff\xff\xfe\xff_\xffI\x00 \xadX\x02\xab\xa8\x8a\xb0\xa4\'\x12\x83IE\xea\xe4\xc4\x01\x13\x01A@Y\xf3\x83\x8e\x8cB\x07O\xb4\x93\x06\x80\x10\x94T\x0c\x98\xe4\x1cl\xd2\xc1T\xbej\xa8\xd1\xa0\x87FC\n\x83\x8aa\x00\x000\t\x95\xa2\xb3\xf8\x90\xe8\xae\xdeK\x9ei~8\xf7YaR\x97:\xb6.\xd1\xd4\xb1\xf7i\xfb\xdes\x98o<;\xbe\xf6S\xac*cw\x0b\xba\xbfs\n^o\x95\xb9\xde\xdc\xff\xff\xfek}\xb1c@x\x14\xc4\x80D\xd5"\x18\x12\x13\x98D\x02\x98\x1e\x08\x18~ \x990\x84\x1a\x87?\x18\xb4`\xdb\x18J\x90-\x1b\xb8\x01\xa9\x98`\xc0\xdf\x18,\xe0 \x18\x06\x80\x12\x18\x05 \x89\x85\xc0,0\x08\x80\x93\x01\x01D`o\x81\xd4`M\x03\x9ca\xab\x82\x00p\xfc\x1a\xece \x84\xacaJ\x01>`@\x80 `9\x00\xc2!u0\xf3\xd1\xa0\xd2\x12\x13 &\x00\x06\xb4\x00\x10j:\xc3\xb2\xaa\xf7 \xd5(1z!"J\xf8e<\xe6\xcaaR8\x1d\x8a\x13r1gf] \xa9OAMz\xf8\xc8\xfb\x8b\x1e\x80m\xf3v\xab\xbf7\xac\xef)\xa7\xe9\xda\x8c\xcbi\xa6(\xec\xf7-\x7f\xef=Z\xd6\xeb)\xba)C\x18}\xf5qW\xf8\xc6\x16\xa5n\xc5Wh\x9ecGje,cH\xff\xe8(\x04\x00\xb4\xeb\x00\t\x97\xdd\xd8k\x06>\x99\x8a\xcaM\x82\x08\x00\x98Z:\x00\x19\x1c\xac,`\xb0\x91T"\xb0\x8b\xd4\x94\n\xd7\x87\x84F\xd6.\x98y\nx\x17\xb9\xaa\x04\x86\x00\x11\x18l\x08<NR\x08F\xbb\x91\xb9.\xa8:{\xf9\xf2\xd9}.\x84\xdc\xe0R\x1b\xaa$\xe3\xa6\xa5R\xa6\x8aV,j\x160\xf9\xfc\x97\xb4\xb1\xe6W4\xab`\xe7\x19\xcd\xedG\xb5\x87\xa2e\xcc\x8bj\x14\xc5U \x00\x17\x1aH\xabI\x816\x00\xbb\xb0\xc0B\xc0\x08\x01@\x1d*\x00x`>\x81Pa\x91\x80\x18`\x15!\xbcrP\x05\x86\r`\xa8\x18\x14\xe5\xea\x02\x82\x10\x80\x02\xc0 \x08`\x04\x04\xe1\x00\x1ac\x8a\x07\xe6\x18@\\x\xbb0\x06W\x01\x08a\xa2\x11f\t@\xa4\x1c\x07geA\x1e!\x81\x98A\x7f\x14}\xe7\x7f]\x88\x84\xdex\xdf\x86L\x99\xd3\xc6\x15%\x8aU\x88\xda\xa1\x88P\x90\x10 &.\xd5\xe5\x95\xa8\xb7\x11\xdfc\xe2 \xd2n\x93w\xaa\xf7}\xa3\xdf0\xad\xab\x99\xf7\x97lZ\x0e\xb5F\x84\xaf<ON\xf7\xab\xf6%Z\xfb\x1b}[?\xfe\x96\x00\x01Q\x90\x02\xa0;\x12R`C!\x13\x0c5\x16#\x04\xb8\x1d;\xa1\x87\xce\x06\xa1\x81\x04\x9bQ\x90\x80\x11\xf9\x82\xdc\x02\xe9\x80:\x01\x19\x80\x08\x00\x18\x8c\x08#\x00d\x01\xb3\x00P\x01\x80\x08\x06\xa6\x01\x90\r\xe2\xc0a\x988\xc0\xf6\x1aL\xa7\x84\x18\xa8@w\x18& \x0c\x98\x16\x00\t\x18\xff\xfb\xd0D\x7f\x04\xc54+E\xbb\xfe\xca@\xa5eX\xa7o\xfa:\x14H\xa3\x10\xce\x7f\xa7\x02\x8c\x95bM\xbf\xe4\xe8\x00 \t\x99*@\xd2\x8c\xd9\x08M \x052wP$\xed\xc9\xf1\xc3\x95\xa4\xa6Uh\xb0\x97\xda+\x1ete\x11\xecbSe\x81\x80\x12rV\xfa\xf4\xf5\x8b6\xac\xe32\x82\x16?\x8c9\xcaz\x0c\xae_\xb7\xd9\xda\xd61\xb9\x7f[\xa8\t\x91\x16H,\xaf\xec\xdc\x80\x1e\x80+y\xb8\x00\x82\x00q\x80\x84\xed\xb1\x88AC$\x83\x80\x93\x0cR0\t\x0c\x07\xe6\xd5\x8cY\xa0\xcb\xcc\x0fp3\x8c\x05\x10\x04\x0c\x020\x04\x8c\x00\xd0\x17@@(\x0e\x80n`\x1f\x00\x9e`$\x81b`\x1b\x03\x80`m\x86\xbae\xb436~j\xb6fa\xd4a\x98\xcab``(\x17\x80AT\x9fIB\xd2\xb0\xa9z\xa3\xe4\xa6\x8ec\xb4\x8e\x19\x85\x01h\xb0O\x02Jj\xdb\xdd=|\xfd\xc6( \xe1.T\xceR\xbfzn\xea\x90\x18\x07\r\x01\xd6%\xdf\xaew\x1b\x99\xf2\xad\x9ci\xabE\x11\xdc\xfaW\xff\xff\xff\xff\xff\xff\xff\xf4\xa0#`\x01\x04\x9e\xa0\xa2\x8b\x18X\xd8\x195{\x99\xf0\x89\xea\xf1\x98\x95 \x8f\x18!k\xd5\x18\xb1a%\x98"\xa0L\x18\x05\xe0\n\x81\x00$\x11\x80\xae`\x11\x004\x1c\x04y\x80|\x01i\x80\xb0\x05y\x81D\x07\xf1\x82\xa6\x17Y\x99\x0c\xe5\x89\x85\xa2\x11\xe9\x82 \x051\x80\x8e\x02\xb8`\x02"1L\xbaL`\x86\x0c8\x03B\xe6n\x90\x89]+zq\xddF\x96oj,\x9e\x19\xc7\xecjg\n:Fv\x1b\xd4%\xd2\x94\xee\xed\x0435\x07\xcb\x81\x03\x0f\x1d-\xde]\xdf\xef\r\xf3z\xc7\x97\xf7\x9f&\x1a\x1c<\x80t\xc1?\xff\xff\xff\xff\xfb\xd5\x00\x81\x000Tm\x98&4\x04\x00@\xb3\x0c\x81\xd3\x0f\xc2C \x83\x93V\xee\x13"\xac\x1b\xa3\nN\xc4\xa3Y\xd4Z\x13\x07\xfc\x0f\x03\x01\x80\nS\x00\xdc\x03c\x00H\x06\x93\x02\x0c\x04\xa3\x01X\x02S\x01\xcc\x00\x83\x02\xb4\t\xc3\x02\x08#\xb3\x04\xf4h\x03\'\x1bK\xc3\xbd\xfdc%\x963\x10\xc9\x83\t\x05\xd1\x000"\x03\x8c\x19\x00\x89B\xc0pf\xd6\x9c\xa2`:\x0f\x87\xafK\xe8$\xa4 \x11\x81Fp\x08\x02\x9b}\xaeJ\xe5\xb5i\xa5p\x01T\'0\x10*v\x18\xac\xf7;\xcb\x96\xb2\x9a*\x82\x91\x0c\xf9\xbb\xdd\xc3\x08\xc86p\x11s\xc3\x8f\xec\x8a\x1a\xfaU\xbew\xfb\x93\xffV\xff\xff\xe3(\x98\xf5m\xfa\xab\x04\x0c\x001c \t\x84|tX\xb4\x12\x16\x00q\xa01 \t\xe3\x03\xf0=0`*\x83W\xc0s0\xaa\x00\xb2\xa8\x0e\x98\x10\x00\x088\n\x93\xe1A\xa2A\xc0\x12`|\x08\x06\n\x81\x12a\xe2\x9f\'\xa4\xcec\x03BA0\xe02\xc2\xa89\x15\xe8\xa1\xd7\x1d\x1d\x1a\x9d\xfe\xa3?\x02\x9b\x85T\xda\xae%\xa7\xf0\x85]Y\xa5\xach\xfef-\x87s\x83\xddo;\xd53\xaa\xf8"\xacc\x18\xfb\xeb\xdf\xf5\x90\x01[\xe8\xc1\x89\x03\xc6\x8e\x0b\x188,a\xa0\xd0\xe0t\xc5\xa3\x93?\xb5MsC2\xc7\x15\x13\x1d\x0c\xb8;\xc7<301\xc51M\x14\x93\x13P\xf90\xef\rs\x0f\x90\xf90\xe5\r\xf3\x0e0\xcd0\xf6\x0b\x83\x0b\xa0\x8c1.\x0f\xe3qYy5\x86#c\x12\x81*1.\x0e\xe3\n\xe0\x940\x98\xff\xfb\xd2d\xc5\x84\x05\xc0%C\x13\xbf\xe9\xc0x$\xe8\xba{o\x80&}W\x1e\xee{\x07\x81\xe8\x90\xa2M\xbfh\xe0\x06\xa3\x05\xd030/\x014\xd2Bq\x90\xc6\x83\x18\x80\x95\x92R\xea\x18\x08hA\xa0\xc0$"p,\r\xa5\n\x80!!\x00\x89\x10\xe2YkjV\x07J\xc4d\x94+\x9d\te\xb3-9m\xd1Mj:O+\xb6a\x18\x18h\xff\x1aP\x00\x08M\'3\x94\x0c5/z\x0bPb1\xa0\x87\xba\x9c\xdek88o;pLD\xc4i\x90R\x18\x00\x04fA\xa1\x06b\x01\x88\x9d\x13\x8e\x02\x80 \x11\x07\x13\x01\x96Q>\xed}\x9c?\x15]\xb53BYr\xcbn\x82\xe8\xf8\xcb9O\x1b\x8d\xcb\xed\xeaV\xff\xbf\xf0\xfc\xbf)C\xf8\xee5\xf7-\xdf\x8d\xdb\xedJL;\x85$b1\x18\x8cRX\xfaJH\xc5%&\x1f\x9e\x18a\xf5\xe9\xe3q\xb8\xd8 \xee\x07\x07\xdf\x07\xc1\xf3\xfc\xa0 \x08\x1f\xf5\x060@\x109\xe0\xf8>\x18\x04F\x88!\xb2\x01@[\x8a`\xa0\x90\x02\n"\x121\xbac\x0e0\x110\xa2T\xa3l\xc0\xbf\x1a\x16@\xc0;&\x00\xc2\xff\xabri\x98\x03\x80q\x80H\x16\x18\x05\x05)\x81P8\x1a\x05!a\xe9\x0cd\xd9\xa2!\x92\x0c\x83l\x96\x1f\x8a\x91\x11\xeb\xb6\xfaO\xe5\x8e\xb7\xacK\xfb?I=\x8e77[\xbaz\xd8v\x10\x9b}\xca\xfe\x1c\xce\xb3\xf4\xf6<\xf1\xf2\xe2\x8c\r\x0b"\x8e\xb5\xff\xec\xd5\xff\xf4+\xf4*\x00\x05l\x8c\x0c\x01\x01A\xc3\x05\xc1\x83\x06\xc2\xa3\x0b\xc2\xa3\rDc\x11AE\x142\xe4z3\xad\xc0?\r,2L\x011\x10t\xc2B\xd3\x1d\x0f\xcc\x80=2aT\xcc\x88S8\xa7\x8dk\x02:\x1c\xe8\xd7\xf1S\xc3V\xcd\x8cU1\xb0\xcchj\xdf!\xc4\xb5\xa5\xc9@\n\xb9\xa2p\x96\x19@\x97k]\x9d\x9aw\xa4\xedia\x97p5\x1d]\xeb[]\x98\x0c\x8c\x8c\x8c\x9e\xf6V\xae\\\xb9r\xef\xaa\xd7~\xabLD\x91$\x9abz}\t$I\x12L]\x80\xe8\xc4\xc5o&%\x03`$\x04\x81\xa8\x92z\xee4\xba\xda\xd1\xd1\x91\x91\x92\xe7\xb4\xe4\xc8\xc8\xc9r\xebN\xd6v\xabV\x9e\x98\xad[o\xadkZ\xceV\xb5\xe9\xb3K\x97-Z\n\xb8\x8c\x1a\x06\x81\xa7\x96\x06\x83\xbcJ\n\x82\xa0\xd7\x95\x05j\x05@\x15[2\xd62\x99\x02\x14\x18\x0b\x80h\x08\x00\x0c\x17\xc1\xa8\xc6\xcc\x05\x8c\x03b\x10\xd9\xb8:\xcc\x13\x02\x10\xd3\x94\xdb\x14\xc78xS>0;f\x01 "`\xf2\x07\xe6\t\xa0nlF\x12f6\xc0\xe4*\x0bF\x06\x00$\xdb\xa8\x10`\x1b\x97\xaa\x94h\x04bn\xe3\xf9(\xb5\xac\xacr`\x94\x01\xb2\x86\xe3u?:\xfa\xbd\xaa"\xb0\n\xed^\xee\xfe\xb5\xbc\xf0\x82\xef \x07C\xd8\x19>\'\x07\xde<\x83A\x05\x9f\xa5\x1e>\xae\x03\xb5nS\xbb\x1aKd@\xae\x17\x14\xee\xc3\xe1\xf5\xe3,4\xd5w\x7f\xfe\x97 \x02\xd2\xc2@\xc6`\x12\x06\xe0\xa0H0+\x03s\x010Q\x0c\x0cc\x060o0\x16\x1a\x10\xa0O\x99\xd1\x0ca\xf1\xa8\xa3\x18\x0f\x89\x89\x88\x88\x08\x18\x0e\x83I\x80x \x06\x02\xf9\x81\xb0>\x11\t\x01\x84(\x0e\x98\x08\x00\xc9\x84\x80\xcc\x19\xa6%\xb9\x94\xb9\x08\x98\xde\x86\xa9\x85H\x0f\x98\x03\x00Q\x81\xe0\x16\x18\x0f\x80\xff\xfb\xd2d\xe6\x04\xc6\xa2M\xca\x1b\xbcb\xe0\x98\xe4(r{>R\x1bp\xef\x0e\xd5\xef\x00\x02\xeb\x99b\n\xbd\xd0\x00\xf1\x81\xd0\x05K\xc1\xa0\x07\x00+\x85\xde\x90\xeeJ\xc3\xa3\xe0\x80\x00\x10\x02\xe37Q`\x03t\xe3\x11\x88\'\xfb1\xdd\xcf\xa8TB\x11\x94j\x8f\x06qA,\x82_\xb94\xf7\xf7\x1f\xafs\x98\xbe\xf1k\x12\x87rsW9C\x9e;\xee{\xe4\xc6\x1a\xa9\x85h\xa4\xbe\xdd5\x9ev\xc6\xf7\x870\xce\xa5\x9bu\xfb\x9c\xbc\xd1\xd8\xbb\x92 \x138a\xc7%\x959\xe8\xc6x\xf1\xe6]0\xcb\x98\xa3/V5\x8d\xa3\xdd\xff|\x80}\xa08a\x00\x06\\q\x80\x18\x01\x01i\x80\x90\x13\x18\x15\x83\t\x87\x88>\x99\x10\x88\x99\x95\x83\xff\x18\xec\x9c\xa9\x87\xc85\x18,\x04I\x80\xa8\x11\x98G\x818pT\x18.\x00)\x80\xc0\n\x18\x00i\x98\xa2\xb8\x1a\x9c\x0c\x9d\xa5\xff\x99.\x02\x00\x8c\xd3\x16\xc63\x05\x00#\r@c\x07\xc0R`\x0c\xc0\xf0<X\x13.\xc4\xfdE\xe8\xc9^\xc7\x8aS\x10~\x12\x9d[\xd4\xf2\xbbA+Vfq\xcd\xbf\xf3\xea\xc80\x01\xbd\x8c\xcd\x9b;\xad\xc9[\x14\xf3#\xa0k\xed\xc6G\x14\xce\xaf%\xf8\xcb%o\xe6\xb1w\xf1\x96\xf279\x18\xa7\xfc\xac\xe1gx\xce\xc92\x8cP\xc3\x9c\xce\xa0\x9c!\x18\'\n\x83\xc0\x81\xdf|T-\xff\xfe\xfa\x80\x018\x00\x00\x00\x00\xc0\x80\x02\x18\xc0\x93\x04\x14\xc1|\x06\x08\xc0h\x04\xe4\xc1\x03\x06\x90\xc1\xaf\t\x90\xc3b\x08t\xc7\x1f\x1a8\xc3\xf9\x0cH\xd2\xbe/@\xc2\xad\x0e\xac\xc6y-\x10\xc11\x02\xfc\xc0\x14\x00\xd0\xc7\x12\x14\x94\xc9\x89\x15$\xe7\xa6\x15\x0c\xd3\x14|\x18\xc7t\xdc\xce\x9a\xc4\xe8\xd2\xd8\x87Mw\x99\x98\xc3szN\x9d\n\xac\xc5$<H\x00,B\x01\x06jCte\x9a(\xa6\x02\x81 e\xd8(\xa6\x06\xc0\xf6aX\x10eP\t/\x188\x07\x07\x80<\xc2\x98\x14\x00 \xb0`\xdc\x0b\xc1\x00\xa8`H\x04\xc6\x08@\n0\x0cF\x13`\xe8\x89\xa5\x00\x12\\\x94\x02\x85\xc0\x0c\xc1(\x1d\x8c\x1f\x81\x10\x12\x01f\x0b@\x00`n\x0c\xe6\x04\x00\xcc`\x0e\x02\x81\x80\x16\x15\x00@\x10\r>\xf6\xa4\xf8L\xdd05\x01r D0\t\x010\xe0\x0b\x04\x80:1\xa0\x84*\x00\x85\xd2OU\xa2\x04\x00\x17\xdb\x19Vt\xff0[C\x01\x90\x05]E\xd8Nc\x00 \x00J\xc3\x00 \x03n)\x13,\x94\xbcE\xaa\xa6\xe68k+\x9a\xf4\xb4@d\xca\xf4Ur\xf9\xa7\x02\xe7d\xf0\x0c\xa1\xfe}\x9ck\xae\x93\x8d3\xfc\xa7\xd7\xef\xba\xdfv\xd2\xddxq\x1f\xe0gr\x1e\\\x8d2\ne\x92\x96\xb2\xbbf_\xdb\xd5j2\xa9\x9b\x1c\xfd\xeb\x9f\xae\xff\xfe\xff\x7fe\xf8\x8e\xb5\xf6I\x13~\xe4\xae\xfd\xf7m\xfb\xa9?\x10\xa6\x9a\x87\xa9\xa5P\xf6\x7f)vuV\x96\xad\x9d\xf7\x9f\xfa\xef\xeb\xff\x9f\xcde\xff\xff\xff\xff\xff\xfe\xeeB\xe3\x11J\x08\xc7\x1f\xc8\xa6r\xc9\xb8\xbb\xf1v_\xff\xff\xff\xff\xff\xffr\xac\xb7,\xa5P\xd7\xe5\x95k]\xad.\xef\x00\t\x80\x00\x00\x02\x06\x02\x00\x18`\\\x03\xa20(0\x89\x00\xd1\x08\x0f\x98.\x04a\x85J\x04\x9c\x1c\x83\t\x90\xa1S\x19\xab!\x81\x92\xe8\xf2\x1b\x8e\x1fY\x88\xb8;\x98E\x81\xd9\x86\xd0-\x98g\x05y\xff\xfb\xd2d\xf4\x00\rU\x8aC\xb6\x7f\xc0\x00\xdc&\xf8\x96\xcfx\x00\x1ad\xc7\x10\xdd\xff\x00\x01\xd4\x17\xa5w\xb7\xb0\x00\x08\x02\x18,\x02\xf9\x83\xb0\xe6\x18\xaa\x8c\x81\x82\x00{\x18\x92\x88\xd9\x828\x8d\x9a\xf0\x80\xf9\x87\x98!\x83\x00\x89\x00\xc4\x81\x00`v\x03*\xd4<\x10f\x01\xe0\x1c\xcf\xcc\x00@\x10 \x02V\x1c\xb6tm\x85\x86\x97\xed\x96\xb4\xc6\x94\xa6H\xaa\xa0\x04\x80\x14\x9c\xf1\x87\xde+\x16\x81\xe36\xa7\xdb\xbcf\xa5\x89t\x87\xb3\xd2\xb6\xb3z\xc7p\xe54\xc5\xcd\xdc\xd4\xb3<p\xe5J\xf3\xb3\x17y\xaev\xf5\\\xbf\xee\xeb\xfb\xbd\xf3\x1ds\x9d\xbd\xe4\xc8\xb9\x1e\x90\x02Rx\xd5\xe9\x13XF\xab^\x8e\xfd\xb9\xeb\xc6b\x94S\xf5\x7f\xee\xee\xfd6#\xad\x00\x01\xf2\xa9\x80&\x00Am\xc5@\x10\x18\x00\x80\xc0#\x00\xb8\xc0\x13\x00D\xc1\'\x04\xd4\xc0\x18\x02\xa0\x88\x04c\x01\xb8\x0f\xf3\x19\xb4J\x83\x13\x15n\x03m0\xdeS!\x80H\xb3\x07\x80\x07\x13\x07\xe4Ec\x13\xcc\x03\x13~\x85\x02#>\xb4\xde2z\x07#\x1brv1[.\xf3\x0e g1@\x0c\xb0p\x92\x98\x07\x00\xa9\x80\x88\n(\xaa8#H`\x006\xd0#\xb1\x0c\xaes\x00\xf0\x15K\x97m:\x16\xc1\x80\x001\x06\x01RM.\xe7\x10\x1a\x07C\x00*\x9a\xb6) \x90(\x04K\xe5,\xd6\x18\xa4m\xa07m\xfe`4\xd4\xed-\xfb\xdd,\xb7p\xc5>S\x11\xdaI}$\xedl\xe7o\xd9\xe7r\xfd\xeb\x1cs\xddJJk\xee\x0c36\xc2.K,\x14\xdb\x92\xf5\xf7\xf4\x93\xae\xa3\x9f\xea\xaa\xcf\xd0-\x00\x00\x00\x80\x7f\xf0\x02\xac\xb9T\x07\x8d\x82\x81# jh\x00\x07\x19)0\xbe\xe3\xd7\t\x01\x06\x12\x91\x08\x05\x12\x01\x8a\x18\x90q\x88\x05\x18\xd88$\x8c\xce\x87N+\xd8\xd2J\x13I\x83\xb3\x95\xf9\x1b\x8dY\xf8\x16\xccB\xdd-.<\xe7\xfeZ\xff\xc3\xff\xff\xf7\xfc\x94T\xb3\xa8>\x92\xed-I\xab\xf4\xb9\xff\xe7w\xbb\xb7\x96\xf9z\xe6w\xaa\xefxs\x9f\xfa\xde\xee\xa8\xa0\x14a\x0e\x96ULAME3.100UUUUUUUUUU4\x00\x00\x83\xae\x8eG\xa9x\x17P\xc0\xbc\x03\x93\x988%\x8c\x1cAd\xc0\x90\x0eH\x00\x98\xc1\x945\xcc\x16B\x04\xc8N7\x8e\xa0\xd6\xa4\xc5\xc4B\x8c\x0e\x00\xe4\xc1\x0c\x0f\x8c\x15\x82\xb4\xfe\x81\xd4\xcc\x0b\x88\xe48\x16A\xc1\x10ad\x0f\x07|\x99\x84\x18Z$\xd1L\xf6\x9c\x96R\x86\xde\x19\x82\xa9\xe3\x90\x08\x90\t]4\xec8B\x81X-c\x0e\x8a\x84\x16\x9f\rKw\xa4U\xffV7F\x0c\x83Z\xdbY\x8b\xd1\xb4\xb6\xd7\xe2\xdb\'j\xf0\x8a\xa3\xcc\xed\x89\x89\x01\x04\xec\xfa\x90\xdc\xab\x99\xaf2\xca\xc5IBY\xf65\xb9\xb9Q\x83b\xa0\xe2/\xd0\xb3\xed\xed\xd1\xfc\xdb\xf4\xedg\xea_J\x0f\x00\x00@[h\x02\xbc\x85\xdf\x10\xa0\x04@A\x81\'Gq\x90!\x81\x9c\x87\x1b\x16\x85\xe4g\xc1X\x98\xec\x14c1H\x90$\xcf\xa8\xf3\x9a\xb5\xc1D\xc3\x1a\x8d\x80\x02\x83\x88\x84\x0cL\x04C"\xf1\xaf\xf6r\xcd\xb8\xc4Ys\xc6\xfcN\xf3\tD\x13\xfa\xae\xc9;\xea\xc2\x0e\xd8\xe5\x94FdR0\x158*o5\x033^\x1d]E\xdbM)kR[sk?\xca\x85\xa4\x16-(]\xbd\xa2\xff\xfb\xd2d\x93\x00E\x829\xc7S\xdaLPw\xc6\t\x1ac\x89>T\xac\xb3\x1bM\xff\xa8\x81\xe3\x98d5\x9e\xa4\xf0\xd4\x91,\x00\x04\x81\xf5M\xc8\x93\xd4`\xe1\x06\x0e\x18e"\xc6 tgB\x06\xba\x8e\tF1\xfc\xb3\x02\xa0\x05S\n\xb4,\x13O\xb4!\xe3\t\x9c\x04\x12\xb01\x87@F0\x05\x80\x194iE\xbe0F\xa00\xe4X\x04\x87\xa6\x84\x82\x03\x80@\x04\x15AT/[+\xa7*\x17\x85\xb8\xc7o\xd6\xe0\xf0\x1d\xf7p\xc1\x00DA\x85\xab\xd4\x8b\xcchB\x97a\xf5R\xbbzEIj\xc0S7\x16\xb4\xe9\xe0\xfa9\x13\x8e\x8cF\xc5\xda\xf1Jz\x97l\xf6Qf[$\xc2]A\x95.\x18\\\x02\xb0&t\xdb\xbf\xb9)\xfcKw\xbf\xff\x17i<S\xd5{X\xcd\xa1\xd0\x03\x03}\x00\x15\x141\r\x95\x10l\xc6\xe5M\x04\xaa\xba;\x85\x05C7D\xa3\t\xd9\x93\x1dM \x10\x06\x97F\x1a\t\xa65\x0e\'\x0fR\xc67\x82A\x00\xebV2\x01=0 \x0b\x1c\x03\xa0\xe6\xb6\xd3\xe0(\x0e\x96\x18P\x15\x05\x8f\x90\x91\xaa\x9easH\xf1N\x9cc\xe7,\xc5\x03\xe9\n\x02*\x85G\t\xce%\x8c\x88\xae\n\xc0\xa1\xca\xb7\nQ\xa7\x89,\xa4b\xec\xf7\xb6\xce\xda\xc4\x96I\xdfR\x15LAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\x03@\x02\x80\x14\x90\x1b\x06\x02@\x00\xf4\x1a\x05\x18\xf8$\x1d\x0cY\x1cF8\x9b\x14z\x98/N\x98\x1c!\xb9\x18N\xb1f\x9a\x1d\xeaG\x18@\xe1\x8c\x98\x0f\x01\x17\x18\r\xe0{\x18\x05\xc0\x89\x1e\xe8\x08\'\x85\t\x110R\x00V0 \x00\xb90\x8b\x80\x963\xde\xf3\x84P2"0\xa1`p\x9a\xd8\x06\x83Ab\xc3\x11\xe7Y\xc0\x7f\xe6L\xd8\x9d\xdfX\xad!\x17Lv\xdc\xdb\x82\xd1\xc1K\x9dB\x05\xb35\x1ce6c\xb3@\xe5\x98riw\xb3zH\x066\xd3\x98k\xd8\xdbFi\xa3\xf7+\xd9\xce\x9f\\\xdd\xf8\x8c\xa7\x9b\x9c\xb7<\x13\x05\x8a\x11`\x8a<L\xc1f\xb5\xe9\x81\xc6\xa0\xbd\x8dB\x9fK\xcf\xfa\xa7\xd94\x92t*\xab\x91j\x02HM9W\xees\xea=s\xd5h\xebh\xa2\xd1\x80\x00\x00\x0e2I\x9f\x8b\x8a\x044a\x06\x99\r04KJ\xe6\x9a\xaafaa\x8dxa\x18\xad\x0fy\xc7\xc08\x18L\x05i\x82\xd0\x1d\x18*\x81!\x81x0\x19\x85\xb5)\x85\xe02\x97\xe0\xc1\x00\rL\x14G\xb0\xc0\xcc\x08\xc6\x80\xa5\xaa ){\x17,\x04\x001&J\xd4\xa3\xf3YG\x1b1\x1d\tbr\xe9Q5\x97:3uc\xfc\xa1\xde\x81)1k\'(\xae\xb9f\xd4\xb3\xdfj\xf9\xc4q$\x84\xfc\xab\xcdD\xc5\xa6\xbb;\x9f\x8d\x8a\x97\x9a\xedb\xb3w\xff]<W\xff\xd0\x00\xac\x90K\xb2^\n@\xb0**\x0f\x18P\x10\x9a\x14-\x19\xceO\x19lV\x99\xf91\x981\xa0\xe6\x18\xaa\x07M\x9c\xc4\xc4\xa1\x18\xff\xfb\xd2d\xc3\x8cFl)\xc2\x13\xbf\xda0\x91e\xe8\x9ak\xccL\x15\xbc\xa5\x0en\xffh\xc2m\x13\xe1I\xbfu\x10\x8a\x80\xce\x980 M\x18\x0f@\x0e\x18\x08\xe0.\x9c\xc0\xa3e\x18!\xc2\xf7\x18\x06@2\x18\x05`C\x98\x03 \x15\x99\x92Y\xb8\x8c\x16\xd0\x80\t\x1fC\x81\x90\xb6C\x0b\xb0\xcd\xa7\xa9\xa2\xa6"M\x10\xb6\xf4,\x19R|\xb6\xf1\x8c\x9a\xf0\x88\xa4\xd0\x80\x1bX\xd6\xb2&3\xaf}wNX~\xe0\'\xeb\t\xd8\x01\xfb\x83\xe0|\xafg\xa9\x05\xdc>\x9eSj\xa6\x16\xb8\x1c4\x02\x9d[\x84I\xecF\x93\x1e\xcd:tuo\xeb\xb9\xe9\xee\xf3\x9b\x16\xaf\xac\x06\x00\x17\x92h\x01\x01\x01 \xc6\x12\x08[3\x99\x000r\xd3\x0c\x065\x8d\xf3\x0equ1`wC\xc4Ds1\xfc\x0f\x03\r\x90\x91X\xe6\x06 \xe2a\x95\xe2\xc7\x0f\x8c\x86\x04\x06\xc6\x14\n\xe6+\xe2&J\x12\xa9\xe8\x98"\xa0\xf8\xa8\x0e<\x03:"\x80M\xb8\x1a\x9eY\x11\xae\x90\xcf\xecN\x01}]\x89m\x05\xf8\xd3\xc2\x8ds3u\xb5#\xb1\x87n\xcc\xe7\x96\x13\x18e\xba\xdb\xb3Z\xd7\xfe4\xd9\xff*\xd6\x89\x9eg\x87\x0e\x9fU\x08\xaa\x83$^\xca\xae4\xcb\x16\xdf\xb3\xf6\xae\x9b~%F\xef0\x84~\xaf\xa3\xeb \x00\x0b\x08$\x86\x00\x84\x05\x87\x06#)p\x0c\xbc\x04\xfcm\r\x8aq\x0f\xce;\x94\xc1\x95\x08\x04\xc58@\x98\xe6*$\xc4\xc4\x82\x05(\xc1]\x02\xe4\xc0\xde\x00\x88\xc0u\x00\x9c\xe6<\x07\xf4\xc1?\x16L\xc08\x02,\xc0\x7f\x00\xb8\xc0\x80\x01L\xdf\xbc\x0b\x03\x04\x82\x1e\xaa\x11|\xcd\x89\x034,\xda\x12\x14\x1d\xc0f\xeb\x81\x12\xc7\x1b\xaf\xc7n0\xc4\xccu\xb0\xf4m\xec-\xe7G\x01:\xac\xd2\x7f\x0c\xc2\x14r\xfaD\xbdoD\xadwJZs\xab \xa6\xa5o\xb9Z\x8aE\x84R\x1f\x9c\xa6\x94K\xeda+\xc4\xb2\xa8V\x05{\x9c\x97j]r]g=\x16\xd8k\xc5\xb41K\xf7b\n\x857u/\xff\xf8\xb9\x00\x00D@"\xf31~S\xdc,\x1c\xda\x877\xf2\x0c\xd2\xd3V\xa8\xc7q06\t\xd3\x06\xf6,8\x8dI\xf3\n0\xe20p\x00\x93\x02\xf0.\n\x81\x01\x8dM\xf6\x86\x16\xe8`0\x82@\x00\xc486\x82\x03\xfc,\x04\x08NT/;\x13j\xd0#{[:\t\x7fXK\xc7,\xd8L(\x97\x1ah-\x11\xac\xc5\xe4\xb1z\x98\xd9\x88\xe8=%8Wf\xa3\xfb\xcc\xcc\xec\xf6<\xc0*\x07q\x97\x0b\x91\xffc\x7fG\xbb\xd8\xe5\xca\xa1\xfd_\xd9\xfd\x9f\xff\xd5\xa4\xd0\x006\x07\xf6"\x0c\x14\xc2\xf8\xc3\xb0\x1bL\x98\xc38\xcax2LkA\xd0\xc7\x88\x07\x0c\x8a\xc3\xe8\xc8X/AI\xdcfN\x08\x86\x8e\x02\xe6q\x0b9G$f\xe6k<3&g\xe5Td\x9c\x8f&=6\xb4y\xbbqF\x9d\xed\\bn{\xa0S\x0e0L#\xf3-b\xe3*\x1c3,YC/\x95\xf3p\xe8\x83\x85\xe5cl\x1f\xf3hZ\xa3e\x16S^\xd2\x03V\x8esMK#D\x88s;\xc3c8\xc6 U\xd1iE\x0bE\x89\x80\x0c\x1a\x11\xc8\x86\x08\x00\x02\x00\nF<\x95\x04\xe5\x9c\x04\x81\x06\x04\x03\x03.B<\x1c9\xe6\x91\xf1\x97Na\x05*!\x10q\t\xe0B\xb3\x0c\xfc\x0b\x10\xc3O1\xb3\x0c\xa4\xd33 \xce\xff\xfb\xd2d\xff\x80E\xb5)C\xbb\x7f\xd20\x89$\xf8wk\xccL(\xd5E\x15OwP\x82\x99\x10 \xc1\xbf\xf1\x10E3\xee\x8d"\xf3L\x9c\xcd\x9c2D\xcchb\xe2\xa7\xd6*ZD\x193\x86\x80\x8f\x06"\x12L(\xa0a0\xf1\xe1\x02A\xd0\x8d\x1a\x15\xfb$u\xe5\x9a\x7f\xdd\x87\x01\x9d\xb0\x06\x06\xc0\x18\x1a\xf0dl\xc1\xb2=pd\x96\xb7+\xcdG`\x17\xdaS\x12\x94\xca\xa32\xe9l\xb6\x9a\xcd\xfeo.v\xd5\xea9\xcbs\x92\xfaKy\xe1\x9e\xbf\xf9\xbc0\xafR\xbdK\xb7.\xe4\x15\x0eTH\x194\x1c4\xeel\xc8\x8cT\xe0\xb6\xb5\x0b4\xe9\x9f\xbcu_E\x12D\xc5\x93\xbd`\xc0\xd1\x10\xa1\x91b\x15RL,\xc0\xd1\xc6\x0c\x17 \x07\x8c+\xb1w\xcd\x8a\xf0\x8e\x0c%\xb0\x0e\xcc\x0b\xc0+\x0c\x0b\x10!K\x00X\x185\x89[\x1a\x96&a\x00A\x8cBF\x9ds\x1a@\\a\x10\xc8\xf0\xd4hz\xd4\xcb\x9c\x9a\xcf[\\\xb5\x1d\xa6\x8ed8\x00\xbb\x8d\x9a\xf0\x14=&\x95\xc3M\xd4H)9\xdf\xa6i\xf7\xf3\xcf[\xdeu?\xeb\xa8x6\x02\x10Z\xd0\xa5\xa2h\xe7\x96PQt\xb5\x95\x91c\xac0\xbe\xc9\xc5\xa0:\x93B\x89\n)\x12\xacI\x84\xef\xa9\xeeU\x82\xcdx\xbc\x83\x089C\\MHc\xdbY]\x9d\xcaR@\x00\x17\x1aI\x18\'\x00\x98\x00\x05\x15i\x80\x00\x0e\x18\r\x00a\x80p\x01\x01\x83\x80\xc1H%\x8c\r\x81\x14\xc0\x9cC\xccU\xc5\xdc\xc9\r\xf2L\x16\x14\xb8\xc9\x08#\x85\x804\xc14)\xcc*\x08@\xcc\xd5\xab\xcf}x\x12\x10d\x86\x06\xa4\x86f\xa2`\xa4\xb1!C\x10$0\x00S\x13\r,\xc1z\xd8\x9ac\xb6\xec<D\x08\xa6\xaa.\xce\x1ew\x12T\x9d\x90\xaa[\x8e\x83s(\x14\xa4\x96[\xc2r\xa5\x05\xe8\xa5\xab\x14\x17\xb2\xbb\xcf\xa3\xb1\x1e\x93K\xaa\xccJ+\xd9\xdd\x8cp\xadO\xce]\xfd\xeb\x1c\xb7\x9dL\xee\x130o\x95V*\xc5\xd1\x7f%\xa4b\x11\xfa\xee\x97\xf7\x94b\nw5r r\x00a(\x06f\x03@l\x1c\x02\xa2\x00\x160(\x01#\x00\x00`0\x1e\n\x13\x020@0)\x0b\xb3\n\x80!0\x1a\x0f\x03\t\xa3\xa45\xceM3\x13P\xd90\xd3\x05s\x01\x00\x8b1\xe7)s\x94w\xfe?\t\x18\xea\x95\x83,\x1e\rQ\x063\t4\xc1\x84c\x0c\r\xcc*\x1c1\x19\xac\xc0D6^b\x10Yf\xcc\x06\x03 \x05\x15\x80\x84\x00B\xa0\r\x90\x98\x00\x04\xe7&\xa4H\xa8\x10p\x1a\xeb\xe0\xf3\x88@)\x89^\xc4\xfc0\xf8\xc8\xe3\x10\\\x99\xff\xce\xd4\xb6\xdc\xe5\xd9\x87\xeeYnWM3M(\xa7\xb9\xcc-\xd1Sc\xbc\xafk\x99r\xa0\xbb\x0e\x12n\x1b\xb39>\xc7\x90\x9d\xa3}5\xde\x97\xed\x16O=\xdd\xf2\x01?m\xba\xbb\x87t\xf1~\xb6\x80\x00\xd0\x00\x00\x00\x00`-\x00L`\x0b\x81\xfc`Q\x00\x98`\x15\x80 `\'\x80\x1e`\x1a\x02X`\x1e\x01\xbe`\xf4\x1fN`y\x81\xe2`\xbc\x0f\xa6`\xa4\x03\xe4a\xeb\x02\xd8h\x02\x07\xfcb\xe0\x16\xb4h\xbf\x03\x04a1\x9b\xe8f\xf6\x00\xc4`\xf9\x84\xb2\x06\xcf\x8dH\x19\x97!\x00\x7fD\x86\x81\x94rH\x074M\xe0\x18#\x01\xa0b@$\x81\x8e\x90\x16\x06\n\x80\xd0\x18b\x01\xc0`dF\x81\x87\xff\xfb\xd2D\xf9\x00\x05\x8b.\xc4\xbd{`\x00\xc6\xc5\x98R\xafp\x00)a\xe5\x08\xd9\xfb\x00\x05c\xc5 \x97=\xe0\x00a\x02\x06V\x848\x18\xc3\x0e\xe0b\x90!\x03c\x00`\x00\x00\x01\x80\x80,\x16R\x02\x80\xf0\x1c\x15\xc0\x10\x10\x06Y\x02A \x0c\x03\x81p\x98,\x01\x80\x88\x06\x01@\x18\x18\x12\x00\x81\x97\xc7,\x88\x80 \x1f.\x85\xd4\r\x14\x80\xc1\xa0\x1a\x00 \x1e\x16\x80\n\x00\x817\x93\xc4\x05\x11\xbeA\xa5\x11\xc4\\ \x05\xe7\x0f\\a\r\x91\x04\xc4\xe6N,\x9b70R\t\x18&\xa3SvQ\xf1e\x97\x14j^ \x89"n\xeat,\x9a\xcf\xa2\x94\xdd\x9cv&\x81p\xe9\\\xfa%\xfd\x93RM\xba\x94\x83"\x9a\x97wr\xba\t\xa6q\x04\\\xd0\xd5\xebZl\xea]\x99\x1b\'\xd5\xa2\x99\xfb]\x05\xa9\x04\xcf\xbb\x1b\x9b\xd6\x95\xd6\xeaGI\xec`l\x82\xfb\x7f\xfa\xdd\xd9\x95A3\x84\xc8\x0c\xfc\x80\x10\xe0\x80s\xc7\x00\x00\x90\x00\x01\x85\x80D\x18P\x04\xb1\x850\x1e\x18%\x02\xa9\x82h%\x98/\x80\xf1\x85\x80\x8a\x99\xdd\x8ba\x8b 9\x18a\x06Y\x8c\xa0\xa2\x19F\x1f\x99\xa9\x99a\x997i\xb9\xa9\x890\x99R$9\xb4Xg\x18\x1cEa\xbd\xd19\x98\xcb\x0fy\xc1P\xf7\x99J\x84!\xa4`\xc6\x98\xbf\x89\x81\x888[\x18_\x83Q\x85\xa8N\x98\xf5\x81\xa9\x87@4\x18:\x80\x91\x82\x80a\x18\xa4\x82i\x85\x00]\x18(\x80\xc9\x83 \r\x18\n\x00!\x80@\x08\x18\x1f\x00\x00\xf0.\xa8H\xf0\x0c\x02@\x88\x12\x04b\x00\x1c02\x00\x80\xb0\x12\xa1\x1a\x99:n\xf0\xa0\x05F\x13\x8dly\x810\x08\x0b\x01\x12\x18\t\x00\xe2\x95\xe0\xc0id\rw<\x1f\xf8}\xab\xda\x85\xae\xb6\xfd.Vz\xa3\x86;\x85L\';b9\xde\xf2\xaf\xe1+e\xf2\x07\x123.v)3\xb7\x97y\x85\xedK\xb5*\x97a\x8e\x1a\xdb4\x91\xe1\x18\x99\x87\xe4veuu\xad\x7f\xf3\rg\x9f\x7f\x1e\xf7=\xe3\x9e\xfe\x1f\xe7m\xd4\x96~T\x93\x99\xf3\xbf\xfc\xd6y\xe1\x97q\xcb\re\xdf\xc7\xf1\xd6\xbf\x99s\xf3\xee\xefco\xf9ow\xb7\x9e?\xac\xb1\xa9\x9f\xf7\x1d\x7f?>k\x1e\xff\xff\xff\xff\xff\xff\xff\xebx\xeb\xf0\xff\xee9\xeb>k\xff\xff\xff\xff\xff\xfe\xe5\xee}\xec/\xe1\x9eye\x7fx\xdcP\x00\x0c=\xf0\xa1\xccH\xc1\xb8\x8c! \xa5L\x16 \xb0\x0c\x13@8L&\xc0p\x8cE\x91\xbcN\x04D\xe2\x8c!\xd2\xc6\x8e\xca@\x83\xcc:p\xbe\xce\xbf\xa0\x80\xcc_!\x97LtR?\xcc+\x00\x1a\x0c\x0e\xf2e\xcc\x1e\xc0\x16\xcc\x1e\xa0z\xcc\xbfU\xb2\xcdsrXL\xa7f-N\x8d$\x17\x8c\xa9\xa3S\x0fU\xe2iLz\xc1\x8a\x0c\x07\x80\xb2\x0c"\x90\x8d\xccA@\x85\xcc\t\xd0/\x0c\n\xf0\x05\x0cc \xaa\x8c\x04\x80\x01K\x00\x0f\x18&\xc0\x9a\x08\x00\x060\x0e@`\x10\x81\x028\x01\xbdS\x03$\x01\x00\x80\x03\x81@2\x05\x00=0\x10\x80T-\xe9\x80\xc8\x04\xd9\x80*\x04\x01\x80h\x00I\x80\x0e\x00\x18@\x07)\x1a,\x00\t\x80&\x03\xa8\xf0\x05\x8dj\xcc\xbc\xc0\x15\x01p8\x00\xab"@9\x98\x06`\x1d\x18\x07\x00\r\x98\x03`\x01\x18\x00\xe0\x06\x00@\x05\x14\x00\x05\x16\xd9d\xae\xbc\xb6\x1e\x02\x00\x0b#\x9f\xff\xfb\xd2d{\x00\x0c;nC\x0e\x7f\xe0\x00\x84\xe3\x88\xd2\xce\xf0\x00\x1b\xb0\xb9\x12}\xff\x80\x01\xdf\x15d\x0f\xb7\xb0\x04\xcb\x13\x00 \x00\x80\xe0\x00\x04\x80\x17\x1a\x00\x01@RY\x06\xdb\x93\xc5/\x94~_\xcb\x99\xe5\xcf\xe2\x08R\xd1[\xe7\x98\x8bNEe\x85r\xaa\xd9\xcb\xbfV\xaf1\xc7_\xcf\xefw\xef\xb3\xbe\xba\x1b\xc6\xfd\xe4}^\xa6\xee\xdc_N\xe3AM\xdf\xee_\xbew\xbf\xff\xdf\xdf\xff\xc4\xedC\xb2&\xbc\xfe\xca\xa5R\xb7rQ\x17\x96R\xc4\xbf\xfe\xad\x9f\xefw\x96\xbf\x9f\xcf\xef\xff\xff\xf3\xff\xff\x7f\xc9\x98fUKV\x927O9n\x9aSj\x1e\xa5\xb5\xf8t\xd0\x08]*o\xf2\xc0[\xce\xb5`\x00\x05\x08t\xec\x0e\x00%\xec\n\x02\x02\x108\xc0\xc0(\x02\r\x98\xc2\xf0\x18$\x0f\x18\';\x182\x05\x18\xaf\x1a\x13\xf0\x06\x0f\x95\'"\x1a&\x1c\x8e\xc6\x0e\x04f \x06\xc0\xf00\x94L\xd2\xa3\xc3\x16\x81L\xb0F3 d*\x1e"+\x96\xf08r\n\r\xb6\xe6\x0e\x00\x83A\x89\x01\x02\xcc\xbe\x12\xd4\xf2\x82\x9e\xa9s\xfc\xd9\xe2\x12\xc6E\xddg\xf0l\xb7z\xfb I\x83\xec(\x1a\xa1\x8eA\x1d\x1d5S\xf6[\xdd\xab\xff\xd55\xec\xeb\xf7\xfb\xc0\n\xb4\t0\x18\x00\x13\x00\x00*`\r\x80\xe0`[\x01f`\x05\x80\xb2`\x0e\x00\xb0\x01\x03\x04\xc1\xd8\x04\\\xc2\x1cV$\xcf\xbe,\xd4\xc6\xce\x0fT\xc22\x00X\xc2\x94\x02\xdc\xc0{\x03\xe8\xc0\xa1\x03\xd0\xc0\x9f\x00|\xc0\xa7\x03\xf0\xc0D\tX\xc1\x1a\x02\x0c\xc1\xdf\x0f\x08\xc4\xbd\x14\xd8\xda\xfb1\xd4\xcb<\x1b\x14\xc2V\x05\x14\xc0\xb4\x01<\xc0\x81\x02\xd0\xc0c\x01`\xc0J\x00\xac\xc0F\x00\x08h\x00\x83\x00<\x00\xc5e\x03\x00\x10\x80\x00\x80\x00\x131j\xc1t\xa6\x00\xa8\n`\xa0\x13W\xcb\x93,\x97B\x1d;z\xa9N\x81F\x01\xc0\x01\xeaZ\xd6\x9ex\x1e#\xaci#\xf5\xe5b \x04\x97ugY\xfe\xa9\x0c:\xd3\x17\xec\xd0E*U\xa0\xcf\x0b\x94U0\xc7[\xd5\xdd\xc5\x02m\x11\x99\x02\x021B\xe1g?\xfbY\xfd\x97\x7f\xdf\xf6\xff\xa8\x00l \n\xec\xdd4\xa0Fv@\x0c\x14\x00HA\t9\xe7N\x05\xd6MN\xd0\xf9nL4L@\x02\xe4\x98\xd1\xb9\x91p\x1bjJ\x1d\xcc\x8d8\xfa,\ra\x81[\x01H%\xb3\x14\x08A;\x9c\x10\x08\x80\xc4$=\x92F\xa6\xee\xcc\xcf\xdf\xb3\xa9\x88\xed4\xe4\xbf\x1al\xf3\xb7\x85o\xdf3\xee\x1a\xc3\x0f\xef;\xda\x08\xdc\xa2\x1c\xb7\x85\x9e\xfdzz\xb72\xca\xf6W\x06-\xa3\x05\x85O\xa8\xc7\xb6\xba\x00(\xd0\x01#E\x8e\x03\xa0\xce\xf5(\xc8\xd0\xcc\x888\xdb\\M\t(\xc43\x98\xceVU4\xc2|W\x0c\x07\x01\xb0\xcaD\x11L\r\x81\\(\x0fa\xc1Z`\x90\x02\x06\x18!\x8e\x05\x05\x03\n\xe0[0\xdd\x113\xfe\xed\xa1\x1azs\x0f\x01\x180q\x02S\x05`b:\xa0\x0e\t\x10P\x86\xc0\x84\xd2\xdd0\xf5Wz]\xf8L\x05\x1b\x1c\x8a\x9du\xa8\xeb\xc5\x9fhv\x18\x7f\xa9%NPE7\xce\xdd4\xab\x1b\x93x]\x8fK\x06@)\xebN\xe4;,\x95\xde\xca\xbf\xd5\xa9K&\xa5\x8c\xee\xefp\xb3\xdb\x19Y\xe8\xbe,\n\x8f\x8d\xdb\x96?\xb8\x80\x1d\x88\x01\x0b\x0e\x140q3\x8f\n2\x90\x93B\xff\xfb\xd2DZ\x0e\xc5!-E\x1b~\xd1\xd2\xa3e\x98\xb3o\xd9:S\xd8\xa7\x12N\x7f\x87\n\x91\x15b\x8d\xcf\xf0\xe191"\xf37\x961B\xc0\xd3\xb14\xf51\x07\t\xa3\x06\x80\x0c0\xf2\x0bS\x03\xc0\x050\t\x03\xf3\x00\x80\x170q\x03c\x08\xa0\\0\xae\x00\x83\x000:1\xb9\x0c\x93\xeb\x8dk5\x07\n\xd3\x11\x80\x1f\x05\x06y\x80\xb8\x0e\x1eb\x9b\xe5\x83\xa1\\\xe2\xa1\xb1\xd2\xb0\x9a\xc2T\xb0\xd8~Y\\\x83\x94\xc3\x8c\xd6\xad\x95=\x1c\xec9/\x86a\xa0\xcd\xe4Y\xc2\xedQ_\x94\xe79v\x90Te\xf9+q\x1d\xfb29\x9d\xde\xb9\x9f*K\xe1\xd8\xcf\xd2s\x1b\xd5\xa9\xf8\x88s\x18\x0c\x9a\xfau\xfe}\x01;T\xd4 "qB\x90\xe8\x00\x04n3\xb0\x00\xd7&\x13\x08x\xb4\xf3aDC\x93\x07\xb4\r\x00h*&\x0c\xa8\tF\x02`\x07\xe0P\x07\x0b\x00%\x89\x00\xf8`q\x00\xba`G\x00\xec`\x06\x02\x06`?\x05\xe4eN\xaax{\x8dA\x8c[&0\x1b\xa6\xd1\x85C\x86D\x08\x03\x83a\x04\x06\x9e\x8a\xc4@E\xdc\xb6\x9d\x9d\xcd\xc7\xc1\x022\x82\x9b\xb3K,\x8f\xcb\xe0\x98\x16]o\x89N`\x00\xa4wjq&\x97X\xbb\x1c\xb9\x9c\xca\x13\xd2\x07\xb0-\xb9$f\xad\xfe_\xd5\xdb\xff7{U0\xc8\x14o\x82\xe2:\xf8\xfe\xc0\x0e4\x00SP\xb8\x14\xc3\x81SJ\x00\x80\xc4\x81\x08\xdc\xce\xc7#R\xc5\xcc(!\x9a\xcdkPWL\x17\xd0M\x0c\t`\x03\x8c\x02\xb0&\x8c\x03P\x16\xc1\x808\x13\x00\x1e`\x11\x00\x94`"\x01\x0c`\x1f\x00l`2\x81\xc2`u\x05le\x07\xb2(},\x91\x91Z\xe6\'%\n\x86\xc2\n&\x02\x0e\x16\x91(\xd1u\x9f\xa6\x04\x9d\xfdm\xe4wg\xc0\x01r!\xfc\xb2\xa5\xba\xf4\x95\xe4\xd4\xd8WO\xd1\x80e^1H\xad\xbb\x1a\xa1\x9a\xceR\x97\xe4\xc0\x1c%w\xea\xce\xca\xf5\xba\xdf\xf5\xeear\xa6\x1fu\x82\xf2k\xde\xf3y\xda\x9d\xde?\xbf\xca\x00\x90\x00(\x10\x01\x05L*\x1d\x8c\x89b\xcc<\x19\x8c\xa11\xcd\x08`\x0e\x03\xd1Lf\xc38\x8e\xf9\xd1T\x8c 0\x06L\x0f\x00_D\x85\xe906\x00\x1e\x11\x00x\x0e\x05\x10\xc0\x95\x03@\xc0\xa5\x04p\x90\x0c\x13\x02\xfc\x18c\x030]S,/3s\x08X:\x13\x02\xec\x16\x00\x08\x1f\xa6\x018\x15\x07e\t\x80\x92k\x84\x98#\xa0\x00\xc8:\xc8\xd5\xf1@{Oc\xa2\xc1\x8c\xd6\x80\xf8\xcb\xd6YE\x1b\x8b\xc4l\xe7\x85\xa1\x81\x07\xa1:\xd4\x86\x1ey~7\xb1\xb5\xf7\xa5$\x86c\xbb\xa5\xbb\xb9u\x8c?\xb8\xe3\xber\xc6\xebyA\x03\x1d\x10,\xda\xe3\xfd\x1e\x11\xebg\xffV\xc7\xd7\xe9\xae\xc7\xf7\x0f\xdf\xb7\xdf\xeb\x8d\n\x90\x00\x00\x06f\xa0\x01,XB\x00F\xd0\x89\x9d&-p\xd33\t:\x16\xc1\xce\x1b)\xcc-\x00L \x0e\xc7\x83r`%{\'\x19@&bp|`\x88&ap\x12`\xd0\xa8s\xa7\x00d\xb9,\t\x04L\t\x02\x94\x02\n-\xf2s\xc4k$\x02\xb5\x1db\x98`\rH\xf0\x9e\x99\x97mx\x1e\xdfB9\xe9\xb5\xde\xfc\xb3]\xa5\xd7\xfd\xd87\x9d\xeaL\xefG\xd7\xec\xb5>?\xdc\xee\n\xe8\x1a\x00\x18t\x00\xa9H\x10E7L\xda0\xc8b1\xa4\xbb3YD7\xf7\x931\xff\xfb\xd2d\xa4\x8cE\xc8*C\x13\xbf\xd1\xd0v\xa5\x88\xedk\xac<Y\\\xa9\nN\xffgA\xd9\x12#)\x9f<\xf1\x9e#<6\xf6L"0J\x82\x170\x1cB\x140\x8c\x01q0\x10\x80\x140\r\x81\x1b0 \xc0\x9e0\x07\x00\x950\x1b\xc0\x920b\xc1\n0P\x01\xbb0\x9bD\xba8\x91-\x822[C\x980\x86\x81\x070&@\xa80\x10\x80/\x04\xaa\x1a\x08\xf1\x94\x99\x15B@\xc2I\xc7]\x15\x90=\x9bO\xcb\xd0(c\x88\xc0A\x16\xcdh\x8eVd\x93\x99V\x81Q8\xe4\xc5U\xae\x03R\xe7\nv\x11\x04>\xef\r$\\\xc2\x8a\xc6\x94\xe1?k\x18\x8d\xdc\xff\xbc\xe71\xd6z\xb9\xd6\x8bN\xa5>\x9e\xc9D\xf5\xaa\x8fZT\xad\t\xda\xf4\xa5\x04\xed\xa1Xu[3\xc7\t\xe9\xf7\xab\x16\x8966\xc8\xe004;\x00\x02*\xa1\x8d$}5\xe0\x87\x03\x9d\x03\xdc\xc3\x08\x82o5\x03\n\xd3\x080L\x15\x01\xa3\x04P\x05C\x10H\x06$\xd0\xe8\x16\x18\x07\x80\x88@\x19\x18\x01\x01A\x810\t\x9a"\x8c\x99\x88\x105\xa7Q\x80\xa0\r\xaa\xe5\x02F\xe5\x84e\xce\x08\xfcz\x9ad\xbb\x1a9H`\x82)\xc9\x91X\x9d\xbf\xde\xed\x9d\x9a\xf9\xf4\xf9\xdf\xf7\xd5\x18#\xcdXV\x9by\x03,d\xab7\xc2>\xe7rLAME3.100\xaa\xaa\xaa\xaa\xaa\xaa\xaa\x80\x005\xbf\xb0\xa2\xc9\x87>j\xe5\x98I\xe7.\x08\x93\xa3\x01@`0\xe0\x16\xe3\x19h\xa05\xa62\x03\x1d\x80\xc40T\t\x83\x00\xa0\x1f0K\x04\x13\x05\xf090[\x03\xd1\x90\x140@\x06c\x0b\x10\xcb1\x1d\x16s\x17Q\xa98\xfd\x0b\xb3?A\xb80\x94\x03\x83\x03\x80\x000\x1f\x02\x936l\xe3.4\x07\x8d\x01\x83 0\xc3\x081\x01\x8c @\x10\x02\xec\'\\\x9d\xc0,\x12\x01\x14,\x81f\x10qt&\xbc\xbe1IB\xed\x85\xc4\x8c\x16X\x88\x07G\xb4%\xa0\x1d\x15\xd4\xdd\xc7\xb5\x0c5\xf8\x19K\xdd\xf57k\xec\xeda\xd0\x0e\x02\x00\x02\x00Z\x04\xe8\x8a\xabyl\xc0 @\xc0\xcc@"\xcc.\x89\xca\xf6\xa5\x0e\xc38br7A\x13\x0b(`\x00\x00\x80 \x01\x82K\x9c\x85\xd8\xbb\x1a\xe49\x8e\x14\x8dma\xd2\x1d\x07\xd2-u\xc0\xf1\x06\x18\x8a\xe9\x16\xef\xc6\xed\xf7\xf7O\x0cC\x91\x8b\x18\xca\xdf\xf7-\xdfw#\x17\xb3\xa7\xb7\x9e\xb0\xcf\xeaRF#\x11\x8aNaIIII\x87\xff\xe7OOOO\x9e\xaaRf\x0f\xbf\xc4\xe0\xf9\xa9> \x04"C\x9f\x90\x18\x0c\x03\xf4\xb6\x92_\xaf)R\xc7!JU"[\x98\xa0`/\x92-\x9a\xfb\x01)\xd1\xc59b\x0bH\x84\x05]|\x18\x1c\x06wF\xe8Nl\x95\xfe\xaf"\x9b\xabf\xe2a\xc3\x89\xc1\x07\xd0\xc3S|\x11\x10\xc7\xb0\xa9)\xbdg\xach\t\xb7\xf8\xcd"9\xda\x95\x86\xdb|%\xe8\xef\xc8\xa5^\xfb\x7f\xfeC\xbb\xd6\x00\x17\xfdX\xc8\x16`\x90&[\xd0\xa84aH\\b\x08\xc0c\xa8\xe8d9\xd8k\xec|j\xd1\xf6i\xc3Y\x97\nfT \x98\x90\x16\xa6\x06\r\x14\x18\xf4\x84d\xf2\xa1\x94\x8cfL\x13\x98\xb1Vujy\xe6\xa4\xe6\xa85\x99\x80\xa6c\x81\t\x85\x02(\x02r\xa1\xeaj\xc1N\x92\x90\xbd\x08\xf09\x848\x85\x13\xa5SZt\xb6\x9aGR\xba6\xf7\x9c\xff\xfb\xd2d\xf4\x0c\t\x00VH\xbb^\xd1`]\xe4)Js%\x87\x1c\xc9W,n\xf1\xe9B\x90\xa6\xe2M\xed\x96!1+^\xc5\xc3\xe5r\xb9\\\xae{\xacY\x9a\xefU\xafr\x9d-\xa2\xda&\xa2\xe2BT2\x12\x915\x17\x12Z\xa1\x8b\x8c\xa7Kp\xb7\t\xb0\xb9\x17\'%)\x05\x12Qn!GS6k\xa8I\xe45\re\x90\xfe-\xc4\x18\x85\x1aJ\xddB|\xfa7\xad|\x16\x14\xea\x1a\x86\xabb\xc2aV\xab^\xc5\xd7\xf9\xb3\xe7\xcf\xad\x98/X_>\xb7\xadu\xf1Z\xfcB|\xf9\xf5\xa0\xd1\xecJ\n\x9d,\n\x9d\xf8*\n\xb0\x05\x8eI.pQ\x00\xc00\x0b\xc9\x80\x00\xc0\x14\x03H\x00X\xc0t\t\xcc:\x940\xd2\xa4\x86\x80\xa0\xbaJ\t&\x0b h@\x01-Ac\x98\x00\x00@`O\xa9A\x80P\x18\x8a\x03!\xa3;R\x1c\xc4\xe1\x86\x80\x19 3\xce[\xc4\xe6l\x16\xda\x8b\x80\xd6\x99bi\xb6\xf2\xfe\xd6O\xe9\xcc\xe9\xe7\xe9-\xe3\xadg\x9dGG.\xa6\xf5|\xc2\x93\n;:\xc8\xa7\x0c\x01\xce\xeeB\x8b\x8b\xddnr9\x08\xb4\x1e\xf5\xd5\x95\xd7\xab\xebR;\xb7+etF.\xad\xdfc5(:\x1aa\x16\xe9\xbe\x0ex\xbc\xee\x01\xb99,\xc1\xfa\xbeQ\x06\xf8\xb6j@\x01\x81@-\xa3\x01\x81\xf8\x1e\x98\x15\x01\xe8\x10\x13L!\xc1\xb0\xc1\x80\x10\x8c\x1d\x82\x14\xc6\xbc_\x8d\xb1\x81\xf8\xc1\xd0\x08\x0c\x1a\xc2\x94\xc0\x94\x0e\x0c\x0b\xc1\x04\xc0\xb4\x00\x05\x00\xb4\xc0|\x0cL\t\x02h\x98\x12\x0c&\xc2D\xc1\xec,\xcd\x11Q<\xc3h+LUBD\xc2<$\xcc\x10@\xb4\xc14\x07\xcc\t\x80\xac\xc0\xdc\x06\xd0F]\xa4\xcc0\x02\x00\x08\x04\xbc\xa94`\x00\x01\x0f\xfb\xc0\r\x01\x16D2\x00+\xae>\xdb\xbf\xee\xf5\xcdX\xa9\x10\x80\xe9\x1e\x17\x1e3ROC\x06^\xd4\xa9\xf8~r\xdfp\xc2\xf5\\\xe3n\xfc\xaa\xf5\x0e\xbf<;\x9f\xff\xf7\x94\x99c\x9fp\xb1V\xfe\x18T\xff\xef\xfe\x1d\xef\xe5\x85\x81#\x82\x06,Yq\xe5\x130\xba\xd9Rh\xec\x16\xf6\xb2\x99\xff\xfb\xaf\x8cw\xff\x8a\x87\xd8\x0b\x18\x9bC\x03\x03\xf0B\x15\x02\xb3\x02\xe0T0<\n\x83\x0f\xa1\x820\xdesCN\xc1z1N\x11\xc3\x06`708\x03\x94\x9d0m\x06\x93\x00\x10\x1f0-\x04C\x030\x0b0c\x08\xe3\x0f\xe0\r0)!s\x17\x88Y1\x0c\x00\x83\x02 \x0704\x07\xf3\x03\xb0\x140:\x02s\x01\x00\x0e\x03\x00(@\x07\x18\x03\x00\xb08\x02\x17\xba{\xc2S\xf9\x9b\xb7\xad\xfddhCD\xefC&H\x87g\x0e^\xde\xd0\xbb\xf2!\x08\x02/\xe7J\x1a-\xe3\xa2\xd1\x18b\x00\x19#Ok\x8f\x0b\x899n\xce\x12\xb9$>\xf0?\xb3\xf7Z\xdcnjy\xf4\xab)\xa7\xfc\xf7r\xe7kW\x8cQ\xc6"1o\xd6\xed\xf7\x0f\xff\xff\xd70\xfc\xed\x88\xd9DQ\x10C\xe8\xa9\x07\xec\xf9I\xffG%!WJ\x7f\xee\xfa\x80\x00\x00 \x020\x000\x18\xc0i0\t\x00\xbb\x1d\x04\x1c\xc1\x9d\x06\xdc\xc1>\x08\x84\xc0v\x10\xb0\xc1)\x0e\x8c\xc32\x02\xc4\xc1U\r$\xc3\x88\x0b\x08\xc4\xbe%\xd8\xc4\xc8\x8e8\xc1\x15\x00\x18\x18\x05\x89\x85P\x16\xc9\x8cB"I\xb6\x00\xff)\xc8\xba2I\x85\x82u\x99( q\xb1\xda\xd8\x9d\xbb\xff\xfb\xd0d\xff\x80\x06\x919C-{\xc0\x00\xd4\'8r\xafx\x005z)\r\x19\xff\x00\x03a\x9c\xa2g=\xd0\x00\x0f\x91\xa8/\x1b\x19\xea\x95\x19\x84\xd8\x1c\x98\x02\x80\t\x80\xb0\x1b\x19+\tQ\x85\xf8\x1c\x98\x13\x02\x11\x88\x00\xe5\x98\x82\x8b\x11\x86\x98 \x08@x\xc0\x04\t\x85\x80\x00H\x04\x8c\x13\x80\x98\xc0\xfc\x0fL\x15@\xd4X\r\x8c\x0fA\x1c\xc1\xe4\x1d\xcc\x02\x01\xb0\xc2\x1c\r\x19s\xfa\x82$\x06!\xd4\xc0\xc4\nL\x08\xc0m<\xd0\x85\x86\x98\x08\x02)\x80\x18\x08\x18\x11\x80\xb00\x01\xcc\x07\x00e\xc5i\xb8\\\x9bk\xa4@>`\\\x03\x01\x00):\\C\x00 \x020 \x00\x13\x00`\r0\x18\x01\x93\x01\x00\x03\x19\x00\x000\x05,\x0c\xae\xb5H\xf5\xb8\x8a\xbcZ\xef\x03\x88\x83\xea\x06\xd7\xc6\x00$\n\x01\x00\xe0\x06\x8b\xd4`@P\x04\x9d\xc6\xe7\xe5={^\xb1\xd6;\xce\xe4a>\x91\x0f\xc6+\x95\xfca\xcf\nB\xae\x97\x85v\xb1\x1b\x98X\xc7\xbf\x8e\xf9\xceC\x0eC\xb1\x17\xa0\x969o\xfd\xb7\xfd\xff}\x9cfz\xc0\x99u\xfdG\x974F\xa7\xeb\x1d\xe3\x96\xb7\xff\xfb\xff\xfbv*\xdbw(\xbe1\x18\x96j\x92r~\xfc5\x1drd\xd1\x17\xf6\x1d\xadi\xd1\x86\xa7\xae\xd6\x86\xb2\xff\xd6\xf5\xfb\xdf\xef\xbf\xbf\xff\xff\xff\xff\xff\xff\xfdC\xf6\xf2\xa7\xa7\xb7\x8d|\xe99\xd9f;\xff\xff\xff\xff\xff\xff\x87\xabC\xd1\xaa\xb3\xb0T3;Z\xac3;)\x8c\xd9\x80\x05\x00\x80O\x00\x00\x00\x000+\x02\xd3\x08\xe1 \x18\x01\x93\x05\x10@*\x80I\x84\x10\x07\x18s\xa6\xd0\x93J\x18\n\xa6\xc1\x9e0Y\x18s\x9dQ\x9e\xe0D\x980\x02H \x18B\x05\xc4\xc2LS\x8c\x16\x014\xc1p\x11\x8cc}O\x93\x97\x8c\xad\x97\xc8\x97\x83!\xe8\xb3-O\x83\x13\x893\x18\x86\x13\x00\x00\xc3\x16\xc2\x03\x03\x02f`c ra0:\x00\x00GA2\x80=\x88)CBS#\x00\x00U\xa4\xaa\x0b\xech\x06O%|\xb3Y\x94]:^\x06\xf5\xbb>\xc8I\x8e\xf6/G,\xc6)fj\x92.\xce?\xee\xee\xae\xebe\xf63\xa3\xd7~\xd6\xa7gq\xef\xdc\xeeTT\xda\xd5\xcc\xef\xf3\xffw\xb9\xcf\xcb\\\xfc\xef\xed\x8a\x89s\xa6\xf6\xa8D\x96\x84\x18[j\x17\xc9\xed\xee\xfd(\xee\xb7\xff\xa6\x9b\xbf\xee\xa1U\x02\xf8\x03\x00L\x00A\x08\x00EP\x04S\x90\xc0%\x00\x98\xc0u\x02\xf0\xc0\x7f\x04\xd0\xc1_\x04@\xc0\xef\x05\xa8\xc2@\x06\xb8\xc1\xfb%\xc0\xd4\xda\x0b\x14\xc4L\x0c\x84\xc2N\t\x9c\xc2\xf4\x13\x0c\xcc"24\xcbo\n \xc0\xe1\x05\x00\xc9A\xd4\xc3gT\xc6G\x04\xe1\x0c\x08\xd6\xf0\x84\xc3\xe0\xa58\xc1@\xc2\xa2\x1a\n\x982\xba].\xe8X\x05\x0e\x07\x9dxi\x87\x85\x83\xb2`\xf9\xac\xb7\x08I\x82!#k#\xc5UT\xda-M\xf5s\xe5H\x06MC.\x89\xc5\' \xaeV\x92s\x98N\xfd\x05,\xd4C\xb2\xda\xb4\x92\xf9M\x05\xda\xb7{\xfa\xd7\xe1\xf7\x7f\no\xe5\x97e\xd7V\xe9zt\xe4\x00\x00\x00\x94\xac\x00\x10\x01L\xf0\x04\x00\x05\x80\x010\r\x02\xa3\x040p0O\r\xa3\x11\x90\x980\xc7\x01\x83\x06!\xfa2Uuc\xff\x82=3>%S\x1d\xa1\xf92\x08<s\x94\t\x8f8\x9f"#\t0\xee1\xff\xfb\xd2Dy\x84E\x8b1\xc5\x17\x7f\xa0\x02\xac\xe6(\xca\xeft\x00T(\xc7\x18\xee\x7f\x88\x8a\xaf\x18\xa2I\xfe\xa5\xe8HA0\x11o1\xe4n3\xfe\xae1(*0\xdc#0\xb4.\x0c\x07\xc4@\xaa\xe1p\x18\xaa\xc2\xc4\x14|\xac\x03w\xa4\xae\x08\x10\'\x16\x07\x97\x93\xdb\x1a0\x04\x14\x87\x1cgM\x1dQI\xe6\xadwW\xf3\x96\xca\xacQJ\xa4\xd3\x99K3\xa6\xdf;\x94\xee\xabScK?E\xa9\xf9f\xb5\r\xdb\xa3\xbf\xae\xfd\xecq\x9f\xb3\x9d=\xe9\xf2\xfb\xe7\xfe\xd5-_\x10\x01\xbbX\x02\x16\x8a\xe3\xa0\x95`08\x0cB\x1e3Q \xeb\xe4S\tR\r\xc0\x060l\x0b&3e\x83\t0\x14\xc0d*\x00\xd6`\x86\x84Ha\x96$\\aI\x85\x18`G\x012c0\xe1\x9a\x95&\x92\x00\x03b`\x12\xb1\x8bD\xa0\xa0\xe8\xe8UI\xc1H\r]\xcbQ\xaf0\x15\xc3K(\x8c\xaf\xd2\x81t\x86\xd3\xfa`\x00\xec\xaa^\xe4&\xf8@2\x0b\x8dJ\xf1w\xa2\xd5\xabQ\xeaS\x0cN\xf3Q\xba\xb5\x7fu\xa3r\x8f\xa9G\x19\x94\xca\xa3T\xd5\xa4\x13\xd4_g\xb8\\\xdd\xec\xb9\x8f3\xb3On\xa6/c\xed\xf4M)`/@]\xce\xe2\x92^D@#\x01\x80n0\x1c\x01\x02\x08\x10,\xc0\xb4\x01\x98\xc0\\\x05\x98\xc1\xf28X\xd2\xf8\x0e\xb4\xc1\xb0\x00\x10\xc0\x04\x05T\xc0\x82\x11X\xc4\x80pX\xc4\x8b\r@\xc0\x0f\x04\xb4B3\x9ax$\x9aPZ\x98\xbd5\x9a\x0c\x14\x18\xbe@\x14\x03\xa2\x00(0R\x18\x01\x0c\x02\x00W\x8a\x01\x9c\xc5\xf2\x9f\x13\xadj@\x94\x01\xc2\xfb0\xa1y\x8c\x14\r\xe6\xdd\xaae\x1fI\x8aZ:\x98B\xf0\xb2a\x91\xc1\x19W\x08\xc5\x02\x14j\x12\x18Q\x11\xf5U=!I\xf2Utq\x02\xda\x95\xae\xbf\x9d\xab\x1e\x83\x10\xb2\x1b\x15\n\x8a\xa2\xa5\x81\x13\xff\xff\xffO\xff\xfa\xd5LAM@\x00\x05\x11\x00)\xd8\x01\x13\x11\xb42:Z4\xa20L\xc0\x9c0\x9d\xc0\x18\x00\x80\x8a`\x97\x00\x0c`\x1a\'le2\x07\x06`j\x00\xfc`:\x81\xd2`\xd6\x01Xe\xb4\x8e\x00eJ\x01\xac`\xfa\x81\xd6c)\xb2a\xf3l`z\x88i\xcc\xe8b\xe0~\n#\x0c\x00\x02\xd0i\xb0\xa1\xfc\xe4\x99\xac?\xb2\xd2!5\xbb\xc5  \xb0t\x10\x1fR\xccP\x85\xc3\xc8\xcd\xe9t\xe1@\x1bRUS\xe7o\xe5\xa8\xb7cR\x8b\xd2\x98\x06\xb4r\xed\xa8\\\xec\xab\x0b\x12\x9a\x92\x1bUmerI\xff\xceV\n\xb024\x93\x10\x01}\x9b\x9a\xe2_\xaf\xff\xfe\xcf\xff\xe8\x08\x00\x00\x00\xe2 \x15\xb2\x94+\n"\x03\t\x00 \xe0\x84\xcc\x11@\xe5\xf1l\xc24\xd4\xcf"<\xc0\xfeK\xc8\xccZ\n\xd4\xc1\\\x02\x08\xc1\x83\x02\x14\xc1\xf4\x00\xa8\xce\xeb\x0ch\xcb\xb6\x04\x98\xc1\x93\x01\xec-\x195G\x90\xc0\\\xa3\x9a\x06I\x9eFB\x0e\x98X<!\x04\x17\xe1\xd0k\xcf\xc4\x04\xf1\xbd\xa3\xc3\x9c(\x99p \x80\x1c.\x90\xbd\xb3F\x0b\x1dM\xcd\xd2\xb8\x04\xc1X\xcd\x9b\xd5y\x8e1\x8bQ\xfb\xd6\xdf\x99\xc8\xf5\x1dJ\xf4\x12*9u\xba\x0b5\xacw+4V%\xda\xc7w\x12\xa10\x14\x13&\xf1*\xdd\xb5t\x7fg\xff\xff\xfdz\xbd\xbb\x02\xf9\x05\xb3&!y\xd1\xc4\x1c\x05\x91\x05\xa67\x0f\x07<\x81A\x84A\xff\xfb\xd2D\xb2\x04E@+D\xbb?\xe9@\xa6EX\x9aw\xfcD\x12\xa4\x9b\x12N\xff\x88\x82\x85\x14"\x1d\xdf\xf1\x10\xa4\xc4\xe8\xcae\x86"\xc8w``\x0c\x0c\x0f@\x1d\x0c\x04`\xbdL\x12\xb6\xafL%@\xbeB\xc0|\x02\x8c\xa6\xf1\x06\x1a\x1c\xc8`<\xe9\xaf\x80\xe6*\x08\x91\x02J\xc2\xa5\xc2^\xb1\xb6\x04\xe7I\xca\x80`\xe0\x8d,\x89\xf0*\x16\x94\xd2\x16\xf8J\xcb\x03\xd9\xbaL\xc9\x00K\x16\x96WK\xdazlj\xca.OR\xd9\x8a^\xbbR\xcdl\xf2\x96\xeb\x99\xdc\xb1\xdb\xa0@DN\xe6,`\x14\x91g\x87G\xba;\xff\xff\xb7\xff\xfdD\x00# \x10\xea$\xe0\xa8\x00\xad\xc2\x00Xh\x040\x10^;\x94\x123\x8194\xd0902V\xb00\xea\x83\x990\x0c@\xe30#\x81\xbe0\x1fD/0\xd3"\xb50\xb0\xc4\xf30A\x8185\xe20\xea\xe7PZ\x8c\xdep\xc0\xc48\x08\xe2\r\x07\x98(\x00\n\x05\xa7\x9bOV\xe6\xfd\xa1\x90\x01\x11F\x0f\xb8\xe0\x10\x9b\x03\x81\x92Xv`\x18I\xb5\x95\x94\xdag\xf3\x95\xf9f\x9fz\x95J\x9d\'m\xc8\x8cRR\xd4\x8cZ\xa2\xbdM!\xde\xbb\xa9\x9aL\xf0\xb1\xe0\xd5\xeaS^\xa3U\xfcz\xfa\xf4jW}\x96u\x7f\xa6\xaf\xff\xffZLAME3.100\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa \x00R\x08\xc2\xc7@$R\x15\x04\xc0A!\x85@a\x9a\xef\xe9\xf9\xe6\xe1\x88\x81\x89\xf5O\t\x84\xc6\xef\x81\xac2#\xc9\x82\x8e\x0cA\x83p\x05\xe9\x866\x089\xa8\xe4\x1d\xc1\xa1\xb6\x0b\x19\x85X\x07\xb1\x81d\tQ\x80\x8a\x18\t\x80(\x0e\t\x82\x8c\n\x11\x91\xdaq\xd0\x05\xc0\x98\xf0j\xf4\xc1\x03Pe\x16\x97\xa6\xe8\x8c\x90\x984\x16\x86\xe1\xc3+\x90\x9dc;\x87[\x91\x92\xed\rY\xb2\x92\xc1\xc5\xe4Xj\x86c=\xcb%sR\xfa\xb4\xb3\x17ql5eYv\x9f\x98\xe3\xbe\xe1\x97n\xd1\th\x1c\xd2\xe4\x03\xc0\x86g\x16b\x0f\x1b\xd1\xa2\xf3N\x1a\x87\x87\xc4\x0e2\xb1`\xe5 \x04\xac@\x8d}kC&\x99\xddWO\x90\xfc(\x07K0(\x8c\n$\x03\x03\x80\xf1\x80 \x14 \x98\xe6\xbf\x9f>=\x19L\x94\x99\xfc\xb8\x984m\xf2\x19\xfc"5\x98:`\xdb\x183\x00K\x98o!X\x1a\xa6\x08\x81\x1a,\xa0\xd9\x18E@5\x18\x0e@\x88\x18\x11\xc1\x85\x98\x18A\x12\x98\x1c\x80{\x1a\xac%\x13\x00\xa3\xcbL[a@o\xea\xfbv\x9eqP\x84\xd6\xd7t?\x101\xb4\x04\xd48r\xdas\x03\xa2{<\xd8\x10\xb2{{\xc6\xee\x1d\xc2v\xac\xfd\x1dyl\x17-\x92A\xb9c\xad\xd7\xaf\xbcy\xcao\xef;\x8f;\xac\xaaw\x99~yc\xaf\xd5FT\x90:L\xa2\xc6?Yr\x8a;u\xc0\x04\x17x&\x81[\xd5\x06lU\xed`\xaa\x1c\xf6\xabM-(\xfa\xbe\xc6\xe8\x10#\x83\x00\n)\x0e\x81!@8\xc0\xb2\x0c\xd7S\xc4\xfc\x15x\xc9\xc8,\xf5f\xb4\xc4\x03t\xc0\xe9\x8f\x12\x04\xc1\xd9\x08\x98\xc1\n\nt\xc1H\x1e\x80\xc7A\xdb\x98\xc6\xcc\x1b\x10\xc1\x9b\x08d\xff\xfb\xd2D\xda\x04\x05\xe7(B\xb3\xbf\xd20\xbd&\x18bw\xfaF\x18,\xa7\x06.\xffh\xd2e\x11\xa2\xe9\xcf\xed\x10\xc1#\x04\xbc\xc2x\x04\x80\xc1v\x04\xd8\xc1\x9d\x040\xd1\xd1\x8c$d\x14\xc0d!\t\x8c:\x0c\xba\xd5U\xac\xbe\x00\xd1\x13m\x0e]N\xaa\xed2\x14\xf1pW]\xe5\x83\xcc\xf6\x85\xfd\xbdee\x87/A\xff\x9d\x99n5+\xe5I*\xa0~ieU#\x96\xb9\xcb\xb4\xdf\xdd\x7f2\xdf9\x97nm\xb7\xc5F\x96XN\xd9\xdb\x1b\xc5O\x05\x05\xdb\xb4qC\x96\x10U\xef`\xbd\x10\x85K\xd2^\xf4\xa0\xfd\x91;\xa8c\x02\x03\x9a\xd9\x89\xb3\x91M\xe7\x15MB\x00\x05\x00tm\xb74\xbc\xe7\x14\x059\x81\x80\xd32\x9a\xcf\x1aX3\x81d\xccJ\xb3\x064\xc5#9\x9c \xf3\x00\x84\x0b\x80\xb8"f\x06\xe0\\\xc6,\xca\xb5\x86#\xe0U\x06\x07\xb8\x1b\'\x1e\xfa}\x16\xc6\xf8hyb\xa9\xce\x0eSK\xd5\xbcP\n\xd8\x1fXq\xd9\xb0\xcf\xc3\x82\xaaU\x96\x81D\xc8\x90h\xf1\x9b*\x14\xef>\xb31\xa0\xab\xf8w\x98\xf3\rZ\xb7Z\x9a)7\xbag\x82{\x1c\xb9L\x98$\x90\xb1\x042\xf2l\x15c\xc5\xefZ\xde\xc1\xa8\xc5\xbd\x16~\x85\\\xddO"<e\xfb\xd9\x9av\xfc\xb5LAME3.10\x10\x00\x00\x06\x00\x7f\xd1\xa0<\x11&\x0b\xe1\x12a\xd6%\x86@\x02p`\xca\x1a&\x11\xe0\xd4c\x08\x0eF\x1a"\xa2b:\r\xc6P\xe3\xbeb\xa1#\xc7p\xeade\xa4\nf>\xe1\xfed\xc4i\xc6\x8c\xad2p\xf47fi\xa4.b\xdf\xa9\xe3\\\xc6\x86\x9b\x18\xc2\x1at\x11\t\xba\x1c\xc66N\x9a\xe4vo\xeaq\xb3\xd5G\x08M\x19Ur\x02\x85\x1a\x89\x05\x8b.\x9b"-\x01T\x039p\x11)d\x00\x00\x90S\x0cE\xe4\xde\x97\x10\xaa\x0c\x0c\xca Vw\r1\x07\xad\x9a\x1b\xba\x9a\xe7\x1e\xd1\x02q#L\xe4\xa0\x10\xa9\xc6H%\x91\xa7\x8c\xc2\x92\x14\xc5\x05-\x80\xca\n\x92$\xb9\x8a\x88$\x03P j"\xc9\x19\x84\x10\n\x1c\x98 %bH\x86\xe2\xa6\xed\x89\\,\x1a\x9c\xa1!J\x90\xa1\x01kY\x00\n>\xb3\xd4\xc2Z\xfcP\xcb\xe6"\x919\x13\xb12\xea8p\xf3\xb9\x05\xc8\xdf\xc9\x98\xbd\x0c\xbe\xa5\x8a{R\x89\x99|\xae\x9aY7G\x18\xabn\xa5\xfc9_*K\xb6\xe92\xb1^\xfd&6\xf0\xe6\x1f\x9fp\xdfp\xc6\xc5{\xf4\x82p\xc1\xf8\xd1\xc5\xc9\x84G;\xb0\xf8\xe4\x90\xfa\x18\xf1\xbfp\xd4\x01J$f%\x0c\xb5\xd0\x80U\x8cM\x80E\xd2c}\xa6\xc4(`6\x8cf\x7f\x82\x00\x01\x06\xf0H!\x18 \x8b\xf1\x86d\xef\x18\xec\x8a!\x80\xf8\x1b\x99H\xb9\xaa\x08\x80\xb1\x0e\x85p1\xc2zJ\xc0%\xd1,0\x87sh\xad\xcb=J\x8b\x01\x15\xaaT\xa7\x0c\x15\xde\x18\xca\x9a\x9f\x7f\xbfc_\xfb\xc7\x0e\xf7;\x06\xdc\x07E\xc0#\x07\x93\xec\x7f\xd0\xc5:\xef\xf7[\xef\xa2\xcd\xff\xfe\x866\xdf\x7f\xf4\x07_I\x8b"\xb0\x08[0\xe8)\x06\x89\x86\x19\x80\xa6$\x0b\xa0B \xc9\xf1`\xcdD\xec\xc6D\x14\xc4\x02$\xf4\x01\x00\xd0`<t63,\xc26\x1b\xac4<\xee2\xa4!55\x00\x03(\x96a\xc4\xd1\x0e\xae\x83\x9d\r$\xb8\x84\xac\x1cz\x00\x13\x05\x02\x01\x82\x82\x80\xff\xfb\xd2d\xfb\x80IiSGk\xdc\xcb\xa0x\x03\xf8ro\xdbD\x190\xfd\x18N\xed\x8fJ\xa2\x14a\x9d\xbfa\x18i\x00]\xa7\xadMY\x13\x99\x01?k\x95\xf4bQ\x18C:Y\x05\xfa^mY\x87?l5\xf4]M\x18\x8c\rG\x01\xd8%&\x08\xc4\x14d\x97\x0c\x9b=L\xa8\x92\xbc\x9a\x98\xd8\xc5a\xf2\x1cG1\x1f6z\x99\xe5\xab\x14\xa1<b\xc1\xf31.av\xbb\x04kh}\x03\xcbXy\x9e{~\xb3o\xaeY\x94\xa0B\x8a\x93E\x8c\xa2\xaam\x14\xc5\x0ea\xb4P\x81\x0e\xe7\xff\xff\xf7\xfe\xdf\xff\xfa\xd1\x08h\xc8\x08q\xddf#\xa0\xc6\x14LbGFf\xaciO\xe6f\x8e\x1b\xcea@af\xf0\x82T`\xae\x18\xa6\x1a!\x02`.\x1ef\xad\xe0\xaeg<\x08\xa6\x16\xa0\xee`p\x07F\x0c\xc1\x88`N\x0b\x06\x02"\xa6y\xf1\xdaAZ\xa9\xb1\xd0H\xe6\xd6X;\xedXB\x12l\xb78~"2%AwR\x80\x15\xaaWBB<\x87\xd9\xa7\xd4\x9f\xb8\xd6\xe9\xdc\x87BY\x1b\x8d\xda\x97K\xe1\xfa{\xb9\xdf\xc6\x92\xf6t\xfb\xa0\x94a\x9e\xfe\x9e\x8c\xb0F)\x08\x02\x03[\xa5\xb8\xa4]\x08\xbc\xbf\xb3E\xe0\x07\x8a\x12i%$\xe9z\xac\xd9Oe\xb7\xe5\x7f\xfa\xb7*\x00\xc4\x00\x00\xc0\xf4\x13\x8c\x0b\x81\xb0\xc0\x80!\x8c\x1c\x00$\xc0\xb0\x04\x8c8\x80\x14t$\x8c\x17\xc3\x0c\xc1\xec[\xcc0J\xd8\xd2p\x96\r\xc5\x15\x04\xc4\x80?\x8cF\x01\xd4\xc4p%\xcd7T\xb0\xc9\xe0\x0bLw\x82\xa0\xf1\xce\x0c\x0c\xb8\xe6HM\xdd\x8c\xdc\x90\x01WFP,f(\xe6R8BDeb%\xa4\x14\x07\x95\x8a\x87\xb1\xd7u\x14\xe1\x80\x81\x04\xc9]\xcb\xdd\x1f\x83\x04_\xdbR\x17iDeq\x8a\xd2\x99\x97\x8d\xc0Nx\xc5GI\t\x0c\r\xac)b\x83\xb2F\xb5\'\xce\xa4\xfd\xc9L\xa3\t\xa7\xe5\xc6\xb1^9!\xb1\x8e\x1c\xcf=~\xfe\xf5q@\x18\x00APx\xa0|L\x16\x08<X\x1f\x1dY\x1d,l\xfd\x08\xbd\xefC\x83\x9bZ\xf5-v\xec\x91}tmbI4\x9aT\xa2q\xba_\xa8\x80 \xf4D\x82\xfc\x17\xb8h\x03@@u#0$\x01c\t\xa0\xb0\x19\x02\xb3\x04\x90\xfb0\x7f\n\x83\x0c\x13\xf09~\x12\xf1\x10\xc0\x18\x81\x02\x91\x8b@\x9a\x18\xe09\xb9\x91\xe8,\x98&\x841\x93\x8c\x9cT\xe8\x11\xa0\xc43\x8d\x84\x18\xc1\x14G\xaf\x8c\x9c\x08B\x04,\x16\x8d\x06$\x00,6,JL&\xad\xadi\x00\x0f\xa2\xaa!\x04\xb1\xae/\x12\xec\xcf;\xed=9\xdc\xd8\\\x06\xdf\xd4z\x9f7V\x02\x12\x05u\xcb\xfc\xc5E\x80\x94%|,\xe9\xd6wI51*ye\x0f#\x8c\xfb\xc6%\xad\xdav\xfe9w-\xf7\x0c2\xc3\r\x7f~\xaev\x92\x1el\xf8<\x03jc\x0b)!\xb8\xd3L\xd3\xfc\xb6\xfe\xd4x\x92\x94\xa1\xf5\x15[o\xfe\xfe\xdf\xe8\x00\x01\x18P\x00\x00\x00\xc1w\x00\x0c\xc1\x1e\x04\x80\xc1\xb9\x158\xc4\xc9\x1cX\xc1\x12\x07\x9c\xc2\xc4\x0c\xb8\xc0\xc2\x03\x18\xd6W<\x9c\xc6\x12Y@\xd0\xb3\x8ep\xcc5W@\xf4\x02Id\xc4\xf5\x03@\xc5p\x00\\\xc8\x854H\xd1\xfb^\xb0\xc6\xb0\x11X\xd2\x9b\xad,\xd5S;\x14\xc7%\x0b|\xea\xb3/`\xc8}\x17`\xcb\x8f3\x00\xc3(\t\x0c\xc1\xff\xfb\xd2d\xff\x80\x06\x9e.\xc2\x1d{`\x00\xc3F(w\xafl\x00<i\xf1\n\xd9\xff\x80\x02\xf2\x95\xa2\x1b=\xc0\x00\x99\x04T\xc0\x1f\x00\xb4\xc0\x1f\x00\x94\xc4)\x10p\xc0\xfc\x06D\xc1\x98\x04L\xc0\xf5\x02\x98(\x03\xc0\\\x003\x01\xa4\x03s\x02\x90\t\x83\x01\xa0\x03\xa1\xd0\x02\xc7\x8140\r\xc0Y0,\x00\x9b0\x1e\x00\xcd0\x05@ 0"\x00q\x1d\x00\x00@\x049\x81t\x04\xa1\x81\x04\x03\xa1\x80\xb0\x00\x810\x04\xc6\x00p\x04\x86\x05\xf8\x0b\xc2@G\x18\x02@f\x98\x06 A\x18\r\xe0(\x06\x01G\x0b0\x01\x00\x1cS\xf3\x86\x01p\x01\x06\x02\x98\x07\xa6\x01X\x02\xa3@\x03\x98\x02`\x08\x98\x02\xe0\x0b\x98\x02 \x01\x98\x01\xa0\x0f\x18\x05 \x19\x18\x06\xa0\x1c\x18\x00@\x06\xa1E\xfa\xf8g\x8d\xf1 \x01\xd3\x01\xb1\xafs\x00\x18\x00$4\x90\x18\x00\xe0\x0f\x18\x00@\x0b\x98\x02\x80\x06\x8b\x00\x02\x95 \x00\x01L\x00\x80\x03h+s\x1e\xf32\xd0\x16\x91K\x18<\x00\xd3\x01@\x01\xa6\x1c\x0e\x8d\xca\xf8D\x00\x08\\\x00\x000\x00K\xf9\xa5"qg\xb1\xd7\xef\x9f\xbc\xbdS\xaav\x9e\xfcGa\xf5\x04k\x97\x98\x83\x10e/\x92G&\x8a\x0e\xb7\xaf\xaa\xc2\xa4+\xa5\'\xe7\xeb.\xe5\xfc\xd7t\xfcO\xc4"\x8b\xae\x1f\xc9\xaf\xb9q}\xc3qw\xe2\xf2\xf1`LJ/\x01.\xe5\xdd)\x98\\\xcd%\xae\xc4\x1d\x96s\xbf\xde\xffY~?\xfb\xd6\xf7N\xd7\x1f\x8b\xd0\xc4bY\x94br7\x95G\xfe\xdf\xff\xff\xff\xff\xff\xff\xbf5_\xd6\xb3\x12\xeb\x82\xfb;\xd3p\xd3\xbd=*v\xa1\xef\xd8\xf9D\xa5\xc6\xc0\x02\x08\x00\x00\x00\x00C\x89\x83P@\x10\x00`pK\x88\x80\xd8\xc1`\x03L?\xc3t\xd5}5\xcc9B(\xcb1\xb5LC\x80\x90\xc4\xc9\xa4\x8c\xa1\x87L\xcd\xb4ZL\x82J\x8c\xcc\x144\x8c{D$\xd1\x80\x89\x0ep;2il\xcfBc\x1e\x8c\x8d\x82a0\xf8\x98 Paq;\xf6\x06C\x18t\x14]\xe1\x80\xf1z\x95\xbd\x9b\x0e\x80cM~\xaa\xbc\x95\xb4\xc7=.\x99\xf3QOz,\xef;\xce\xe5\xda\n\xd6\xe1\x1f(\xa6\x95\xc3\xfa\xa5\xddl?uw\xbe[\xd6\x1b\xc7\xb9j\xe7\xe3\xbf\xbe\x1b\x02\xb0\x82H^ \xa5h\x92\\#i6\xed\xb5?\xf4\xd9\xf4\xa2\xc5\xbeb\xad\xa2\x89u\x0f\xb3\xfb\x13\xa5c\x17\xfd\x9dG\x99\x80\xe9\x11\x08\xc0\xb0\x00\xc0@\x12`\x1c\x11\xa6\x00`"\x06\x01\x12\x00\x1d0\x1a\x05\xa3\x0cq\x0b1A\x10\xb3\x14\xfb\x183\x9f0\x13\x19`00O\x02\x81`\xc30\x0c\x0fs\x12!\x9d1b\x11\x03\xb2\xc8\xe57\xb5\x04\xe8$\xa3/\x13\xcc\x08\x1b\x01\rY\x02\xe2B\xa5\n\xbb\x11[\n\xed\x00\xc5\xe8b\xac\xb5m\xcf\x18\x14T\xc9\x1e,\xa8 \xd9j\r\x8d\x19\x9c)\x16\xf1\xa6\xa6/\xbcfy\xfe\x83\x9biE\xd8na\xe1\x7f\xe4k\xbeG\xab]\xb9\x18\x9a\xfd\xce\xceV\xc2\x92\x8a\x93;|\xcf\xf2\xec\xe5?\xd4\xdd\x9e\xa5\x80F\x8b\x87\xc5\x04d\x03#\xc5\xa3:}\xbf\xfb\xbb\xd9Px\x00\x00\x1b\xf4\x00a(Qg\xa4\xa8\x040\xc00\xc7b#\x08\x94\x80\x84\x03\x12\x83\xccG.0i\xdc\xcc\x00\xa4\xf71XL\xcd\xb1\x93$\xa3M\x16u2\x03>\xd97\xc1D\xe4\xf9\x0eF\xff\xfb\xd2dt\x0cEm0G\x9f{\x80\x08w\x05\x99\x1a\xeed\x00\x19\xbc\xcd\x10n\xffg\x01\xdb\x96$)\x9e$\xf1\x07oX$^:\xeb\xc0\xf4w\xebY\xedX\xfe?\x96\x19\xd8\xf8\xde\xb7\xac\xfb\xfb\xde\xf5\x85NZ\xa7\xafo\xf9\xf6*M\xca\xe5su\xa3\x12\x0c\xae\xcb\xe5_\x96z\xab\x9f\x7fV!\xc1`\x01\xcf\xdfJ\x01\xc6A&\x05\x8af\x06\x8cFK8\x86+\x84\xc6\t\x85&\x1a\x05\xe6;\x12\xe6\x90\xeb\xa60\x88\'\x86\tk5\x86\xc8\xf8\x81\xa6\x04\xb0$\xc6\n\x10\n\xa6\x02\xe8\x07F\x02\x00\x03\xe6\x04\x80\x18&\x0cx\x14F\xf7\xea\xb6\xc6\x0c0\x9e\xc6\x01h\x04\xc6\x02(\x0e1#W\x0b2Q\xe2\x81\xc6Xc\xe1\x05P\xb01\x8a\xfb\x03E\x03\x00\x915!Wua\xd01\x04z\x99\xba\xade\xb9I\xed\x0c\x0c\x93e\xc8\xddzXV\xe2d\xa1U\'\x94&6\xd6\xeb\xc2%\xce\xfc\x81\xc8r\x9c\xe8\x01\xf2\x82\xecG/\xbbxi\xad[\xa2\xa6u\x9b\x8d\x0c\xe5\xe8\x95\x0c\xf6\xab\xc6\xf5IMb\xa6\xf9\x8dZ]T$H\\\n\xe00\xb2\x18\xb7>:M\xd7\xd5r\xd8\xb7s}~sz\x7f\xab\xfe\xb0`\x01[ \x025\r\xae\x05\x811\xc9/\xb1\x99i\xbdPP8\x00K\x9d\xe2pi\x13\xf9\x95\x06\xe0 \xb848ea\xf9\x96\xde\x87\xfa\x97\x1a\xc4fD>\x03\x05\x8c"\x15ca`z\t\x10\xfd\xaf@L\xbd\xdd\x95\x01\xa0\xec\x1bg\x8em\xa9\x1a\xa0p\x12B\\H\x84\x8b\x9cjX2\xa2\x01\r\xac g\x163#\n\x92Z.\x8a0\xd3y\xe3\x95\xba\xbc\x99\x0e\xd6nt\xc6y\xfb4\xf2\xaaLAM J\xd0\x01\x15\xcc\x00\x01\xcc\xaf+\xc4\x00(\x10\x04*\x82\xc6\t\x03\x06O\xca\xe6\x13\xa8\n\xc6\x07y\x97\xc6\x98\xb88F\x0c\xa8\x0c\x86\x02\xe0\x01\xc6\x01\xa8\x03&\x01P\x14\x06\x04HKF\x01`\x1e\x86\x85Q\xae\xa6\x08\x90X&\x03\xb8\x0bE`6\x03\x80o\x0b\x13\x12\x02b\t\x01\x8f\xb1"\xde\xa0\xdae\x8b\nG\x89\xa7\xe9\xa2\xc9\xdc#\t\x11\xa7J+RI\xed\xc1"X\xea\xee\x82\xe6t\xa8\x83{\x15\xefA\x00>\x14\xf0\xfc\x03\x06E\xed\xb5\xe9C\xf5O\x05\xc4-J\xa1\xadT\x96\xd0\xd2\xc3\xd2\x0f\xa6\xb9\xdak\xbc\xca\xe5mw\x1c\xf5j\xb3NC\x88q\x14!\xac\xfdd\x01\x81\xac\x8d8R^\x983\x83H@\x0c\x05\x80D\n\x03\x01\x00\xaa`n5&0\xe0|c\xd3\tG\xccb\xfaa\\\x01\xc6\x06\x00>`\xbe\x02\xc6\x04\xc0Pa\n\x04\xa6\x03\xa1 |\xb8\xa3f\x00Dr`\x9c\x06E\xd6\x8e\x1a\x03"\x9b2mQ\x06P\xf3\xac\x94.t\x99C\x8a\xd3c\x8e\x11\x85$\xffr\xa7\xdf\xa6\xd9FS\xd71\xcf\x9cn:\xf6U=\x01A\x14\x8e\xf3\xe1!\x96\xc0ov)\xaf\x0f,\x1a1\xbc/qR\xd1\x8cg*\xc8\x81\x80b%\xc2`\x98\\\xc3\x86\x90SR\xbe\xbau\x7f\xd1\xed\xdb\xeb\xf4\xe9C\x90E\xea<#:\xa1T\xca\xe1 0\x10\xc2\xa2C\x010\x04\x93\x01\xd4D3\n\xfc\x07#\x08\xf4\xe3C\x8fl\t\xa3\r,\x13#\x00\xe0\x050P\x00\xa2\xa0u\x98\x15aF\x98\x0bAX\x9c\x05\xab\xc3\x18,b\xb3\x18\x1a\xc0E\x18\x19\xe0\x0f\x05@)5\xb0N\xff\xfb\xd2D\xcd\x8cEc1E\x1b\xbf\xd1\xc0\x9e\xa5\xb8\xd7{&\x8a\x16\xd8\xa5\x0cN\x7fEB\xe7\x95!\x89\xcf\xe8\xa8\x03\x12\x16@\x00\xc6L\xc2\t\x93@\xa8\x14Hc\xea\xb0-M#\xa0\x14\xc99{\xdd\x9e\xca\xe4\xd6\xe2\x90\x01=(\xe5\xa9e=\x98\xf9\x81\x11/\xae\xd3%\xf1\xea\xf2\x8b\xb1\xcb\xd2\x9ej\n\xa1\xe4\xa7.\xc9r\xbf\x7fy\xd8\xfaN\x05\x01\x91w\xb8:.\xa6\x05\x03\xd3qQ}\x88u/\xdf\xb3\xb3\xb3\x1e\xaaU\xfd\xf6\xff\xdcJ\xca:u\xd5\xa1\n@,\x03\x81gJ\x19\x98\xfc\x08b\x819\x91DF\x01\xb8\t\xe6\x00\xd0\x94\xa6\x15\xe83\x06\x13\xd93G;\xe8;&\x00\x88\x07\x86\x02\x00\r\xc0`Z\x8c\x05\x10(\xcc\t\xc0Q\xcc\x12 \x0e\x0eD\x91\xea\x0c&\x81V\x8c\n \n\xcc\x030\tF\x80v5\xc6\xcb\xa4a\xdf\x16yQ\x18!`\xe0\xa0\x83!\x02\tC\xaf\x06\xa8\xaa\xcd5v\x9d\x9b\xa9C\x04\xd5\x92<\xb2\xd2\x01\xe5|\xdc*+\xf0\xf5i\xb0\x08KW\xdbIl\xfe\xe47\xb5zj3\xbb\xf4\xb4\xbd\xc6v\xbdJn\xde\x9e\xed\xeb\x967t\xe9\xf0Ms\xe7\x1a:\xc4\xd8"]\x8d+\xd9W\x18\xeb\x13\xf4\\\x95\x7fU?KW\xfd\xfa\xaazU\xeeuLAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\x0c\x00\x02\x81\xebI1`\x94,\x05\x19:x\x01\x84\x83\x03\x02\xf0(\xb0`\x98\x86`%\xfab\xa9\x14q\xd8\x1em?\x81B,\r\x90\x90\x18&\x008\x02F\x00\xf0\x01\xa6\x01\x18$ \x80\t\x8d\x81\x82KL\x04`\xe5\xcc\x01 \x12P\x1c\x9b\xea\xa0\x94\x8b\x9a\t\xc6q\xa7\xa5H\xb8\x0b"Z\x8f\xe5\x88\xf0.1\xf8c\x1e\xa2\xcf\x0e\xdb\xb2S\xfe\xfb\xcd~\x8b\xb3{\xaa\xed\xfbpa\xd8\x1a[n\xdc\xfbq\x90\xd2RS|\xdeq\x0f\xde\xafg\x9d^\x8f;\x1e\xb3T\x98\x1b\xaf\xb5\xe8\xd3\xf6\xff\x15\xf4v)\xabA\xdd\xf9\xa5\x18\x99\xcc\x01p\n\x89\x88\x0e\x93\x08k\x0f\xea.\x19\xd1f\x0b1\x85H#\x18($\xd1\xab0)\x18\xef\x80\xe1\x82X\x1c\x18\x18\x00\xb9\x80h\x1e 0\xc1\x00/\xccjt,\xf6pC\x82w\x0bV4\x03\xd4\xc5\xf7d \xa0Pk\xed\x0f"6\x13\x7fCj\x812$\xf7\xa9%9\xf5;\x94\x8dn\xf6\xe5\xdcis\xfbYo\n\xb5kZ\xaf\x9d\xce\xf3\x9b\xd7\xef<\xadc\xca\xbd\xac\\PX\xf5`\x11\x82\xdfO\xec\xff\xfd?\xee\xfd\xba\xe80;\x80R0%\xc1C0<C\x9f0,\x81H0`\x81d0\x1a\x01\x910\xd2\xc3\x1d0\x87\x84[1\xc5\x0220]S\xf1?x\xc1|1\xc6D\xf30\x1eB(0\x8f\x01r0|\x02\xce0s\x80\xc91\x93D\xfd?MS\x181{\xc7\xf01\x16\x85\xcc0\xc4\x82;0\xeaB\xc10]@\xa00~\x02r\x08\rd\xc1g\x07d\xece\x93\x83\xdd\xcev\x8d3\xb40\xe9\xca\x83\t\x1e\xcdv\x9f1\xc8\xe8\xcf\x08\xa1\xa3\xe9\x92\x8a\x86\x95/\x18\x082bp\xcaA\x08\x80\x06\x06\x06\t\x02\x14\x1c\xd5\xa0\x00HL\xc2 2\xa0\x10\xc1\x80\xc4\x150X4\xc7`$\x12\x17\xed|)\xa3\xff\xfb\xd2d\xe9\x04\xc5\x01(\xc5\xd3\xbf\xca0\x80\xe5\x18\x82k\xda6%\xc5m\x08\x0f\xf13\x8a\x8c\x91aI\xaf\xf0\xd8\xea\xeb\xcb\xed\xd28\x90\xf2\xc2)\xe53d\xebAj:l\xbe\x03r\xe8\xe1\x89g)\xe1\xbc\x9d\xb8\xbb\xe8\xfcAm~\x81\xc8\x96\xb9\x13\x92\xb9}\xca\x98`\xb9"b\xb5\x85\x0c\x85\xcd\x94\'I\x8b\x9e\xff\t r6\xc8\x18#m6\xea\x19~{7\xa8\xc2m\xd2\x0bA\xe7\xb0\x87\xdf\xe3:c\'\xe1\xb0\xb9\xef\xf5\xf7#:\x84g\xab\xec\x0f\xf7\x84m!\x125Y\xffT\x81\xf2I}_\xf3\xfc\xd35K\xff\xddvG\x81J\n\xecBiTR\xb5\x19C\x03\x81\xc9\x98\x1d\x9b\x06\x0b\xd8\x0cF\x03\xa1\x15\x06)\x808\xe6\x02X\x19\x06\x01P\t \x10\x01L\x07P\x06\x0c\x00`\x0f\x8c\x0c\x00@\xcc4\x84\xbc\x0e\x8a\n0\xf8I[\xcc\x06\x191\x00\x14\x94$\x98\xe5\xbe`j\xc4\xbd]\x90\xe0\x1b6\x85J\xb9V\xe8@\x0eMj\x8a\xdd52\x05"\xc5%\xeb=\xb9\xf2\xee\xf6\xec\xd5\xbc7k\x96*eK\xbcf\x84\xe02\x81\xd0\xcb\x83\xa0\xa8\x89j \x97\x08^\xf1\xf5\x8d\xca\xad\x144\xbbn\xabu\x8aB\xac\xbd\xd6Fn\xe4\x0cR\xe2IR\x15\xe3Q\xee\xf7hZ\x15\x00o\xa3 \xc0l.\xcc.\x00\xc4\xc1\xc4@\x8c<\xc2\xe0\xc0$3\xccU\x054\xc1\xd0.\x0cI\xc4\x90T\x83\xcc\xf1G \xd8\xc4\xd0\x0c\xa1H\xf8\xc7\xb4E\x8c\x01\x00|\xc0t\x1d\xccD\t\x0c\xcd\xd1n\xce\x1b\xa5\xbc\xd6\\\xab\x8ci\x8a|\xc9\xd8\x7fL3\x03\xf0\xf8y\xe3i\x99\xce9A7P<\xd5\xb0\x83V\x15L\xa6\xac5i\x80\xc1\xc6\xf3B\x16@\x83\x83,\x92\x0c"\x111\x80\xc4\xc0 \x13\xba\xd3\x80Tv.\xd3.\x97\xa3h\x08UN\x86\xa9\xecZ&VZV:\xc3\x9eu\xcc\x0f\x08\xc2D\x1c\xabr\x87\xd8A\x86!y\xcc\xd5\x06\x8b3\x9d\x12\x94\xd3\xb0\xe7\x18\xc0\x8c\xe8LucaT\x12\x19c*4\xc5k\xac\xa6\x04-\xd2\xf5.qz\x90d\x14*m\x00\x86\\\xe5\xa5u\xd15\xcdeO\xd5^\xc02\xd8\x8b\xbb\x1cgQ\xb6s kP{\xb5\x16\x94\xc5r\xcb+Y\xca\xad\xc6oF\xa7\xa22\xd9\xa9mJm\xe3\xcc\xff.V\xb5V[r]vZT\x05\xac$\x15:\x1d\x0e\x92\xe5K\x15\x01)\xfeu\x88o\xca\xeb\t\x95H\x12\x00\x89\xbcU\x00\x84Q\n\x80@\x14\x14\xc4`lc\x16\x0f\x06\x0f3\xf4`4\t&\r\xc1\x16`|\x06\x06\r`\xc0\t\x02S\x01\x14\x04\xb3\x01,\x13#\x03eU\xb3\xd0Q\x01G\x981\xc0\x14dd\x0eP\x18@_\xf7\xc4.\x07>\x0c\x03R\xe6\xc7+\xad3\x03?`\xa1\x16\xdb\xf2\xaf\x17\xc5\'\t\x84i\xecr\xbf0\x87E\x86\x9b\x1ctT*\xd3\r:xT\xdaEkZ!\x81V\xbf?<\xd1F\xad\x05\x9f\x9fE\xabo[M\xadM0\xe3@\x836\x19z\t%\xf6z\x8d;\xae\xa9Yo\'\x17b\x10\x19\x15\x18\x0c&\xc0\x0c\xc0`\t\x0c\x14@\xf4\xc0\x0c\tL\x00A\x08\xc1\xb0\x07\x8c\x02\x82x\xc3\xb8\x00\x0c\xa9\x01\xc0\xc9\xffY\xcct\xcf\x08\xc8pe\x0c\x16\x00D\xc0\xe8\x0b\x0c\x0e\x01,\xc1\xc8MLH\xc4\x14\xc7<\xecM\x04\\\xfd\x9e\xff\xfb\xd2d\xff\x8c\xc8\xd0HF\x1b\xdc\xcc \xa0\x03XA{\xfb`\x16\x90\x91\n5\xed\x80\x02\xd1\x96!\x8e\xbd\xd0\x00\x0e`\xcc\xc0D\x0c\x9c\xdc\xc4\xcd\x8clD\xc4\x8a\x8cx80\x88\xc4\n\x89\x88\x00\xc6lD\xc1\xc6Te2P\x04\x18\x06b M6\x1e\x81"v\xa5\x0fC\xb4\xe6\xda\x9f\x89Be\x0f\x9d\xc9%\x8b|\xc7Xw\x97a\xf9\x1c\xe6\xf9ou\x02"\x03\x9c\xf8P\xa1\xac\xf8\x7f6\x1fX\x19m{E\xee\xf9\x94-\xee\xad*\xa3\xfb\xbbm\xa5\xaaGrT\xfe\xde\xc5\xa7\xd5*\x90\x1cd\x00!\x92\xe8\x96\xacT\x00\x0c\x02\x00H\xc04\x10L\x05Al\x14 \xe61!\x92b\xb2\xa0F\x9ce\xbebz\x03&\x0c\x80\xe8`\xd4\x13\xc6\x11\xc0\xbcJ\x0c&8\xe82l{\xcdF\xc4\xd8g+\x8cf\x17\x90\xa6,\x0b\x02\xc1iA\xa6`\x08\xce\x0e"\xcc6\x10\x16\xa1\x83 l\xb8\xc1@X\xc1\x00P\x14\x16.d-]P84\ne\x95/\xd9\x88\xbbK\x90\x14\x1e\xb2\xa5\xf0\x99\x8f\xa3\x04x\x18\xc4^7\x02;\xf2\xbb\x15)"\x15\xa7\xff*y\xb8\xc46\xe5\xd1\xcb\xe3q{\x17s\xfb\x9f\xfc\xcf\x98}\xb0\xcb\xd7l\xa2\x15\xa3\xe8wE\x17t\xffF\xdf\xbdMs\xa2\x9f\xdd\xff\xfa\xee(\x00\x01\xa9\x08\x00\x00\x00\xc1\x1c\x14\xcc\x1b@\x18\xc1 \x07\x0c\x05A\xe4\xc2\x88\r\x0c;A,\xc2`q\x8c\x8e\x08\xb0\xc2\xacb\x0c\xde\x05T\xc3\x88\x1d\x82\xe1\x94c\x0c\x17f-t\x92`\xe4\x18\xa6\x82\x07\xaa`D+&@\xad\xc0\x07L\x8fP\x18\xcc\x06 x\xe0\xbd\x81\x85\x10\x14\x06\xaf\x13h\x18\xbf\x14\x00a\xb4;\x01\x82\xb0\xd6\x06\x14\x01\xd8\x18\xd5\x07`\x98\x0e\x02\xc1\xa4\x0c?\x01@\xa0\xb8\x03\t\xa0\x84\x06\x810\x18\n\x041"\x0b\xfe\x06\x03\xc0!\n,``\xe0\x16\x00\xe04\x02A\x08@\x02\x04\xb0XE\x10T\x8f\x83c\xc1\x84N\x0b\x89 0B\x07\x80\xc0\x80\x07\x02@\xcc\x0b\x02\xe0\x14\x04\x86\x05%(\xfb\x1c.\x17\x8bD\xe3\x81\x81\xb0&\x02\xe0$\x03\x00\x90\x11\x00\xe0`\x10\x05\x80\x08\x02\x9a\xb2+\xa8\xc1\x14K\xe7\xd6|@\x81\x85C\xb6\x18\x90V\x81\xe9\x89\xb3z\xb5\xcd\xd97\xbb:\x02\x03\nDw\t\xc8U\tLf\xc5h,\xf6\xa2\xb7\xfc\xf3\xa0\xd6v\xa7\x18\xd1\x9e"\xa2\xe1\x1aC D\x06le\x07P\xf9\xb6\xfe\xfa\xd4\xc9\xbe\xcfg\xa1C&\x86hp\x8e\xf2Lp\x0ey*:\x0b#\x9aE\x89\x02D\x89\xdf\xfe\xdf\xff\xf7\xbb\xd3O\xedo\xff\x1c\xc2`\x87\x91\x84\x08\x99-\x91"X\x83\x97\xc8\x01\x0f!\xa48\xd6\x12\x00\x00 #I\x9d\xd2p\x18\x02\x00\x80\x0cS\tLg;\x8c\x16\x01\xc4\x85\xa6\x86`\xc0Fa"\xaco\xc0dch\x02d\x816` \x8abh\xacb@:dv\xc8`\x90,d\xde\xe4a\x10\x1eei\xf0\x06\x11~\x81\x98\x89\xa0}1\xf0\x0b\x8b\xc0\xc7g\x801\xa8\xb4\x0c\x9cd\x03\x1c\x00\xc0\xc8!`3\x91\x14\x0c^\n\x03\x01\x02\x80\xc5\x04@1\t0\x04\x0eA\x08H8\xb2\x88\xfa\r\x9c(\x12\'\x85\x9c\x06\x01\x03\x01\x86A\x00\x14)\x01AX\xb9\x84\x00\x14qA\xa2\x1aH\x18D\x0c\x17\xc0\x05\x04\x82~\x01\x81X\x18`\x0c\x06\x13\t\x84 \xf0\xff\xfb\xd2D\xfe\x00\n\x9e\x8aD6z\xc0\x01XqH\xfd\xce\xd4\x00\x14\x98\xed\x0c\xbd\xac\x80\x02\xb08c#\x9e\xb0\x01\x1c\x12Est\x18f\x05\xb0\xf1\x14R\x00\xd4:\x06"\x13\x81\x86C\x00Xx\x01\xc4\xd0\x14\'\xdb\xf2\xb9\xa9\xb9]\x12\xf8\x18\x90,\x06\x02\x06\x01\x82\xc3`` \xb0\x18\x140\x01\x01P\x18\x05\x7f\xd3\xa6\xce\x81\xe74\x01@0(\x01\x01@8`\xb0m\xa07\xf0\xbf!\x9e\t\xb7\xff\x9aP\xdc\xfb&~\x17:\x1e\xb0{\x82h\x1d8b\x81<\x08F\'\x80\xcb\xc2\x15\xff\xfe\x9fg@\xf3\xa0\xd6y\n,C\x00N\xe3\x9e+Ag\x8ch\xcf\x11Qp\x8d!p\x0e\xc1q\xff\xff\xff\xfb\xbd7\xbfgA\x07o\xff\x15\xa0\xdc\x1a\xe4p\xb9\x86di\x8d\xa1\xa0,\xb2\x1e1\x83\xacY\xa3\x94H\x88\x00a=\x8c\x08C\n\x015\x9b\xaab\xb2\xc3\x02@\xc5\x88`\x86\x04@\x08\x93/\x04\x01/H\\\x81\xab|q\xe1\x07Rg\xccx\xd8p\xa0\x9c`\x80P\x1a\x8e\xc6)\t\xaa\xaa\xc8<\xba\xa8\xe1\x99l\xd3\xfdz\x1ar\x9d\xe8z\xfc\xa5\xfd\x7fe\xdb\xe5jjk\xb0\xcb\x93=3\x19\xb3\xac\xbbV\x97\xb5iiq\xfc\xb2\xcb\x1f\xfcq\xc7T\xd1\xab5\xa9\xb2\xde<\xadM\xca\xd4\xd6\xbb\xf8\xe3\x8f\xfeYe\xdd\xd2\xd2\xe5\xbcy\xac\xbe\xad/AS\xbcJtD\x1c\xe0\xd0\xc0\xefQ\xe8+\xca\x86\xc4\xba!\xaa\x8fpj\xfa\x8f\x16\xfc\xa9\xde%\x9d\xfcD\x0f\\\xc0\x05\xf5\x87\xca\xe9\xc9\xe8\x17A\xcae6\xb8\x93\xe0\x8f\x06\x12\xbc8@u\x00 &\x01\xf0z\x1dO$\x87\x91\xdallJ\x1d\xc3\xb8\xf2 \x82\x03\xd2r\xa6\xac66Tm\x01\xe9q$v\x9a\xb1\xd6\x89\xad\xa2jjwq\xb1\xb3}\xadl\x12\x87q\xd4\x8d\x9d-\xa4\x8d\xa9#c\xd7-o\xc3\x9c\xeb\x93SWKw:Q5\xb6\x9a\xb7\x8b\x96\xedk[\xc3\x9d_\xb5\xb0\x91\xb59\xd7\xb7s\xa9\xc6\xce\xbd\xadm\xfb\x9drjj\xe6\xb6\xa1\xda&\xb6\xd6\xb7\xff\xf6\xb5\xbc9\xd5\xdf5\x0e6\xa8u\xff\x0e\xe1\xce\xbeZ\xdf\xf7\\\xb4\xd5\xb1_\x88\xb8\xa6\xff\xffM\x84\x13LAME3.100UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU'
def write_bytes_to_file(byte_data, filename):
    with open(filename, "wb") as f:
        f.write(byte_data)
write_bytes_to_file(old_dialing,"Dial_Up.mp3")

In [14]:
# @title 1) GUI functions cell for accounting project run this to run the Accounting Project
#A11
#^these are intentional using ctrl+f typing these in you could
#more easily navigate think of it as developer features
#simple_it_works_but_easily_hackable_not_ideal
!pip install simpleeval
import pandas as pd
import plotly.express as px
import math
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from scipy import stats
import numpy as np
import time
from ipywidgets import Layout,Combobox,Output, FloatText, Button, VBox, Label,FloatProgress
from IPython.display import  Audio,display, clear_output,YouTubeVideo,HTML

combobX = Combobox()
out = Output()
#this function is a one man army capable of calculating several types of algebra
#now its about identifying agebraic paterns rather than creating functions for each formula
#if a type of algebra doesn't exist add it in to add more formulas easier to maintain and debug
#addition,subtraction,multiplication,division, and mixes of them more can be added this marks a new era in coding for me
#values = [debug(f"{v}: ") for v in variables]
#calc_btn = Button(description="Calculate", button_style='success')
ALLOWED_FUNCS = {
    "sin": math.sin,
    "cos": math.cos,
    "tan": math.tan,
    "sqrt": math.sqrt,
    "log": math.log,
    "abs": abs,
    "min": min,
    "max": max,
    "round": round,}
ALLOWED_NAMES = {
    "pi": math.pi,
    "e": math.e,}
general_ledger = {
    "Cash": 0.0,
    "Accounts Receivable": 0.0,
    "Supplies": 0.0,
    "Equipment": 0.0,
    "Accounts Payable": 0.0,
    "Notes Payable": 0.0,
    "Owner's Equity": 0.0,
    "Revenue": 0.0,
    "Expenses": 0.0,
    "Dividends": 0.0}
values =[]
data = []
color_codes = {
    'black': '\033[30m',
    'red': '\033[91m',
    'green': '\033[92m',
    'matrix_green':'#00FF00',
    'bright_':'\033[92m',
    'yellow': '\033[33m',
    'bright_yellow':'\033[93m',
    'blue': '\033[94m',
    'white':'\033[37m',
    'purple': '\033[95m',
    'magenta': '\033[35m',
    'coal':'#0C0908',
    'cyan': '\033[96m',
    'bright_white': '\033[97m',
    'bright_black': '\033[90m',
    'bright_red': '\033[91m',
    'bright_magenta': '\033[95m',
    'orange':'\033[38;5;208m',
    'rainbow_colors':['\033[91m','\033[38;5;208m','\033[93m','\033[92m','\033[94m','\033[95m'],
    'RAINBOW_CODES':[
    # Red
    '\033[91m',
    # Orange (Bright Yellow substitute)
    '\033[93m',
    # Yellow (Bright Yellow substitute)
    '\033[93m',
    # Green (Bright Green)
    '\033[92m',
    # Blue (Bright Blue)
    '\033[94m',
    # Indigo (Bright Blue substitute)
    '\033[94m',
    # Violet (Bright Magenta substitute)
    '\033[95m',],
    'reset': '\033[0m'} # Resets the color
html_colors = {
        'red': '#FF0000', #HTML colors
        'green': '#00AA00', # A dark green for better visibility on white/dark backgrounds
        'blue': '#0000FF',
        'yellow': '#CCCC00',
        'purple': '#800080',
        'cyan': '#00FFFF',
        'black': '#000000',
        'white': '#FFFFFF',
        'orange': '#FFA500' }
D_sign = "$"
display(HTML("""<style>label.widget-label{color: #00FF00 !important}</style>"""))
def print_colored(text, color='reset'): #works with CLI
    """Prints text in the specified color. Defaults to resetting color."""
    code = color_codes.get(color.lower(), color_codes['reset'])
    print(f"{code}{text}{color_codes['reset']}")
def universal_variables():
    out = Output()
    EQUATION = combobox_menu.value.strip().lower()
    FORMULA = Accounting_Equations[EQUATION]['formula']
    variables = Accounting_Equations[EQUATION]['variables']
    input_box0 = [FloatText(description=v + ":",value=0,style = {'description_width': 'initial'},layout=Layout(border='2px solid green')) for v in variables]
    calc_btn = Button(description="Calculate", button_style='success')
    calc_btn.style.button_color = '#002D04'
    print_colored(f"FORMULA: {FORMULA}","green")
    display(VBox(input_box0 + [calc_btn, out]))
    def on_calc(bb):
        with out:
            out.clear_output()
            oper = Accounting_Equations[EQUATION]['operation']

            try:
                values = [box.value for box in input_box0]
                if oper == "pass":
                    result = 0
                    form = "normal"
                if oper == "add":
                   result = sum(values)
                   form = "normal"
                elif oper == "sub":
                   result = values[0] - values[1]
                   form = "normal"
                elif oper ==  "ssssub":
                   result = values[0] - values[1] - values[2]- values[3]
                   form = "normal"
                elif oper == "add_sub":
                   result = values[0]+values[1]-values[2]
                   form = "normal"
                elif oper == "aaadd_sub":
                  result = values[0] + values[1] + values[3] - values[4]
                  form = "normal"
                elif oper == "assa":
                  result = values[0]-values[1]-values[2]+values[3]
                  form = "normal"
                elif oper == "multi":
                  result = 1
                  for v in values:
                    result *= v
                    form = "normal"
                elif oper == "div":
                  result = values[0]
                  for v in values[1:]:
                    result /= v
                    form = "normal"
                elif oper == "add_div":
                    result = (values[0]+values[1]) / values[2]
                    form = "normal"
                elif oper == "add_div2":
                    result = sum(values) / 2
                    form = "normal"
                elif oper == "div_sub2":
                    result = (values[0]) / (values[1] - values[2])
                    form = "normal"
                elif oper == "sub_div":
                    result = (values[0]-values[1]) / values[2]
                    form = "normal"
                elif oper == "pmulti100":
                    result = (values[0]/values[1]) * 100
                    form = "percentage"
                elif oper == "365div":
                    result = 365 / values[0]
                    form = "normal"
                elif oper == "pow":
                    result = values[0] ** values[1]
                    form = "normal"
                elif oper == "delta":
                    delta_a = values[0] - values[1]
                    delta_l = values[2] - values[3]
                    delta_e = values[4] - values[5]
                    a_result = delta_a
                    le_result = delta_l + delta_e
                    if delta_a == delta_l + delta_e:
                      form = "delta"
                    else:
                        form = "not_delta"
                elif oper == "b":
                    mn = values[0] * 60
                    sec = values[1] / 60
                    form = "break"
                    result = 0
                    if sec == 0:
                        for remaining in range(int(mn), 0, -1):
                            clear_output(wait=True)
                            Sec = remaining / 60
                            print_colored(f"{values[1]} seconds = {sec:.4f} minutes\n⏳ Break time remaining: {remaining:.4f} seconds\n{Sec} minutes","green")
                            print_colored(f"\n","green")
                            time.sleep(1)
                    else:
                        for remaining in range(int(mn), 0, -1):
                            clear_output(wait=True)
                            Sec = remaining / 60
                            print_colored(f"{values[1]} seconds = {sec:.4f} minutes\n⏳ Break time remaining: {remaining:.4f} seconds\n{Sec} minutes","green")
                            print_colored(f"\n","green")
                            time.sleep(1)
                if form == "percentage":
                        print(f"\nYour {EQUATION} is: {result:,.2f}%")
                        return result
                elif form == "break":
                    clear_output(wait=True)
                    try:
                      display(Audio(filename="Dial_Up.mp3", autoplay=True))
                    except:
                      pass
                    print_colored(f"\n{values[1]} seconds = {sec:.4f} minutes\nhope you had a refereshing break. NOW BACK TO WORK NO PROCRASTINATING!!!\n","green")
                elif form == "delta":
                    print_colored(f"\nYour {EQUATION} is: {a_result:,.2f} and {le_result:,.2f}\n balanced well done!!","green")
                    return result
                elif form == "not_delta":
                    print_colored(f"\nYour {EQUATION} is: {a_result:,.2f} and {le_result:,.2f}\nNot balanced something doesn't add up","red")

                else:
                    print_colored(f"\nYour {color_codes['green']}{EQUATION.title()}{color_codes['reset']} are: {color_codes['green']}{D_sign}{result:,.2f}{color_codes['reset']}")
            except Exception as e:
                    print_colored(f"Error during calculation: {e}","red")
    calc_btn.on_click(on_calc)
try:
   display(Audio(filename="Dial_Up.mp3", autoplay=True))
except:
  pass
charts_button = Button(description="📊 Show Chart", button_style="info")
def show_chart(b):
    ledger_df = pd.DataFrame(general_ledger.items(), columns=['Account', 'Balance'])
    fig = px.bar(ledger_df, x="Account", y="Balance", title="Account Balances")
    fig.show()
charts_button.on_click(show_chart)
save_table= Button(description="💾>>Excel", button_style="success",layout=Layout(height='29px',width='95px',padding='1.15px',border='2.5px solid #00FF00'))
Save2table = Button(description="💾>>Excel", button_style="success",layout=Layout(height='29px',width='95px',padding='1.15px',border='2.5px solid #00FF00'))
float_progress = FloatProgress(
    value=0.0,
    min=0.0,
    max=0.5,
    description='LOADING>',
    bar_style='success',
    orientation='horizontal')
display(float_progress)
# Simulate progress
for i in range(7):
    float_progress.value += 0.1
    out.clear_output
    perc=(float_progress.value/0.5)*100
    #print({perc})
    time.sleep(0.3)
print_colored(f"Functions loaded calculator ready to boot","green")

Requirement already satisfied: simpleeval in /usr/local/lib/python3.12/dist-packages (1.0.3)

FloatProgress(value=0.0, bar_style='success', description='LOADING>', max=0.5)

Functions loaded calculator ready to boot

In [15]:
from operator import inv
#a11
#@title 2) Accounting project GUI (run this)
import pandas as pd
from itertools import batched
from concurrent.futures import ThreadPoolExecutor
pd.set_option('display.max_colwidth', None,'display.max_colwidth', None,'display.max_columns',None,'display.max_rows',None,)
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import statsmodels.api as sm
from scipy import stats
import numpy as np
import math,datetime,time,re
from simpleeval import simple_eval
from IPython.display import display,clear_output,Audio,Markdown,YouTubeVideo
from ipywidgets import (Layout,Combobox,Tab,Style,Accordion,TwoByTwoLayout, GridspecLayout,
    Button, Checkbox, Dropdown, FloatSlider, IntSlider,DatePicker,HTML,
    RadioButtons, Text, Textarea, ToggleButton, VBox, HBox, Label,interact,Output,IntText, FloatText)
#my version draft 2.5
#f3 cell tech name J7n1KBlhNu7z
combobX = Combobox()
a_lbl = Label
out = Output()
Accounting_Equations = { #            ⬇️
    "": {"lf":" ", "formula":" ".title(), "function":universal_variables,"variables":["0"],"operation":"pass","description":"o",},
    "accrued expenses":{"lf":"_", "formula":"Accrued Expense=Total Expense Incurred−Cash Paid".title(),"function":universal_variables,"variables":["Total Expense Incurred","Cash Paid"],"operation":"sub","description":"not available",},
    "accrued revenue": {"lf":"_", "formula":"Accrued Revenue=Revenue Earned−Cash Received".title(),"function": universal_variables,"variables":["Revenue Earned","Cash Received"],"operation":"sub","description":"o",},
    "adjusted cash balance book side": {"lf":" ", "formula":"Adjusted Cash Balance = Book Balance + Interest Earned - Bank Service Charges".title(), "function":universal_variables,"variables":["Book Balance","Interest Earned","Bank Service Charges"],"operation":"add_sub","description":"o",},
    "assets":{"lf":"_",  "formula": "Assets = Liabilities + Equity".title(),"function": universal_variables,"variables":["Liabilities","Equity"],"operation":"add","description":"o",},
    "assets lf" : {"lf":"_", "formula":"Assets=Liabilities+Common Stock-Dividend-Revenue+Expense".title(),"function":universal_variables,"variables":["Liabilities","Common Stock","Dividend","Revenue","Expense"],"operation":"assa","description":"o",},
    "asset turnover ratio": {"lf":"_", "formula": "Net Sales / Average Total Assets".title(),"function": universal_variables,"variables":["Net Sales","Average Total Assets"],"operation":"div","description":"o",},
    "average_accounts_receivable":{"lf":"_", "formula": "Average Accounts Receivable = Net Credit Sales / Avg. Accounts Receivable".title(), "function":universal_variables,"variables":["Net Credit Sales","Avg. Accounts Receivable"],"operation":"div","description":"o",},
    "average inventory": {"lf":"_", "formula":"Average Inventory = (Beginning Inventory + Ending Inventory) / 2".title(),"function":universal_variables,"variables":["Beginning Inventory","Ending Inventory"],"operation":"add_div2","description":"o",},
    "b": {"lf":"break", "formula":"sec/60=min min/60=hr....NOTE: 1 Sec: 0.0833, 5 Sec: 0.0167, 10 sec: 0.1667, 20 sec: 0.3333, 30 sec: 0.5\n" , "function": universal_variables,"variables":["how many mins","sec > min or hit 0 to skip"],"operation":"b","description": "note: 1 Sec: 0.0833, 5 Sec: 0.0167, 10 sec: 0.1667, 20 sec: 0.3333, 30 sec: 0.5\n",},
    "bad debt": {"lf":"_", "formula": "Bad Debt Expense = Estimated % × Accounts Receivable".title(),"function": universal_variables,"variables":["Estimated %","Accounts Receivable"],"operation":"multi","description":"o",},
    "book value per share": {"lf":"_", "formula":"Book Value Per Share = Equity - Preferred Equity/ Outstanding Shares".title(),"function":universal_variables,"variables":["Equity","Preferred Equity","Outstanding Shares"],"operation":"div_sub","description":"o",},
    "break even units": {"lf":"_", "formula":"Break Even Units = Fixed Costs/Price Per Unit-Variable Cost Per Unit".title(),"function":universal_variables,"variables":["Fixed Costs","Price Per Unit","Variable Cost Per Unit"],"operation":"sub_div","description":"o",},
    "capital employed": {"lf":"_", "formula":"Capital Employed = Total Assets − Current Liabilities".title(),"function":universal_variables,"variables":["Total Assets","Current Liabilities"],"operation":"sub","description":"o",},
    "cash flow from operations": {"lf":"_", "formula":"Cash Flow From Operations = Net Income + Non-Cash Expenses − Change In Working Capital".title(),"function":universal_variables,"variables":["Net Income","Non-Cash Expenses","Change In Working Capital"],"operation":"add_sub","description":"o",},
    "cash conversion cycle": {"lf":"_", "formula":"Ccc = Days Inventory Outstanding + Days Sales Outstanding – Days Payable Outstanding".title(),"function":universal_variables,"variables":["Days Inventory Outstanding","Days Sales Outstanding","Days Payable Outstanding"],"operation":"add_sub","description":"o",},
    "cash ratio" : {"lf":"_", "formula":"(Cash + Cash Equivalents) / Current Liabilities".title(),"function":universal_variables,"variables":["Cash","Cash Equivalents","Current Liabilities"],"operation":"add_div","description":"o",},
    "capital expenditure ratio": {"lf":"_", "formula": "Capital Expenditure Ratio = Operating Cash Flow / Capital Expenditures".title(),"function": universal_variables,"variables":["Operating Cash Flow","Capital Expenditures"],"operation":"div","description":"o",},
    "capital structure ratio": {"lf":"_", "formula": "Long-Term Debt / (Long-Term Debt + Equity)".title(),"function": universal_variables,"variables":["Long-Term Debt","Equity"],"operation":"div","description":"o",},
    "cash flow to debt ratio": {"lf":"_", "formula": "Cash Flow To Debt Ratio = Operating Cash Flow / Total Debt".title(),"function": universal_variables,"variables":["Operating Cash Flow","Total Debt"],"operation":"div","description":"o",},
    "cogs": {"lf":"_", "formula":"Cogs=Beginning Inventory+Purchases−Ending Inventory".title(),"function":universal_variables,"variables":["Beginning Inventory","Purchases","Ending Inventory"],"operation":"add_sub","description":"o",},
    "cogs 2": {"lf":"_", "formula":"Cogs=Net Sales−Gross Profit".title(),"function":universal_variables,"variables":["Net Sales","Gross Profit"],"operation":"sub","description":"the cost of the merchandise sold in perpetual inventory systems it is calculated for every sale",},
    "contribution margin": {"lf":"_", "formula":"Contribution Margin = Sales - Variable Costs".title(),"function":universal_variables,"variables":["Sales","Variable Costs"],"operation":"sub","description":"o",},
    "contribution margin ratio": {"lf":"_", "formula":"Contribution Margin Ratio = (Sales - Variable Costs) / Sales".title(),"function":universal_variables,"variables":["Sales","Variable Costs"],"operation":"sub_div","description":"the cost of the merchandise sold in perpetual inventory systems it is calculated for every sale",},
    "current ratio": {"lf":"_", "formula":"Current Ratio= Current Assets/ Current Liabilities".title(),"function":universal_variables,"variables":["Current Assets","Current Liabilities"],"operation":"div","description":"o",},
    "debt to equity": {"lf":"_", "formula":"Debt-To-Equity=Total Liabilities/Shareholder’S Equity".title(),"function":universal_variables,"variables":["Total Liabilities","Shareholder’S Equity"],"operation":"div","description":"o",},
    "depreciation": {"lf":"_", "formula":"Depreciation = (Cost Of Asset−Salvage Value​)/ Number Of Years".title(),"function":universal_variables,"variables":["Cost Of Asset","Salvage Value","Number Of Years"],"operation":"sub_div","description":"o",},
    "dpr": {"lf":"_", "formula":"Dpr = Dividend Payout Ratio=Dividends Per Share / Earnings Per Share".title(),"function": universal_variables,"variables":["Dividends Per Share","Earnings Per Share"],"operation":"div","description":"o",},
    "dps": {"lf":"_", "formula":"Dps=Total Dividends / Outstanding Shares".title(),"function":universal_variables,"variables":["Total Dividends","Outstanding Shares"],"operation":"div","description":"o",},
    "dso": {"lf":"_", "formula":"Days Sales Outstanding = 365 / Receivables Turnover".title(),"function":universal_variables,"variables":["Receivables Turnover"],"operation":"365div","description":"o",}, "dio": {"lf":"_", "formula":"Days Inventory Outstanding = 365 / Inventory Turnover".title(),"function":universal_variables,"variables":["Inventory Turnover"],"operation":"365div","description":"o",}, "dpt": {"lf":"_", "formula":"Days Payable Outstanding = 365 / Accounts Payable Turnover".title(),"function":universal_variables,"variables":["Accounts Payable Turnover"],"operation":"365div","description":"o",},
    "dupont roe": {"lf":"_", "formula": "Dupont Roe = (Net Profit Margin) × (Asset Turnover) × (Equity Multiplier)".title(),"function": universal_variables,"variables":["Net Profit Margin","Asset Turnover","Equity Multiplier"],"operation":"multi","description":"o",},
    "earnings per share": {"lf":"_", "formula":"Earnings Per Share (Eps) = Net Income / Average Outstanding Shares".title(),"function":universal_variables,"variables":["Net Income","Average Outstanding Shares"],"operation":"div","description":"o",}, "ebit" : {"lf":"_", "formula":"Ebit = Revenue – Operating Expenses".title(),"function":universal_variables,"variables":["Revenue","Operating Expenses"],"operation":"sub","description":"o",},
    "ebitda": {"lf":"_", "formula":"Ebitda = Net Income + Interest + Taxes + Depreciation + Amortization".title(),"function":universal_variables,"variables":["Net Income","Interest","Taxes","Depreciation","Amortization"],"operation":"add","description":"o",},
    "ending retained earnings": {"lf":"_", "formula":"Ending Retained Earnings=Beginning Retained Earnings+Net Income−Dividends".title(),"function":universal_variables,"variables":["Beginning Retained Earnings","Net Income","Dividends"],"operation":"add_sub","description":"o",},
    "enterprise value": {"lf":"_", "formula": "Ev = Market Cap + Total Debt – Cash And Cash Equivalents".title(),"function": universal_variables,"variables":["Market Cap","Total Debt","Cash And Cash Equivalents"],"operation":"add_sub","description":"o",},
    "equity ratio": {"lf":"_", "formula": "Equity Ratio = Total Equity / Total Assets".title(),"function": universal_variables,"variables":["Total Equity","Total Assets"],"operation":"div","description":"o",},
    "ev to ebitda": {"lf":"_", "formula": "Ev To Ebitda = Enterprise Value / Ebitda".title(),"function": universal_variables,"variables":["Enterprise Value","Ebitda"],"operation":"div","description":"o",},
    "equity": {"lf":"_", "formula":"Equity = Assets-Liabilities".title(),"function":universal_variables,"variables":["Assets","Liabilities"],"operation":"sub","description":"o",},
    "free cash flow": {"lf":"_", "formula":"Free Cash Flow = Operating Cash Flow − Capital Expenditures".title(),"function":universal_variables,"variables":["Operating Cash Flow","Capital Expenditures"],"operation":"sub","description":"o",},
    "fixed asset turnover": {"lf":"_", "formula": "Revenue / Net Fixed Assets".title(),"function": universal_variables,"variables":["Revenue","Net Fixed Assets"],"operation":"div","description":"o",},
    "gross margin": {"lf":"_", "formula":"Gross Margin = (Gross Profit / Revenue) × 100".title(),"function":universal_variables,"variables":["Gross Profit","Revenue"],"operation":"pmulti100","description":"o",},
    "gross profit": {"lf":"_", "formula":"Gross Profit=Net Sales−Cost Of Goods Sold (Cogs)".title(),"function":universal_variables,"variables":["Net Sales","Cost Of Goods Sold (Cogs)"],"operation":"sub","description":"o",},
    "inventory turnover": {"lf":"_", "formula":"Inventory Turnover = Cogs/Average Inventory".title(),"function":universal_variables,"variables":["Cogs","Average Inventory"],"operation":"div","description":"o",},
    "interest coverage ratio": {"lf":"_", "formula": "Ebit / Interest Expense".title(),"function": universal_variables,"variables":["Ebit","Interest Expense"],"operation":"div","description":"o",},
    "liabilities" : {"lf":"_", "formula":"Liabilities=Assets-Equity".title(),"function":universal_variables,"variables":["Assets","Equity"],"operation":"sub","description":"o",},
    "net cash flow": {"lf":"_", "formula": "Net Cash Flow = Inflows - Outflows".title(),"function": universal_variables,"variables":["Inflows","Outflows"],"operation":"sub","description":"o",},
    "net profit margin": {"lf":"_", "formula": "Net Profit Margin = (Net Income / Revenue) × 100".title(),"function": universal_variables,"variables":["Net Income","Revenue"],"operation":"pmulti100","description":"o",},
    "net profit": {"lf":"_", "formula":"Net Income=Revenue−Expenses".title(),"function":universal_variables,"variables":["Revenue","Expenses"],"operation":"sub","description":"o",},
    "net profit lf": {"lf":"_","formula":"Net Profit=(Gross Profit Or Net Sales)−Operating Expenses−Interest−Taxes".title(),"function":universal_variables,"variables":["Gross Profit Or Net Sales","Operating Expenses","Interest","Taxes"],"operation":"ssssub","description":"o",},
    "net income" : {"lf":"_","formula":"Net Profit=Sales Revenue−Cogs−Operating Expenses".title(),"function":universal_variables,"variables":["Sales Revenue","Cogs","Operating Expenses"],"operation":"sub","description":"o",},
    "non cash expenses" : {"lf":"_", "formula":"Non-Cash Expenses = Operating Expenses - Operating Income".title(),"function":universal_variables,"variables":["Operating Expenses","Operating Income"],"operation":"sub","description":"o",},
    "operating income": {"lf":"_", "formula":"Operating Income = Gross Profit − Operating Expenses".title(),"function":universal_variables,"variables":["Gross Profit","Operating Expenses"],"operation":"sub","description":"o",},
    "operating margin": {"lf":"_", "formula":"Operating Margin = (Operating Income / Revenue) × 100".title(),"function":universal_variables,"variables":["Operating Income","Revenue"],"operation":"pmulti100","description":"o",},
    "operating cash flow ratio": {"lf":"_", "formula": "Operating Cash Flow / Current Liabilities".title(),"function": universal_variables,"variables":["Operating Cash Flow","Current Liabilities"],"operation":"div","description":"o",},
    "operating leverage": {"lf":"_", "formula": "Degree Of Operating Leverage = % Change In Ebit / % Change In Sales".title(),"function": universal_variables,"variables":["% Change In Ebit","% Change In Sales"],"operation":"div","description":"o",},
    "payables turnover": {"lf":"_", "formula":"Payables Turnover = Purchases / Avg. Accounts Payable".title(),"function":universal_variables,"variables":["Purchases","Avg. Accounts Payable"],"operation":"div","description":"o",},
    "prepaid expenses adjustment": {"lf":"_", "formula":"Used Expense=Beginning Balance+Purchases−Ending Balance".title(),"function":universal_variables,"variables":["Beginning Balance","Purchases","Ending Balance"],"operation":"add_sub","description":"o",},
    "price per unit": {"lf":"_", "formula": "Price Per Unit = Revenue / Number Of Units Sold".title(),"function": universal_variables,"variables":["Revenue","Number Of Units Sold"],"operation":"div","description":"o",},
    "price to book ratio": {"lf":"_", "formula": "Price To Book Ratio = Market Price Per Share / Book Value Per Share".title(),"function": universal_variables,"variables":["Market Price Per Share","Book Value Per Share"],"operation":"div","description":"o",},
    "price to earnings ratio": {"lf":"_", "formula": "Price To Earnings Ratio = Price Per Share / Earnings Per Share".title(),"function": universal_variables,"variables":["Price Per Share","Earnings Per Share"],"operation":"div","description":"o",},
    "production cost per unit": {"lf":"_", "formula": "Total Production Cost / Number Of Units Produced".title(),"function": universal_variables,"variables":["Total Production Cost","Number Of Units Produced"],"operation":"div","description":"o",},
    "profit margin": {"lf":"_", "formula": "Net Profit / Revenue × 100".title(),"function": universal_variables,"variables":["Net Profit","Revenue"],"operation":"pmulti100","description":"o",},
    "quick ratio": {"lf":"_", "formula":"Quick Ratio = (Current Assets-Inventory)/Current Liabilities".title(),"function":universal_variables,"variables":["Current Assets","Inventory","Current Liabilities"],"operation":"sub_div","description":"o",},
    "receivables turnover": {"lf":"_", "formula":"Receivables Turnover = Net Credit Sales / Avg. Accounts Receivable".title(),"function":universal_variables,"variables":["Net Credit Sales","Avg. Accounts Receivable"],"operation":"div","description":"o",},
    "return on assets": {"lf":"_", "formula":"Return On Assets  (Roa) = Net Income / Total Assets".title(),"function":universal_variables,"variables":["Net Income","Total Assets"],"operation":"div","description":"o",},
    "return on equity": {"lf":"_", "formula":"Return On Equity (Roe) = Net Income / Shareholder’S Equity".title(),"function":universal_variables,"variables":["Net Income","Shareholder’S Equity"],"operation":"div","description":"o",},
    "roi": {"lf":"_", "formula":"Roi (%) = (Net Profit / Investment) × 100".title(),"function":universal_variables,"variables":["Net Profit","Investment"],"operation":"pmulti100","description":"o",},
    "revenue": {"formula": "Revenue = Price Per Unit × Number Of Units Sold".title(),"function": universal_variables,"variables":["Price Per Unit","Number Of Units Sold"],"operation":"multi","description":"o",},
    "return on capital employed (roce)": {"formula": "Roce = Ebit / Capital Employed".title(),"function": universal_variables,"variables":["Ebit","Capital Employed"],"operation":"div","description":"o",},
    "supplies used": {"lf":"_", "formula":"Supplies Used (Expense)=Beginning Balance+Purchases−Ending Balance".title(),"function": universal_variables,"variables":["Beginning Balance","Purchases","Ending Balance"],"operation":"add_sub","description":"o"},
    "sales": {"lf":"_", "formula": "Sales = Price Per Unit × Number Of Units Sold".title(),"function": universal_variables,"variables":["Price Per Unit","Number Of Units Sold"],"operation":"multi","description":"o",},
    "sales cash overage entry": {"lf":"_","formula":"$$Debit (Cash) = Credit(CR) Sales + Credit(CR) Cash Over and Short".title(),"function":universal_variables,"variables":["CR(Sales)","CR(Cash Over and Short)"],"operation":"add","description":"not available",},
    "unearned revenue": {"lf":"_", "formula":"Revenue Earned=Beginning Unearned Revenue+Cash Received−Ending Unearned Revenue".title(),"function":universal_variables,"variables":["Beginning Unearned Revenue","Cash Received","Ending Unearned Revenue"],"operation":"add_sub","description":"o",},
    "tangible book value": {"lf":"_", "formula": "Tangible Book Value = Total Equity - Intangible Assets".title(),"function": universal_variables,"variables":["Total Equity","Intangible Assets"],"operation":"sub","description":"o",},
    "times interest earned": {"lf":"_", "formula": "Ebit / Interest Expense".title(),"function": universal_variables,"variables":["Ebit","Interest Expense"],"operation":"div","description":"o",},
    "total assets": {"lf":"_", "formula": "Total Assets = Current Assets + Non_Current Assets".title(),"function": universal_variables,"variables":["Current Assets","Non-Current Assets"],"operation":"add","description":"o",},
    "total liabilities": {"lf":"_", "formula": "Total Liabilities = Current Liabilities + Long_Term Liabilities".title(),"function": universal_variables,"variables":["Current Liabilities","Long-Term Liabilities"],"operation":"add","description":"o",},
    "working capital": {"lf":"_", "formula":"Working Capital = Current Assets - Current Liabilities".title(),"function":universal_variables,"variables":["Current Assets","Current Liabilities"],"operation":"sub","description":"o",},"working capital turnover" : {"lf":"_", "formula":"Working Capital Turnover = Net Sales / Average Working Capital".title(),"function":universal_variables,"variables":["Net Sales","Average Working Capital"],"operation":"div","description":"o",},
    "+" : {"lf":"_", "formula": "a+b" .title(),"function": universal_variables,"variables":["num1","num2","num3","num5","num6","num7"],"operation":"add","description":"o",},
    "-" : {"lf":"_", "formula": "a-b" .title(),"function": universal_variables,"variables":["num1","num2","num3","num5","num6","num7"],"operation":"sub","description":"o",},
    "*" : {"lf":"_", "formula": "a*b" .title(),"function": universal_variables,"variables":["num1","num2","num3","num5","num6","num7"],"operation":"multi","description":"o",},
    "**": {"lf":"_", "formula": "A to the power of A" .title(),"function": universal_variables,"variables":["num1","num2",],"operation":"pow","description":"o",},
    "/" : {"lf":"_", "formula": "a/b" .title(),"function": universal_variables,"variables":["num1","num2","num3","num5","num6","num7"],"operation":"div","description":"o",},
    "%" : {"lf":"_", "formula": "(part/whole)*100" .title(),"function": universal_variables,"variables":["part","whole"],"operation":"pmulti100","description":"o",},
    "+-" : {"lf":"_", "formula": "(num1+num2)-num3" .title(),"function": universal_variables,"variables":["num1","num2","num3"],"operation":"add_sub","description":"o",},
    "+/" : {"lf":"_", "formula": "(num1+num2)/num3" .title(),"function": universal_variables,"variables":["num1","num2","num3"],"operation":"add_div","description":"o",},
    "/-" : {"lf":"_", "formula": "(num1-num2)/num3" .title(),"function": universal_variables,"variables":["num1","num2","num3"],"operation":"sub_div","description":"o",},
} #f4
# add definitions for each of the variables listed ex net income
# credit terms 4/10 meaning pay in 10 days to get 40% discount n/30 pay within 30 days
#Assets=Liabilities+Common Stock+Beginning Retained Earnings+Revenues−Expenses−Dividends
#Net Profit=Gross Profit−Operating Expenses−Interest−Taxes gp or net sales
#periodic inventory system and the gross method of accounting for sales.
#Cushman Company had $832,000 in net sales, $364,000 in gross profit, and $208,000 in operating expenses. Cost of goods sold equals
#468,000 correct
#May 1: Costco sold some food products to a customer for $3,000. The cost of the products is $1,000. Also, Costco's daily operating exepsnes is $500 #
#What is the net profit from the sale on May 1. $2,000
#May 1: Costco sold food products to a customer for $3,000. The cost of the product is $1,000. Costco's daily operating expenses is $500.
#What is the Net Income for CostCo
#1,500"
#A service company earns net income by buying and selling merchandisea_lbl("")  .to_csv("people.csv", index=False) to save \>> csv file open("ledger.json", "w") as f:
#    json.dump(general_ledger, f, indent=4)
display(HTML("""
<style>
label.widget-label {color: #00FF00 !important}
/* Forces green text on ALL buttons */
.widget-button {color: #00FF00 !important;}
widget.value{color: #00FF00 !important}
/* Active Tab Background */
.lm-TabBar-tab.lm-mod-current {
    background-color: #00FF00; !important;}
/* Target the active tab header */
.lm-TabBar-tab.lm-mod-current {
/* Remove the default bottom border to avoid double lines */
border-bottom: none !important;
/* Set the border color, thickness, and style for the TOP edge */
border-top: 7px solid #00FF00 !important;}
/* Inactive Tabs Background */
.lm-TabBar-tab {
    background-color: #00FF00; !important;}
/* Tab Header Text Color (optional) */
.lm-TabBar-tab.lm-mod-current .lm-TabBar-tabLabel {
    color: #00FF00 !important;} /* White text for the blue active tab */
.Textarea.widget-value {color: #00FF00 !important;}
</style>
"""))
#display(HTML("""<style>.widget-button,.custom-input input {color: #00FF00 !important; /* Forces green text on ALL buttons */}</style>"""))  f5
display(HTML("""<style>.Textarea.widget-value {color: #00FF00 !important; /* Forces green text on ALL buttons */}</style>"""))
label1 = HTML("""<p><span style='color: #00FF00;'>Greetings! My name is Profitsa Soaring, your accounting assistant. Acceptable inputs only
  <br>What are you calculating? (type x to exit, enter o for more options)<br>if nothing happens keep clicking the button</span></p>""")
label2= HTML("""<p><span style='color: #00FF00;'>coming soon</span></p>""")
#notes = "" #@param {type: "string"}
#date = "2025-10-29" # @param {"type":"date","placeholder":"input the date"}
Del = Button(description="ALL_CLEAR",layout=Layout(height='29px',width='95px',padding='1.15px',border='2.5px solid #00FF00'))
Del.style.button_color = 'black'
Clear_t = Button(description="Clear_Array",button_style='danger' ,layout=Layout(width='95px',border='0.9px solid #00FF00'))
Clear_t.style.button_color = 'black'
Clear_n=Button(description="Clear_Notes",layout=Layout(height='30px',width='auto',padding='1.25px',border='0.9px solid #00FF00'))
Clear_n.style.button_color = 'black'
Clear_selection = Button(description="<<Clear",layout=Layout(height='30px',width='95px',border='0.9px solid #00FF00'))
Clear_selection.style.button_color = 'black'
Len_button=Button(description="Character_lenght",layout=Layout(height='70px',width='220px',border='0.9px solid #00FF00'))
create_table= Button(description="Create_Table",layout=Layout(height='30px',width='95',border='0.9px solid #00FF00'))
save_button = Button(description="💾>>Excel", button_style="success",layout=Layout(height='29px',width='95px',padding='1.15px',border='2.5px solid #00FF00'))
combobox_menu = Combobox(
placeholder='Choose or type...',
options=list(Accounting_Equations.keys()), # Use the keys of the dictionary as options f6
value = "",
description='Your choice:', Layout = Layout(width='auto'),
style = {'description_width': 'initial'},
layout = Layout(height='auto',width='auto',),
ensure_option=False)
Matrix_button = Button(description="Submit", button_style='info',layout=Layout(height='29px',width='95px',padding='1.15px',border='2.5px solid #00FF00'))
Matrix_button.style.button_color = '#006400' #display this outside button
Base_tab = VBox([label1,HBox([combobox_menu, Matrix_button,Del])],layout=Layout(padding='50px',border='1px solid #00FF00'))
combobox_s = Combobox(
placeholder='Choose or type...',
options=list(Accounting_Equations.keys()), # Use the keys of the dictionary as options
value = "",
description='Your choice:',
ensure_option=False)
label3 = HTML("""<p><span style='color: #00FF00;'>Study buddy(work in proggress)</span></p>""")
s_button = Button(description="Submit", button_style='info',layout=Layout(width='95px',border='0.9px solid green',))
s_button.style.button_color = '#002D04' #display this outside button
combobox_e = Combobox(
placeholder='Choose or type...',
options=list(Accounting_Equations.keys()), # Use the keys of the dictionary as options  f7
value = "",
description='Your choice:',
ensure_option=False)
label4 = HTML("""<p><span style='color: #00FF00;'>Ask for any equation on the menu</span></p>""")
e_button = Button(description="Submit", button_style='info',layout=Layout(width='95px',border='0.9px solid green',))
e_button.style.button_color = '#002D04' #display this outside button
Hbox_study = VBox([HBox([label3,]),HBox([combobox_s,s_button,Del])])
Hbox_equation = VBox([HBox([label4,Clear_n,]),HBox([combobox_e, e_button,Del])])
Cbx_btn_es = VBox([Hbox_equation, Hbox_study],layout=Layout(padding='50px',background='red', border='2px solid #00FF00'))
textarea_inputs =Textarea(value='Notes', placeholder='Type something', description='Temp notes:',layout=Layout(height='300px',width='auto',border='0.9px solid green',))
text_input = Text(value='o',description="Enter Expression:",style={'description_width': 'initial'},layout=Layout(width='auto',border='0.9px solid green'))
label5 = HTML("""<p><span style='color: #00FF00;'>Calculator<br>MATH ONLY!!!</span></p>""")
Calc = VBox([label5,HBox([text_input,Del,]),out],layout=Layout(padding='25px',border='2px solid #00FF00'))
sub_btn = Button(description="Submit", button_style='info',layout=Layout(width='95px',border='2px solid green'))
sub_btn.style.button_color = '#002D04' #display this outside button f8
grid = GridspecLayout(3, 9)
Clear_T_df = Button(description="Clear_Table",button_style='danger',layout=Layout(width='105px',border='1.9px solid green'))
Clear_T_df.style.button_color = 'black'
grid[0,0] = DatePicker(description='Select Date:',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',)) #default value to today's date f9
grid[1,0] = Combobox(options=list(general_ledger.keys()),ensure_option=False,description='Debit(DR)', layout=Layout(height='auto',width='auto',border='1.9px solid green'))
grid[2,1] = HBox([sub_btn,Clear_T_df,Del]) #
grid[1,1] = Combobox(options=list(general_ledger.keys()),ensure_option=False,description='Credit(CR)', layout=Layout(border='1.9px solid green',width='100', height='auto'))
grid[2,0] = FloatText(description="Amount" + ":",value=0,style = {'description_width': 'initial'},layout=Layout(border='1.9px solid green',))
grid[0,1] = Text(description="Description:",layout=Layout(border='1.9px solid green',))
grid[0,3] = Button(description="💾>>Excel", button_style="success",layout=Layout(height='29px',width='95px',padding='1.15px',border='2.5px solid #00FF00'))
label6 = HTML("""<p><span style='color: #00FF00;'>🐢--- Double-Entry Transaction Input ---🐢_________________(On account = credit, Cash = debit)</span></p>""")
grid1 = VBox([label6,grid,])
dates = DatePicker(description="Date:",value=datetime.date.today(),layout=Layout(width='215px',border='0.9px solid green',))
val = Textarea(description="Description:",value='',placeholder="ex: Provided Legal Service to a client and got paid $10,000 Cash",layout=Layout(height='120px',width='502px',border='0.9px solid green',))
submit_button = Button(description="Submit", button_style='success',layout=Layout(width='85px',border='2px solid green',))
submit_button.style.button_color = '#002D04' #display this outside button
label7 = HTML("""<p><span style='color: #00FF00;'>🐢------------------ General_Ledger ---------------🐢<br>Use consistent character length for best display</span></p>""")
Tabbles_tab = VBox([HBox([label7,Len_button,save_table,]),HBox([dates,submit_button,Clear_t,Del]),HBox([val,])])
label8 = HTML("""<p><span style='color: #00FF00;'>INVENTORY_TAB</span></p>""")
grid2 = GridspecLayout(12, 30) #a safe number of rows for real accounting is around 10 so (30,3) should be good
fili_button=Button(description='Submit',button_style='success',layout=Layout(width='86px',border='1.9px solid green',))
fili_button.style.button_color = '#002D04' #display this outside button
inv_options=Combobox(description="Inv",value="",placeholder="choose_one",options=["FIFO_perpetual",'LIFO_perpetual',"FIFO_periodic","LIFO_periodic","AVCO_periodic","AVCO_perpetual"],ensure_option=False,layout=Layout(border='1.9px solid green',width='70', height='85'))
grid2[0,0]=DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[1,0] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[2,0] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[0,1] = FloatText(description='First_inv',value=float("100"),disabled=False,layout=Layout(border='1.9px solid green',))
grid2[1,1] = FloatText(description='Purchase',disabled=False,value=float("200"),layout=Layout(border='1.9px solid green',))
grid2[2,1] = FloatText(description='Sales',disabled=False,value=float("150"),layout=Layout(border='1.9px solid green',))
grid2[0,2] = FloatText(description='Each_@',disabled=False,value=float("10"),layout=Layout(border='1.9px solid green',))
grid2[1,2] = FloatText(description='Each_@',disabled=False,value=float("12"),layout=Layout(border='1.9px solid green',))
grid2[2,2] = FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[3,0] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[4,0] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[5,0] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[3,1] = FloatText(description='Purchase',disabled=False,value=float("100"),layout=Layout(border='1.9px solid green',))
grid2[4,1] = FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[5,1]=FloatText(description='Sales',disabled=False,value=float("120"),layout=Layout(border='1.9px solid green',))
grid2[3,2]=FloatText(description='Each_@',disabled=False,value=float("14"),layout=Layout(border='1.9px solid green'))
grid2[4,2]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[5,2]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[6,0]=DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[7,0]=DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[8,0]=DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[6,1]=FloatText(description='Purchase',disabled=False,value=float("80"),layout=Layout(border='1.9px solid green',))
grid2[7,1]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[8,1]=FloatText(description='Sales',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[6,2]=FloatText(description='Each_@',disabled=False,value=float("11"),layout=Layout(border='1.9px solid green',))
grid2[7,2]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[8,2]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[9,0]=DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[10,0]=DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[11,0]=DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[9,1]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[10,1]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[11,1]=FloatText(description='Sale',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[9,2]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[10,2]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[11,2]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[0,3] = DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[1,3] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[2,3] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[0,4] = FloatText(description='Purchase',value=float("100"),disabled=False,layout=Layout(border='1.9px solid green',))
grid2[1,4] = FloatText(description='Purchase',disabled=False,value=float("200"),layout=Layout(border='1.9px solid green',))
grid2[2,4] = FloatText(description='Sales',disabled=False,value=float("150"),layout=Layout(border='1.9px solid green',))
grid2[0,5] = FloatText(description='Each_@',disabled=False,value=float("10"),layout=Layout(border='1.9px solid green',))
grid2[1,5] = FloatText(description='Each_@',disabled=False,value=float("12"),layout=Layout(border='1.9px solid green',))
grid2[2,5] = FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[3,3] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[4,3] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[5,3] = DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[3,4] = FloatText(description='Purchase',disabled=False,value=float("100"),layout=Layout(border='1.9px solid green',))
grid2[4,4] = FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[5,4]=FloatText(description='Sales',disabled=False,value=float("120"),layout=Layout(border='1.9px solid green',))
grid2[3,5]=FloatText(description='Each_@',disabled=False,value=float("14"),layout=Layout(border='1.9px solid green'))
grid2[4,5]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[5,5]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[6,3]=DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[7,3]=DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[8,3]=DatePicker(description= 'Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[6,4]=FloatText(description='Purchase',disabled=False,value=float("80"),layout=Layout(border='1.9px solid green',))
grid2[7,4]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[8,4]=FloatText(description='Sales',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[6,5]=FloatText(description='Each_@',disabled=False,value=float("11"),layout=Layout(border='1.9px solid green',))
grid2[7,5]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[8,5]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[9,3]=DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[10,3]=DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[11,3]=DatePicker(description='Date',disabled=False,value=datetime.date.today(),layout=Layout(border='1.9px solid green',))
grid2[9,4]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[10,4]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[11,4]=FloatText(description='Sale',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[9,5]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[10,5]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[11,5]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[0,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[1,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[2,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[0,7] = FloatText(description='Purchase', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[1,7] = FloatText(description='Purchase', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[2,7] = FloatText(description='Sales', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[0,8] = FloatText(description='Each_@', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[1,8] = FloatText(description='Each_@', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[2,8] = FloatText(description='Each_@', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[3,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[4,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[5,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[3,7] = FloatText(description='Purchase', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[4,7] = FloatText(description='Purchase', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[5,7] = FloatText(description='Sales', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[3,8] = FloatText(description='Each_@', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[4,8] = FloatText(description='Each_@', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[5,8] = FloatText(description='Each_@', disabled=False, value=float("0"), layout=Layout(border='1.9px solid green'))
grid2[6,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[7,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[8,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[6,7]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[7,7]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[8,7]=FloatText(description='Sale',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[6,8]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[7,8]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[8,8]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[9,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[10,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[11,6] = DatePicker(description='Date', disabled=False, value=datetime.date.today(), layout=Layout(border='1.9px solid green'))
grid2[9,7]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[10,7]=FloatText(description='Purchase',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[11,7]=FloatText(description='Sale',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[9,8]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
grid2[10,8]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green'))
grid2[11,8]=FloatText(description='Each_@',disabled=False,value=float("0"),layout=Layout(border='1.9px solid green',))
fifo_lifo = VBox([HBox([fili_button,Del,label8,inv_options,Clear_selection,Save2table]),VBox([grid2])])#
tab_widget = Tab(children=[Base_tab,Cbx_btn_es,textarea_inputs,Calc,grid1,Tabbles_tab,fifo_lifo,],layout=Layout(width='830px', height='auto', border='8.5px solid #00FF00'))
Tab_widget2=Tab(children=[label2],layout=Layout(width='830px', height='auto', border='8.5px solid #00FF00'))
accordion=Accordion(children=[tab_widget],layout=Layout(width='900px', height='auto',padding='1.5px',border='5px solid #00FF00'))
accordion2 =Accordion(children=[Tab_widget2],layout=Layout(width='895px', height='auto',padding='0.1px',border='2.5px solid #00FF00'))
tab_widget.set_title(0, "Base module")
tab_widget.set_title(1, "More options")
tab_widget.set_title(2, "Notes")
tab_widget.set_title(3, "Calculator")
tab_widget.set_title(4, "T table")
tab_widget.set_title(5, "T list",)
tab_widget.set_title(6, "FIFO/LIFO")
tab_widget.set_title(7, "Coming soon")
accordion.set_title(0, 'Section_1')
accordion2.set_title(0,'Section_2')  #GUI    accordion2,
label9 = a_lbl(print_colored("Accounting project GUI version","green"))

display(label9,accordion,out,)
def clear_sel(s):
    with out:
        out.clear_output()
        inv_options.value=""
Clear_selection.on_click(clear_sel)
def del_n(n):
    with out:
        out.clear_output()
        textarea_inputs.value="Notes"
        print_colored("Notes cleared","green")
Clear_n.on_click(del_n)
def Le_character(l):
    with out:
         out.clear_output()
         print_colored(f"Character_lenght_(CLEN)is_{len(val.value)}","green")
         print_colored(f"(CLEN)_for_notes_is_{len(textarea_inputs.value)}","green")
Len_button.on_click(Le_character)
def submit_transaction(m):
    with out:
        out.clear_output() # Clear previous output f10
        #__________________________________________________________________________________________
        if len(val.value)>150:
            print_colored(f"Notes too long.{len(val.value)}","yellow")
            print_colored("Please enter a shorter note.","yellow")
            return
        #__________________________________________________________________________________________
        general_journal_series = pd.Series(values,index=data)
        general_journal_series.index.name ="date"
        general_journal_series.name = "General_Journal"
        data.append(dates.value)
        values.append(val.value)
        gen_journal=[(dates.value,val.value)]
        general_j = pd.DataFrame(gen_journal, columns=['description', 'transaction'])
        general_journal_series = pd.Series(values,index=data)
        print_colored(f"{len(val.value)}","green")
        display(general_journal_series)
def entryreset(d):
    with out:
         out.clear_output()
         combobox_s .value=""
         combobox_e.value=""
         val.value=""
         text_input.value="o"
         combobox_menu.value=""
         inv_options.value=""
         float_reset=float("0")
         grid[1,0].value=""
         grid[0,1].value=""
         grid[2,0].value=f"{float_reset}"
         grid[1,0].value=""
         grid[1,1].value=""
         grid[2,1].value=""
         grid2[0,1].value=f"{float_reset}"
         grid2[1,1].value=f"{float_reset}"
         grid2[2,1].value=f"{float_reset}"
         grid2[0,2].value=f"{float_reset}"
         grid2[1,2].value=f"{float_reset}"
         grid2[2,2].value=f"{float_reset}"
         grid2[3,1].value=f"{float_reset}"
         grid2[4,1].value=f"{float_reset}"
         grid2[5,1].value=f"{float_reset}"
         grid2[3,2].value=f"{float_reset}"
         grid2[4,2].value=f"{float_reset}"
         grid2[5,2].value=f"{float_reset}"
         grid2[6,1].value=f"{float_reset}"
         grid2[7,1].value=f"{float_reset}"
         grid2[8,1].value=f"{float_reset}"
         grid2[6,2].value=f"{float_reset}"
         grid2[7,2].value=f"{float_reset}"
         grid2[8,2].value=f"{float_reset}"
         grid2[9,1].value=f"{float_reset}"
         grid2[10,1].value=f"{float_reset}"
         grid2[11,1].value=f"{float_reset}"
         grid2[9,2].value=f"{float_reset}"
         grid2[10,2].value=f"{float_reset}"
         grid2[11,2].value=f"{float_reset}"
         print_colored("ALL_CLEAR","green")
Del.on_click(entryreset)
def clear_entries(b):
    with out:
        out.clear_output()
        global values,data,pd,plt
        pd.set_option('display.max_colwidth', None,'display.max_colwidth', None,'display.max_columns',None,'display.max_rows',None,)
        values.clear()
        data.clear()
        general_journal_series = pd.Series(dtype='object')
        print_colored("All entries cleared ✅","green")
# --- Button events ---
Clear_t.on_click(clear_entries)
submit_button.on_click(submit_transaction)
def submit_transactions(m):
    with out:
        out.clear_output() # Clear previous output
        date = grid[0,0].value
        debit_account = grid[1,0].value
        credit_account = grid[1,1].value
        amount = grid[2,0].value
        description = grid[0,1].value
        if amount <= 0:
            print_colored("❌ Error: Amount must be greater than zero.","red")
            return
        general_ledger[debit_account] += amount
        general_ledger[credit_account] -= amount  # A credit is the opposite of a debit
        print_colored(f"✅ Transaction Posted on {date}:","green")
        print_colored(f"   - Debited {debit_account}: ${amount:,.2f}","green")
        print_colored(f"   - Credited {credit_account}: ${amount:,.2f}","green")
        ledger_df = pd.DataFrame(general_ledger.items(), columns=['Account', 'Balance'])
        print_colored("\n💰 Updated General Ledger:","green")
        print_colored("If you want the interactive features of a Pandas DF run the next cell\nyou may want to re run it after updating the data\n👇(Pandas DataFrame(s))👇")
        display(ledger_df)
        assets = ledger_df['Balance'][:4].sum()
        liabilities_equity = ledger_df['Balance'][4:].sum()
        if abs(assets - liabilities_equity) < 0.01:
             print_colored(f"\n✨ Accounting Equation Balanced! A (${assets:,.2f}) = L+E (${liabilities_equity:,.2f})","green")
        else:
             print_colored(f"\n⚠️ WARNING: Accounting Equation is NOT balanced! A (${assets:,.2f}) != L+E (${liabilities_equity:,.2f})","red")
        def clear_t_datatframe(t):
            with out:
                 out.clear_output()
                 global general_ledger,pd,plt
                 general_ledger = {k: 0.0 for k in general_ledger}
                 ledger_df["Balance"] = ledger_df["Account"].map(general_ledger) #.map?
                 print_colored("ALL_CLEAR","green")

        Clear_T_df.on_click(clear_t_datatframe)
sub_btn.on_click(submit_transactions)
def save_ledger_to_excel(b):
    ledger_df = pd.DataFrame(general_ledger.items(), columns=['Account', 'Balance'])
    ledger_df.to_excel("ledger.xlsx", index=False)
    print_colored("✅ Ledger saved to 'ledger.xlsx'", "green")
grid[0,3].on_click(save_ledger_to_excel)
def handle_enter(change): #tab_widget
    with out:
        clear_output()
        expression = text_input.value.strip()
        if not expression:
            print_colored("Please enter an expression.","yellow")
            return
        elif expression == "o":
            print_colored("""()\n*:multiplication\n/:division\n-:subtraction\n+:addition\n**:powers\n%:percentage\noperators():abs(), round(), ceil(),\nfloor(), exp(), log(),\nsqrt(), sin(), cos(), tan(), degrees(), radians()
            \ne=2.718281828459045\n//:\nand  or  not\n==  !=  <  <=  >  >=\n&  |  ^  ~  <<  >>\n""","green")
            return
        elif len(expression) > 200:
            print_colored("Expression too long.","yellow")
            return
        try:
            # Use simple_eval to safely evaluate the expression string
            result = simple_eval(expression, names=ALLOWED_NAMES, functions=ALLOWED_FUNCS)
            print_colored(f"{change.value}={result}","green")
        except Exception as e:
            # Catch potential errors during evaluation (e.g., invalid syntax)
            print_colored(f"Error: {e}","red")
text_input.on_submit(handle_enter)
def on_button_clicked(b):
      with out:
        out.clear_output() # Clear previous output
        EQUATION = combobox_menu.value.strip().lower()
        try:
            if EQUATION: # Check if the input is not empty
                print_colored(f"You chose: {EQUATION}","green")
            else:
                print_colored("Please enter or select a value.","orange")
            if EQUATION in Accounting_Equations:
            # Call the corresponding function #f6
                result = Accounting_Equations[EQUATION]["function"]()
                print_colored(f"\nResult for {EQUATION}: {result}\n","green")
            elif EQUATION == "x":
                print_colored("Goodbye!","green")
                exit()
            elif EQUATION == "p":
              for key,value in Accounting_Equations.items():#
                print_colored(f"\n{key}: {value['formula']}","green")
            elif EQUATION == "v":
              for key, value in Accounting_Equations.items():
                  print_colored(f"{key}: {value['variables']}","green")
            elif EQUATION == "o":
                  print_colored("p for full menu,\ne to ask for any equation,\ns for study features\nb to take a timed break\nv to print variable name in the dictionary\ne to select equation","green")
            else:
              print_colored("Sorry, I don't recognize that equation. Try again or type 'p' to see the list.\n","orange")
        except ValueError:
            print_colored("error","red")
            pass
def e_button_click(e):
      with out:
        out.clear_output() # Clear previous output
        equation_requested = combobox_e.value.strip().lower()
        try:
            if equation_requested: # Check if the input is not empty
                print_colored(f"You chose: {equation_requested}","green")
            else:
                print_colored("Please enter or select a value.","orange")
            if equation_requested in Accounting_Equations:
                print_colored(f"\n{Accounting_Equations[equation_requested]['formula']}\n","green")
            else:
                print_colored("Formula not found.\n","yellow")
        except ValueError:
            print_colored("error","red")
            pass
def s_button_click(s):
      with out:
        out.clear_output() # Clear previous output
        study = combobox_s.value.strip().lower()
        try:
            if study:
              print_colored(f"You chose: {study}","green")
            else:
                print_colored("Please enter or select a value.","orange")
            if study in Accounting_Equations:
                print_colored(f"{Accounting_Equations[study]['description']}","green")
            else:
                print_colored("Concept not found or no description available.","red")
        except ValueError:
            print_colored("error","red")
            pass
e_button.on_click(e_button_click)
s_button.on_click(s_button_click)
Matrix_button.on_click(on_button_clicked)
def fifo_lifo_table(fili):
    with out:
        out.clear_output()

        print_colored("FIFO/LIFO/PERPETUAL/PERIODIC","green")
        fili=inv_options.value
        print_colored(f"You chose: {fili}","green")
        inventory_type=inv_options.value
        beginning_inv=grid2[0,1].value
        Purchase1=grid2[1,1].value
        Sales=grid2[2,1].value
        each_at1=grid2[0,2].value
        each_at2=grid2[1,2].value
        each_at3=grid2[2,2].value
        Purchase2=grid2[3,1].value
        Purchase3=grid2[4,1].value
        Sales2=grid2[5,1].value
        each_at4=grid2[3,2].value
        each_at5=grid2[4,2].value
        each_at6=grid2[5,2].value
        Purchase4=grid2[6,1].value
        Purchase5=grid2[7,1].value
        Sales3=grid2[8,1].value
        each_at7=grid2[6,2].value
        each_at8=grid2[7,2].value
        each_at9=grid2[8,2].value
        Purchase6=grid2[9,1].value
        Purchase7=grid2[10,1].value
        Sales4=grid2[11,1].value
        each_at10=grid2[9,2].value
        each_at11=grid2[10,2].value
        each_at12=grid2[11,2].value
        inventory = []
        cogs = 0
        # Collect all transaction groups dynamically
        transactions = {
        }
        #for transaction in transactions:
        #    inventory.append(transaction)
        if fili == "FIFO_perpetual":
            #inventory = {'transaction1':{"rev1":Sales,"inv1":[beginning_inv, each_at1]},'transaction2':{"rev1":Sales2,"inv2":[Purchase1, each_at2]},'transaction3':{"rev1":Sales3,"inv3":[Purchase2, each_at4]},'transaction4':{"rev1":Sales4,"inv4":[Purchase3, each_at5]},'transation5':{"rev1":Sales5,"inv5":[Purchase4, each_at7]},'transaction6'{"rev1":Sales6,"inv6":[Purchase5, each_at8]}}
            inventory=[[beginning_inv, each_at1],[Purchase1, each_at2],[Purchase2, each_at4],[Purchase3, each_at5],[Purchase4, each_at7], [Purchase5,each_at8], [Purchase6,each_at9], [Purchase7,each_at10],
            [grid2[0,4].value,grid2[0,5].value],[grid2[1,4].value,grid2[1,5].value],[grid2[3,4].value,grid2[3,5].value],[grid2[4,4].value,grid2[4,5].value],[grid2[6,4].value,grid2[6,5].value],[grid2[7,4].value,grid2[7,5].value],
            [grid2[9,4].value,grid2[9,5].value],[grid2[10,4].value,grid2[10,5].value],[grid2[0,7].value,grid2[0,8].value],[grid2[1,7].value,grid2[1,8].value],[grid2[3,7].value,grid2[3,8].value],
            [grid2[4,7].value,grid2[4,8].value],[grid2[6,7].value,grid2[6,8].value],[grid2[7,7].value,grid2[7,8].value],[grid2[9,7].value,grid2[9,8].value],[grid2[10,7].value,grid2[10,8].value],]
            sales =[Sales,Sales2,Sales3,Sales4, grid2[2,4].value, grid2[5,4].value, grid2[8,4].value, grid2[11,4].value, grid2[2,7].value, grid2[5,7].value, grid2[8,7].value, grid2[11,7].value]
            Inventory_turnover=[[Purchase2, each_at4],[Purchase3, each_at5],[Purchase4, each_at7],[Purchase5, each_at8]]
            qty_to_sell = Sales
            cogs = 0
            for sale_qty in sales:
              qty_to_sell = sale_qty
              sale_cogs = 0
              for batch in inventory:#
                  batch_qty, batch_cost = batch
                  if qty_to_sell <= 0:
                      break
                  if batch_qty <= 0:
                     continue
                  if batch_qty <= qty_to_sell:
                      sale_cogs += batch_qty * batch_cost
                      qty_to_sell -= batch_qty
                      batch[0] = 0  # batch fully used
                  else:
                      sale_cogs += qty_to_sell * batch_cost
                      batch[0] -= qty_to_sell  # subtract sold units
                      qty_to_sell = 0
              cogs += sale_cogs
              print_colored(f"Sale of {sale_qty} units → COGS = {sale_cogs:.2f}","yellow")
            total_units = sum([batch[0] for batch in inventory])
            ending_inventory_value = sum(batch[0] * batch[1] for batch in inventory)
            ending_inventory_cost = cogs - ending_inventory_value
            print_colored(f"\nTotal COGS = {cogs:.2f}","cyan")
            print_colored(f"Remaining inventory = {total_units}\n{inventory}","green")
            print_colored(f"remaining inventory Cost {ending_inventory_value}","green")
        elif fili == "LIFO_perpetual":
            transactions = [("First_inv", beginning_inv, each_at1),("Purchase",Purchase1, each_at2),("Sale", Sales,0.0), # Cost doesn't matter for sales input
                ("Purchase", Purchase2, each_at4),("Purchase", Purchase3, each_at5),("Sale", Sales2,0.0),("Purchase",Purchase4, each_at7),("Purchase", Purchase5,each_at8),("Sale", Sales3, 0.0),("Purchase",Purchase6,each_at9),("Purchase", Purchase7,each_at10),("Sale", Sales4, 0.0),
                ("Purchase", grid2[0,4].value,grid2[0,5].value),("Purchase",grid2[1,4].value,grid2[1,5].value),("Sale",grid2[2,4].value , 0.0),("Purchase",grid2[3,4].value,grid2[3,5].value),("Purchase",grid2[9,4].value,grid2[9,5].value),("Purchase",grid2[4,4].value,grid2[4,5].value),
                ("Sale",grid2[5,4].value , 0.0), ("Purchase",grid2[6,4].value,grid2[6,5].value),("Purchase",grid2[7,4].value,grid2[7,5].value),("Sale",grid2[8,4].value , 0.0),("Purchase",grid2[10,4].value,grid2[10,5].value),("Sale",grid2[11,4].value , 0.0),
                ("Purchase",grid2[0,7].value,grid2[0,8].value),("Purchase",grid2[1,7].value,grid2[1,8].value),("Sale",grid2[2,7].value , 0.0),("Purchase",grid2[3,7].value,grid2[3,8].value),("Purchase",grid2[4,7].value,grid2[4,8].value),("Sale",grid2[5,7].value, 0.0),
                ("Purchase",grid2[6,7].value,grid2[6,8].value),("Purchase",grid2[7,7].value,grid2[7,8].value),("Sale",grid2[8,7].value , 0.0),("Purchase",grid2[9,7].value,grid2[9,8].value),("Purchase",grid2[10,7].value,grid2[10,8].value),("Sale",grid2[11,7].value , 0.0)]
            total_cogs = 0.0
            # current_inventory will hold the cost layers [qty, cost] in chronological order
            current_inventory = []

            for transaction_type, qty, cost in transactions:
                if transaction_type in ["First_inv", "Purchase"]:
                    # Add the new layer to the end of the inventory list
                    if qty > 0:
                        current_inventory.append([qty, cost])

                elif transaction_type == "Sale":
                    sale_qty = qty
                    sale_cogs = 0.0
                    qty_to_sell = sale_qty

                    # LIFO: Iterate in reverse order (newest stock first)
                    # We must use a separate index or copy to iterate and modify the list
                    for i in reversed(range(len(current_inventory))):
                        batch = current_inventory[i]
                        batch_qty, batch_cost = batch

                        if qty_to_sell <= 0:
                            break

                        if batch_qty > 0:
                            # Determine how much of this batch is sold
                            sold_from_batch = min(qty_to_sell, batch_qty)

                            sale_cogs += sold_from_batch * batch_cost
                            qty_to_sell -= sold_from_batch
                            batch[0] -= sold_from_batch # Update the remaining quantity in the batch

                    total_cogs += sale_cogs

                    # Clean up batches with 0 units after sale
                    current_inventory = [batch for batch in current_inventory if batch[0] > 0]

                    print_colored(f"Sale of {sale_qty} units → COGS = {sale_cogs:.2f}","yellow")

            # Final calculations
            ending_inventory_value = sum(batch[0] * batch[1] for batch in current_inventory)
            ending_inventory_units = sum(batch[0] for batch in current_inventory)
            ending_inventory_cost = cogs - ending_inventory_value
            print_colored("\n-----------------------------","cyan")
            print_colored(f"Total COGS = {total_cogs:.2f}","cyan")
            print_colored(f"Ending Inventory Units = {ending_inventory_units:.0f}","green")
            print_colored(f"Ending Inventory Value = {ending_inventory_value:.2f}","green")
        elif fili == "FIFO_periodic":
            print_colored("FIFO_periodic", "green")
            inventory=[[beginning_inv, each_at1],[Purchase1, each_at2],[Purchase2, each_at4],[Purchase3, each_at5],[Purchase4, each_at7], [Purchase5,each_at8], [Purchase6,each_at9], [Purchase7,each_at10],
            [grid2[0,4].value,grid2[0,5].value],[grid2[1,4].value,grid2[1,5].value],[grid2[3,4].value,grid2[3,5].value],[grid2[4,4].value,grid2[4,5].value],[grid2[6,4].value,grid2[6,5].value],[grid2[7,4].value,grid2[7,5].value],
            [grid2[9,4].value,grid2[9,5].value],[grid2[10,4].value,grid2[10,5].value],[grid2[0,7].value,grid2[0,8].value],[grid2[1,7].value,grid2[1,8].value],[grid2[3,7].value,grid2[3,8].value],
            [grid2[4,7].value,grid2[4,8].value],[grid2[6,7].value,grid2[6,8].value],[grid2[7,7].value,grid2[7,8].value],[grid2[9,7].value,grid2[9,8].value],[grid2[10,7].value,grid2[10,8].value],]

            total_sales_units = Sales + Sales2 + Sales3 + Sales4 + grid2[2,4].value + grid2[5,4].value + grid2[8,4].value + grid2[11,4].value + grid2[2,7].value + grid2[5,7].value + grid2[8,7].value + grid2[11,7].value
            qty_to_sell = total_sales_units
            cogs = 0
            for batch in inventory:
                batch_qty, batch_cost = batch
                if qty_to_sell <= 0:
                   break
                if batch_qty <= 0:
                     continue
                if batch_qty <= qty_to_sell:
                   cogs += batch_qty * batch_cost
                   qty_to_sell -= batch_qty
                else:
                   cogs += qty_to_sell * batch_cost
                   qty_to_sell = 0
            total_units = sum([batch[0] for batch in inventory])
            print_colored(f"Total Periodic FIFO COGS = {cogs:.2f}","cyan")
            ending_inventory_value=sum(batch[0] * batch[1] for batch in inventory)
            ending_inventory_cost = cogs - ending_inventory_value
            print_colored(f"Remaining inventory  = {total_units}\n{inventory}\nEnding Inventory {ending_inventory_cost:.2f}","green")
            print_colored(f"Total inventory Cost {ending_inventory_value}","green")
        elif fili == "LIFO_periodic":
            print_colored("LIFO_periodic", "green")
            inventory=[[beginning_inv, each_at1],[Purchase1, each_at2],[Purchase2, each_at4],[Purchase3, each_at5],[Purchase4, each_at7], [Purchase5,each_at8], [Purchase6,each_at9], [Purchase7,each_at10],
            [grid2[0,4].value,grid2[0,5].value],[grid2[1,4].value,grid2[1,5].value],[grid2[3,4].value,grid2[3,5].value],[grid2[4,4].value,grid2[4,5].value],[grid2[6,4].value,grid2[6,5].value],[grid2[7,4].value,grid2[7,5].value],
            [grid2[9,4].value,grid2[9,5].value],[grid2[10,4].value,grid2[10,5].value],[grid2[0,7].value,grid2[0,8].value],[grid2[1,7].value,grid2[1,8].value],[grid2[3,7].value,grid2[3,8].value],
            [grid2[4,7].value,grid2[4,8].value],[grid2[6,7].value,grid2[6,8].value],[grid2[7,7].value,grid2[7,8].value],[grid2[9,7].value,grid2[9,8].value],[grid2[10,7].value,grid2[10,8].value],]
            total_sales_units = Sales + Sales2 + Sales3 + Sales4 + grid2[2,4].value + grid2[5,4].value + grid2[8,4].value + grid2[11,4].value + grid2[2,7].value + grid2[5,7].value + grid2[8,7].value + grid2[11,7].value
            qty_to_sell = total_sales_units
            cogs = 0
            for batch in reversed(inventory):
                batch_qty, batch_cost = batch
                if qty_to_sell <= 0:
                   break
                if batch_qty <= 0:
                     continue
                if batch_qty <= qty_to_sell:
                   cogs += batch_qty * batch_cost
                   qty_to_sell -= batch_qty
                else:
                    cogs += qty_to_sell * batch_cost
                    qty_to_sell = 0
            total_units = sum([batch[0] for batch in inventory])
            cogas = sum([batch[0] * batch[1] for batch in inventory])
            print_colored(f"Total Periodic LIFO COGS = {cogs:.2f}","cyan")
            ending_inventory_value=sum(batch[0] * batch[1] for batch in inventory)
            ending_inventory_cost = cogs - ending_inventory_value
            print_colored(f"Remaining inventory  = {total_units}\n{inventory}\nEnding Inventory {ending_inventory_cost:.2f}","green")
            print_colored(f"Total inventory Cost {ending_inventory_value}  ","green")
        elif fili == "AVCO_periodic":
            print_colored("AVCO (Weighted Average Cost Method)", "green")
            inventory=[[beginning_inv, each_at1],[Purchase1, each_at2],[Purchase2, each_at4],[Purchase3, each_at5],[Purchase4, each_at7], [Purchase5,each_at8], [Purchase6,each_at9], [Purchase7,each_at10],
            [grid2[0,4].value,grid2[0,5].value],[grid2[1,4].value,grid2[1,5].value],[grid2[3,4].value,grid2[3,5].value],[grid2[4,4].value,grid2[4,5].value],[grid2[6,4].value,grid2[6,5].value],[grid2[7,4].value,grid2[7,5].value],
            [grid2[9,4].value,grid2[9,5].value],[grid2[10,4].value,grid2[10,5].value],[grid2[0,7].value,grid2[0,8].value],[grid2[1,7].value,grid2[1,8].value],[grid2[3,7].value,grid2[3,8].value],
            [grid2[4,7].value,grid2[4,8].value],[grid2[6,7].value,grid2[6,8].value],[grid2[7,7].value,grid2[7,8].value],[grid2[9,7].value,grid2[9,8].value],[grid2[10,7].value,grid2[10,8].value],]
            sales = [Sales, Sales2, Sales3, Sales4,grid2[2,4].value, grid2[5,4].value, grid2[8,4].value, grid2[11,4].value, grid2[2,7].value, grid2[5,7].value, grid2[8,7].value, grid2[11,7].value]
            total_sales_units = sum(sales)
            total_cost = sum(qty * cost for qty, cost in inventory)
            total_units = sum(qty for qty, _ in inventory)
            average_cost_per_unit = total_cost / total_units if total_units else 0
            cogs = total_sales_units * average_cost_per_unit
            ending_units = total_units - total_sales_units
            ending_inventory_value = ending_units * average_cost_per_unit
            print_colored(f"Average Cost per Unit = {average_cost_per_unit:.2f}", "cyan")
            print_colored(f"Total AVCO COGS = {cogs:.2f}", "green")
            print_colored(f"Ending Inventory Units = {ending_units}", "green")
            print_colored(f"Ending Inventory Cost = {ending_inventory_value:.2f} ", "green")

        elif fili == "AVCO_perpetual":
            # --- Setup (Based on your input data) ---
            # Your input values for this example were:
            # First_inv: 100 @ 10, Purchase 1: 200 @ 12, Sales 1: 150
            # Purchase 2: 100 @ 14, Purchase 3: 0 @ 0, Sales 2: 120
            # Purchase 4: 80 @ 0, Purchase 5: 0 @ 0, Sales 3: 0
            # I will use these placeholders for the transactions:
            transactions = [("First_inv", beginning_inv, each_at1),("Purchase",Purchase1, each_at2),("Sale", Sales,0.0), # Cost doesn't matter for sales input
                ("Purchase", Purchase2, each_at4),("Purchase", Purchase3, each_at5),("Sale", Sales2,0.0),("Purchase",Purchase4, each_at7),("Purchase", Purchase5,each_at8),("Sale", Sales3, 0.0),("Purchase",Purchase6,each_at9),("Purchase", Purchase7,each_at10),("Sale", Sales4, 0.0),
                ("Purchase", grid2[0,4].value,grid2[0,5].value),("Purchase",grid2[1,4].value,grid2[1,5].value),("Sale",grid2[2,4].value , 0.0),("Purchase",grid2[3,4].value,grid2[3,5].value),("Purchase",grid2[9,4].value,grid2[9,5].value),("Purchase",grid2[4,4].value,grid2[4,5].value),
                ("Sale",grid2[5,4].value , 0.0), ("Purchase",grid2[6,4].value,grid2[6,5].value),("Purchase",grid2[7,4].value,grid2[7,5].value),("Sale",grid2[8,4].value , 0.0),("Purchase",grid2[10,4].value,grid2[10,5].value),("Sale",grid2[11,4].value , 0.0),
                ("Purchase",grid2[0,7].value,grid2[0,8].value),("Purchase",grid2[1,7].value,grid2[1,8].value),("Sale",grid2[2,7].value , 0.0),("Purchase",grid2[3,7].value,grid2[3,8].value),("Purchase",grid2[4,7].value,grid2[4,8].value),("Sale",grid2[5,7].value, 0.0),
                ("Purchase",grid2[6,7].value,grid2[6,8].value),("Purchase",grid2[7,7].value,grid2[7,8].value),("Sale",grid2[8,7].value , 0.0),("Purchase",grid2[9,7].value,grid2[9,8].value),("Purchase",grid2[10,7].value,grid2[10,8].value),("Sale",grid2[11,7].value , 0.0)]


            # --- AVCO Perpetual Logic ---
            print_colored("AVCO Perpetual", "green")

            # Initialize the running inventory
            running_units = 0.0
            running_cost = 0.0
            total_cogs = 0.0

            for transaction_type, qty, cost in transactions:
                current_wac = running_cost / running_units if running_units > 0 else 0.0

                if transaction_type in ["First_inv", "Purchase"]:
                    # 1. Handle Purchases (Increase inventory, recalculate WAC)
                    if qty > 0:
                        transaction_value = qty * cost
                        running_units += qty
                        running_cost += transaction_value
                        # New WAC is automatically running_cost / running_units

                        # Print Purchase Info
                        new_wac = running_cost / running_units
                        print_colored(f">>> {transaction_type} of {qty} units @ {cost:.2f}", "yellow")
                        print_colored(f"    New Inventory: {running_units:.0f} units @ {new_wac:.2f}", "green")

                elif transaction_type == "Sale":
                    # 2. Handle Sales (Decrease inventory, COGS based on CURRENT WAC)
                    if qty > 0 and running_units >= qty:
                        cogs = qty * current_wac
                        total_cogs += cogs
                        running_units -= qty
                        running_cost -= cogs # The value decreases by the COGS

                        # Print Sale Info
                        print_colored(f"--- Sale of {qty} units:", "yellow")
                        print_colored(f"    WAC Used: {current_wac:.2f}", "green")
                        print_colored(f"    COGS: {cogs:.2f}", "green")
                    elif qty > 0 and running_units < qty:
                        print_colored(f"!!! Error: Sale of {qty} units, but only {running_units:.0f} in stock.", "red")
            # --- Final Totals ---
            print_colored(f"-----------------------------", "cyan")
            print_colored(f"Total COGS (All Sales) = {total_cogs:.2f}", "green")
            print_colored(f"Ending Inventory Units = {running_units:.0f}", "green")
            print_colored(f"Ending Inventory Value = {running_cost:.2f}", "green")
        else:
          print_colored("invalid input","red")
          pass
def save_general_journal_to_excel(b):
    general_journal_series = pd.Series(values,index=data)
    general_journal_series.to_excel("inventory_Journal.xlsx", index=False)
    print_colored("✅ Journal saved to 'Transaction_journal.xlsx'", "green")
save_button.on_click(save_general_journal_to_excel)

fili_button.on_click(fifo_lifo_table)
def save_chart2(b):
    #def convert_datetime_if_needed(value):
    #    if isinstance(DatePicker.value, DatePicker):   # check if it's a datetime object
    #        return value.strftime('%Y-%m-%d')  # convert to string
    #    return value  # leave numbers/other types unchanged
    transactions = [("Date",grid2[0,0].value,"First_inv", grid2[0,1].value, grid2[0,2].value,inv_options.value,0.0,0.0,0.0),("Date",grid2[1,0].value,"Purchase",grid2[1,1].value, grid2[1,2].value),("Date",grid2[2,0].value,"Sale", grid2[2,1].value,0.0), # Cost doesn't matter for sales input
    ("Date",grid2[3,0].value,"Purchase", grid2[3,1].value, grid2[3,2].value),("Date",grid2[4,0].value,"Purchase", grid2[4,1].value, grid2[4,2].value),("Date",grid2[5,0].value,"Sale", grid2[5,1].value,0.0),("Date",grid2[6,0].value,"Purchase",grid2[6,1].value, grid2[6,2].value),("Date",grid2[7,0].value,"Purchase", grid2[7,1].value,grid2[7,2].value),("Date",grid2[8,0].value,"Sale",grid2[8,1].value, 0.0),("Date",grid2[9,0].value,"Purchase",grid2[9,1].value,grid2[9,2].value),("Date",grid2[10,0].value,"Purchase", grid2[10,1].value,grid2[10,2].value),("Date",grid2[11,0].value,"Sale", grid2[11,1].value, 0.0),
    ("Date",grid2[0,3].value,"Purchase", grid2[0,4].value,grid2[0,5].value),("Date",grid2[1,3].value,"Purchase",grid2[1,4].value,grid2[1,5].value),("Date",grid2[2,3].value,"Sale",grid2[2,4].value , 0.0),("Date",grid2[3,3].value,"Purchase",grid2[3,4].value,grid2[3,5].value),("Date",grid2[9,3].value,"Purchase",grid2[9,4].value,grid2[9,5].value),("Date",grid2[4,3].value,"Purchase",grid2[4,4].value,grid2[4,5].value),
    ("Date",grid2[5,3].value,"Sale",grid2[5,4].value , 0.0), ("Date",grid2[6,3].value,"Purchase",grid2[6,4].value,grid2[6,5].value),("Date",grid2[7,3].value,"Purchase",grid2[7,4].value,grid2[7,5].value),("Date",grid2[8,3].value,"Sale",grid2[8,4].value , 0.0),("Date",grid2[10,3].value,"Purchase",grid2[10,4].value,grid2[10,5].value),("Date",grid2[11,3].value,"Sale",grid2[11,4].value , 0.0),
    ("Date",grid2[0,6].value,"Purchase",grid2[0,7].value,grid2[0,8].value),("Date",grid2[1,6].value,"Purchase",grid2[1,7].value,grid2[1,8].value),("Date",grid2[2,6].value,"Sale",grid2[2,7].value , 0.0),("Date",grid2[3,6].value,"Purchase",grid2[3,7].value,grid2[3,8].value),("Date",grid2[4,6].value,"Purchase",grid2[4,7].value,grid2[4,8].value),("Date",grid2[5,6].value,"Sale",grid2[5,7].value, 0.0),
    ("Date",grid2[6,6].value,"Purchase",grid2[6,7].value,grid2[6,8].value),("Date",grid2[7,6].value,"Purchase",grid2[7,7].value,grid2[7,8].value),("Date",grid2[8,6].value,"Sale",grid2[8,7].value , 0.0),("Date",grid2[9,6].value,"Purchase",grid2[9,7].value,grid2[9,8].value),("Date",grid2[10,6].value,"Purchase",grid2[10,7].value,grid2[10,8].value),("Date",grid2[11,6].value,"Sale",grid2[11,7].value , 0.0,)]
    inv_journal = pd.DataFrame(transactions, columns=["Date","dates","Type", "Quantity", "Unit_Cost","inv type","COGS","end_inv_val","end_inv_cost"])#
    def to_number(v):
        try:
            return float(v)
        except:
            return 0.0
    #converted_list = [
    #tuple(convert_datetime_if_needed(v) for v in row)
    #for row in transactions]
    #inv_journal['dates'] = inv_journal['dates'].dt.strftime('%Y-%m-%d')
    inv_journal["Quantity"] = inv_journal["Quantity"].apply(to_number)
    inv_journal["Unit_Cost"] = inv_journal["Unit_Cost"].apply(to_number)
    inv_journal.to_excel("inventory_Journal.xlsx", index=False)
    print_colored("✅ Journal saved to 'inventory_journal.xlsx'", "green")
Save2table.on_click(save_chart2)
def save_general_journal_to_excel(b):
    general_journal_series = pd.Series(values,index=data)
    gen_journal=[(dates.value,val.value)]
    general_j = pd.DataFrame(gen_journal, columns=['description', 'transaction'])
    general_j.to_excel("Transaction_Journal.xlsx", index=False)
    print_colored("✅ Journal saved to 'Transaction_journal.xlsx'", "green")
save_table.on_click(save_general_journal_to_excel)
       #z99

HTML(value='\n<style>\nlabel.widget-label {color: #00FF00 !important}\n/* Forces green text on ALL buttons */\…

HTML(value='<style>.Textarea.widget-value {color: #00FF00 !important; /* Forces green text on ALL buttons */}<…

Accounting project GUI version

Label(value='')

Accordion(children=(Tab(children=(VBox(children=(HTML(value="<p><span style='color: #00FF00;'>Greetings! My na…

Output()

In [ ]:
# @title Pandas DataFrame(s)

import pandas as pd
import matplotlib.pyplot as plt
ledger_df = pd.DataFrame(general_ledger.items(), columns=['Account', 'Balance'])
display(ledger_df)

               Account  Balance
0                 Cash      0.0
1  Accounts Receivable      0.0
2             Supplies      0.0
3            Equipment      0.0
4     Accounts Payable      0.0
5        Notes Payable      0.0
6       Owner's Equity      0.0
7              Revenue      0.0
8             Expenses      0.0
9            Dividends      0.0

In [ ]:
# @title A quiz project GUI draft using ipywidgets
#study guide layout=Layout(height='auto',width='auto')
from IPython.display import display,clear_output
from ipywidgets import (Layout,
    Button, Checkbox, Dropdown, FloatSlider, IntSlider,
    RadioButtons, Text, Textarea, ToggleButton, VBox, HBox, Label,interact,Output,IntText, FloatText)
def x():
  print(f"\n {score} gg")
  exit()
quiz_data = [
        {"question": "What are the 4 accounting principles (GAAP)?",
         "options": [
            "A) revenue recognition, expense, full disclosure, cost",
            "B) honesty, integrity, honor, efficiency",
            "C) fraud, theft, dishonesty, secrecy","x","s"],
        "correct": "A) revenue recognition, expense, full disclosure, cost"},{

        "question": "DEARLO stands for:",
        "options": [
            "A) deadly, extreme, awesome, lethal, operational",
            "B) dividend, expense, asset, revenue, liabilities, owner's equity",
            "C) dividend, exports, assets, unearned revenue, liability, owners equity","x","s"],
        "correct": "B) dividend, expense, asset, revenue, liabilities, owner's equity"},{

         "question": "the six accounting types are:","options": ["A)debt,expense,asset revenue,liability,operations","B)dividend,expense,asset,revenue,liability,owner's equity","C)dividend,exports,assets,unearned revenue,liability,owners equity","x","s"]
         ,"correct": "B) dividend, expense, asset, revenue, liabilities, owner's equity"},
        {"question": "The 4 financial statements are income, balance, cash flow and equity.",
        "options": ["True", "False","x","s"],
        "correct": "True"},
        {"question": "What are the three transaction types?",
        "options": [
            "A) Buying, Selling, Saving",
            "B) Operating, Investing, Financing",
            "C) Borrowing, Lending, Donating","x","s"],
        "correct": "B) Operating, Investing, Financing"},
        {"question": "What are the three debit types?",
        "options": [
            "A) dividend",
            "B) expense",
            "C) asset",
            "D) all the above","x","s"],
        "correct": "D) all the above"},

        {"question": "D.E.A.D. stands for Dividend, Expense, Asset, Debit.",
        "options": ["True", "False","x","s"],
        "correct": "True"},
        ]
output = Output()
question_index = 0
score = 0
question_label = Label()
dropdown = Dropdown()
submit_button = Button(description="Submit")
submit_button.style.button_color = 'green' #display this outside button
next_button = Button(description="Next", disabled=True)
next_button.style.button_color = 'red' #display this outside button
def load_question(index):
    question_label.value = f"Q{index+1}: {quiz_data[index]['question']}"
    dropdown.options = quiz_data[index]['options']
    dropdown.value = None
    submit_button.disabled = False
    next_button.disabled = True
    output.clear_output()
def handle_submit(b):
    global score #global meaning universal accross all code even outside functions
    user_answer = dropdown.value
    correct_answer = quiz_data[question_index]['correct']
    with output:
        clear_output()
        if user_answer == correct_answer:
            print("✅ Correct!")
            score += 1
        elif user_answer == "x":
            x()
        elif user_answer == "s":
            pass
        else:
            print(f"❌ Incorrect. Correct answer was: {correct_answer}")
    submit_button.disabled = True
    next_button.disabled = False

# Move to next question
def handle_next(b):
    global question_index
    question_index += 1
    if question_index < len(quiz_data):
        load_question(question_index)
    else:
        with output:
            clear_output()
            print(f"🎉 Quiz complete! Final score: {score} / {len(quiz_data)}")
        # Disable widgets at the end
        dropdown.disabled = True
        submit_button.disabled = True
        next_button.disabled = True

# Button click events
submit_button.on_click(handle_submit)
next_button.on_click(handle_next)

# Initial UI
load_question(question_index)
display(VBox([
    question_label,
    dropdown,
    HBox([submit_button, next_button]),
    output
]))

In [11]:
#@title chart, starting to mess around with pandas
import pandas as pd
import matplotlib.pyplot as plt
general_ledger = {
    "Cash": 0.0,
    "Accounts Receivable": 0.0,
    "Supplies": 0.0,
    "Equipment": 0.0,
    "Accounts Payable": 0.0,
    "Notes Payable": 0.0,
    "Owner's Equity": 0.0,
    "Revenue": 0.0,
    "Expenses": 0.0,
    "Dividends": 0.0}
data = ["a","b","c",1,2,3,4,5,5,6,]
datas = pd.DataFrame(general_ledger.items(),columns=['Account', 'Balance'],index=[data]) # by dictionary
print("Pandas dataframe")
d = pd.Series(data, index=[1,2,3,4,5,6,7,8,9,10]) #lists
print("Pandas series")
display(datas,d)

Pandas dataframe
Pandas series

               Account  Balance
a                 Cash      0.0
b  Accounts Receivable      0.0
c             Supplies      0.0
1            Equipment      0.0
2     Accounts Payable      0.0
3        Notes Payable      0.0
4       Owner's Equity      0.0
5              Revenue      0.0
5             Expenses      0.0
6            Dividends      0.0

1     a
2     b
3     c
4     1
5     2
6     3
7     4
8     5
9     5
10    6
dtype: object